name: draw_guess
description: A new Flutter package.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared:
    path: ../shared

  chat_room:
    path: ../chat_room

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  flutter_lints: ^2.0.2
  assets_gen: ^1.5.0

assets_gen:
  omit_path_levels: 2
  plurals:
    - assets/images/ic_count_down_?.webp

flutter:
  assets:
    - assets/images/
    - assets/sound/
