// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 2.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'premade';

  static const String ic_drag_open_svg = 'assets/images/ic_drag_open.svg';
  static const String premade$ic_drag_open_svg =
      'packages/premade/assets/images/ic_drag_open.svg';

  static const String triangleImage_png = 'assets/images/triangleImage.png';
  static const String premade$triangleImage_png =
      'packages/premade/assets/images/triangleImage.png';
}
