// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 167.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'vip';

  static const String bag_bg_coupon_png = 'assets/images/bag_bg_coupon.png';
  static const String vip$bag_bg_coupon_png =
      'packages/vip/assets/images/bag_bg_coupon.png';

  static const String bag_ic_coin_webp = 'assets/images/bag_ic_coin.webp';
  static const String vip$bag_ic_coin_webp =
      'packages/vip/assets/images/bag_ic_coin.webp';

  static const String bag_ic_shop_svg = 'assets/images/bag_ic_shop.svg';
  static const String vip$bag_ic_shop_svg =
      'packages/vip/assets/images/bag_ic_shop.svg';

  static const String box_box1_png = 'assets/images/box/box1.png';
  static const String vip$box_box1_png =
      'packages/vip/assets/images/box/box1.png';

  static const String box_box10_png = 'assets/images/box/box10.png';
  static const String vip$box_box10_png =
      'packages/vip/assets/images/box/box10.png';

  static const String box_box2_png = 'assets/images/box/box2.png';
  static const String vip$box_box2_png =
      'packages/vip/assets/images/box/box2.png';

  static const String box_box3_png = 'assets/images/box/box3.png';
  static const String vip$box_box3_png =
      'packages/vip/assets/images/box/box3.png';

  static const String box_box4_png = 'assets/images/box/box4.png';
  static const String vip$box_box4_png =
      'packages/vip/assets/images/box/box4.png';

  static const String box_box5_png = 'assets/images/box/box5.png';
  static const String vip$box_box5_png =
      'packages/vip/assets/images/box/box5.png';

  static const String box_box6_png = 'assets/images/box/box6.png';
  static const String vip$box_box6_png =
      'packages/vip/assets/images/box/box6.png';

  static const String box_box7_png = 'assets/images/box/box7.png';
  static const String vip$box_box7_png =
      'packages/vip/assets/images/box/box7.png';

  static const String box_box8_png = 'assets/images/box/box8.png';
  static const String vip$box_box8_png =
      'packages/vip/assets/images/box/box8.png';

  static const String box_box9_png = 'assets/images/box/box9.png';
  static const String vip$box_box9_png =
      'packages/vip/assets/images/box/box9.png';

  static const String box_open_bg_png = 'assets/images/box_open_bg.png';
  static const String vip$box_open_bg_png =
      'packages/vip/assets/images/box_open_bg.png';

  static const String cherish_activity_mini_bg_webp =
      'assets/images/cherish_activity_mini_bg.webp';
  static const String vip$cherish_activity_mini_bg_webp =
      'packages/vip/assets/images/cherish_activity_mini_bg.webp';

  static const String contact_check_nor_png =
      'assets/images/contact_check_nor.png';
  static const String vip$contact_check_nor_png =
      'packages/vip/assets/images/contact_check_nor.png';

  static const String contact_check_sel_png =
      'assets/images/contact_check_sel.png';
  static const String vip$contact_check_sel_png =
      'packages/vip/assets/images/contact_check_sel.png';

  static const String double_eleven_activity_bg_webp =
      'assets/images/double_eleven_activity_bg.webp';
  static const String vip$double_eleven_activity_bg_webp =
      'packages/vip/assets/images/double_eleven_activity_bg.webp';

  static const String double_eleven_activity_buy_webp =
      'assets/images/double_eleven_activity_buy.webp';
  static const String vip$double_eleven_activity_buy_webp =
      'packages/vip/assets/images/double_eleven_activity_buy.webp';

  static const String double_eleven_activity_icon_webp =
      'assets/images/double_eleven_activity_icon.webp';
  static const String vip$double_eleven_activity_icon_webp =
      'packages/vip/assets/images/double_eleven_activity_icon.webp';

  static const String double_eleven_activity_mini_bg_webp =
      'assets/images/double_eleven_activity_mini_bg.webp';
  static const String vip$double_eleven_activity_mini_bg_webp =
      'packages/vip/assets/images/double_eleven_activity_mini_bg.webp';

  static const String double_eleven_activity_price_webp =
      'assets/images/double_eleven_activity_price.webp';
  static const String vip$double_eleven_activity_price_webp =
      'packages/vip/assets/images/double_eleven_activity_price.webp';

  static const String double_eleven_activity_time_bg_webp =
      'assets/images/double_eleven_activity_time_bg.webp';
  static const String vip$double_eleven_activity_time_bg_webp =
      'packages/vip/assets/images/double_eleven_activity_time_bg.webp';

  static const String fan_group_integral_bg_webp =
      'assets/images/fan_group_integral_bg.webp';
  static const String vip$fan_group_integral_bg_webp =
      'packages/vip/assets/images/fan_group_integral_bg.webp';

  static const String ic_add_no_border_webp =
      'assets/images/ic_add_no_border.webp';
  static const String vip$ic_add_no_border_webp =
      'packages/vip/assets/images/ic_add_no_border.webp';

  static const String ic_add_no_border_dark_webp =
      'assets/images/ic_add_no_border_dark.webp';
  static const String vip$ic_add_no_border_dark_webp =
      'packages/vip/assets/images/ic_add_no_border_dark.webp';

  static const String ic_collection_room_entrance_webp =
      'assets/images/ic_collection_room_entrance.webp';
  static const String vip$ic_collection_room_entrance_webp =
      'packages/vip/assets/images/ic_collection_room_entrance.webp';

  static const String ic_dialog_close_webp =
      'assets/images/ic_dialog_close.webp';
  static const String vip$ic_dialog_close_webp =
      'packages/vip/assets/images/ic_dialog_close.webp';

  static const String ic_gift_play_png = 'assets/images/ic_gift_play.png';
  static const String vip$ic_gift_play_png =
      'packages/vip/assets/images/ic_gift_play.png';

  static const String ic_key_copper_png = 'assets/images/ic_key_copper.png';
  static const String vip$ic_key_copper_png =
      'packages/vip/assets/images/ic_key_copper.png';

  static const String ic_key_gold_png = 'assets/images/ic_key_gold.png';
  static const String vip$ic_key_gold_png =
      'packages/vip/assets/images/ic_key_gold.png';

  static const String ic_key_pac_copper_png =
      'assets/images/ic_key_pac_copper.png';
  static const String vip$ic_key_pac_copper_png =
      'packages/vip/assets/images/ic_key_pac_copper.png';

  static const String ic_key_pac_gold_png = 'assets/images/ic_key_pac_gold.png';
  static const String vip$ic_key_pac_gold_png =
      'packages/vip/assets/images/ic_key_pac_gold.png';

  static const String ic_key_pac_silver_png =
      'assets/images/ic_key_pac_silver.png';
  static const String vip$ic_key_pac_silver_png =
      'packages/vip/assets/images/ic_key_pac_silver.png';

  static const String ic_key_silver_png = 'assets/images/ic_key_silver.png';
  static const String vip$ic_key_silver_png =
      'packages/vip/assets/images/ic_key_silver.png';

  static const String ic_key_star_copper_png =
      'assets/images/ic_key_star_copper.png';
  static const String vip$ic_key_star_copper_png =
      'packages/vip/assets/images/ic_key_star_copper.png';

  static const String ic_key_star_gold_png =
      'assets/images/ic_key_star_gold.png';
  static const String vip$ic_key_star_gold_png =
      'packages/vip/assets/images/ic_key_star_gold.png';

  static const String ic_key_star_silver_png =
      'assets/images/ic_key_star_silver.png';
  static const String vip$ic_key_star_silver_png =
      'packages/vip/assets/images/ic_key_star_silver.png';

  static const String ic_key_travel_copper_webp =
      'assets/images/ic_key_travel_copper.webp';
  static const String vip$ic_key_travel_copper_webp =
      'packages/vip/assets/images/ic_key_travel_copper.webp';

  static const String ic_key_travel_gold_webp =
      'assets/images/ic_key_travel_gold.webp';
  static const String vip$ic_key_travel_gold_webp =
      'packages/vip/assets/images/ic_key_travel_gold.webp';

  static const String ic_key_travel_silver_webp =
      'assets/images/ic_key_travel_silver.webp';
  static const String vip$ic_key_travel_silver_webp =
      'packages/vip/assets/images/ic_key_travel_silver.webp';

  static const String ic_minus_no_border_webp =
      'assets/images/ic_minus_no_border.webp';
  static const String vip$ic_minus_no_border_webp =
      'packages/vip/assets/images/ic_minus_no_border.webp';

  static const String ic_minus_no_border_dark_webp =
      'assets/images/ic_minus_no_border_dark.webp';
  static const String vip$ic_minus_no_border_dark_webp =
      'packages/vip/assets/images/ic_minus_no_border_dark.webp';

  static const String ic_next_svg = 'assets/images/ic_next.svg';
  static const String vip$ic_next_svg =
      'packages/vip/assets/images/ic_next.svg';

  static const String ic_next_small_svg = 'assets/images/ic_next_small.svg';
  static const String vip$ic_next_small_svg =
      'packages/vip/assets/images/ic_next_small.svg';

  static const String ic_title_privilege_left_svg =
      'assets/images/ic_title_privilege_left.svg';
  static const String vip$ic_title_privilege_left_svg =
      'packages/vip/assets/images/ic_title_privilege_left.svg';

  static const String ic_title_privilege_right_svg =
      'assets/images/ic_title_privilege_right.svg';
  static const String vip$ic_title_privilege_right_svg =
      'packages/vip/assets/images/ic_title_privilege_right.svg';

  static const String icon_btn_close_svg = 'assets/images/icon_btn_close.svg';
  static const String vip$icon_btn_close_svg =
      'packages/vip/assets/images/icon_btn_close.svg';

  static const String level_bg_upgrade_popularity_webp =
      'assets/images/level/bg_upgrade_popularity.webp';
  static const String vip$level_bg_upgrade_popularity_webp =
      'packages/vip/assets/images/level/bg_upgrade_popularity.webp';

  static const String level_bg_upgrade_title_webp =
      'assets/images/level/bg_upgrade_title.webp';
  static const String vip$level_bg_upgrade_title_webp =
      'packages/vip/assets/images/level/bg_upgrade_title.webp';

  static const String level_bg_upgrade_vip_webp =
      'assets/images/level/bg_upgrade_vip.webp';
  static const String vip$level_bg_upgrade_vip_webp =
      'packages/vip/assets/images/level/bg_upgrade_vip.webp';

  static const String level_box_bg_webp = 'assets/images/level/box_bg.webp';
  static const String vip$level_box_bg_webp =
      'packages/vip/assets/images/level/box_bg.webp';

  static const String level_btn_accept_webp =
      'assets/images/level/btn_accept.webp';
  static const String vip$level_btn_accept_webp =
      'packages/vip/assets/images/level/btn_accept.webp';

  static const String level_btn_accept_disable_webp =
      'assets/images/level/btn_accept_disable.webp';
  static const String vip$level_btn_accept_disable_webp =
      'packages/vip/assets/images/level/btn_accept_disable.webp';

  static const String level_btn_open_title_webp =
      'assets/images/level/btn_open_title.webp';
  static const String vip$level_btn_open_title_webp =
      'packages/vip/assets/images/level/btn_open_title.webp';

  static const String level_ic_badge_webp = 'assets/images/level/ic_badge.webp';
  static const String vip$level_ic_badge_webp =
      'packages/vip/assets/images/level/ic_badge.webp';

  static const String level_ic_big_star_svg =
      'assets/images/level/ic_big_star.svg';
  static const String vip$level_ic_big_star_svg =
      'packages/vip/assets/images/level/ic_big_star.svg';

  static const String level_ic_box_webp = 'assets/images/level/ic_box.webp';
  static const String vip$level_ic_box_webp =
      'packages/vip/assets/images/level/ic_box.webp';

  static const String level_ic_close_png = 'assets/images/level/ic_close.png';
  static const String vip$level_ic_close_png =
      'packages/vip/assets/images/level/ic_close.png';

  static const String level_ic_gift_webp = 'assets/images/level/ic_gift.webp';
  static const String vip$level_ic_gift_webp =
      'packages/vip/assets/images/level/ic_gift.webp';

  static const String level_ic_help_svg = 'assets/images/level/ic_help.svg';
  static const String vip$level_ic_help_svg =
      'packages/vip/assets/images/level/ic_help.svg';

  static const String level_ic_nick_name_webp =
      'assets/images/level/ic_nick_name.webp';
  static const String vip$level_ic_nick_name_webp =
      'packages/vip/assets/images/level/ic_nick_name.webp';

  static const String level_ic_scroll_left_png =
      'assets/images/level/ic_scroll_left.png';
  static const String vip$level_ic_scroll_left_png =
      'packages/vip/assets/images/level/ic_scroll_left.png';

  static const String level_ic_scroll_right_png =
      'assets/images/level/ic_scroll_right.png';
  static const String vip$level_ic_scroll_right_png =
      'packages/vip/assets/images/level/ic_scroll_right.png';

  static const String level_ic_small_star_svg =
      'assets/images/level/ic_small_star.svg';
  static const String vip$level_ic_small_star_svg =
      'packages/vip/assets/images/level/ic_small_star.svg';

  static const String level_ic_title_arrow_png =
      'assets/images/level/ic_title_arrow.png';
  static const String vip$level_ic_title_arrow_png =
      'packages/vip/assets/images/level/ic_title_arrow.png';

  static const String level_level_activity_tips_get_webp =
      'assets/images/level/level_activity_tips_get.webp';
  static const String vip$level_level_activity_tips_get_webp =
      'packages/vip/assets/images/level/level_activity_tips_get.webp';

  static const String level_level_anim_arrow_webp =
      'assets/images/level/level_anim_arrow.webp';
  static const String vip$level_level_anim_arrow_webp =
      'packages/vip/assets/images/level/level_anim_arrow.webp';

  static const String level_level_bg_webp = 'assets/images/level/level_bg.webp';
  static const String vip$level_level_bg_webp =
      'packages/vip/assets/images/level/level_bg.webp';

  static const String level_level_bg_vip_webp =
      'assets/images/level/level_bg_vip.webp';
  static const String vip$level_level_bg_vip_webp =
      'packages/vip/assets/images/level/level_bg_vip.webp';

  static const String level_vip_popular_guide_title_bg_webp =
      'assets/images/level/vip_popular_guide_title_bg.webp';
  static const String vip$level_vip_popular_guide_title_bg_webp =
      'packages/vip/assets/images/level/vip_popular_guide_title_bg.webp';

  static const String level_welfare_box_big_webp =
      'assets/images/level/welfare_box_big.webp';
  static const String vip$level_welfare_box_big_webp =
      'packages/vip/assets/images/level/welfare_box_big.webp';

  static const String level_welfare_box_invalid_webp =
      'assets/images/level/welfare_box_invalid.webp';
  static const String vip$level_welfare_box_invalid_webp =
      'packages/vip/assets/images/level/welfare_box_invalid.webp';

  static const String level_welfare_box_valid_webp =
      'assets/images/level/welfare_box_valid.webp';
  static const String vip$level_welfare_box_valid_webp =
      'packages/vip/assets/images/level/welfare_box_valid.webp';

  static const String level_welfare_card_popularity_1_webp =
      'assets/images/level/welfare_card_popularity_1.webp';
  static const String vip$level_welfare_card_popularity_1_webp =
      'packages/vip/assets/images/level/welfare_card_popularity_1.webp';

  static const String level_welfare_card_popularity_2_webp =
      'assets/images/level/welfare_card_popularity_2.webp';
  static const String vip$level_welfare_card_popularity_2_webp =
      'packages/vip/assets/images/level/welfare_card_popularity_2.webp';

  static const String level_welfare_card_popularity_3_webp =
      'assets/images/level/welfare_card_popularity_3.webp';
  static const String vip$level_welfare_card_popularity_3_webp =
      'packages/vip/assets/images/level/welfare_card_popularity_3.webp';

  static const String level_welfare_card_popularity_4_webp =
      'assets/images/level/welfare_card_popularity_4.webp';
  static const String vip$level_welfare_card_popularity_4_webp =
      'packages/vip/assets/images/level/welfare_card_popularity_4.webp';

  static const String level_welfare_card_popularity_5_webp =
      'assets/images/level/welfare_card_popularity_5.webp';
  static const String vip$level_welfare_card_popularity_5_webp =
      'packages/vip/assets/images/level/welfare_card_popularity_5.webp';

  static const String level_welfare_card_vip_1_webp =
      'assets/images/level/welfare_card_vip_1.webp';
  static const String vip$level_welfare_card_vip_1_webp =
      'packages/vip/assets/images/level/welfare_card_vip_1.webp';

  static const String level_welfare_card_vip_2_webp =
      'assets/images/level/welfare_card_vip_2.webp';
  static const String vip$level_welfare_card_vip_2_webp =
      'packages/vip/assets/images/level/welfare_card_vip_2.webp';

  static const String level_welfare_card_vip_3_webp =
      'assets/images/level/welfare_card_vip_3.webp';
  static const String vip$level_welfare_card_vip_3_webp =
      'packages/vip/assets/images/level/welfare_card_vip_3.webp';

  static const String level_welfare_card_vip_4_webp =
      'assets/images/level/welfare_card_vip_4.webp';
  static const String vip$level_welfare_card_vip_4_webp =
      'packages/vip/assets/images/level/welfare_card_vip_4.webp';

  static const String level_welfare_card_vip_5_webp =
      'assets/images/level/welfare_card_vip_5.webp';
  static const String vip$level_welfare_card_vip_5_webp =
      'packages/vip/assets/images/level/welfare_card_vip_5.webp';

  static const String level_welfare_card_vip_6_webp =
      'assets/images/level/welfare_card_vip_6.webp';
  static const String vip$level_welfare_card_vip_6_webp =
      'packages/vip/assets/images/level/welfare_card_vip_6.webp';

  static const String level_welfare_card_vip_7_webp =
      'assets/images/level/welfare_card_vip_7.webp';
  static const String vip$level_welfare_card_vip_7_webp =
      'packages/vip/assets/images/level/welfare_card_vip_7.webp';

  static const String level_welfare_card_vip_8_webp =
      'assets/images/level/welfare_card_vip_8.webp';
  static const String vip$level_welfare_card_vip_8_webp =
      'packages/vip/assets/images/level/welfare_card_vip_8.webp';

  static const String level_welfare_list_light_shadow_webp =
      'assets/images/level/welfare_list_light_shadow.webp';
  static const String vip$level_welfare_list_light_shadow_webp =
      'packages/vip/assets/images/level/welfare_list_light_shadow.webp';

  static const String level_welfare_receive_list_bg_webp =
      'assets/images/level/welfare_receive_list_bg.webp';
  static const String vip$level_welfare_receive_list_bg_webp =
      'packages/vip/assets/images/level/welfare_receive_list_bg.webp';

  static const String level_welfare_upgrade_icon_webp =
      'assets/images/level/welfare_upgrade_icon.webp';
  static const String vip$level_welfare_upgrade_icon_webp =
      'packages/vip/assets/images/level/welfare_upgrade_icon.webp';

  static const String mall_bg_bubble_webp = 'assets/images/mall/bg_bubble.webp';
  static const String vip$mall_bg_bubble_webp =
      'packages/vip/assets/images/mall/bg_bubble.webp';

  static const String mall_bg_decorate_webp =
      'assets/images/mall/bg_decorate.webp';
  static const String vip$mall_bg_decorate_webp =
      'packages/vip/assets/images/mall/bg_decorate.webp';

  static const String mall_bg_light_webp = 'assets/images/mall/bg_light.webp';
  static const String vip$mall_bg_light_webp =
      'packages/vip/assets/images/mall/bg_light.webp';

  static const String mall_collection_buy_bg_webp =
      'assets/images/mall/collection_buy_bg.webp';
  static const String vip$mall_collection_buy_bg_webp =
      'packages/vip/assets/images/mall/collection_buy_bg.webp';

  static const String mall_collection_buy_bg_dark_webp =
      'assets/images/mall/collection_buy_bg_dark.webp';
  static const String vip$mall_collection_buy_bg_dark_webp =
      'packages/vip/assets/images/mall/collection_buy_bg_dark.webp';

  static const String mall_func_waiting_webp =
      'assets/images/mall/func_waiting.webp';
  static const String vip$mall_func_waiting_webp =
      'packages/vip/assets/images/mall/func_waiting.webp';

  static const String mall_header_bg_webp = 'assets/images/mall/header_bg.webp';
  static const String vip$mall_header_bg_webp =
      'packages/vip/assets/images/mall/header_bg.webp';

  static const String mall_header_bg_dark_webp =
      'assets/images/mall/header_bg_dark.webp';
  static const String vip$mall_header_bg_dark_webp =
      'packages/vip/assets/images/mall/header_bg_dark.webp';

  static const String mall_ic_arrow_svg = 'assets/images/mall/ic_arrow.svg';
  static const String vip$mall_ic_arrow_svg =
      'packages/vip/assets/images/mall/ic_arrow.svg';

  static const String mall_ic_diy_png = 'assets/images/mall/ic_diy.png';
  static const String vip$mall_ic_diy_png =
      'packages/vip/assets/images/mall/ic_diy.png';

  static const String mall_ic_diy_dark_png =
      'assets/images/mall/ic_diy_dark.png';
  static const String vip$mall_ic_diy_dark_png =
      'packages/vip/assets/images/mall/ic_diy_dark.png';

  static const String mall_ic_dropdown_svg =
      'assets/images/mall/ic_dropdown.svg';
  static const String vip$mall_ic_dropdown_svg =
      'packages/vip/assets/images/mall/ic_dropdown.svg';

  static const String mall_ic_gift_svg = 'assets/images/mall/ic_gift.svg';
  static const String vip$mall_ic_gift_svg =
      'packages/vip/assets/images/mall/ic_gift.svg';

  static const String mall_ic_question_mark_svg =
      'assets/images/mall/ic_question_mark.svg';
  static const String vip$mall_ic_question_mark_svg =
      'packages/vip/assets/images/mall/ic_question_mark.svg';

  static const String mount_bg_exchange_success_png =
      'assets/images/mount/bg_exchange_success.png';
  static const String vip$mount_bg_exchange_success_png =
      'packages/vip/assets/images/mount/bg_exchange_success.png';

  static const String mount_ic_lock_png = 'assets/images/mount/ic_lock.png';
  static const String vip$mount_ic_lock_png =
      'packages/vip/assets/images/mount/ic_lock.png';

  static const String mount_ic_mount_piece_png =
      'assets/images/mount/ic_mount_piece.png';
  static const String vip$mount_ic_mount_piece_png =
      'packages/vip/assets/images/mount/ic_mount_piece.png';

  static const String mount_ic_piece_png = 'assets/images/mount/ic_piece.png';
  static const String vip$mount_ic_piece_png =
      'packages/vip/assets/images/mount/ic_piece.png';

  static const String mount_ic_play_png = 'assets/images/mount/ic_play.png';
  static const String vip$mount_ic_play_png =
      'packages/vip/assets/images/mount/ic_play.png';

  static const String mount_rank_1_webp = 'assets/images/mount/rank_1.webp';
  static const String vip$mount_rank_1_webp =
      'packages/vip/assets/images/mount/rank_1.webp';

  static const String mount_rank_2_webp = 'assets/images/mount/rank_2.webp';
  static const String vip$mount_rank_2_webp =
      'packages/vip/assets/images/mount/rank_2.webp';

  static const String mount_rank_3_webp = 'assets/images/mount/rank_3.webp';
  static const String vip$mount_rank_3_webp =
      'packages/vip/assets/images/mount/rank_3.webp';

  static const String mount_top_light_png = 'assets/images/mount/top_light.png';
  static const String vip$mount_top_light_png =
      'packages/vip/assets/images/mount/top_light.png';

  static const String mount_top_mount_base_png =
      'assets/images/mount/top_mount_base.png';
  static const String vip$mount_top_mount_base_png =
      'packages/vip/assets/images/mount/top_mount_base.png';

  static const String mount_top_mount_shadow_png =
      'assets/images/mount/top_mount_shadow.png';
  static const String vip$mount_top_mount_shadow_png =
      'packages/vip/assets/images/mount/top_mount_shadow.png';

  static const String next_level_tip_star_left_svg =
      'assets/images/next_level_tip_star_left.svg';
  static const String vip$next_level_tip_star_left_svg =
      'packages/vip/assets/images/next_level_tip_star_left.svg';

  static const String next_level_tip_star_right_svg =
      'assets/images/next_level_tip_star_right.svg';
  static const String vip$next_level_tip_star_right_svg =
      'packages/vip/assets/images/next_level_tip_star_right.svg';

  static const String noble_nobility_activity_arrow_webp =
      'assets/images/noble/nobility_activity_arrow.webp';
  static const String vip$noble_nobility_activity_arrow_webp =
      'packages/vip/assets/images/noble/nobility_activity_arrow.webp';

  static const String noble_nobility_activity_bg_webp =
      'assets/images/noble/nobility_activity_bg.webp';
  static const String vip$noble_nobility_activity_bg_webp =
      'packages/vip/assets/images/noble/nobility_activity_bg.webp';

  static const String noble_nobility_activity_buy_webp =
      'assets/images/noble/nobility_activity_buy.webp';
  static const String vip$noble_nobility_activity_buy_webp =
      'packages/vip/assets/images/noble/nobility_activity_buy.webp';

  static const String noble_nobility_activity_buy_disable_webp =
      'assets/images/noble/nobility_activity_buy_disable.webp';
  static const String vip$noble_nobility_activity_buy_disable_webp =
      'packages/vip/assets/images/noble/nobility_activity_buy_disable.webp';

  static const String noble_nobility_activity_close_webp =
      'assets/images/noble/nobility_activity_close.webp';
  static const String vip$noble_nobility_activity_close_webp =
      'packages/vip/assets/images/noble/nobility_activity_close.webp';

  static const String noble_nobility_activity_des_webp =
      'assets/images/noble/nobility_activity_des.webp';
  static const String vip$noble_nobility_activity_des_webp =
      'packages/vip/assets/images/noble/nobility_activity_des.webp';

  static const String noble_nobility_activity_extra_left_webp =
      'assets/images/noble/nobility_activity_extra_left.webp';
  static const String vip$noble_nobility_activity_extra_left_webp =
      'packages/vip/assets/images/noble/nobility_activity_extra_left.webp';

  static const String noble_nobility_activity_extra_right_webp =
      'assets/images/noble/nobility_activity_extra_right.webp';
  static const String vip$noble_nobility_activity_extra_right_webp =
      'packages/vip/assets/images/noble/nobility_activity_extra_right.webp';

  static const String noble_nobility_activity_icon_bg_webp =
      'assets/images/noble/nobility_activity_icon_bg.webp';
  static const String vip$noble_nobility_activity_icon_bg_webp =
      'packages/vip/assets/images/noble/nobility_activity_icon_bg.webp';

  static const String noble_nobility_activity_litter_bg_webp =
      'assets/images/noble/nobility_activity_litter_bg.webp';
  static const String vip$noble_nobility_activity_litter_bg_webp =
      'packages/vip/assets/images/noble/nobility_activity_litter_bg.webp';

  static const String noble_nobility_activity_mini_bg_webp =
      'assets/images/noble/nobility_activity_mini_bg.webp';
  static const String vip$noble_nobility_activity_mini_bg_webp =
      'packages/vip/assets/images/noble/nobility_activity_mini_bg.webp';

  static const String noble_nobility_activity_time_bg_webp =
      'assets/images/noble/nobility_activity_time_bg.webp';
  static const String vip$noble_nobility_activity_time_bg_webp =
      'packages/vip/assets/images/noble/nobility_activity_time_bg.webp';

  static const String noble_nobility_activity_title_webp =
      'assets/images/noble/nobility_activity_title.webp';
  static const String vip$noble_nobility_activity_title_webp =
      'packages/vip/assets/images/noble/nobility_activity_title.webp';

  static const String noble_noble_new_tag_webp =
      'assets/images/noble/noble_new_tag.webp';
  static const String vip$noble_noble_new_tag_webp =
      'packages/vip/assets/images/noble/noble_new_tag.webp';

  static const String privilege_auto_year_opened_webp =
      'assets/images/privilege_auto_year_opened.webp';
  static const String vip$privilege_auto_year_opened_webp =
      'packages/vip/assets/images/privilege_auto_year_opened.webp';

  static const String privilege_card_bg_webp =
      'assets/images/privilege_card_bg.webp';
  static const String vip$privilege_card_bg_webp =
      'packages/vip/assets/images/privilege_card_bg.webp';

  static const String privilege_detail_close_webp =
      'assets/images/privilege_detail_close.webp';
  static const String vip$privilege_detail_close_webp =
      'packages/vip/assets/images/privilege_detail_close.webp';

  static const String privilege_renew_button_webp =
      'assets/images/privilege_renew_button.webp';
  static const String vip$privilege_renew_button_webp =
      'packages/vip/assets/images/privilege_renew_button.webp';

  static const String privilege_title_webp =
      'assets/images/privilege_title.webp';
  static const String vip$privilege_title_webp =
      'packages/vip/assets/images/privilege_title.webp';

  static const String privilege_upgrade_auto_year_webp =
      'assets/images/privilege_upgrade_auto_year.webp';
  static const String vip$privilege_upgrade_auto_year_webp =
      'packages/vip/assets/images/privilege_upgrade_auto_year.webp';

  static const String title_add_popularity_svg =
      'assets/images/title_add_popularity.svg';
  static const String vip$title_add_popularity_svg =
      'packages/vip/assets/images/title_add_popularity.svg';

  static const String title_anti_kick_out_svg =
      'assets/images/title_anti_kick_out.svg';
  static const String vip$title_anti_kick_out_svg =
      'packages/vip/assets/images/title_anti_kick_out.svg';

  static const String title_create_fleet_svg =
      'assets/images/title_create_fleet.svg';
  static const String vip$title_create_fleet_svg =
      'packages/vip/assets/images/title_create_fleet.svg';

  static const String title_enter_quitely_svg =
      'assets/images/title_enter_quitely.svg';
  static const String vip$title_enter_quitely_svg =
      'packages/vip/assets/images/title_enter_quitely.svg';

  static const String title_enter_welcome_svg =
      'assets/images/title_enter_welcome.svg';
  static const String vip$title_enter_welcome_svg =
      'packages/vip/assets/images/title_enter_welcome.svg';

  static const String title_global_badge_svg =
      'assets/images/title_global_badge.svg';
  static const String vip$title_global_badge_svg =
      'packages/vip/assets/images/title_global_badge.svg';

  static const String title_global_notice_svg =
      'assets/images/title_global_notice.svg';
  static const String vip$title_global_notice_svg =
      'packages/vip/assets/images/title_global_notice.svg';

  static const String title_invisible_in_rank_svg =
      'assets/images/title_invisible_in_rank.svg';
  static const String vip$title_invisible_in_rank_svg =
      'packages/vip/assets/images/title_invisible_in_rank.svg';

  static const String title_special_room_svg =
      'assets/images/title_special_room.svg';
  static const String vip$title_special_room_svg =
      'packages/vip/assets/images/title_special_room.svg';

  static const String title_vip_speed_up_svg =
      'assets/images/title_vip_speed_up.svg';
  static const String vip$title_vip_speed_up_svg =
      'packages/vip/assets/images/title_vip_speed_up.svg';

  static const String vip_bag_break_webp = 'assets/images/vip_bag_break.webp';
  static const String vip$vip_bag_break_webp =
      'packages/vip/assets/images/vip_bag_break.webp';

  static const String vip_dress_arrow_right_webp =
      'assets/images/vip_dress_arrow_right.webp';
  static const String vip$vip_dress_arrow_right_webp =
      'packages/vip/assets/images/vip_dress_arrow_right.webp';

  static const String vip_dress_bg_center_webp =
      'assets/images/vip_dress_bg_center.webp';
  static const String vip$vip_dress_bg_center_webp =
      'packages/vip/assets/images/vip_dress_bg_center.webp';

  static const String vip_dress_chip_webp = 'assets/images/vip_dress_chip.webp';
  static const String vip$vip_dress_chip_webp =
      'packages/vip/assets/images/vip_dress_chip.webp';
  static const String vip$vip_dress_chip_png ='packages/vip/assets/images/vip_dress_chip.png';

  static const String vip_dress_lock_webp = 'assets/images/vip_dress_lock.webp';
  static const String vip$vip_dress_lock_webp =
      'packages/vip/assets/images/vip_dress_lock.webp';

  static const String vip_dress_star_webp = 'assets/images/vip_dress_star.webp';
  static const String vip$vip_dress_star_webp =
      'packages/vip/assets/images/vip_dress_star.webp';

  static const String vip_dress_time_webp = 'assets/images/vip_dress_time.webp';
  static const String vip$vip_dress_time_webp =
      'packages/vip/assets/images/vip_dress_time.webp';

  static const String vip_head_webp = 'assets/images/vip_head.webp';
  static const String vip$vip_head_webp =
      'packages/vip/assets/images/vip_head.webp';

  static const String vip_head_gray_webp = 'assets/images/vip_head_gray.webp';
  static const String vip$vip_head_gray_webp =
      'packages/vip/assets/images/vip_head_gray.webp';

  static const String vip_ic_note_svg = 'assets/images/vip_ic_note.svg';
  static const String vip$vip_ic_note_svg =
      'packages/vip/assets/images/vip_ic_note.svg';

  static const String vip_kefu_svg = 'assets/images/vip_kefu.svg';
  static const String vip$vip_kefu_svg =
      'packages/vip/assets/images/vip_kefu.svg';

  static const String vip_room_badge_svg = 'assets/images/vip_room_badge.svg';
  static const String vip$vip_room_badge_svg =
      'packages/vip/assets/images/vip_room_badge.svg';

  static const String x4_x4_button_badge_webp =
      'assets/images/x4/x4_button_badge.webp';
  static const String vip$x4_x4_button_badge_webp =
      'packages/vip/assets/images/x4/x4_button_badge.webp';

  static const String x4_x4_button_bg_webp =
      'assets/images/x4/x4_button_bg.webp';
  static const String vip$x4_x4_button_bg_webp =
      'packages/vip/assets/images/x4/x4_button_bg.webp';

  static const String x4_x4_button_disable_bg_webp =
      'assets/images/x4/x4_button_disable_bg.webp';
  static const String vip$x4_x4_button_disable_bg_webp =
      'packages/vip/assets/images/x4/x4_button_disable_bg.webp';

  static const String x4_x4_button_fg_webp =
      'assets/images/x4/x4_button_fg.webp';
  static const String vip$x4_x4_button_fg_webp =
      'packages/vip/assets/images/x4/x4_button_fg.webp';

  static const String x4_x4_content_bg_webp =
      'assets/images/x4/x4_content_bg.webp';
  static const String vip$x4_x4_content_bg_webp =
      'packages/vip/assets/images/x4/x4_content_bg.webp';

  static const String x4_x4_dialog_bg_webp =
      'assets/images/x4/x4_dialog_bg.webp';
  static const String vip$x4_x4_dialog_bg_webp =
      'packages/vip/assets/images/x4/x4_dialog_bg.webp';

  static const String x4_x4_dialog_fg_webp =
      'assets/images/x4/x4_dialog_fg.webp';
  static const String vip$x4_x4_dialog_fg_webp =
      'packages/vip/assets/images/x4/x4_dialog_fg.webp';

  static const String x4_x4_float_bg_webp = 'assets/images/x4/x4_float_bg.webp';
  static const String vip$x4_x4_float_bg_webp =
      'packages/vip/assets/images/x4/x4_float_bg.webp';

  static const String left_icon_tips = 'assets/images/left_icon_tips.png';
  static const String vip$left_icon_tips =
      'packages/vip/assets/images/left_icon_tips.png';
  static const String right_icon_tips = 'assets/images/right_icon_tips.png';
  static const String vip$right_icon_tips =
      'packages/vip/assets/images/right_icon_tips.png';

  static const String icon_v_0_vip = 'assets/images/icon_v_0_vip.png';
  static const String vip$icon_v_0_vip =
      'packages/vip/assets/images/icon_v_0_vip.png';

  static const String icon_v_1_vip = 'assets/images/icon_v_1_vip.png';
  static const String vip$icon_v_1_vip =
      'packages/vip/assets/images/icon_v_1_vip.png';

  static const String icon_v_2_vip = 'assets/images/icon_v_2_vip.png';
  static const String vip$icon_v_2_vip =
      'packages/vip/assets/images/icon_v_2_vip.png';

  static const String icon_v_3_vip = 'assets/images/icon_v_3_vip.png';
  static const String vip$icon_v_3_vip =
      'packages/vip/assets/images/icon_v_3_vip.png';

  static const String icon_v_4_vip = 'assets/images/icon_v_4_vip.png';
  static const String vip$icon_v_4_vip =
      'packages/vip/assets/images/icon_v_4_vip.png';

  static const String icon_v_5_vip = 'assets/images/icon_v_5_vip.png';
  static const String vip$icon_v_5_vip =
      'packages/vip/assets/images/icon_v_5_vip.png';

  static const String icon_v_6_vip = 'assets/images/icon_v_6_vip.png';
  static const String vip$icon_v_6_vip =
      'packages/vip/assets/images/icon_v_6_vip.png';

  static const String icon_v_7_vip = 'assets/images/icon_v_7_vip.png';
  static const String vip$icon_v_7_vip =
      'packages/vip/assets/images/icon_v_7_vip.png';

  static const String guizu_bg_new = 'assets/images/guizu_bg_new.webp';
  static const String vip$guizu_bg_new =
      'packages/vip/assets/images/guizu_bg_new.webp';

  static const String vip_dress_bg_new = 'assets/images/vip_dress_bg_new.webp';
  static const String vip$vip_dress_bg_new =
      'packages/vip/assets/images/vip_dress_bg_new.webp';

  static const String zhuangban_bottom_bg =
      'assets/images/zhuangban_bottom_bg.png';
  static const String vip$zhuangban_bottom_bg =
      'packages/vip/assets/images/zhuangban_bottom_bg.png';

  static const String vip_big_bg = 'assets/images/vipBigBg.png';
  static const String vip$vip_big_bg =
      'packages/vip/assets/images/vipBigBg.png';
}
