name: rtc_audio_effects
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: ">=2.13.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: ly.plugins.rtc_audio_effects
        pluginClass: RtcAudioEffectPlugin
      ios:
        pluginClass: RtcAudioEffectPlugin
