// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 306.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class BaseAssets {
  static const String package = 'shared';

  static const String accost_notify_bg_female_webp =
      'assets/images/accost_notify_bg_female.webp';
  static const String shared$accost_notify_bg_female_webp =
      'packages/shared/assets/images/accost_notify_bg_female.webp';

  static const String accost_notify_bg_male_webp =
      'assets/images/accost_notify_bg_male.webp';
  static const String shared$accost_notify_bg_male_webp =
      'packages/shared/assets/images/accost_notify_bg_male.webp';

  static const String anim_living_webp = 'assets/images/anim_living.webp';
  static const String shared$anim_living_webp =
      'packages/shared/assets/images/anim_living.webp';

  static const String anim_unlike_webp = 'assets/images/anim_unlike.webp';
  static const String shared$anim_unlike_webp =
      'packages/shared/assets/images/anim_unlike.webp';

  static const String avatar_in_room_webp = 'assets/images/avatar_in_room.webp';
  static const String shared$avatar_in_room_webp =
      'packages/shared/assets/images/avatar_in_room.webp';

  static const String bb_gift_png = 'assets/images/bb_gift.png';
  static const String shared$bb_gift_png =
      'packages/shared/assets/images/bb_gift.png';

  static const String bb_null_webp = 'assets/images/bb_null.webp';
  static const String shared$bb_null_webp =
      'packages/shared/assets/images/bb_null.webp';

  static const String bb_pretty_id_webp = 'assets/images/bb_pretty_id.webp';
  static const String shared$bb_pretty_id_webp =
      'packages/shared/assets/images/bb_pretty_id.webp';

  static const String bg_colorful_name_level_3_png =
      'assets/images/bg_colorful_name_level_3.png';
  static const String shared$bg_colorful_name_level_3_png =
      'packages/shared/assets/images/bg_colorful_name_level_3.png';

  static const String bg_dotted_line_svg = 'assets/images/bg_dotted_line.svg';
  static const String shared$bg_dotted_line_svg =
      'packages/shared/assets/images/bg_dotted_line.svg';

  static const String bg_error_data_svg = 'assets/images/bg_error_data.svg';
  static const String shared$bg_error_data_svg =
      'packages/shared/assets/images/bg_error_data.svg';

  static const String box_first_charge_bg_webp =
      'assets/images/box/first_charge_bg.webp';
  static const String shared$box_first_charge_bg_webp =
      'packages/shared/assets/images/box/first_charge_bg.webp';

  static const String box_first_charge_left_coin_webp =
      'assets/images/box/first_charge_left_coin.webp';
  static const String shared$box_first_charge_left_coin_webp =
      'packages/shared/assets/images/box/first_charge_left_coin.webp';

  static const String box_first_charge_rect_webp =
      'assets/images/box/first_charge_rect.webp';
  static const String shared$box_first_charge_rect_webp =
      'packages/shared/assets/images/box/first_charge_rect.webp';

  static const String box_first_charge_right_coin_webp =
      'assets/images/box/first_charge_right_coin.webp';
  static const String shared$box_first_charge_right_coin_webp =
      'packages/shared/assets/images/box/first_charge_right_coin.webp';

  static const String box_first_charge_title_bg_webp =
      'assets/images/box/first_charge_title_bg.webp';
  static const String shared$box_first_charge_title_bg_webp =
      'packages/shared/assets/images/box/first_charge_title_bg.webp';

  static const String box_first_charge_top_webp =
      'assets/images/box/first_charge_top.webp';
  static const String shared$box_first_charge_top_webp =
      'packages/shared/assets/images/box/first_charge_top.webp';

  static const String box_ic_close_svg = 'assets/images/box/ic_close.svg';
  static const String shared$box_ic_close_svg =
      'packages/shared/assets/images/box/ic_close.svg';

  static const String box_ic_close_w_png = 'assets/images/box/ic_close_w.png';
  static const String shared$box_ic_close_w_png =
      'packages/shared/assets/images/box/ic_close_w.png';

  static const String box_ic_next_small_svg =
      'assets/images/box/ic_next_small.svg';
  static const String shared$box_ic_next_small_svg =
      'packages/shared/assets/images/box/ic_next_small.svg';

  static const String box_package_bottom_bg_webp =
      'assets/images/box/package_bottom_bg.webp';
  static const String shared$box_package_bottom_bg_webp =
      'packages/shared/assets/images/box/package_bottom_bg.webp';

  static const String box_pop_circle_close_webp =
      'assets/images/box/pop_circle_close.webp';
  static const String shared$box_pop_circle_close_webp =
      'packages/shared/assets/images/box/pop_circle_close.webp';

  static const String btn_back_d_png = 'assets/images/btn_back_d.png';
  static const String shared$btn_back_d_png =
      'packages/shared/assets/images/btn_back_d.png';

  static const String btn_back_white_png = 'assets/images/btn_back_white.png';
  static const String shared$btn_back_white_png =
      'packages/shared/assets/images/btn_back_white.png';

  static const String btn_chat_svg = 'assets/images/btn_chat.svg';
  static const String shared$btn_chat_svg =
      'packages/shared/assets/images/btn_chat.svg';

  static const String btn_close_black_png = 'assets/images/btn_close_black.png';
  static const String shared$btn_close_black_png =
      'packages/shared/assets/images/btn_close_black.png';

  static const String char_bar_login_bg_webp =
      'assets/images/char_bar_login_bg.webp';
  static const String shared$char_bar_login_bg_webp =
      'packages/shared/assets/images/char_bar_login_bg.webp';

  static const String char_bar_login_logo_webp =
      'assets/images/char_bar_login_logo.webp';
  static const String shared$char_bar_login_logo_webp =
      'packages/shared/assets/images/char_bar_login_logo.webp';

  static const String chat_card_audio_anim_webp =
      'assets/images/chat_card_audio_anim.webp';
  static const String shared$chat_card_audio_anim_webp =
      'packages/shared/assets/images/chat_card_audio_anim.webp';

  static const String chat_card_audio_play_webp =
      'assets/images/chat_card_audio_play.webp';
  static const String shared$chat_card_audio_play_webp =
      'packages/shared/assets/images/chat_card_audio_play.webp';

  static const String chat_card_audio_stop_webp =
      'assets/images/chat_card_audio_stop.webp';
  static const String shared$chat_card_audio_stop_webp =
      'packages/shared/assets/images/chat_card_audio_stop.webp';

  static const String chat_friend_audio_default_png =
      'assets/images/chat_friend_audio_default.png';
  static const String shared$chat_friend_audio_default_png =
      'packages/shared/assets/images/chat_friend_audio_default.png';

  static const String chat_record_default_icon_png =
      'assets/images/chat_record_default_icon.png';
  static const String shared$chat_record_default_icon_png =
      'packages/shared/assets/images/chat_record_default_icon.png';

  static const String close_icon_svg = 'assets/images/close_icon.svg';
  static const String shared$close_icon_svg =
      'packages/shared/assets/images/close_icon.svg';

  static const String common_rank_1_webp = 'assets/images/common_rank_1.webp';
  static const String shared$common_rank_1_webp =
      'packages/shared/assets/images/common_rank_1.webp';

  static const String common_rank_2_webp = 'assets/images/common_rank_2.webp';
  static const String shared$common_rank_2_webp =
      'packages/shared/assets/images/common_rank_2.webp';

  static const String common_rank_3_webp = 'assets/images/common_rank_3.webp';
  static const String shared$common_rank_3_webp =
      'packages/shared/assets/images/common_rank_3.webp';

  static const String core_common_sex_female_webp =
      'assets/images/core_common_sex_female.webp';
  static const String shared$core_common_sex_female_webp =
      'packages/shared/assets/images/core_common_sex_female.webp';

  static const String core_common_sex_male_webp =
      'assets/images/core_common_sex_male.webp';
  static const String shared$core_common_sex_male_webp =
      'packages/shared/assets/images/core_common_sex_male.webp';

  static const String dropdown_cancel_png = 'assets/images/dropdown_cancel.png';
  static const String shared$dropdown_cancel_png =
      'packages/shared/assets/images/dropdown_cancel.png';

  static const String dropdown_error_png = 'assets/images/dropdown_error.png';
  static const String shared$dropdown_error_png =
      'packages/shared/assets/images/dropdown_error.png';

  static const String dropdown_info_png = 'assets/images/dropdown_info.png';
  static const String shared$dropdown_info_png =
      'packages/shared/assets/images/dropdown_info.png';

  static const String dropdown_order_notify_png =
      'assets/images/dropdown_order_notify.png';
  static const String shared$dropdown_order_notify_png =
      'packages/shared/assets/images/dropdown_order_notify.png';

  static const String dropdown_room_notify_bottom_png =
      'assets/images/dropdown_room_notify_bottom.png';
  static const String shared$dropdown_room_notify_bottom_png =
      'packages/shared/assets/images/dropdown_room_notify_bottom.png';

  static const String dropdown_room_notify_top_png =
      'assets/images/dropdown_room_notify_top.png';
  static const String shared$dropdown_room_notify_top_png =
      'packages/shared/assets/images/dropdown_room_notify_top.png';

  static const String dropdown_success_png =
      'assets/images/dropdown_success.png';
  static const String shared$dropdown_success_png =
      'packages/shared/assets/images/dropdown_success.png';

  static const String dropdown_warn_png = 'assets/images/dropdown_warn.png';
  static const String shared$dropdown_warn_png =
      'packages/shared/assets/images/dropdown_warn.png';

  static const String emotion_ic_emotion_select_user_png =
      'assets/images/emotion/ic_emotion_select_user.png';
  static const String shared$emotion_ic_emotion_select_user_png =
      'packages/shared/assets/images/emotion/ic_emotion_select_user.png';

  static const String emotion_ic_extend_user_webp =
      'assets/images/emotion/ic_extend_user.webp';
  static const String shared$emotion_ic_extend_user_webp =
      'packages/shared/assets/images/emotion/ic_extend_user.webp';

  static const String error_data_webp = 'assets/images/error_data.webp';
  static const String shared$error_data_webp =
      'packages/shared/assets/images/error_data.webp';

  static const String gift_king_tail_bg_webp =
      'assets/images/gift_king_tail_bg.webp';
  static const String shared$gift_king_tail_bg_webp =
      'packages/shared/assets/images/gift_king_tail_bg.webp';

  static const String gift_king_tail_bottom_webp =
      'assets/images/gift_king_tail_bottom.webp';
  static const String shared$gift_king_tail_bottom_webp =
      'packages/shared/assets/images/gift_king_tail_bottom.webp';

  static const String gift_king_tail_top_webp =
      'assets/images/gift_king_tail_top.webp';
  static const String shared$gift_king_tail_top_webp =
      'packages/shared/assets/images/gift_king_tail_top.webp';

  static const String giftbook_gift_book_level_1_webp =
      'assets/images/giftbook/gift_book_level_1.webp';
  static const String shared$giftbook_gift_book_level_1_webp =
      'packages/shared/assets/images/giftbook/gift_book_level_1.webp';

  static const String giftbook_gift_book_level_2_webp =
      'assets/images/giftbook/gift_book_level_2.webp';
  static const String shared$giftbook_gift_book_level_2_webp =
      'packages/shared/assets/images/giftbook/gift_book_level_2.webp';

  static const String giftbook_gift_book_level_3_webp =
      'assets/images/giftbook/gift_book_level_3.webp';
  static const String shared$giftbook_gift_book_level_3_webp =
      'packages/shared/assets/images/giftbook/gift_book_level_3.webp';

  static const String giftbook_gift_book_level_4_webp =
      'assets/images/giftbook/gift_book_level_4.webp';
  static const String shared$giftbook_gift_book_level_4_webp =
      'packages/shared/assets/images/giftbook/gift_book_level_4.webp';

  static const String giftbook_gift_book_level_5_webp =
      'assets/images/giftbook/gift_book_level_5.webp';
  static const String shared$giftbook_gift_book_level_5_webp =
      'packages/shared/assets/images/giftbook/gift_book_level_5.webp';

  static const String handbook_level_0_0_webp =
      'assets/images/handbook_level/0-0.webp';
  static const String shared$handbook_level_0_0_webp =
      'packages/shared/assets/images/handbook_level/0-0.webp';

  static const String handbook_level_0_1_webp =
      'assets/images/handbook_level/0-1.webp';
  static const String shared$handbook_level_0_1_webp =
      'packages/shared/assets/images/handbook_level/0-1.webp';

  static const String handbook_level_0_2_webp =
      'assets/images/handbook_level/0-2.webp';
  static const String shared$handbook_level_0_2_webp =
      'packages/shared/assets/images/handbook_level/0-2.webp';

  static const String handbook_level_1_0_webp =
      'assets/images/handbook_level/1-0.webp';
  static const String shared$handbook_level_1_0_webp =
      'packages/shared/assets/images/handbook_level/1-0.webp';

  static const String handbook_level_1_1_webp =
      'assets/images/handbook_level/1-1.webp';
  static const String shared$handbook_level_1_1_webp =
      'packages/shared/assets/images/handbook_level/1-1.webp';

  static const String handbook_level_1_2_webp =
      'assets/images/handbook_level/1-2.webp';
  static const String shared$handbook_level_1_2_webp =
      'packages/shared/assets/images/handbook_level/1-2.webp';

  static const String handbook_level_2_0_webp =
      'assets/images/handbook_level/2-0.webp';
  static const String shared$handbook_level_2_0_webp =
      'packages/shared/assets/images/handbook_level/2-0.webp';

  static const String handbook_level_2_1_webp =
      'assets/images/handbook_level/2-1.webp';
  static const String shared$handbook_level_2_1_webp =
      'packages/shared/assets/images/handbook_level/2-1.webp';

  static const String handbook_level_2_2_webp =
      'assets/images/handbook_level/2-2.webp';
  static const String shared$handbook_level_2_2_webp =
      'packages/shared/assets/images/handbook_level/2-2.webp';

  static const String handbook_level_3_0_webp =
      'assets/images/handbook_level/3-0.webp';
  static const String shared$handbook_level_3_0_webp =
      'packages/shared/assets/images/handbook_level/3-0.webp';

  static const String handbook_level_3_1_webp =
      'assets/images/handbook_level/3-1.webp';
  static const String shared$handbook_level_3_1_webp =
      'packages/shared/assets/images/handbook_level/3-1.webp';

  static const String handbook_level_3_2_webp =
      'assets/images/handbook_level/3-2.webp';
  static const String shared$handbook_level_3_2_webp =
      'packages/shared/assets/images/handbook_level/3-2.webp';

  static const String handbook_level_4_0_webp =
      'assets/images/handbook_level/4-0.webp';
  static const String shared$handbook_level_4_0_webp =
      'packages/shared/assets/images/handbook_level/4-0.webp';

  static const String handbook_level_4_1_webp =
      'assets/images/handbook_level/4-1.webp';
  static const String shared$handbook_level_4_1_webp =
      'packages/shared/assets/images/handbook_level/4-1.webp';

  static const String handbook_level_4_2_webp =
      'assets/images/handbook_level/4-2.webp';
  static const String shared$handbook_level_4_2_webp =
      'packages/shared/assets/images/handbook_level/4-2.webp';

  static const String handbook_level_5_0_webp =
      'assets/images/handbook_level/5-0.webp';
  static const String shared$handbook_level_5_0_webp =
      'packages/shared/assets/images/handbook_level/5-0.webp';

  static const String handbook_level_5_1_webp =
      'assets/images/handbook_level/5-1.webp';
  static const String shared$handbook_level_5_1_webp =
      'packages/shared/assets/images/handbook_level/5-1.webp';

  static const String handbook_level_5_2_webp =
      'assets/images/handbook_level/5-2.webp';
  static const String shared$handbook_level_5_2_webp =
      'packages/shared/assets/images/handbook_level/5-2.webp';

  static const String have_fun_id_svg = 'assets/images/have_fun_id.svg';
  static const String shared$have_fun_id_svg =
      'packages/shared/assets/images/have_fun_id.svg';

  static const String home_bg_friend_in_room_webp =
      'assets/images/home/bg_friend_in_room.webp';
  static const String shared$home_bg_friend_in_room_webp =
      'packages/shared/assets/images/home/bg_friend_in_room.webp';

  static const String home_bg_rcmd_friends_playing_webp =
      'assets/images/home/bg_rcmd_friends_playing.webp';
  static const String shared$home_bg_rcmd_friends_playing_webp =
      'packages/shared/assets/images/home/bg_rcmd_friends_playing.webp';

  static const String home_ic_followed_svg =
      'assets/images/home/ic_followed.svg';
  static const String shared$home_ic_followed_svg =
      'packages/shared/assets/images/home/ic_followed.svg';

  static const String home_ic_friends_playing_in_room_webp =
      'assets/images/home/ic_friends_playing_in_room.webp';
  static const String shared$home_ic_friends_playing_in_room_webp =
      'packages/shared/assets/images/home/ic_friends_playing_in_room.webp';

  static const String home_ic_rcmd_friends_playing_webp =
      'assets/images/home/ic_rcmd_friends_playing.webp';
  static const String shared$home_ic_rcmd_friends_playing_webp =
      'packages/shared/assets/images/home/ic_rcmd_friends_playing.webp';

  static const String home_ic_room_svg = 'assets/images/home/ic_room.svg';
  static const String shared$home_ic_room_svg =
      'packages/shared/assets/images/home/ic_room.svg';

  static const String home_ic_tag_right_png =
      'assets/images/home/ic_tag_right.png';
  static const String shared$home_ic_tag_right_png =
      'packages/shared/assets/images/home/ic_tag_right.png';

  static const String home_icon_chat_svg = 'assets/images/home/icon_chat.svg';
  static const String shared$home_icon_chat_svg =
      'packages/shared/assets/images/home/icon_chat.svg';

  static const String home_icon_follow_svg =
      'assets/images/home/icon_follow.svg';
  static const String shared$home_icon_follow_svg =
      'packages/shared/assets/images/home/icon_follow.svg';

  static const String home_icon_play_webp = 'assets/images/home/icon_play.webp';
  static const String shared$home_icon_play_webp =
      'packages/shared/assets/images/home/icon_play.webp';

  static const String home_icon_playing_webp =
      'assets/images/home/icon_playing.webp';
  static const String shared$home_icon_playing_webp =
      'packages/shared/assets/images/home/icon_playing.webp';

  static const String home_icon_sound_png = 'assets/images/home/icon_sound.png';
  static const String shared$home_icon_sound_png =
      'packages/shared/assets/images/home/icon_sound.png';

  static const String home_icon_sound_webp =
      'assets/images/home/icon_sound.webp';
  static const String shared$home_icon_sound_webp =
      'packages/shared/assets/images/home/icon_sound.webp';

  static const String home_icon_videoplay_svg =
      'assets/images/home/icon_videoplay.svg';
  static const String shared$home_icon_videoplay_svg =
      'packages/shared/assets/images/home/icon_videoplay.svg';

  static const String home_sound_normal_svg =
      'assets/images/home/sound_normal.svg';
  static const String shared$home_sound_normal_svg =
      'packages/shared/assets/images/home/sound_normal.svg';

  static const String home_sound_play_webp =
      'assets/images/home/sound_play.webp';
  static const String shared$home_sound_play_webp =
      'packages/shared/assets/images/home/sound_play.webp';

  static const String home_sound_record_bg_webp =
      'assets/images/home/sound_record_bg.webp';
  static const String shared$home_sound_record_bg_webp =
      'packages/shared/assets/images/home/sound_record_bg.webp';

  static const String home_sound_record_bg_dark_webp =
      'assets/images/home/sound_record_bg_dark.webp';
  static const String shared$home_sound_record_bg_dark_webp =
      'packages/shared/assets/images/home/sound_record_bg_dark.webp';

  static const String horn_global_awake_float_screen_bg_webp =
      'assets/images/horn/global_awake_float_screen_bg.webp';
  static const String shared$horn_global_awake_float_screen_bg_webp =
      'packages/shared/assets/images/horn/global_awake_float_screen_bg.webp';

  static const String horn_global_horn_float_screen_bg_webp =
      'assets/images/horn/global_horn_float_screen_bg.webp';
  static const String shared$horn_global_horn_float_screen_bg_webp =
      'packages/shared/assets/images/horn/global_horn_float_screen_bg.webp';

  static const String hot_num_svg = 'assets/images/hot_num.svg';
  static const String shared$hot_num_svg =
      'packages/shared/assets/images/hot_num.svg';

  static const String ic_ad_logo_webp = 'assets/images/ic_ad_logo.webp';
  static const String shared$ic_ad_logo_webp =
      'packages/shared/assets/images/ic_ad_logo.webp';

  static const String ic_add_png = 'assets/images/ic_add.png';
  static const String shared$ic_add_png =
      'packages/shared/assets/images/ic_add.png';

  static const String ic_add_svg = 'assets/images/ic_add.svg';
  static const String shared$ic_add_svg =
      'packages/shared/assets/images/ic_add.svg';

  static const String ic_add_num_svg = 'assets/images/ic_add_num.svg';
  static const String shared$ic_add_num_svg =
      'packages/shared/assets/images/ic_add_num.svg';

  static const String ic_add_small_webp = 'assets/images/ic_add_small.webp';
  static const String shared$ic_add_small_webp =
      'packages/shared/assets/images/ic_add_small.webp';

  static const String ic_audio_delete_svg = 'assets/images/ic_audio_delete.svg';
  static const String shared$ic_audio_delete_svg =
      'packages/shared/assets/images/ic_audio_delete.svg';

  static const String ic_audio_finish_svg = 'assets/images/ic_audio_finish.svg';
  static const String shared$ic_audio_finish_svg =
      'packages/shared/assets/images/ic_audio_finish.svg';

  static const String ic_base_pop_selected_webp =
      'assets/images/ic_base_pop_selected.webp';
  static const String shared$ic_base_pop_selected_webp =
      'packages/shared/assets/images/ic_base_pop_selected.webp';

  static const String ic_bonus_webp = 'assets/images/ic_bonus.webp';
  static const String shared$ic_bonus_webp =
      'packages/shared/assets/images/ic_bonus.webp';

  static const String ic_box_tip_arrow_down_webp =
      'assets/images/ic_box_tip_arrow_down.webp';
  static const String shared$ic_box_tip_arrow_down_webp =
      'packages/shared/assets/images/ic_box_tip_arrow_down.webp';

  static const String ic_charm_svg = 'assets/images/ic_charm.svg';
  static const String shared$ic_charm_svg =
      'packages/shared/assets/images/ic_charm.svg';

  static const String ic_check_box_selected_webp =
      'assets/images/ic_check_box_selected.webp';
  static const String shared$ic_check_box_selected_webp =
      'packages/shared/assets/images/ic_check_box_selected.webp';

  static const String ic_check_box_un_selected_webp =
      'assets/images/ic_check_box_un_selected.webp';
  static const String shared$ic_check_box_un_selected_webp =
      'packages/shared/assets/images/ic_check_box_un_selected.webp';

  static const String ic_checkbox_selected_svg =
      'assets/images/ic_checkbox_selected.svg';
  static const String shared$ic_checkbox_selected_svg =
      'packages/shared/assets/images/ic_checkbox_selected.svg';

  static const String ic_clear_svg = 'assets/images/ic_clear.svg';
  static const String shared$ic_clear_svg =
      'packages/shared/assets/images/ic_clear.svg';

  static const String ic_close_svg = 'assets/images/ic_close.svg';
  static const String shared$ic_close_svg =
      'packages/shared/assets/images/ic_close.svg';

  static const String ic_close_a_svg = 'assets/images/ic_close_a.svg';
  static const String shared$ic_close_a_svg =
      'packages/shared/assets/images/ic_close_a.svg';

  static const String ic_close_circle_border_webp =
      'assets/images/ic_close_circle_border.webp';
  static const String shared$ic_close_circle_border_webp =
      'packages/shared/assets/images/ic_close_circle_border.webp';

  static const String ic_close_with_circle_border_svg =
      'assets/images/ic_close_with_circle_border.svg';
  static const String shared$ic_close_with_circle_border_svg =
      'packages/shared/assets/images/ic_close_with_circle_border.svg';

  static const String ic_coin_png = 'assets/images/ic_coin.png';
  static const String shared$ic_coin_png =
      'packages/shared/assets/images/ic_coin.png';

  static const String ic_consume_label_webp =
      'assets/images/ic_consume_label.webp';
  static const String shared$ic_consume_label_webp =
      'packages/shared/assets/images/ic_consume_label.webp';

  static const String ic_copy_svg = 'assets/images/ic_copy.svg';
  static const String shared$ic_copy_svg =
      'packages/shared/assets/images/ic_copy.svg';

  static const String ic_cross_pk_star_webp =
      'assets/images/ic_cross_pk_star.webp';
  static const String shared$ic_cross_pk_star_webp =
      'packages/shared/assets/images/ic_cross_pk_star.webp';

  static const String ic_cross_pk_star_l_webp =
      'assets/images/ic_cross_pk_star_l.webp';
  static const String shared$ic_cross_pk_star_l_webp =
      'packages/shared/assets/images/ic_cross_pk_star_l.webp';

  static const String ic_cross_pk_star_s_webp =
      'assets/images/ic_cross_pk_star_s.webp';
  static const String shared$ic_cross_pk_star_s_webp =
      'packages/shared/assets/images/ic_cross_pk_star_s.webp';

  static const String ic_cross_pk_star_s_l_webp =
      'assets/images/ic_cross_pk_star_s_l.webp';
  static const String shared$ic_cross_pk_star_s_l_webp =
      'packages/shared/assets/images/ic_cross_pk_star_s_l.webp';

  static const String ic_delete_svg = 'assets/images/ic_delete.svg';
  static const String shared$ic_delete_svg =
      'packages/shared/assets/images/ic_delete.svg';

  static const String ic_delete_small_svg = 'assets/images/ic_delete_small.svg';
  static const String shared$ic_delete_small_svg =
      'packages/shared/assets/images/ic_delete_small.svg';

  static const String ic_dialog_close_png = 'assets/images/ic_dialog_close.png';
  static const String shared$ic_dialog_close_png =
      'packages/shared/assets/images/ic_dialog_close.png';

  static const String ic_diamond_webp = 'assets/images/ic_diamond.webp';
  static const String shared$ic_diamond_webp =
      'packages/shared/assets/images/ic_diamond.webp';

  static const String ic_edit_svg = 'assets/images/ic_edit.svg';
  static const String shared$ic_edit_svg =
      'packages/shared/assets/images/ic_edit.svg';

  static const String ic_expand_down_svg = 'assets/images/ic_expand_down.svg';
  static const String shared$ic_expand_down_svg =
      'packages/shared/assets/images/ic_expand_down.svg';

  static const String ic_expand_right_svg = 'assets/images/ic_expand_right.svg';
  static const String shared$ic_expand_right_svg =
      'packages/shared/assets/images/ic_expand_right.svg';

  static const String ic_expand_up_svg = 'assets/images/ic_expand_up.svg';
  static const String shared$ic_expand_up_svg =
      'packages/shared/assets/images/ic_expand_up.svg';

  static const String ic_female_svg = 'assets/images/ic_female.webp';
  static const String shared$ic_female_svg =
      'packages/shared/assets/images/ic_female.webp';

  static const String ic_fire_svg = 'assets/images/ic_fire.svg';
  static const String shared$ic_fire_svg =
      'packages/shared/assets/images/ic_fire.svg';

  static const String ic_flash_small_png = 'assets/images/ic_flash_small.png';
  static const String shared$ic_flash_small_png =
      'packages/shared/assets/images/ic_flash_small.png';

  static const String ic_fleet_png = 'assets/images/ic_fleet.png';
  static const String shared$ic_fleet_png =
      'packages/shared/assets/images/ic_fleet.png';

  static const String ic_friends_playing_webp =
      'assets/images/ic_friends_playing.webp';
  static const String shared$ic_friends_playing_webp =
      'packages/shared/assets/images/ic_friends_playing.webp';

  static const String ic_grow_user_png = 'assets/images/ic_grow_user.png';
  static const String shared$ic_grow_user_png =
      'packages/shared/assets/images/ic_grow_user.png';

  static const String ic_help_svg = 'assets/images/ic_help.svg';
  static const String shared$ic_help_svg =
      'packages/shared/assets/images/ic_help.svg';

  static const String ic_help_webp = 'assets/images/ic_help.webp';
  static const String shared$ic_help_webp =
      'packages/shared/assets/images/ic_help.webp';

  static const String ic_home_banner_bg_webp =
      'assets/images/ic_home_banner_bg.webp';
  static const String shared$ic_home_banner_bg_webp =
      'packages/shared/assets/images/ic_home_banner_bg.webp';

  static const String ic_home_bottom_bg_webp =
      'assets/images/ic_home_bottom_bg.webp';
  static const String shared$ic_home_bottom_bg_webp =
      'packages/shared/assets/images/ic_home_bottom_bg.webp';

  static const String ic_home_hot_webp = 'assets/images/ic_home_hot.webp';
  static const String shared$ic_home_hot_webp =
      'packages/shared/assets/images/ic_home_hot.webp';

  static const String ic_home_sub_tab_selected_webp =
      'assets/images/ic_home_sub_tab_selected.webp';
  static const String shared$ic_home_sub_tab_selected_webp =
      'packages/shared/assets/images/ic_home_sub_tab_selected.webp';

  static const String ic_home_sub_tab_selected_dark_webp =
      'assets/images/ic_home_sub_tab_selected_dark.webp';
  static const String shared$ic_home_sub_tab_selected_dark_webp =
      'packages/shared/assets/images/ic_home_sub_tab_selected_dark.webp';

  static const String ic_home_top_bg_webp = 'assets/images/ic_home_top_bg.webp';
  static const String shared$ic_home_top_bg_webp =
      'packages/shared/assets/images/ic_home_top_bg.webp';

  static const String ic_home_top_bg_dark_webp =
      'assets/images/ic_home_top_bg_dark.webp';
  static const String shared$ic_home_top_bg_dark_webp =
      'packages/shared/assets/images/ic_home_top_bg_dark.webp';

  static const String ic_hot_svg = 'assets/images/ic_hot.svg';
  static const String shared$ic_hot_svg =
      'packages/shared/assets/images/ic_hot.svg';

  static const String ic_id_webp = 'assets/images/ic_id.webp';
  static const String shared$ic_id_webp =
      'packages/shared/assets/images/ic_id.webp';

  static const String ic_id_dark_webp = 'assets/images/ic_id_dark.webp';
  static const String shared$ic_id_dark_webp =
      'packages/shared/assets/images/ic_id_dark.webp';

  static const String ic_inroom_chat_svg = 'assets/images/ic_inroom_chat.svg';
  static const String shared$ic_inroom_chat_svg =
      'packages/shared/assets/images/ic_inroom_chat.svg';

  static const String ic_invite_room_webp = 'assets/images/ic_invite_room.webp';
  static const String shared$ic_invite_room_webp =
      'packages/shared/assets/images/ic_invite_room.webp';

  static const String ic_ka_tag_png = 'assets/images/ic_ka_tag.png';
  static const String shared$ic_ka_tag_png =
      'packages/shared/assets/images/ic_ka_tag.png';

  static const String ic_lock_svg = 'assets/images/ic_lock.svg';
  static const String shared$ic_lock_svg =
      'packages/shared/assets/images/ic_lock.svg';

  static const String ic_male_svg = 'assets/images/ic_male.webp';
  static const String shared$ic_male_svg =
      'packages/shared/assets/images/ic_male.webp';

  static const String ic_minus_svg = 'assets/images/ic_minus.svg';
  static const String shared$ic_minus_svg =
      'packages/shared/assets/images/ic_minus.svg';

  static const String ic_minus_small_webp = 'assets/images/ic_minus_small.webp';
  static const String shared$ic_minus_small_webp =
      'packages/shared/assets/images/ic_minus_small.webp';

  static const String ic_more_svg = 'assets/images/ic_more.svg';
  static const String shared$ic_more_svg =
      'packages/shared/assets/images/ic_more.svg';

  static const String ic_music_none_webp = 'assets/images/ic_music_none.webp';
  static const String shared$ic_music_none_webp =
      'packages/shared/assets/images/ic_music_none.webp';

  static const String ic_new_noble_webp = 'assets/images/ic_new_noble.webp';
  static const String shared$ic_new_noble_webp =
      'packages/shared/assets/images/ic_new_noble.webp';

  static const String ic_new_rich_webp = 'assets/images/ic_new_rich.webp';
  static const String shared$ic_new_rich_webp =
      'packages/shared/assets/images/ic_new_rich.webp';

  static const String ic_newer_webp = 'assets/images/ic_newer.webp';
  static const String shared$ic_newer_webp =
      'packages/shared/assets/images/ic_newer.webp';

  static const String ic_official_png = 'assets/images/ic_official.png';
  static const String shared$ic_official_png =
      'packages/shared/assets/images/ic_official.png';

  static const String ic_offline_svg = 'assets/images/ic_offline.svg';
  static const String shared$ic_offline_svg =
      'packages/shared/assets/images/ic_offline.svg';

  static const String ic_online_svg = 'assets/images/ic_online.svg';
  static const String shared$ic_online_svg =
      'packages/shared/assets/images/ic_online.svg';

  static const String ic_people_in_room_svg =
      'assets/images/ic_people_in_room.svg';
  static const String shared$ic_people_in_room_svg =
      'packages/shared/assets/images/ic_people_in_room.svg';

  static const String ic_phone_call_accept_webp =
      'assets/images/ic_phone_call_accept.webp';
  static const String shared$ic_phone_call_accept_webp =
      'packages/shared/assets/images/ic_phone_call_accept.webp';

  static const String ic_phone_call_refuse_webp =
      'assets/images/ic_phone_call_refuse.webp';
  static const String shared$ic_phone_call_refuse_webp =
      'packages/shared/assets/images/ic_phone_call_refuse.webp';

  static const String ic_playing_people_svg =
      'assets/images/ic_playing_people.svg';
  static const String shared$ic_playing_people_svg =
      'packages/shared/assets/images/ic_playing_people.svg';

  static const String ic_popularity_upgrade_webp =
      'assets/images/ic_popularity_upgrade.webp';
  static const String shared$ic_popularity_upgrade_webp =
      'packages/shared/assets/images/ic_popularity_upgrade.webp';

  static const String ic_pretty_tag_webp = 'assets/images/ic_pretty_tag.webp';
  static const String shared$ic_pretty_tag_webp =
      'packages/shared/assets/images/ic_pretty_tag.webp';

  static String ic_prize_cup_x_webp(Object p0) =>
      'assets/images/ic_prize_cup_${p0.toString()}.webp';

  static String shared$ic_prize_cup_x_webp(Object p0) =>
      'packages/shared/assets/images/ic_prize_cup_${p0.toString()}.webp';

  static const String ic_prompt_svg = 'assets/images/ic_prompt.svg';
  static const String shared$ic_prompt_svg =
      'packages/shared/assets/images/ic_prompt.svg';

  static const String ic_qixi_rank_1_webp = 'assets/images/ic_qixi_rank_1.webp';
  static const String shared$ic_qixi_rank_1_webp =
      'packages/shared/assets/images/ic_qixi_rank_1.webp';

  static const String ic_qixi_rank_2_webp = 'assets/images/ic_qixi_rank_2.webp';
  static const String shared$ic_qixi_rank_2_webp =
      'packages/shared/assets/images/ic_qixi_rank_2.webp';

  static const String ic_qixi_rank_3_webp = 'assets/images/ic_qixi_rank_3.webp';
  static const String shared$ic_qixi_rank_3_webp =
      'packages/shared/assets/images/ic_qixi_rank_3.webp';

  static const String ic_quality_user_label_webp =
      'assets/images/ic_quality_user_label.webp';
  static const String shared$ic_quality_user_label_webp =
      'packages/shared/assets/images/ic_quality_user_label.webp';

  static const String ic_recharge_label_webp =
      'assets/images/ic_recharge_label.webp';
  static const String shared$ic_recharge_label_webp =
      'packages/shared/assets/images/ic_recharge_label.webp';

  static const String ic_red_v_user_webp = 'assets/images/ic_red_v_user.webp';
  static const String shared$ic_red_v_user_webp =
      'packages/shared/assets/images/ic_red_v_user.webp';

  static const String ic_reduce_png = 'assets/images/ic_reduce.png';
  static const String shared$ic_reduce_png =
      'packages/shared/assets/images/ic_reduce.png';

  static const String ic_search_action_png =
      'assets/images/ic_search_action.png';
  static const String shared$ic_search_action_png =
      'packages/shared/assets/images/ic_search_action.png';

  static const String ic_select_small_svg = 'assets/images/ic_select_small.svg';
  static const String shared$ic_select_small_svg =
      'packages/shared/assets/images/ic_select_small.svg';

  static const String ic_selected_svg = 'assets/images/ic_selected.svg';
  static const String shared$ic_selected_svg =
      'packages/shared/assets/images/ic_selected.svg';

  static const String ic_singer_1_webp = 'assets/images/ic_singer_1.webp';
  static const String shared$ic_singer_1_webp =
      'packages/shared/assets/images/ic_singer_1.webp';

  static const String ic_singer_2_webp = 'assets/images/ic_singer_2.webp';
  static const String shared$ic_singer_2_webp =
      'packages/shared/assets/images/ic_singer_2.webp';

  static const String ic_singer_3_webp = 'assets/images/ic_singer_3.webp';
  static const String shared$ic_singer_3_webp =
      'packages/shared/assets/images/ic_singer_3.webp';

  static const String ic_singer_4_webp = 'assets/images/ic_singer_4.webp';
  static const String shared$ic_singer_4_webp =
      'packages/shared/assets/images/ic_singer_4.webp';

  static const String ic_singer_5_webp = 'assets/images/ic_singer_5.webp';
  static const String shared$ic_singer_5_webp =
      'packages/shared/assets/images/ic_singer_5.webp';

  static const String ic_singer_6_webp = 'assets/images/ic_singer_6.webp';
  static const String shared$ic_singer_6_webp =
      'packages/shared/assets/images/ic_singer_6.webp';

  static const String ic_singer_7_webp = 'assets/images/ic_singer_7.webp';
  static const String shared$ic_singer_7_webp =
      'packages/shared/assets/images/ic_singer_7.webp';

  static const String ic_small_alarm_label_webp =
      'assets/images/ic_small_alarm_label.webp';
  static const String shared$ic_small_alarm_label_webp =
      'packages/shared/assets/images/ic_small_alarm_label.webp';

  static const String ic_star_verify_user_webp =
      'assets/images/ic_star_verify_user.webp';
  static const String shared$ic_star_verify_user_webp =
      'packages/shared/assets/images/ic_star_verify_user.webp';

  static const String ic_subtract_num_svg = 'assets/images/ic_subtract_num.svg';
  static const String shared$ic_subtract_num_svg =
      'packages/shared/assets/images/ic_subtract_num.svg';

  static const String ic_switch_down_svg = 'assets/images/ic_switch_down.svg';
  static const String shared$ic_switch_down_svg =
      'packages/shared/assets/images/ic_switch_down.svg';

  static const String ic_switch_up_svg = 'assets/images/ic_switch_up.svg';
  static const String shared$ic_switch_up_svg =
      'packages/shared/assets/images/ic_switch_up.svg';

  static const String ic_titlebar_back_svg =
      'assets/images/ic_titlebar_back.svg';
  static const String shared$ic_titlebar_back_svg =
      'packages/shared/assets/images/ic_titlebar_back.svg';

  static const String ic_union_png = 'assets/images/ic_union.png';
  static const String shared$ic_union_png =
      'packages/shared/assets/images/ic_union.png';

  static const String ic_union_gold_money_webp =
      'assets/images/ic_union_gold_money.webp';
  static const String shared$ic_union_gold_money_webp =
      'packages/shared/assets/images/ic_union_gold_money.webp';

  static const String ic_union_silver_money_webp =
      'assets/images/ic_union_silver_money.webp';
  static const String shared$ic_union_silver_money_webp =
      'packages/shared/assets/images/ic_union_silver_money.webp';

  static const String ic_unselected_svg = 'assets/images/ic_unselected.svg';
  static const String shared$ic_unselected_svg =
      'packages/shared/assets/images/ic_unselected.svg';

  static const String ic_user_female_png = 'assets/images/ic_user_female.png';
  static const String shared$ic_user_female_png =
      'packages/shared/assets/images/ic_user_female.png';

  static const String ic_user_friend_relation_svg =
      'assets/images/ic_user_friend_relation.svg';
  static const String shared$ic_user_friend_relation_svg =
      'packages/shared/assets/images/ic_user_friend_relation.svg';

  static const String ic_user_male_png = 'assets/images/ic_user_male.png';
  static const String shared$ic_user_male_png =
      'packages/shared/assets/images/ic_user_male.png';

  static const String ic_user_none_png = 'assets/images/ic_user_none_one.png';
  static const String shared$ic_user_none_png =
      'packages/shared/assets/images/ic_user_none_one.png';

  static const String ic_user_none_two_png =
      'assets/images/ic_user_none_two.png';
  static const String shared$ic_user_none_two_png =
      'packages/shared/assets/images/ic_user_none_two.png';

  static const String ic_user_none_three_png =
      'assets/images/ic_user_none_three.png';
  static const String shared$ic_user_none_three_png =
      'packages/shared/assets/images/ic_user_none_three.png';

  static const String ic_user_none_four_png =
      'assets/images/ic_user_none_four.png';
  static const String shared$ic_user_none_four =
      'packages/shared/assets/images/ic_user_none_four.png';

  static const String ic_user_none_round_png =
      'assets/images/ic_user_none_round.png';
  static const String shared$ic_user_none_round_png =
      'packages/shared/assets/images/ic_user_none_round.png';

  static const String icon_add_svg = 'assets/images/icon_add.svg';
  static const String shared$icon_add_svg =
      'packages/shared/assets/images/icon_add.svg';

  static const String icon_app_comment_webp =
      'assets/images/icon_app_comment.webp';
  static const String shared$icon_app_comment_webp =
      'packages/shared/assets/images/icon_app_comment.webp';

  static const String icon_btn_close_png = 'assets/images/icon_btn_close.png';
  static const String shared$icon_btn_close_png =
      'packages/shared/assets/images/icon_btn_close.png';

  static const String icon_checkbox_selected_svg =
      'assets/images/icon_checkbox_selected.svg';
  static const String shared$icon_checkbox_selected_svg =
      'packages/shared/assets/images/icon_checkbox_selected.svg';

  static const String icon_delete_svg = 'assets/images/icon_delete.svg';
  static const String shared$icon_delete_svg =
      'packages/shared/assets/images/icon_delete.svg';

  static const String icon_next_svg = 'assets/images/icon_next.svg';
  static const String shared$icon_next_svg =
      'packages/shared/assets/images/icon_next.svg';

  static const String icon_next_center_svg =
      'assets/images/icon_next_center.svg';
  static const String shared$icon_next_center_svg =
      'packages/shared/assets/images/icon_next_center.svg';

  static const String icon_next_fq_svg = 'assets/images/icon_next_fq.svg';
  static const String shared$icon_next_fq_svg =
      'packages/shared/assets/images/icon_next_fq.svg';

  static const String icon_personal_id_svg =
      'assets/images/icon_personal_id.svg';
  static const String shared$icon_personal_id_svg =
      'packages/shared/assets/images/icon_personal_id.svg';

  static const String icon_red_dot_svg = 'assets/images/icon_red_dot.svg';
  static const String shared$icon_red_dot_svg =
      'packages/shared/assets/images/icon_red_dot.svg';

  static const String icon_select_svg = 'assets/images/icon_select.svg';
  static const String shared$icon_select_svg =
      'packages/shared/assets/images/icon_select.svg';

  static const String icon_sex_colours_female_svg =
      'assets/images/icon_sex_colours_female.svg';
  static const String shared$icon_sex_colours_female_svg =
      'packages/shared/assets/images/icon_sex_colours_female.svg';

  static const String icon_sex_colours_male_svg =
      'assets/images/icon_sex_colours_male.svg';
  static const String shared$icon_sex_colours_male_svg =
      'packages/shared/assets/images/icon_sex_colours_male.svg';

  static const String icon_star_png = 'assets/images/icon_star.png';
  static const String shared$icon_star_png =
      'packages/shared/assets/images/icon_star.png';

  static const String icon_star1_png = 'assets/images/icon_star1.png';
  static const String shared$icon_star1_png =
      'packages/shared/assets/images/icon_star1.png';

  static const String icon_star2_png = 'assets/images/icon_star2.png';
  static const String shared$icon_star2_png =
      'packages/shared/assets/images/icon_star2.png';

  static const String icon_top_menu_svg = 'assets/images/icon_top_menu.svg';
  static const String shared$icon_top_menu_svg =
      'packages/shared/assets/images/icon_top_menu.svg';



  static const String in_room_status_webp = 'assets/images/in_room_status.webp';
  static const String shared$in_room_status_webp =
      'packages/shared/assets/images/in_room_status.webp';

  static const String in_room_status_dark_webp =
      'assets/images/in_room_status_dark.webp';
  static const String shared$in_room_status_dark_webp =
      'packages/shared/assets/images/in_room_status_dark.webp';

  static const String ka_user_dialog_bg_one_webp =
      'assets/images/ka_user_dialog_bg_one.webp';
  static const String shared$ka_user_dialog_bg_one_webp =
      'packages/shared/assets/images/ka_user_dialog_bg_one.webp';

  static const String ka_user_dialog_bg_two_webp =
      'assets/images/ka_user_dialog_bg_two.webp';
  static const String shared$ka_user_dialog_bg_two_webp =
      'packages/shared/assets/images/ka_user_dialog_bg_two.webp';

  static const String liked_webp = 'assets/images/liked.webp';
  static const String shared$liked_webp =
      'packages/shared/assets/images/liked.webp';

  static const String living_gif = 'assets/images/living.gif';
  static const String shared$living_gif =
      'packages/shared/assets/images/living.gif';

  static const String living_small_gif = 'assets/images/living_small.gif';
  static const String shared$living_small_gif =
      'packages/shared/assets/images/living_small.gif';

  static const String living_small_webp = 'assets/images/living_small.webp';
  static const String shared$living_small_webp =
      'packages/shared/assets/images/living_small.webp';

  static const String login_ic_follow_and_say_hi_svg =
      'assets/images/login/ic_follow_and_say_hi.svg';
  static const String shared$login_ic_follow_and_say_hi_svg =
      'packages/shared/assets/images/login/ic_follow_and_say_hi.svg';

  static const String login_ic_ignore_gs_png =
      'assets/images/login/ic_ignore_gs.png';
  static const String shared$login_ic_ignore_gs_png =
      'packages/shared/assets/images/login/ic_ignore_gs.png';

  static const String login_bg_webp = 'assets/images/login_bg.webp';
  static const String shared$login_bg_webp =
      'packages/shared/assets/images/login_bg.webp';

  static const String metro_address_icon_webp =
      'assets/images/metro_address_icon.webp';
  static const String shared$metro_address_icon_webp =
      'packages/shared/assets/images/metro_address_icon.webp';

  static const String metro_icon_female_webp =
      'assets/images/metro_icon_female.webp';
  static const String shared$metro_icon_female_webp =
      'packages/shared/assets/images/metro_icon_female.webp';

  static const String metro_icon_male_webp =
      'assets/images/metro_icon_male.webp';
  static const String shared$metro_icon_male_webp =
      'packages/shared/assets/images/metro_icon_male.webp';

  static const String nav_add_svg = 'assets/images/nav_add.svg';
  static const String shared$nav_add_svg =
      'packages/shared/assets/images/nav_add.svg';

  static const String online_num_svg = 'assets/images/online_num.svg';
  static const String shared$online_num_svg =
      'packages/shared/assets/images/online_num.svg';

  static const String package_bg_png = 'assets/images/package_bg.png';
  static const String shared$package_bg_png =
      'packages/shared/assets/images/package_bg.png';

  static const String profile_add_png = 'assets/images/profile_add.png';
  static const String shared$profile_add_png =
      'packages/shared/assets/images/profile_add.png';

  static const String profile_audio_animation_webp =
      'assets/images/profile_audio_animation.webp';
  static const String shared$profile_audio_animation_webp =
      'packages/shared/assets/images/profile_audio_animation.webp';

  static String rank_top_rankx_webp(Object p0) =>
      'assets/images/rank/top_rank${p0.toString()}.webp';

  static String shared$rank_top_rankx_webp(Object p0) =>
      'packages/shared/assets/images/rank/top_rank${p0.toString()}.webp';

  static const String recommend_room_close_png =
      'assets/images/recommend_room_close.png';
  static const String shared$recommend_room_close_png =
      'packages/shared/assets/images/recommend_room_close.png';

  static const String recommend_room_close_dark_png =
      'assets/images/recommend_room_close_dark.png';
  static const String shared$recommend_room_close_dark_png =
      'packages/shared/assets/images/recommend_room_close_dark.png';

  static const String recommend_room_wave_webp =
      'assets/images/recommend_room_wave.webp';
  static const String shared$recommend_room_wave_webp =
      'packages/shared/assets/images/recommend_room_wave.webp';

  static const String recommend_top_label_bg_png =
      'assets/images/recommend_top_label_bg.png';
  static const String shared$recommend_top_label_bg_png =
      'packages/shared/assets/images/recommend_top_label_bg.png';

  static const String recommend_top_label_border_png =
      'assets/images/recommend_top_label_border.png';
  static const String shared$recommend_top_label_border_png =
      'packages/shared/assets/images/recommend_top_label_border.png';

  static const String redpoint_png = 'assets/images/redpoint.png';
  static const String shared$redpoint_png =
      'packages/shared/assets/images/redpoint.png';

  static const String room_flash_webp = 'assets/images/room/flash.webp';
  static const String shared$room_flash_webp =
      'packages/shared/assets/images/room/flash.webp';

  static const String room_rank_room_hot_small_svg =
      'assets/images/room/rank_room_hot_small.svg';
  static const String shared$room_rank_room_hot_small_svg =
      'packages/shared/assets/images/room/rank_room_hot_small.svg';

  static const String room_room_hot_small_png =
      'assets/images/room/room_hot_small.png';
  static const String shared$room_room_hot_small_png =
      'packages/shared/assets/images/room/room_hot_small.png';

  static const String room_active_purple_webp =
      'assets/images/room_active_purple.webp';
  static const String shared$room_active_purple_webp =
      'packages/shared/assets/images/room_active_purple.webp';

  static const String room_little_png = 'assets/images/room_little.png';
  static const String shared$room_little_png =
      'packages/shared/assets/images/room_little.png';

  static const String room_recommend_bg_webp =
      'assets/images/room_recommend_bg.webp';
  static const String shared$room_recommend_bg_webp =
      'packages/shared/assets/images/room_recommend_bg.webp';

  static const String rush_chat_friend_audio_default_png =
      'assets/images/rush_chat_friend_audio_default.png';
  static const String shared$rush_chat_friend_audio_default_png =
      'packages/shared/assets/images/rush_chat_friend_audio_default.png';

  static const String rush_default_head_female_svg =
      'assets/images/rush_default_head_female.svg';
  static const String shared$rush_default_head_female_svg =
      'packages/shared/assets/images/rush_default_head_female.svg';

  static const String rush_default_head_male_svg =
      'assets/images/rush_default_head_male.svg';
  static const String shared$rush_default_head_male_svg =
      'packages/shared/assets/images/rush_default_head_male.svg';

  static const String search_bar_clear_btn_webp =
      'assets/images/search_bar_clear_btn.webp';
  static const String shared$search_bar_clear_btn_webp =
      'packages/shared/assets/images/search_bar_clear_btn.webp';

  static const String sign_btn_sign_disabled_webp =
      'assets/images/sign/btn_sign_disabled.webp';
  static const String shared$sign_btn_sign_disabled_webp =
      'packages/shared/assets/images/sign/btn_sign_disabled.webp';

  static const String sign_btn_sign_forward_webp =
      'assets/images/sign/btn_sign_forward.webp';
  static const String shared$sign_btn_sign_forward_webp =
      'packages/shared/assets/images/sign/btn_sign_forward.webp';

  static const String sign_btn_sign_new_webp =
      'assets/images/sign/btn_sign_new.webp';
  static const String shared$sign_btn_sign_new_webp =
      'packages/shared/assets/images/sign/btn_sign_new.webp';

  static const String sign_header_webp = 'assets/images/sign/header.webp';
  static const String shared$sign_header_webp =
      'packages/shared/assets/images/sign/header.webp';

  static const String sign_header_bg_forward_1_webp =
      'assets/images/sign/header_bg_forward_1.webp';
  static const String shared$sign_header_bg_forward_1_webp =
      'packages/shared/assets/images/sign/header_bg_forward_1.webp';

  static const String sign_header_bg_forward_2_webp =
      'assets/images/sign/header_bg_forward_2.webp';
  static const String shared$sign_header_bg_forward_2_webp =
      'packages/shared/assets/images/sign/header_bg_forward_2.webp';

  static const String sign_header_bg_new_webp =
      'assets/images/sign/header_bg_new.webp';
  static const String shared$sign_header_bg_new_webp =
      'packages/shared/assets/images/sign/header_bg_new.webp';

  static const String sign_ic_sign_webp = 'assets/images/sign/ic_sign.webp';
  static const String shared$sign_ic_sign_webp =
      'packages/shared/assets/images/sign/ic_sign.webp';

  static const String sign_ic_sign_dark_webp =
      'assets/images/sign/ic_sign_dark.webp';
  static const String shared$sign_ic_sign_dark_webp =
      'packages/shared/assets/images/sign/ic_sign_dark.webp';

  static const String sign_sign_succeed_tips_webp =
      'assets/images/sign/sign_succeed_tips.webp';
  static const String shared$sign_sign_succeed_tips_webp =
      'packages/shared/assets/images/sign/sign_succeed_tips.webp';

  static const String sign_sign_succeed_tips_forward_webp =
      'assets/images/sign/sign_succeed_tips_forward.webp';
  static const String shared$sign_sign_succeed_tips_forward_webp =
      'packages/shared/assets/images/sign/sign_succeed_tips_forward.webp';

  static const String star_off_svg = 'assets/images/star_off.svg';
  static const String shared$star_off_svg =
      'packages/shared/assets/images/star_off.svg';

  static const String star_on_svg = 'assets/images/star_on.svg';
  static const String shared$star_on_svg =
      'packages/shared/assets/images/star_on.svg';

  static const String success_icon_svg = 'assets/images/success_icon.svg';
  static const String shared$success_icon_svg =
      'packages/shared/assets/images/success_icon.svg';

  static const String tab_indicator_webp = 'assets/images/tab_indicator.webp';
  static const String shared$tab_indicator_webp =
      'packages/shared/assets/images/tab_indicator.webp';

  static const String titlebar_ic_titlebar_close_svg =
      'assets/images/titlebar/ic_titlebar_close.svg';
  static const String shared$titlebar_ic_titlebar_close_svg =
      'packages/shared/assets/images/titlebar/ic_titlebar_close.svg';

  static const String titlebar_ic_titlebar_more_svg =
      'assets/images/titlebar/ic_titlebar_more.svg';
  static const String shared$titlebar_ic_titlebar_more_svg =
      'packages/shared/assets/images/titlebar/ic_titlebar_more.svg';

  static const String titlebar_ic_titlebar_notification_svg =
      'assets/images/titlebar/ic_titlebar_notification.svg';
  static const String shared$titlebar_ic_titlebar_notification_svg =
      'packages/shared/assets/images/titlebar/ic_titlebar_notification.svg';

  static const String titlebar_ic_titlebar_question_svg =
      'assets/images/titlebar/ic_titlebar_question.svg';
  static const String shared$titlebar_ic_titlebar_question_svg =
      'packages/shared/assets/images/titlebar/ic_titlebar_question.svg';

  static const String titlebar_ic_titlebar_shot_svg =
      'assets/images/titlebar/ic_titlebar_shot.svg';
  static const String shared$titlebar_ic_titlebar_shot_svg =
      'packages/shared/assets/images/titlebar/ic_titlebar_shot.svg';

  static const String uid_tip_cute_svg = 'assets/images/uid_tip_cute.svg';
  static const String shared$uid_tip_cute_svg =
      'packages/shared/assets/images/uid_tip_cute.svg';

  static const String uid_tip_cute_webp = 'assets/images/uid_tip_cute.webp';
  static const String shared$uid_tip_cute_webp =
      'packages/shared/assets/images/uid_tip_cute.webp';

  static const String user_icon_default_png =
      'assets/images/user_icon_default.png';
  static const String shared$user_icon_default_png =
      'packages/shared/assets/images/user_icon_default.png';

  static const String user_icon_default1_png =
      'assets/images/user_icon_default1.png';
  static const String shared$user_icon_default1_png =
      'packages/shared/assets/images/user_icon_default1.png';

  static const String user_new_transfer_l_webp =
      'assets/images/user_new_transfer_l.webp';
  static const String shared$user_new_transfer_l_webp =
      'packages/shared/assets/images/user_new_transfer_l.webp';

  static const String user_new_transfer_n_webp =
      'assets/images/user_new_transfer_n.webp';
  static const String shared$user_new_transfer_n_webp =
      'packages/shared/assets/images/user_new_transfer_n.webp';

  static const String vindicate_instruction_webp =
      'assets/images/vindicate_instruction.webp';
  static const String shared$vindicate_instruction_webp =
      'packages/shared/assets/images/vindicate_instruction.webp';

  static const String visitant_room_visitant_1_webp =
      'assets/images/visitant/room_visitant_1.webp';
  static const String shared$visitant_room_visitant_1_webp =
      'packages/shared/assets/images/visitant/room_visitant_1.webp';

  static const String visitant_room_visitant_2_webp =
      'assets/images/visitant/room_visitant_2.webp';
  static const String shared$visitant_room_visitant_2_webp =
      'packages/shared/assets/images/visitant/room_visitant_2.webp';

  static const String visitant_room_visitant_3_webp =
      'assets/images/visitant/room_visitant_3.webp';
  static const String shared$visitant_room_visitant_3_webp =
      'packages/shared/assets/images/visitant/room_visitant_3.webp';

  static const String visitant_room_visitant_4_webp =
      'assets/images/visitant/room_visitant_4.webp';
  static const String shared$visitant_room_visitant_4_webp =
      'packages/shared/assets/images/visitant/room_visitant_4.webp';

  static const String visitant_room_visitant_5_webp =
      'assets/images/visitant/room_visitant_5.webp';
  static const String shared$visitant_room_visitant_5_webp =
      'packages/shared/assets/images/visitant/room_visitant_5.webp';

  static const String visitant_room_visitant_6_webp =
      'assets/images/visitant/room_visitant_6.webp';
  static const String shared$visitant_room_visitant_6_webp =
      'packages/shared/assets/images/visitant/room_visitant_6.webp';

  static const String visitant_room_visitant_7_webp =
      'assets/images/visitant/room_visitant_7.webp';
  static const String shared$visitant_room_visitant_7_webp =
      'packages/shared/assets/images/visitant/room_visitant_7.webp';

  static const String year_beast_primary_box_webp =
      'assets/images/year_beast_primary_box.webp';
  static const String shared$year_beast_primary_box_webp =
      'packages/shared/assets/images/year_beast_primary_box.webp';

  static const String year_beast_senior_box_webp =
      'assets/images/year_beast_senior_box.webp';
  static const String shared$year_beast_senior_box_webp =
      'packages/shared/assets/images/year_beast_senior_box.webp';

  static const String shared$normal_main_bg_webp =
      'packages/shared/assets/images/normal_main_bg.webp';

  static const String img_loading_failed_webp =
      'assets/images/img_loading_failed.webp';
  static const String shared$img_loading_failed_webp =
      'packages/shared/$img_loading_failed_webp';

  static const String home_top_tab_selected =
      'assets/images/home_top_tab_selected.png';

  static const String shared$home_top_tab_selected =
      'packages/shared/$home_top_tab_selected';
  static const String dy_tai_top_icon =
      'assets/images/home/dy_tai_top_icon.png';

  static const String shared$dy_tai_top_icon =
      'packages/shared/$dy_tai_top_icon';

  static const String pk_lright_icon = 'assets/images/pk_lright_icon.png';

  static const String shared$pk_lright_icon = 'packages/shared/$pk_lright_icon';

  static const String pk_left_icon = 'assets/images/pk_left_icon.png';

  static const String shared$pk_left_icon = 'packages/shared/$pk_left_icon';

  static const String pk_l_shafa_icon = 'assets/images/pk_l_shafa_icon.png';

  static const String shared$pk_l_shafa_icon =
      'packages/shared/$pk_l_shafa_icon';

  static const String pk_r_shafa_icon = 'assets/images/pk_r_shafa_icon.png';

  static const String shared$pk_r_shafa_icon =
      'packages/shared/$pk_r_shafa_icon';

  // static const String empty_page_png ='assets/images/empty_page.png';
}
