name: flutter_qq
description: Flutter plugin for QQ.
version: 1.1.4
homepage: https://github.com/marekchen/flutter_qq

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  image_picker: ^0.4.6
  flutter_lints: ^2.0.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.github.marekchen.flutterqq
    pluginClass: FlutterQqPlugin


