// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 35.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'draw_guess';

  static const String guess_change_word_button_webp =
      'assets/images/guess_change_word_button.webp';
  static const String draw_guess$guess_change_word_button_webp =
      'packages/draw_guess/assets/images/guess_change_word_button.webp';

  static const String guess_mode_normal_webp =
      'assets/images/guess_mode_normal.webp';
  static const String draw_guess$guess_mode_normal_webp =
      'packages/draw_guess/assets/images/guess_mode_normal.webp';

  static const String guess_mode_queue_webp =
      'assets/images/guess_mode_queue.webp';
  static const String draw_guess$guess_mode_queue_webp =
      'packages/draw_guess/assets/images/guess_mode_queue.webp';

  static const String guess_queue_bottom_triangle_png =
      'assets/images/guess_queue_bottom_triangle.png';
  static const String draw_guess$guess_queue_bottom_triangle_png =
      'packages/draw_guess/assets/images/guess_queue_bottom_triangle.png';

  static const String guess_queue_confirm_word_done_webp =
      'assets/images/guess_queue_confirm_word_done.webp';
  static const String draw_guess$guess_queue_confirm_word_done_webp =
      'packages/draw_guess/assets/images/guess_queue_confirm_word_done.webp';

  static const String guess_queue_mode_guess_webp =
      'assets/images/guess_queue_mode_guess.webp';
  static const String draw_guess$guess_queue_mode_guess_webp =
      'packages/draw_guess/assets/images/guess_queue_mode_guess.webp';

  static const String guess_queue_mode_queue_webp =
      'assets/images/guess_queue_mode_queue.webp';
  static const String draw_guess$guess_queue_mode_queue_webp =
      'packages/draw_guess/assets/images/guess_queue_mode_queue.webp';

  static const String guess_queue_result_rank_close_webp =
      'assets/images/guess_queue_result_rank_close.webp';
  static const String draw_guess$guess_queue_result_rank_close_webp =
      'packages/draw_guess/assets/images/guess_queue_result_rank_close.webp';

  static const String guess_queue_shalou_webp =
      'assets/images/guess_queue_shalou.webp';
  static const String draw_guess$guess_queue_shalou_webp =
      'packages/draw_guess/assets/images/guess_queue_shalou.webp';

  static const String guess_queue_submit_answer_title_icon_webp =
      'assets/images/guess_queue_submit_answer_title_icon.webp';
  static const String draw_guess$guess_queue_submit_answer_title_icon_webp =
      'packages/draw_guess/assets/images/guess_queue_submit_answer_title_icon.webp';

  static const String guess_queue_success_header_bg_webp =
      'assets/images/guess_queue_success_header_bg.webp';
  static const String draw_guess$guess_queue_success_header_bg_webp =
      'packages/draw_guess/assets/images/guess_queue_success_header_bg.webp';

  static const String guess_queue_success_item_bg_webp =
      'assets/images/guess_queue_success_item_bg.webp';
  static const String draw_guess$guess_queue_success_item_bg_webp =
      'packages/draw_guess/assets/images/guess_queue_success_item_bg.webp';

  static const String guess_select_mark_webp =
      'assets/images/guess_select_mark.webp';
  static const String draw_guess$guess_select_mark_webp =
      'packages/draw_guess/assets/images/guess_select_mark.webp';

  static const String guess_start_bg_webp = 'assets/images/guess_start_bg.webp';
  static const String draw_guess$guess_start_bg_webp =
      'packages/draw_guess/assets/images/guess_start_bg.webp';

  static const String guess_start_bg_for_visitor_webp =
      'assets/images/guess_start_bg_for_visitor.webp';
  static const String draw_guess$guess_start_bg_for_visitor_webp =
      'packages/draw_guess/assets/images/guess_start_bg_for_visitor.webp';

  static const String ic_big_arrow_svg = 'assets/images/ic_big_arrow.svg';
  static const String draw_guess$ic_big_arrow_svg =
      'packages/draw_guess/assets/images/ic_big_arrow.svg';

  static String ic_count_down_x_webp(Object p0) =>
      'assets/images/ic_count_down_${p0.toString()}.webp';

  static String draw_guess$ic_count_down_x_webp(Object p0) =>
      'packages/draw_guess/assets/images/ic_count_down_${p0.toString()}.webp';

  static const String ic_dot_arrow_svg = 'assets/images/ic_dot_arrow.svg';
  static const String draw_guess$ic_dot_arrow_svg =
      'packages/draw_guess/assets/images/ic_dot_arrow.svg';

  static const String ic_guess_next_svg = 'assets/images/ic_guess_next.svg';
  static const String draw_guess$ic_guess_next_svg =
      'packages/draw_guess/assets/images/ic_guess_next.svg';

  static const String ic_guess_pre_svg = 'assets/images/ic_guess_pre.svg';
  static const String draw_guess$ic_guess_pre_svg =
      'packages/draw_guess/assets/images/ic_guess_pre.svg';

  static const String ic_guess_queue_count_down_bg_webp =
      'assets/images/ic_guess_queue_count_down_bg.webp';
  static const String draw_guess$ic_guess_queue_count_down_bg_webp =
      'packages/draw_guess/assets/images/ic_guess_queue_count_down_bg.webp';

  static const String ic_guess_queue_drop_down_png =
      'assets/images/ic_guess_queue_drop_down.png';
  static const String draw_guess$ic_guess_queue_drop_down_png =
      'packages/draw_guess/assets/images/ic_guess_queue_drop_down.png';

  static const String ic_guess_video_icon_png =
      'assets/images/ic_guess_video_icon.png';
  static const String draw_guess$ic_guess_video_icon_png =
      'packages/draw_guess/assets/images/ic_guess_video_icon.png';

  static const String ic_replay_image_webp =
      'assets/images/ic_replay_image.webp';
  static const String draw_guess$ic_replay_image_webp =
      'packages/draw_guess/assets/images/ic_replay_image.webp';

  static const String ic_share_btn_svg = 'assets/images/ic_share_btn.svg';
  static const String draw_guess$ic_share_btn_svg =
      'packages/draw_guess/assets/images/ic_share_btn.svg';

  static const String ic_share_icon_webp = 'assets/images/ic_share_icon.webp';
  static const String draw_guess$ic_share_icon_webp =
      'packages/draw_guess/assets/images/ic_share_icon.webp';

  static const String ic_small_arrow_svg = 'assets/images/ic_small_arrow.svg';
  static const String draw_guess$ic_small_arrow_svg =
      'packages/draw_guess/assets/images/ic_small_arrow.svg';

  static const String ic_vote_fail_svg = 'assets/images/ic_vote_fail.svg';
  static const String draw_guess$ic_vote_fail_svg =
      'packages/draw_guess/assets/images/ic_vote_fail.svg';

  static const String ic_vote_suc_svg = 'assets/images/ic_vote_suc.svg';
  static const String draw_guess$ic_vote_suc_svg =
      'packages/draw_guess/assets/images/ic_vote_suc.svg';

  static const String guess_count_down_mp3 =
      'assets/sound/guess_count_down.mp3';
  static const String draw_guess$guess_count_down_mp3 =
      'packages/draw_guess/assets/sound/guess_count_down.mp3';

  static const String guess_draw_bgm_mp3 = 'assets/sound/guess_draw_bgm.mp3';
  static const String draw_guess$guess_draw_bgm_mp3 =
      'packages/draw_guess/assets/sound/guess_draw_bgm.mp3';

  static const String guess_queue_draw_done_mp3 =
      'assets/sound/guess_queue_draw_done.mp3';
  static const String draw_guess$guess_queue_draw_done_mp3 =
      'packages/draw_guess/assets/sound/guess_queue_draw_done.mp3';

  static const String guess_replay_bgm_mp3 =
      'assets/sound/guess_replay_bgm.mp3';
  static const String draw_guess$guess_replay_bgm_mp3 =
      'packages/draw_guess/assets/sound/guess_replay_bgm.mp3';

  static const String guess_send_text_mp3 = 'assets/sound/guess_send_text.mp3';
  static const String draw_guess$guess_send_text_mp3 =
      'packages/draw_guess/assets/sound/guess_send_text.mp3';

  static const String guess_show_guess_text_mp3 =
      'assets/sound/guess_show_guess_text.mp3';
  static const String draw_guess$guess_show_guess_text_mp3 =
      'packages/draw_guess/assets/sound/guess_show_guess_text.mp3';

  static const String ic_guess_queue_start =
      'assets/images/ic_guess_queue_start.png';
  static const String draw_guess$ic_guess_queue_start =
      'packages/draw_guess/assets/images/ic_guess_queue_start.png';
}
