name: moment
description: 朋友圈
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_image_compress: 1.1.1

  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  assets_gen: 1.5.0
  flutter_lints: ^2.0.2

assets_gen:
  omit_path_levels: 2
  exclude:
    - assets/images_*/**

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/circle/
    - assets/images/club/
    - assets/images/small_mood/
