// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 32.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'login';

  static const String douyin_channel_btn_logo_webp =
      'assets/images/douyin_channel_btn_logo.webp';
  static const String login$douyin_channel_btn_logo_webp =
      'packages/login/assets/images/douyin_channel_btn_logo.webp';

  static const String douyin_login_phone_webp =
      'assets/images/douyin_login_phone.webp';
  static const String login$douyin_login_phone_webp =
      'packages/login/assets/images/douyin_login_phone.webp';

  static const String ic_change_nick_name_svg =
      'assets/images/ic_change_nick_name.svg';
  static const String login$ic_change_nick_name_svg =
      'packages/login/assets/images/ic_change_nick_name.svg';

  static const String ic_douyin_channel_login_webp =
      'assets/images/ic_douyin_channel_login.webp';
  static const String login$ic_douyin_channel_login_webp =
      'packages/login/assets/images/ic_douyin_channel_login.webp';

  static const String ic_edit_svg = 'assets/images/ic_edit.svg';
  static const String login$ic_edit_svg =
      'packages/login/assets/images/ic_edit.svg';

  static const String ic_gender_female_svg =
      'assets/images/ic_gender_female.svg';
  static const String login$ic_gender_female_svg =
      'packages/login/assets/images/ic_gender_female.svg';

  static const String ic_gender_female_webp =
      'assets/images/ic_gender_female.webp';
  static const String login$ic_gender_female_webp =
      'packages/login/assets/images/ic_gender_female.webp';

  static const String ic_gender_inset_female_webp =
      'assets/images/ic_gender_inset_female.webp';
  static const String login$ic_gender_inset_female_webp =
      'packages/login/assets/images/ic_gender_inset_female.webp';

  static const String ic_gender_inset_female_checked_webp =
      'assets/images/ic_gender_inset_female_checked.webp';
  static const String login$ic_gender_inset_female_checked_webp =
      'packages/login/assets/images/ic_gender_inset_female_checked.webp';

  static const String ic_gender_inset_male_webp =
      'assets/images/ic_gender_inset_male.webp';
  static const String login$ic_gender_inset_male_webp =
      'packages/login/assets/images/ic_gender_inset_male.webp';

  static const String ic_gender_inset_male_checked_webp =
      'assets/images/ic_gender_inset_male_checked.webp';
  static const String login$ic_gender_inset_male_checked_webp =
      'packages/login/assets/images/ic_gender_inset_male_checked.webp';

  static const String ic_gender_male_svg = 'assets/images/ic_gender_male.svg';
  static const String login$ic_gender_male_svg =
      'packages/login/assets/images/ic_gender_male.svg';

  static const String ic_gender_male_webp = 'assets/images/ic_gender_male.webp';
  static const String login$ic_gender_male_webp =
      'packages/login/assets/images/ic_gender_male.webp';

  static const String ic_has_followed_gs_png =
      'assets/images/ic_has_followed_gs.png';
  static const String login$ic_has_followed_gs_png =
      'packages/login/assets/images/ic_has_followed_gs.png';

  static const String ic_input_clear_svg = 'assets/images/ic_input_clear.svg';
  static const String login$ic_input_clear_svg =
      'packages/login/assets/images/ic_input_clear.svg';

  static const String ic_interset_selected_svg =
      'assets/images/ic_interset_selected.svg';
  static const String login$ic_interset_selected_svg =
      'packages/login/assets/images/ic_interset_selected.svg';

  static const String ic_invite_code_webp = 'assets/images/ic_invite_code.webp';
  static const String login$ic_invite_code_webp =
      'packages/login/assets/images/ic_invite_code.webp';

  static const String ic_login_avatar_svg = 'assets/images/ic_login_avatar.svg';
  static const String login$ic_login_avatar_svg =
      'packages/login/assets/images/ic_login_avatar.svg';

  static const String ic_login_next_svg = 'assets/images/ic_login_next.svg';
  static const String login$ic_login_next_svg =
      'packages/login/assets/images/ic_login_next.svg';

  static const String ic_search_svg = 'assets/images/ic_search.svg';
  static const String login$ic_search_svg =
      'packages/login/assets/images/ic_search.svg';

  static const String ic_share_fans_webp = 'assets/images/ic_share_fans.webp';
  static const String login$ic_share_fans_webp =
      'packages/login/assets/images/ic_share_fans.webp';

  static const String ic_share_in_app_webp =
      'assets/images/ic_share_in_app.webp';
  static const String login$ic_share_in_app_webp =
      'packages/login/assets/images/ic_share_in_app.webp';

  static const String ic_split_svg = 'assets/images/ic_split.svg';
  static const String login$ic_split_svg =
      'packages/login/assets/images/ic_split.svg';

  static const String login_invite_code_header_webp =
      'assets/images/login_invite_code_header.webp';
  static const String login$login_invite_code_header_webp =
      'packages/login/assets/images/login_invite_code_header.webp';

  static const String login_nick_default_icon_webp =
      'assets/images/login_nick_default_icon.webp';
  static const String login$login_nick_default_icon_webp =
      'packages/login/assets/images/login_nick_default_icon.webp';

  static const String login_phone_svg = 'assets/images/login_phone.svg';
  static const String login$login_phone_svg =
      'packages/login/assets/images/login_phone.svg';

  static const String package_bg_png = 'assets/images/package_bg.png';
  static const String login$package_bg_png =
      'packages/login/assets/images/package_bg.png';

  static const String package_phone_png = 'assets/images/package_phone.png';
  static const String login$package_phone_png =
      'packages/login/assets/images/package_phone.png';

  static const String phone_verify_webp = 'assets/images/phone_verify.webp';
  static const String login$phone_verify_webp =
      'packages/login/assets/images/phone_verify.webp';

  static const String share_close_svg = 'assets/images/share_close.svg';
  static const String login$share_close_svg =
      'packages/login/assets/images/share_close.svg';

  static const String share_inapp_svg = 'assets/images/share_inapp.svg';
  static const String login$share_inapp_svg =
      'packages/login/assets/images/share_inapp.svg';

  static const String verify_dialog_icon_webp =
      'assets/images/verify_dialog_icon.webp';
  static const String login$verify_dialog_icon_webp =
      'packages/login/assets/images/verify_dialog_icon.webp';
  static const String login$login_bg_webp =
      'packages/login/assets/images/logo_bg.webp';

  static const String login_top_text = 'assets/images/login_top_text.webp';
  static const String login$login_top_text =
      'packages/login/assets/images/login_top_text.webp';

  static const String verify_dialog_icon_png =
      'packages/login/assets/images/verify_dialog_icon.png';
}
