// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 128.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'moment';

  static const String bg_error_data_webp = 'assets/images/bg_error_data.webp';
  static const String moment$bg_error_data_webp =
      'packages/moment/assets/images/bg_error_data.webp';

  static const String bg_no_data_webp = 'assets/images/bg_no_data.webp';
  static const String moment$bg_no_data_webp =
      'packages/moment/assets/images/bg_no_data.webp';

  static const String bg_topic_default_webp =
      'assets/images/bg_topic_default.webp';
  static const String moment$bg_topic_default_webp =
      'packages/moment/assets/images/bg_topic_default.webp';

  static const String chat_bottom_pic_svg = 'assets/images/chat_bottom_pic.svg';
  static const String moment$chat_bottom_pic_svg =
      'packages/moment/assets/images/chat_bottom_pic.svg';

  static const String chat_bottom_voice_svg =
      'assets/images/chat_bottom_voice.svg';
  static const String moment$chat_bottom_voice_svg =
      'packages/moment/assets/images/chat_bottom_voice.svg';

  static const String circle_circle_hot_mark_webp =
      'assets/images/circle/circle_hot_mark.webp';
  static const String moment$circle_circle_hot_mark_webp =
      'packages/moment/assets/images/circle/circle_hot_mark.webp';

  static const String circle_circle_recommend_mark_webp =
      'assets/images/circle/circle_recommend_mark.webp';
  static const String moment$circle_circle_recommend_mark_webp =
      'packages/moment/assets/images/circle/circle_recommend_mark.webp';

  static const String circle_ic_activity_webp =
      'assets/images/circle/ic_activity.webp';
  static const String moment$circle_ic_activity_webp =
      'packages/moment/assets/images/circle/ic_activity.webp';

  static const String circle_ic_female_rush_png =
      'assets/images/circle/ic_female_rush.png';
  static const String moment$circle_ic_female_rush_png =
      'packages/moment/assets/images/circle/ic_female_rush.png';

  static const String circle_ic_male_rush_png =
      'assets/images/circle/ic_male_rush.png';
  static const String moment$circle_ic_male_rush_png =
      'packages/moment/assets/images/circle/ic_male_rush.png';

  static const String circle_ic_others_profile_svg =
      'assets/images/circle/ic_others_profile.svg';
  static const String moment$circle_ic_others_profile_svg =
      'packages/moment/assets/images/circle/ic_others_profile.svg';

  static const String circle_ic_recommend_circle_name_svg =
      'assets/images/circle/ic_recommend_circle_name.svg';
  static const String moment$circle_ic_recommend_circle_name_svg =
      'packages/moment/assets/images/circle/ic_recommend_circle_name.svg';

  static const String circle_ic_rush_add_circle_svg =
      'assets/images/circle/ic_rush_add_circle.svg';
  static const String moment$circle_ic_rush_add_circle_svg =
      'packages/moment/assets/images/circle/ic_rush_add_circle.svg';

  static const String circle_ic_rush_circle_next_svg =
      'assets/images/circle/ic_rush_circle_next.svg';
  static const String moment$circle_ic_rush_circle_next_svg =
      'packages/moment/assets/images/circle/ic_rush_circle_next.svg';

  static const String circle_ic_rush_circle_tag_svg =
      'assets/images/circle/ic_rush_circle_tag.svg';
  static const String moment$circle_ic_rush_circle_tag_svg =
      'packages/moment/assets/images/circle/ic_rush_circle_tag.svg';

  static const String circle_ic_rush_my_circle_svg =
      'assets/images/circle/ic_rush_my_circle.svg';
  static const String moment$circle_ic_rush_my_circle_svg =
      'packages/moment/assets/images/circle/ic_rush_my_circle.svg';

  static const String circle_ic_rush_my_circle_redpoint_webp =
      'assets/images/circle/ic_rush_my_circle_redpoint.webp';
  static const String moment$circle_ic_rush_my_circle_redpoint_webp =
      'packages/moment/assets/images/circle/ic_rush_my_circle_redpoint.webp';

  static const String circle_ic_rush_recommend_circle_svg =
      'assets/images/circle/ic_rush_recommend_circle.svg';
  static const String moment$circle_ic_rush_recommend_circle_svg =
      'packages/moment/assets/images/circle/ic_rush_recommend_circle.svg';

  static const String circle_ic_set_top_webp =
      'assets/images/circle/ic_set_top.webp';
  static const String moment$circle_ic_set_top_webp =
      'packages/moment/assets/images/circle/ic_set_top.webp';

  static const String circle_ic_set_top_dark_webp =
      'assets/images/circle/ic_set_top_dark.webp';
  static const String moment$circle_ic_set_top_dark_webp =
      'packages/moment/assets/images/circle/ic_set_top_dark.webp';

  static const String circle_moment_wedding_bg_webp =
      'assets/images/circle/moment_wedding_bg.webp';
  static const String moment$circle_moment_wedding_bg_webp =
      'packages/moment/assets/images/circle/moment_wedding_bg.webp';

  static const String circle_moment_wedding_title_left_webp =
      'assets/images/circle/moment_wedding_title_left.webp';
  static const String moment$circle_moment_wedding_title_left_webp =
      'packages/moment/assets/images/circle/moment_wedding_title_left.webp';

  static const String circle_moment_wedding_title_right_webp =
      'assets/images/circle/moment_wedding_title_right.webp';
  static const String moment$circle_moment_wedding_title_right_webp =
      'packages/moment/assets/images/circle/moment_wedding_title_right.webp';

  static const String club_anchor_rank_top_bg_png =
      'assets/images/club/anchor_rank_top_bg.png';
  static const String moment$club_anchor_rank_top_bg_png =
      'packages/moment/assets/images/club/anchor_rank_top_bg.png';

  static const String club_ic_club_more_webp =
      'assets/images/club/ic_club_more.webp';
  static const String moment$club_ic_club_more_webp =
      'packages/moment/assets/images/club/ic_club_more.webp';

  static const String club_ic_club_rank_webp =
      'assets/images/club/ic_club_rank.webp';
  static const String moment$club_ic_club_rank_webp =
      'packages/moment/assets/images/club/ic_club_rank.webp';

  static const String club_ic_next_small_svg =
      'assets/images/club/ic_next_small.svg';
  static const String moment$club_ic_next_small_svg =
      'packages/moment/assets/images/club/ic_next_small.svg';

  static const String ic_add_svg = 'assets/images/ic_add.svg';
  static const String moment$ic_add_svg =
      'packages/moment/assets/images/ic_add.svg';

  static const String ic_album_chat_svg = 'assets/images/ic_album_chat.svg';
  static const String moment$ic_album_chat_svg =
      'packages/moment/assets/images/ic_album_chat.svg';

  static const String ic_album_gift_svg = 'assets/images/ic_album_gift.svg';
  static const String moment$ic_album_gift_svg =
      'packages/moment/assets/images/ic_album_gift.svg';

  static const String ic_album_say_hi_svg = 'assets/images/ic_album_say_hi.svg';
  static const String moment$ic_album_say_hi_svg =
      'packages/moment/assets/images/ic_album_say_hi.svg';

  static const String ic_all_svg = 'assets/images/ic_all.svg';
  static const String moment$ic_all_svg =
      'packages/moment/assets/images/ic_all.svg';

  static const String ic_audio_yellow_svg = 'assets/images/ic_audio_yellow.svg';
  static const String moment$ic_audio_yellow_svg =
      'packages/moment/assets/images/ic_audio_yellow.svg';

  static const String ic_case_list_comment_svg =
      'assets/images/ic_case_list_comment.svg';
  static const String moment$ic_case_list_comment_svg =
      'packages/moment/assets/images/ic_case_list_comment.svg';

  static const String ic_case_list_watch_svg =
      'assets/images/ic_case_list_watch.svg';
  static const String moment$ic_case_list_watch_svg =
      'packages/moment/assets/images/ic_case_list_watch.svg';

  static const String ic_check_svg = 'assets/images/ic_check.svg';
  static const String moment$ic_check_svg =
      'packages/moment/assets/images/ic_check.svg';

  static const String ic_checkbox_false_svg =
      'assets/images/ic_checkbox_false.svg';
  static const String moment$ic_checkbox_false_svg =
      'packages/moment/assets/images/ic_checkbox_false.svg';

  static const String ic_checkbox_true_svg =
      'assets/images/ic_checkbox_true.svg';
  static const String moment$ic_checkbox_true_svg =
      'packages/moment/assets/images/ic_checkbox_true.svg';

  static const String ic_close_svg = 'assets/images/ic_close.svg';
  static const String moment$ic_close_svg =
      'packages/moment/assets/images/ic_close.svg';

  static const String ic_close_pic_svg = 'assets/images/ic_close_pic.svg';
  static const String moment$ic_close_pic_svg =
      'packages/moment/assets/images/ic_close_pic.svg';

  static const String ic_comment_svg = 'assets/images/ic_comment.webp';
  static const String moment$ic_comment_svg =
      'packages/moment/assets/images/ic_comment.webp';

  static const String ic_comment_dark_webp =
      'assets/images/ic_comment_dark.webp';
  static const String moment$ic_comment_dark_webp =
      'packages/moment/assets/images/ic_comment_dark.webp';

  static const String ic_delete_svg = 'assets/images/ic_delete.svg';
  static const String moment$ic_delete_svg =
      'packages/moment/assets/images/ic_delete.svg';

  static const String ic_follow_svg = 'assets/images/ic_follow.svg';
  static const String moment$ic_follow_svg =
      'packages/moment/assets/images/ic_follow.svg';

  static const String ic_follow_add_svg = 'assets/images/ic_follow_add.svg';
  static const String moment$ic_follow_add_svg =
      'packages/moment/assets/images/ic_follow_add.svg';

  static const String ic_game_svg = 'assets/images/ic_game.svg';
  static const String moment$ic_game_svg =
      'packages/moment/assets/images/ic_game.svg';

  static const String ic_game_verify_png = 'assets/images/ic_game_verify.png';
  static const String moment$ic_game_verify_png =
      'packages/moment/assets/images/ic_game_verify.png';

  static const String ic_history_delete_svg =
      'assets/images/ic_history_delete.svg';
  static const String moment$ic_history_delete_svg =
      'packages/moment/assets/images/ic_history_delete.svg';

  static const String ic_home_send_moment_webp =
      'assets/images/ic_home_send_moment.webp';
  static const String moment$ic_home_send_moment_webp =
      'packages/moment/assets/images/ic_home_send_moment.webp';

  static const String ic_home_send_moment_dark_webp =
      'assets/images/ic_home_send_moment_dark.webp';
  static const String moment$ic_home_send_moment_dark_webp =
      'packages/moment/assets/images/ic_home_send_moment_dark.webp';

  static const String ic_horn_webp = 'assets/images/ic_horn.webp';
  static const String moment$ic_horn_webp =
      'packages/moment/assets/images/ic_horn.webp';

  static const String ic_like_small_svg = 'assets/images/ic_like_small.svg';
  static const String moment$ic_like_small_svg =
      'packages/moment/assets/images/ic_like_small.svg';

  static const String ic_list_more_svg = 'assets/images/ic_list_more.svg';
  static const String moment$ic_list_more_svg =
      'packages/moment/assets/images/ic_list_more.svg';

  static const String ic_location_svg = 'assets/images/ic_location.svg';
  static const String moment$ic_location_svg =
      'packages/moment/assets/images/ic_location.svg';

  static const String ic_moment_follow_png =
      'assets/images/ic_moment_follow.png';
  static const String moment$ic_moment_follow_png =
      'packages/moment/assets/images/ic_moment_follow.png';

  static const String ic_moment_goto_sing_svg =
      'assets/images/ic_moment_goto_sing.svg';
  static const String moment$ic_moment_goto_sing_svg =
      'packages/moment/assets/images/ic_moment_goto_sing.svg';

  static const String ic_moment_hot_topic_dark_webp =
      'assets/images/ic_moment_hot_topic_dark.webp';
  static const String moment$ic_moment_hot_topic_dark_webp =
      'packages/moment/assets/images/ic_moment_hot_topic_dark.webp';

  static const String ic_moment_publish_webp =
      'assets/images/ic_moment_publish.webp';
  static const String moment$ic_moment_publish_webp =
      'packages/moment/assets/images/ic_moment_publish.webp';

  static const String ic_more_svg = 'assets/images/ic_more.svg';
  static const String moment$ic_more_svg =
      'packages/moment/assets/images/ic_more.svg';

  static const String ic_next_svg = 'assets/images/ic_next.svg';
  static const String moment$ic_next_svg =
      'packages/moment/assets/images/ic_next.svg';

  static const String ic_next_small_fq_svg =
      'assets/images/ic_next_small_fq.svg';
  static const String moment$ic_next_small_fq_svg =
      'packages/moment/assets/images/ic_next_small_fq.svg';

  static const String ic_play_game_svg = 'assets/images/ic_play_game.svg';
  static const String moment$ic_play_game_svg =
      'packages/moment/assets/images/ic_play_game.svg';

  static const String ic_play_tag_svg = 'assets/images/ic_play_tag.svg';
  static const String moment$ic_play_tag_svg =
      'packages/moment/assets/images/ic_play_tag.svg';

  static const String ic_publish_audio_png =
      'assets/images/ic_publish_audio.png';
  static const String moment$ic_publish_audio_png =
      'packages/moment/assets/images/ic_publish_audio.png';

  static const String ic_publish_audio_dark_png =
      'assets/images/ic_publish_audio_dark.png';
  static const String moment$ic_publish_audio_dark_png =
      'packages/moment/assets/images/ic_publish_audio_dark.png';

  static const String ic_publish_image_png =
      'assets/images/ic_publish_image.png';
  static const String moment$ic_publish_image_png =
      'packages/moment/assets/images/ic_publish_image.png';

  static const String ic_publish_image_dark_png =
      'assets/images/ic_publish_image_dark.png';
  static const String moment$ic_publish_image_dark_png =
      'packages/moment/assets/images/ic_publish_image_dark.png';

  static const String ic_publish_video_png =
      'assets/images/ic_publish_video.png';
  static const String moment$ic_publish_video_png =
      'packages/moment/assets/images/ic_publish_video.png';

  static const String ic_publish_video_dark_png =
      'assets/images/ic_publish_video_dark.png';
  static const String moment$ic_publish_video_dark_png =
      'packages/moment/assets/images/ic_publish_video_dark.png';

  static const String ic_recommend_webp = 'assets/images/ic_recommend.webp';
  static const String moment$ic_recommend_webp =
      'packages/moment/assets/images/ic_recommend.webp';

  static const String ic_record_start_svg = 'assets/images/ic_record_start.svg';
  static const String moment$ic_record_start_svg =
      'packages/moment/assets/images/ic_record_start.svg';

  static const String ic_record_stop_svg = 'assets/images/ic_record_stop.svg';
  static const String moment$ic_record_stop_svg =
      'packages/moment/assets/images/ic_record_stop.svg';

  static const String ic_rush_like_svg = 'assets/images/ic_rush_like.webp';
  static const String moment$ic_rush_like_svg =
      'packages/moment/assets/images/ic_rush_like.webp';

  static const String ic_rush_like_default_svg =
      'assets/images/ic_rush_like_default.webp';
  static const String moment$ic_rush_like_default_svg =
      'packages/moment/assets/images/ic_rush_like_default.webp';

  static const String ic_say_hi_v2_svg = 'assets/images/ic_say_hi_v2.svg';
  static const String moment$ic_say_hi_v2_svg =
      'packages/moment/assets/images/ic_say_hi_v2.svg';

  static const String ic_share_svg = 'assets/images/ic_share.svg';
  static const String moment$ic_share_svg =
      'packages/moment/assets/images/ic_share.svg';

  static const String ic_soundplay_svg = 'assets/images/ic_soundplay.svg';
  static const String moment$ic_soundplay_svg =
      'packages/moment/assets/images/ic_soundplay.svg';

  static const String ic_tag_svg = 'assets/images/ic_tag.svg';
  static const String moment$ic_tag_svg =
      'packages/moment/assets/images/ic_tag.svg';

  static const String ic_tag_blue_svg = 'assets/images/ic_tag_blue.svg';
  static const String moment$ic_tag_blue_svg =
      'packages/moment/assets/images/ic_tag_blue.svg';

  static const String ic_tag_delete_svg = 'assets/images/ic_tag_delete.svg';
  static const String moment$ic_tag_delete_svg =
      'packages/moment/assets/images/ic_tag_delete.svg';

  static const String ic_title_tag_svg = 'assets/images/ic_title_tag.svg';
  static const String moment$ic_title_tag_svg =
      'packages/moment/assets/images/ic_title_tag.svg';

  static const String ic_topic_send_moment_webp =
      'assets/images/ic_topic_send_moment.webp';
  static const String moment$ic_topic_send_moment_webp =
      'packages/moment/assets/images/ic_topic_send_moment.webp';

  static const String ic_topic_square_svg = 'assets/images/ic_topic_square.svg';
  static const String moment$ic_topic_square_svg =
      'packages/moment/assets/images/ic_topic_square.svg';

  static const String ic_topic_square_follow_png =
      'assets/images/ic_topic_square_follow.png';
  static const String moment$ic_topic_square_follow_png =
      'packages/moment/assets/images/ic_topic_square_follow.png';

  static const String ic_topic_square_follow_dark_png =
      'assets/images/ic_topic_square_follow_dark.png';
  static const String moment$ic_topic_square_follow_dark_png =
      'packages/moment/assets/images/ic_topic_square_follow_dark.png';

  static const String ic_topic_square_followed_png =
      'assets/images/ic_topic_square_followed.png';
  static const String moment$ic_topic_square_followed_png =
      'packages/moment/assets/images/ic_topic_square_followed.png';

  static const String ic_topic_square_followed_dark_png =
      'assets/images/ic_topic_square_followed_dark.png';
  static const String moment$ic_topic_square_followed_dark_png =
      'packages/moment/assets/images/ic_topic_square_followed_dark.png';

  static const String ic_topic_square_followed_dart_png =
      'assets/images/ic_topic_square_followed_dart.png';
  static const String moment$ic_topic_square_followed_dart_png =
      'packages/moment/assets/images/ic_topic_square_followed_dart.png';

  static const String ic_topic_tag_svg = 'assets/images/ic_topic_tag.svg';
  static const String moment$ic_topic_tag_svg =
      'packages/moment/assets/images/ic_topic_tag.svg';

  static const String ic_topic_tag_2_webp = 'assets/images/ic_topic_tag_2.webp';
  static const String moment$ic_topic_tag_2_webp =
      'packages/moment/assets/images/ic_topic_tag_2.webp';

  static const String ic_topic_tag_2_dark_webp =
      'assets/images/ic_topic_tag_2_dark.webp';
  static const String moment$ic_topic_tag_2_dark_webp =
      'packages/moment/assets/images/ic_topic_tag_2_dark.webp';

  static const String ic_video_mute_png = 'assets/images/ic_video_mute.png';
  static const String moment$ic_video_mute_png =
      'packages/moment/assets/images/ic_video_mute.png';

  static const String ic_video_no_mute_png =
      'assets/images/ic_video_no_mute.png';
  static const String moment$ic_video_no_mute_png =
      'packages/moment/assets/images/ic_video_no_mute.png';

  static const String ic_video_play_svg = 'assets/images/ic_video_play.svg';
  static const String moment$ic_video_play_svg =
      'packages/moment/assets/images/ic_video_play.svg';

  static const String ic_zuan_webp = 'assets/images/ic_zuan.webp';
  static const String moment$ic_zuan_webp =
      'packages/moment/assets/images/ic_zuan.webp';

  static const String master_content_bg_big_webp =
      'assets/images/master/content_bg_big.webp';
  static const String moment$master_content_bg_big_webp =
      'packages/moment/assets/images/master/content_bg_big.webp';

  static const String master_content_bg_small_webp =
      'assets/images/master/content_bg_small.webp';
  static const String moment$master_content_bg_small_webp =
      'packages/moment/assets/images/master/content_bg_small.webp';

  static const String master_content_top_webp =
      'assets/images/master/content_top.webp';
  static const String moment$master_content_top_webp =
      'packages/moment/assets/images/master/content_top.webp';

  static const String master_dialog_bg_webp =
      'assets/images/master/dialog_bg.webp';
  static const String moment$master_dialog_bg_webp =
      'packages/moment/assets/images/master/dialog_bg.webp';

  static const String master_text_btn_get_award_webp =
      'assets/images/master/text_btn_get_award.webp';
  static const String moment$master_text_btn_get_award_webp =
      'packages/moment/assets/images/master/text_btn_get_award.webp';

  static const String master_text_btn_see_webp =
      'assets/images/master/text_btn_see.webp';
  static const String moment$master_text_btn_see_webp =
      'packages/moment/assets/images/master/text_btn_see.webp';

  static const String master_text_task_webp =
      'assets/images/master/text_task.webp';
  static const String moment$master_text_task_webp =
      'packages/moment/assets/images/master/text_task.webp';

  static const String master_text_topic_webp =
      'assets/images/master/text_topic.webp';
  static const String moment$master_text_topic_webp =
      'packages/moment/assets/images/master/text_topic.webp';

  static const String moment_at_icon_svg = 'assets/images/moment_at_icon.svg';
  static const String moment$moment_at_icon_svg =
      'packages/moment/assets/images/moment_at_icon.svg';

  static const String moment_at_selected_svg =
      'assets/images/moment_at_selected.svg';
  static const String moment$moment_at_selected_svg =
      'packages/moment/assets/images/moment_at_selected.svg';

  static const String moment_at_unSelected_png =
      'assets/images/moment_at_unSelected.png';
  static const String moment$moment_at_unSelected_png =
      'packages/moment/assets/images/moment_at_unSelected.png';

  static const String moment_follow_activity_love_bg_webp =
      'assets/images/moment_follow_activity_love_bg.webp';
  static const String moment$moment_follow_activity_love_bg_webp =
      'packages/moment/assets/images/moment_follow_activity_love_bg.webp';

  static const String moment_follow_activity_user_bg_webp =
      'assets/images/moment_follow_activity_user_bg.webp';
  static const String moment$moment_follow_activity_user_bg_webp =
      'packages/moment/assets/images/moment_follow_activity_user_bg.webp';

  static const String moment_tag_bg_webp = 'assets/images/moment_tag_bg.webp';
  static const String moment$moment_tag_bg_webp =
      'packages/moment/assets/images/moment_tag_bg.webp';

  static const String small_mood_empty_webp =
      'assets/images/small_mood/empty.webp';
  static const String moment$small_mood_empty_webp =
      'packages/moment/assets/images/small_mood/empty.webp';

  static const String small_mood_entry_webp =
      'assets/images/small_mood/entry.webp';
  static const String moment$small_mood_entry_webp =
      'packages/moment/assets/images/small_mood/entry.webp';

  static const String small_mood_ic_bottom_bg_decoration_webp =
      'assets/images/small_mood/ic_bottom_bg_decoration.webp';
  static const String moment$small_mood_ic_bottom_bg_decoration_webp =
      'packages/moment/assets/images/small_mood/ic_bottom_bg_decoration.webp';

  static const String small_mood_ic_emojifq_webp =
      'assets/images/small_mood/ic_emojifq.webp';
  static const String moment$small_mood_ic_emojifq_webp =
      'packages/moment/assets/images/small_mood/ic_emojifq.webp';

  static const String small_mood_ic_top_bg_decoration_webp =
      'assets/images/small_mood/ic_top_bg_decoration.webp';
  static const String moment$small_mood_ic_top_bg_decoration_webp =
      'packages/moment/assets/images/small_mood/ic_top_bg_decoration.webp';

  static const String statistic_bg_fragment_webp =
      'assets/images/statistic/bg_fragment.webp';
  static const String moment$statistic_bg_fragment_webp =
      'packages/moment/assets/images/statistic/bg_fragment.webp';

  static const String statistic_bg_head_webp =
      'assets/images/statistic/bg_head.webp';
  static const String moment$statistic_bg_head_webp =
      'packages/moment/assets/images/statistic/bg_head.webp';

  static const String statistic_bg_tab_default_webp =
      'assets/images/statistic/bg_tab_default.webp';
  static const String moment$statistic_bg_tab_default_webp =
      'packages/moment/assets/images/statistic/bg_tab_default.webp';

  static const String statistic_bg_tab_selected_webp =
      'assets/images/statistic/bg_tab_selected.webp';
  static const String moment$statistic_bg_tab_selected_webp =
      'packages/moment/assets/images/statistic/bg_tab_selected.webp';

  static const String statistic_bg_week_content_info_webp =
      'assets/images/statistic/bg_week_content_info.webp';
  static const String moment$statistic_bg_week_content_info_webp =
      'packages/moment/assets/images/statistic/bg_week_content_info.webp';

  static const String statistic_bg_week_statistic_dialog_webp =
      'assets/images/statistic/bg_week_statistic_dialog.webp';
  static const String moment$statistic_bg_week_statistic_dialog_webp =
      'packages/moment/assets/images/statistic/bg_week_statistic_dialog.webp';

  static const String statistic_btn_week_statistic_see_webp =
      'assets/images/statistic/btn_week_statistic_see.webp';
  static const String moment$statistic_btn_week_statistic_see_webp =
      'packages/moment/assets/images/statistic/btn_week_statistic_see.webp';

  static const String statistic_ic_back_webp =
      'assets/images/statistic/ic_back.webp';
  static const String moment$statistic_ic_back_webp =
      'packages/moment/assets/images/statistic/ic_back.webp';

  static const String statistic_ic_cool_webp =
      'assets/images/statistic/ic_cool.webp';
  static const String moment$statistic_ic_cool_webp =
      'packages/moment/assets/images/statistic/ic_cool.webp';

  static const String statistic_ic_dialog_close_webp =
      'assets/images/statistic/ic_dialog_close.webp';
  static const String moment$statistic_ic_dialog_close_webp =
      'packages/moment/assets/images/statistic/ic_dialog_close.webp';

  static const String statistic_ic_top_one_webp =
      'assets/images/statistic/ic_top_one.webp';
  static const String moment$statistic_ic_top_one_webp =
      'packages/moment/assets/images/statistic/ic_top_one.webp';

  static const String statistic_ic_top_three_webp =
      'assets/images/statistic/ic_top_three.webp';
  static const String moment$statistic_ic_top_three_webp =
      'packages/moment/assets/images/statistic/ic_top_three.webp';

  static const String statistic_ic_top_two_webp =
      'assets/images/statistic/ic_top_two.webp';
  static const String moment$statistic_ic_top_two_webp =
      'packages/moment/assets/images/statistic/ic_top_two.webp';

  static const String statistic_img_paper_webp =
      'assets/images/statistic/img_paper.webp';
  static const String moment$statistic_img_paper_webp =
      'packages/moment/assets/images/statistic/img_paper.webp';

  static const String moment_ic_comment_svg =
      'assets/images/moment/ic_comment.webp';
  static const String shared$moment_ic_comment_svg =
      'packages/shared/assets/images/moment/ic_comment.webp';

  static const String moment_ic_rush_like_svg =
      'assets/images/moment/ic_rush_like.webp';
  static const String shared$moment_ic_rush_like_svg =
      'packages/shared/assets/images/moment/ic_rush_like.webp';

  static const String moment_ic_rush_like_webp =
      'assets/images/ic_rush_like.webp';
  static const String shared$moment_ic_rush_like_webp =
      'packages/shared/assets/images/ic_rush_like.webp';

  static const String moment_ic_rush_like_dark_webp =
      'assets/images/ic_rush_like.webp';
  static const String shared$moment_ic_rush_like_dark_webp =
      'packages/shared/assets/images/ic_rush_like.webp';

  static const String moment_ic_rush_like_default_svg =
      'assets/images/ic_rush_like_default.webp';
  static const String shared$moment_ic_rush_like_default_svg =
      'packages/shared/assets/images/ic_rush_like_default.webp';

  static const String moment_ic_rush_unlike_svg =
      'assets/images/ic_rush_unlike.webp';
  static const String shared$moment_ic_rush_unlike_svg =
      'packages/shared/assets/images/ic_rush_unlike.webp';

  static const String moment_ic_rush_unlike_webp =
      'assets/images/ic_rush_unlike.webp';
  static const String shared$moment_ic_rush_unlike_webp =
      'packages/shared/assets/images/ic_rush_unlike.webp';

  static const String moment_ic_rush_unlike_dark_webp =
      'assets/images/ic_rush_unlike_dark.webp';
  static const String shared$moment_ic_rush_unlike_dark_webp =
      'packages/shared/assets/images/ic_rush_unlike_dark.webp';

  static const String moment_ic_say_hi_svg = 'assets/images/ic_say_hi.svg';
  static const String shared$moment_ic_say_hi_svg =
      'packages/shared/assets/images/ic_say_hi.svg';

  static const String moment_ic_say_hi_webp = 'assets/images/ic_say_hi.webp';
  static const String shared$moment_ic_say_hi_webp =
      'packages/shared/assets/images/ic_say_hi.webp';

  static const String moment_ic_say_hi_dark_webp =
      'assets/images/ic_say_hi.webp';
  static const String shared$moment_ic_say_hi_dark_webp =
      'packages/shared/assets/images/ic_say_hi.webp';
}
