// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 39.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'settings';

  static const String auth_success_svg = 'assets/images/auth_success.svg';
  static const String settings$auth_success_svg =
      'packages/settings/assets/images/auth_success.svg';

  static const String balance_rechange_activity_bg_webp =
      'assets/images/balance/rechange_activity_bg.webp';
  static const String settings$balance_rechange_activity_bg_webp =
      'packages/settings/assets/images/balance/rechange_activity_bg.webp';

  static const String balance_rechange_activity_button_webp =
      'assets/images/balance/rechange_activity_button.webp';
  static const String settings$balance_rechange_activity_button_webp =
      'packages/settings/assets/images/balance/rechange_activity_button.webp';

  static const String balance_rechange_activity_count_down_bg_webp =
      'assets/images/balance/rechange_activity_count_down_bg.webp';
  static const String settings$balance_rechange_activity_count_down_bg_webp =
      'packages/settings/assets/images/balance/rechange_activity_count_down_bg.webp';

  static const String balance_recommend_top_demo_png =
      'assets/images/balance/recommend_top_demo.png';
  static const String settings$balance_recommend_top_demo_png =
      'packages/settings/assets/images/balance/recommend_top_demo.png';

  static const String balance_recommend_top_done_png =
      'assets/images/balance/recommend_top_done.png';
  static const String settings$balance_recommend_top_done_png =
      'packages/settings/assets/images/balance/recommend_top_done.png';

  static const String btn_bind_success_png =
      'assets/images/btn_bind_success.png';
  static const String settings$btn_bind_success_png =
      'packages/settings/assets/images/btn_bind_success.png';

  static const String dialog_close_webp = 'assets/images/dialog_close.webp';
  static const String settings$dialog_close_webp =
      'packages/settings/assets/images/dialog_close.webp';

  static const String hot_request_1_webp = 'assets/images/hot_request_1.webp';
  static const String settings$hot_request_1_webp =
      'packages/settings/assets/images/hot_request_1.webp';

  static const String hot_request_2_webp = 'assets/images/hot_request_2.webp';
  static const String settings$hot_request_2_webp =
      'packages/settings/assets/images/hot_request_2.webp';

  static const String hot_request_3_webp = 'assets/images/hot_request_3.webp';
  static const String settings$hot_request_3_webp =
      'packages/settings/assets/images/hot_request_3.webp';

  static const String ic_account_add_png = 'assets/images/ic_account_add.png';
  static const String settings$ic_account_add_png =
      'packages/settings/assets/images/ic_account_add.png';

  static const String ic_account_add_dark_png =
      'assets/images/ic_account_add_dark.png';
  static const String settings$ic_account_add_dark_png =
      'packages/settings/assets/images/ic_account_add_dark.png';

  static const String ic_add_skill_svg = 'assets/images/ic_add_skill.svg';
  static const String settings$ic_add_skill_svg =
      'packages/settings/assets/images/ic_add_skill.svg';

  static const String ic_charm_svg = 'assets/images/ic_charm.svg';
  static const String settings$ic_charm_svg =
      'packages/settings/assets/images/ic_charm.svg';

  static const String ic_check_svg = 'assets/images/ic_check.svg';
  static const String settings$ic_check_svg =
      'packages/settings/assets/images/ic_check.svg';

  static const String ic_checkbox_normal_svg =
      'assets/images/ic_checkbox_normal.svg';
  static const String settings$ic_checkbox_normal_svg =
      'packages/settings/assets/images/ic_checkbox_normal.svg';

  static const String ic_checkbox_select_svg =
      'assets/images/ic_checkbox_select.svg';
  static const String settings$ic_checkbox_select_svg =
      'packages/settings/assets/images/ic_checkbox_select.svg';

  static const String ic_god_certify_success_webp =
      'assets/images/ic_god_certify_success.webp';
  static const String settings$ic_god_certify_success_webp =
      'packages/settings/assets/images/ic_god_certify_success.webp';

  static const String ic_gold_bean_webp = 'assets/images/ic_gold_bean.webp';
  static const String settings$ic_gold_bean_webp =
      'packages/settings/assets/images/ic_gold_bean.webp';

  static const String ic_gold_coin_png = 'assets/images/ic_gold_coin.png';
  static const String settings$ic_gold_coin_png =
      'packages/settings/assets/images/ic_gold_coin.png';

  static const String ic_home_theme_bg_dark_webp =
      'assets/images/ic_home_theme_bg_dark.webp';
  static const String settings$ic_home_theme_bg_dark_webp =
      'packages/settings/assets/images/ic_home_theme_bg_dark.webp';

  static const String ic_home_theme_bg_light_webp =
      'assets/images/ic_home_theme_bg_light.webp';
  static const String settings$ic_home_theme_bg_light_webp =
      'packages/settings/assets/images/ic_home_theme_bg_light.webp';

  static const String ic_money_png = 'assets/images/ic_money.png';
  static const String settings$ic_money_png =
      'packages/settings/assets/images/ic_money.png';

  static const String ic_money_diamond_png =
      'assets/images/ic_money_diamond.png';
  static const String settings$ic_money_diamond_png =
      'packages/settings/assets/images/ic_money_diamond.png';

  static const String ic_money_ios_png = 'assets/images/ic_money_ios.png';
  static const String settings$ic_money_ios_png =
      'packages/settings/assets/images/ic_money_ios.png';

  static const String ic_next_svg = 'assets/images/ic_next.svg';
  static const String settings$ic_next_svg =
      'packages/settings/assets/images/ic_next.svg';

  static const String ic_order_coupon_webp =
      'assets/images/ic_order_coupon.webp';
  static const String settings$ic_order_coupon_webp =
      'packages/settings/assets/images/ic_order_coupon.webp';

  static const String img_bind_safe_mobile_webp =
      'assets/images/img_bind_safe_mobile.webp';
  static const String settings$img_bind_safe_mobile_webp =
      'packages/settings/assets/images/img_bind_safe_mobile.webp';

  static const String juveniles_guide_icon_webp =
      'assets/images/juveniles_guide_icon.webp';
  static const String settings$juveniles_guide_icon_webp =
      'packages/settings/assets/images/juveniles_guide_icon.webp';

  static const String juveniles_guide_icon_disable_webp =
      'assets/images/juveniles_guide_icon_disable.webp';
  static const String settings$juveniles_guide_icon_disable_webp =
      'packages/settings/assets/images/juveniles_guide_icon_disable.webp';

  static const String nlogin_phone_png = 'assets/images/nlogin_phone.png';
  static const String settings$nlogin_phone_png =
      'packages/settings/assets/images/nlogin_phone.png';

  static const String nlogin_qq_png = 'assets/images/nlogin_qq.png';
  static const String settings$nlogin_qq_png =
      'packages/settings/assets/images/nlogin_qq.png';

  static const String nlogin_wechat_png = 'assets/images/nlogin_wechat.png';
  static const String settings$nlogin_wechat_png =
      'packages/settings/assets/images/nlogin_wechat.png';

  static const String recharge_bg_dark_webp =
      'assets/images/recharge_bg_dark.webp';
  static const String settings$recharge_bg_dark_webp =
      'packages/settings/assets/images/recharge_bg_dark.webp';

  static const String recharge_bg_light_webp =
      'assets/images/recharge_bg_light.webp';
  static const String settings$recharge_bg_light_webp =
      'packages/settings/assets/images/recharge_bg_light.webp';

  static const String review_review_approved_png =
      'assets/images/review/review_approved.png';
  static const String settings$review_review_approved_png =
      'packages/settings/assets/images/review/review_approved.png';

  static const String review_review_pending_png =
      'assets/images/review/review_pending.png';
  static const String settings$review_review_pending_png =
      'packages/settings/assets/images/review/review_pending.png';

  static const String unbind_success_webp = 'assets/images/unbind_success.webp';
  static const String settings$unbind_success_webp =
      'packages/settings/assets/images/unbind_success.webp';
  static const String icAutoCallRemindPng =
      'packages/settings/assets/images/ic_auto_call_remind.png';
}
