// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 496.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'chat';

  static const String accompany_house_im_accompany_house_heart1_webp = 'assets/images/accompany_house/im_accompany_house_heart1.webp';
  static const String chat$accompany_house_im_accompany_house_heart1_webp = 'packages/chat/assets/images/accompany_house/im_accompany_house_heart1.webp';

  static const String accompany_house_im_accompany_house_heart2_webp = 'assets/images/accompany_house/im_accompany_house_heart2.webp';
  static const String chat$accompany_house_im_accompany_house_heart2_webp = 'packages/chat/assets/images/accompany_house/im_accompany_house_heart2.webp';

  static const String accompany_house_im_accompany_house_heart3_webp = 'assets/images/accompany_house/im_accompany_house_heart3.webp';
  static const String chat$accompany_house_im_accompany_house_heart3_webp = 'packages/chat/assets/images/accompany_house/im_accompany_house_heart3.webp';

  static const String arrow_down_anim_webp = 'assets/images/arrow_down_anim.webp';
  static const String chat$arrow_down_anim_webp = 'packages/chat/assets/images/arrow_down_anim.webp';

  static const String arrow_up_anim_webp = 'assets/images/arrow_up_anim.webp';
  static const String chat$arrow_up_anim_webp = 'packages/chat/assets/images/arrow_up_anim.webp';

  static const String bg_chat_match_game_left_png = 'assets/images/bg_chat_match_game_left.png';
  static const String chat$bg_chat_match_game_left_png = 'packages/chat/assets/images/bg_chat_match_game_left.png';

  static const String bg_chat_match_game_right_png = 'assets/images/bg_chat_match_game_right.png';
  static const String chat$bg_chat_match_game_right_png = 'packages/chat/assets/images/bg_chat_match_game_right.png';

  static const String chat_add_image_webp = 'assets/images/chat_add_image.webp';
  static const String chat$chat_add_image_webp = 'packages/chat/assets/images/chat_add_image.webp';

  static const String chat_add_image_dark_webp = 'assets/images/chat_add_image_dark.webp';
  static const String chat$chat_add_image_dark_webp = 'packages/chat/assets/images/chat_add_image_dark.webp';

  static const String chat_bottom_emote_webp = 'assets/images/chat_bottom_emote.webp';
  static const String chat$chat_bottom_emote_webp = 'packages/chat/assets/images/chat_bottom_emote.webp';

  static const String chat_bottom_emote_dark_webp = 'assets/images/chat_bottom_emote_dark.webp';
  static const String chat$chat_bottom_emote_dark_webp = 'packages/chat/assets/images/chat_bottom_emote_dark.webp';

  static const String chat_bottom_emote_select_webp = 'assets/images/chat_bottom_emote_select.webp';
  static const String chat$chat_bottom_emote_select_webp = 'packages/chat/assets/images/chat_bottom_emote_select.webp';

  static const String chat_bottom_emote_select_dark_webp = 'assets/images/chat_bottom_emote_select_dark.webp';
  static const String chat$chat_bottom_emote_select_dark_webp = 'packages/chat/assets/images/chat_bottom_emote_select_dark.webp';

  static const String chat_bottom_game_svg = 'assets/images/chat_bottom_game.svg';
  static const String chat$chat_bottom_game_svg = 'packages/chat/assets/images/chat_bottom_game.svg';

  static const String chat_bottom_gift_svg = 'assets/images/chat_bottom_gift.svg';
  static const String chat$chat_bottom_gift_svg = 'packages/chat/assets/images/chat_bottom_gift.svg';

  static const String chat_bottom_gift_webp = 'assets/images/chat_bottom_gift.webp';
  static const String chat$chat_bottom_gift_webp = 'packages/chat/assets/images/chat_bottom_gift.webp';

  static const String chat_bottom_gift_dark_webp = 'assets/images/chat_bottom_gift_dark.webp';
  static const String chat$chat_bottom_gift_dark_webp = 'packages/chat/assets/images/chat_bottom_gift_dark.webp';

  static const String chat_bottom_light_svg = 'assets/images/chat_bottom_light.svg';
  static const String chat$chat_bottom_light_svg = 'packages/chat/assets/images/chat_bottom_light.svg';

  static const String chat_bottom_more_add_webp = 'assets/images/chat_bottom_more_add.webp';
  static const String chat$chat_bottom_more_add_webp = 'packages/chat/assets/images/chat_bottom_more_add.webp';

  static const String chat_bottom_more_add_dark_webp = 'assets/images/chat_bottom_more_add_dark.webp';
  static const String chat$chat_bottom_more_add_dark_webp = 'packages/chat/assets/images/chat_bottom_more_add_dark.webp';

  static const String chat_bottom_more_close_webp = 'assets/images/chat_bottom_more_close.webp';
  static const String chat$chat_bottom_more_close_webp = 'packages/chat/assets/images/chat_bottom_more_close.webp';

  static const String chat_bottom_more_close_dark_webp = 'assets/images/chat_bottom_more_close_dark.webp';
  static const String chat$chat_bottom_more_close_dark_webp = 'packages/chat/assets/images/chat_bottom_more_close_dark.webp';

  static const String chat_bottom_more_extend_audio_webp = 'assets/images/chat_bottom_more_extend_audio.webp';
  static const String chat$chat_bottom_more_extend_audio_webp = 'packages/chat/assets/images/chat_bottom_more_extend_audio.webp';

  static const String chat_bottom_more_extend_audio_dark_webp = 'assets/images/chat_bottom_more_extend_audio_dark.webp';
  static const String chat$chat_bottom_more_extend_audio_dark_webp = 'packages/chat/assets/images/chat_bottom_more_extend_audio_dark.webp';

  static const String chat_bottom_more_extend_business_card_webp = 'assets/images/chat_bottom_more_extend_business_card.webp';
  static const String chat$chat_bottom_more_extend_business_card_webp = 'packages/chat/assets/images/chat_bottom_more_extend_business_card.webp';

  static const String chat_bottom_more_extend_business_card_dark_webp = 'assets/images/chat_bottom_more_extend_business_card_dark.webp';
  static const String chat$chat_bottom_more_extend_business_card_dark_webp = 'packages/chat/assets/images/chat_bottom_more_extend_business_card_dark.webp';

  static const String chat_bottom_more_extend_change_gift_webp = 'assets/images/chat_bottom_more_extend_change_gift.webp';
  static const String chat$chat_bottom_more_extend_change_gift_webp = 'packages/chat/assets/images/chat_bottom_more_extend_change_gift.webp';

  static const String chat_bottom_more_extend_change_gift_dark_webp = 'assets/images/chat_bottom_more_extend_change_gift_dark.webp';
  static const String chat$chat_bottom_more_extend_change_gift_dark_webp = 'packages/chat/assets/images/chat_bottom_more_extend_change_gift_dark.webp';

  static const String chat_bottom_more_extend_defend_webp = 'assets/images/chat_bottom_more_extend_defend.webp';
  static const String chat$chat_bottom_more_extend_defend_webp = 'packages/chat/assets/images/chat_bottom_more_extend_defend.webp';

  static const String chat_bottom_more_extend_defend_dark_webp = 'assets/images/chat_bottom_more_extend_defend_dark.webp';
  static const String chat$chat_bottom_more_extend_defend_dark_webp = 'packages/chat/assets/images/chat_bottom_more_extend_defend_dark.webp';

  static const String chat_bottom_more_extend_location_webp = 'assets/images/chat_bottom_more_extend_location.webp';
  static const String chat$chat_bottom_more_extend_location_webp = 'packages/chat/assets/images/chat_bottom_more_extend_location.webp';

  static const String chat_bottom_more_extend_location_dark_webp = 'assets/images/chat_bottom_more_extend_location_dark.webp';
  static const String chat$chat_bottom_more_extend_location_dark_webp = 'packages/chat/assets/images/chat_bottom_more_extend_location_dark.webp';

  static const String chat_bottom_more_extend_package_webp = 'assets/images/chat_bottom_more_extend_package.webp';
  static const String chat$chat_bottom_more_extend_package_webp = 'packages/chat/assets/images/chat_bottom_more_extend_package.webp';

  static const String chat_bottom_more_extend_package_dark_webp = 'assets/images/chat_bottom_more_extend_package_dark.webp';
  static const String chat$chat_bottom_more_extend_package_dark_webp = 'packages/chat/assets/images/chat_bottom_more_extend_package_dark.webp';

  static const String chat_bottom_more_extend_tacit_webp = 'assets/images/chat_bottom_more_extend_tacit.webp';
  static const String chat$chat_bottom_more_extend_tacit_webp = 'packages/chat/assets/images/chat_bottom_more_extend_tacit.webp';

  static const String chat_bottom_more_extend_tacit_dark_webp = 'assets/images/chat_bottom_more_extend_tacit_dark.webp';
  static const String chat$chat_bottom_more_extend_tacit_dark_webp = 'packages/chat/assets/images/chat_bottom_more_extend_tacit_dark.webp';

  static const String chat_bottom_more_extend_true_word_webp = 'assets/images/chat_bottom_more_extend_true_word.webp';
  static const String chat$chat_bottom_more_extend_true_word_webp = 'packages/chat/assets/images/chat_bottom_more_extend_true_word.webp';

  static const String chat_bottom_more_extend_true_word_dark_webp = 'assets/images/chat_bottom_more_extend_true_word_dark.webp';
  static const String chat$chat_bottom_more_extend_true_word_dark_webp = 'packages/chat/assets/images/chat_bottom_more_extend_true_word_dark.webp';

  static const String chat_bottom_more_extend_video_svg = 'assets/images/chat_bottom_more_extend_video.svg';
  static const String chat$chat_bottom_more_extend_video_svg = 'packages/chat/assets/images/chat_bottom_more_extend_video.svg';

  static const String chat_bottom_pic_webp = 'assets/images/chat_bottom_pic.webp';
  static const String chat$chat_bottom_pic_webp = 'packages/chat/assets/images/chat_bottom_pic.webp';

  static const String chat_bottom_pic_dark_webp = 'assets/images/chat_bottom_pic_dark.webp';
  static const String chat$chat_bottom_pic_dark_webp = 'packages/chat/assets/images/chat_bottom_pic_dark.webp';

  static const String chat_bottom_pic_select_webp = 'assets/images/chat_bottom_pic_select.webp';
  static const String chat$chat_bottom_pic_select_webp = 'packages/chat/assets/images/chat_bottom_pic_select.webp';

  static const String chat_bottom_pic_select_dark_webp = 'assets/images/chat_bottom_pic_select_dark.webp';
  static const String chat$chat_bottom_pic_select_dark_webp = 'packages/chat/assets/images/chat_bottom_pic_select_dark.webp';

  static const String chat_bottom_true_word_svg = 'assets/images/chat_bottom_true_word.svg';
  static const String chat$chat_bottom_true_word_svg = 'packages/chat/assets/images/chat_bottom_true_word.svg';

  static const String chat_bottom_true_word_webp = 'assets/images/chat_bottom_true_word.webp';
  static const String chat$chat_bottom_true_word_webp = 'packages/chat/assets/images/chat_bottom_true_word.webp';

  static const String chat_bottom_true_word_dark_webp = 'assets/images/chat_bottom_true_word_dark.webp';
  static const String chat$chat_bottom_true_word_dark_webp = 'packages/chat/assets/images/chat_bottom_true_word_dark.webp';

  static const String chat_bottom_voice_webp = 'assets/images/chat_bottom_voice.webp';
  static const String chat$chat_bottom_voice_webp = 'packages/chat/assets/images/chat_bottom_voice.webp';

  static const String chat_bottom_voice_dark_webp = 'assets/images/chat_bottom_voice_dark.webp';
  static const String chat$chat_bottom_voice_dark_webp = 'packages/chat/assets/images/chat_bottom_voice_dark.webp';

  static const String chat_bottom_voice_select_webp = 'assets/images/chat_bottom_voice_select.webp';
  static const String chat$chat_bottom_voice_select_webp = 'packages/chat/assets/images/chat_bottom_voice_select.webp';

  static const String chat_bottom_voice_select_dark_webp = 'assets/images/chat_bottom_voice_select_dark.webp';
  static const String chat$chat_bottom_voice_select_dark_webp = 'packages/chat/assets/images/chat_bottom_voice_select_dark.webp';

  static const String chat_card_close_svg = 'assets/images/chat_card_close.svg';
  static const String chat$chat_card_close_svg = 'packages/chat/assets/images/chat_card_close.svg';

  static const String chat_card_follow_tips_arrow_webp = 'assets/images/chat_card_follow_tips_arrow.webp';
  static const String chat$chat_card_follow_tips_arrow_webp = 'packages/chat/assets/images/chat_card_follow_tips_arrow.webp';

  static const String chat_card_followed_anim_webp = 'assets/images/chat_card_followed_anim.webp';
  static const String chat$chat_card_followed_anim_webp = 'packages/chat/assets/images/chat_card_followed_anim.webp';

  static const String chat_close_svg = 'assets/images/chat_close.svg';
  static const String chat$chat_close_svg = 'packages/chat/assets/images/chat_close.svg';

  static const String chat_close_icon_svg = 'assets/images/chat_close_icon.svg';
  static const String chat$chat_close_icon_svg = 'packages/chat/assets/images/chat_close_icon.svg';

  static const String chat_confirm_off_png = 'assets/images/chat_confirm_off.png';
  static const String chat$chat_confirm_off_png = 'packages/chat/assets/images/chat_confirm_off.png';

  static const String chat_confirm_on_png = 'assets/images/chat_confirm_on.png';
  static const String chat$chat_confirm_on_png = 'packages/chat/assets/images/chat_confirm_on.png';

  static const String chat_custom_gift_stencil_webp = 'assets/images/chat_custom_gift_stencil.webp';
  static const String chat$chat_custom_gift_stencil_webp = 'packages/chat/assets/images/chat_custom_gift_stencil.webp';

  static const String chat_custom_gift_value_webp = 'assets/images/chat_custom_gift_value.webp';
  static const String chat$chat_custom_gift_value_webp = 'packages/chat/assets/images/chat_custom_gift_value.webp';

  static const String chat_filter_all_svg = 'assets/images/chat_filter_all.svg';
  static const String chat$chat_filter_all_svg = 'packages/chat/assets/images/chat_filter_all.svg';

  static const String chat_fliter_female_svg = 'assets/images/chat_fliter_female.svg';
  static const String chat$chat_fliter_female_svg = 'packages/chat/assets/images/chat_fliter_female.svg';

  static const String chat_fliter_male_svg = 'assets/images/chat_fliter_male.svg';
  static const String chat$chat_fliter_male_svg = 'packages/chat/assets/images/chat_fliter_male.svg';

  static const String chat_friend_card_bg_png = 'assets/images/chat_friend_card_bg.png';
  static const String chat$chat_friend_card_bg_png = 'packages/chat/assets/images/chat_friend_card_bg.png';

  static const String chat_game_default_icon_png = 'assets/images/chat_game_default_icon.png';
  static const String chat$chat_game_default_icon_png = 'packages/chat/assets/images/chat_game_default_icon.png';

  static const String chat_guide_bg_webp = 'assets/images/chat_guide_bg.webp';
  static const String chat$chat_guide_bg_webp = 'packages/chat/assets/images/chat_guide_bg.webp';

  static const String chat_hi_png = 'assets/images/chat_hi.png';
  static const String chat$chat_hi_png = 'packages/chat/assets/images/chat_hi.png';

  static const String chat_hi_match_card_bg_webp = 'assets/images/chat_hi_match_card_bg.webp';
  static const String chat$chat_hi_match_card_bg_webp = 'packages/chat/assets/images/chat_hi_match_card_bg.webp';

  static const String chat_hi_match_heart_png = 'assets/images/chat_hi_match_heart.png';
  static const String chat$chat_hi_match_heart_png = 'packages/chat/assets/images/chat_hi_match_heart.png';

  static const String chat_ic_expand_arrow_svg = 'assets/images/chat_ic_expand_arrow.svg';
  static const String chat$chat_ic_expand_arrow_svg = 'packages/chat/assets/images/chat_ic_expand_arrow.svg';

  static const String chat_ic_pause_svg = 'assets/images/chat_ic_pause.svg';
  static const String chat$chat_ic_pause_svg = 'packages/chat/assets/images/chat_ic_pause.svg';

  static const String chat_ic_people_svg = 'assets/images/chat_ic_people.svg';
  static const String chat$chat_ic_people_svg = 'packages/chat/assets/images/chat_ic_people.svg';

  static const String chat_ic_play_svg = 'assets/images/chat_ic_play.svg';
  static const String chat$chat_ic_play_svg = 'packages/chat/assets/images/chat_ic_play.svg';

  static const String chat_ic_shrink_arrow_svg = 'assets/images/chat_ic_shrink_arrow.svg';
  static const String chat$chat_ic_shrink_arrow_svg = 'packages/chat/assets/images/chat_ic_shrink_arrow.svg';

  static const String chat_ic_video_play_png = 'assets/images/chat_ic_video_play.png';
  static const String chat$chat_ic_video_play_png = 'packages/chat/assets/images/chat_ic_video_play.png';

  static const String chat_icon_delete_svg = 'assets/images/chat_icon_delete.svg';
  static const String chat$chat_icon_delete_svg = 'packages/chat/assets/images/chat_icon_delete.svg';

  static const String chat_in_room_webp = 'assets/images/chat_in_room.webp';
  static const String chat$chat_in_room_webp = 'packages/chat/assets/images/chat_in_room.webp';

  static const String chat_instant_match_circle_bg_webp = 'assets/images/chat_instant_match_circle_bg.webp';
  static const String chat$chat_instant_match_circle_bg_webp = 'packages/chat/assets/images/chat_instant_match_circle_bg.webp';

  static const String chat_instant_match_rotate_bg_webp = 'assets/images/chat_instant_match_rotate_bg.webp';
  static const String chat$chat_instant_match_rotate_bg_webp = 'packages/chat/assets/images/chat_instant_match_rotate_bg.webp';

  static const String chat_intimacy_icon_webp = 'assets/images/chat_intimacy_icon.webp';
  static const String chat$chat_intimacy_icon_webp = 'packages/chat/assets/images/chat_intimacy_icon.webp';

  static const String chat_match_add_friendcard_webp = 'assets/images/chat_match_add_friendcard.webp';
  static const String chat$chat_match_add_friendcard_webp = 'packages/chat/assets/images/chat_match_add_friendcard.webp';

  static const String chat_match_button_bg_png = 'assets/images/chat_match_button_bg.png';
  static const String chat$chat_match_button_bg_png = 'packages/chat/assets/images/chat_match_button_bg.png';

  static const String chat_match_card_dismiss_png = 'assets/images/chat_match_card_dismiss.png';
  static const String chat$chat_match_card_dismiss_png = 'packages/chat/assets/images/chat_match_card_dismiss.png';

  static const String chat_match_card_follow_svg = 'assets/images/chat_match_card_follow.svg';
  static const String chat$chat_match_card_follow_svg = 'packages/chat/assets/images/chat_match_card_follow.svg';

  static const String chat_match_card_sayhi_webp = 'assets/images/chat_match_card_sayhi.webp';
  static const String chat$chat_match_card_sayhi_webp = 'packages/chat/assets/images/chat_match_card_sayhi.webp';

  static const String chat_match_card_sayhi_circle_png = 'assets/images/chat_match_card_sayhi_circle.png';
  static const String chat$chat_match_card_sayhi_circle_png = 'packages/chat/assets/images/chat_match_card_sayhi_circle.png';

  static const String chat_match_egg_dialog_bg_webp = 'assets/images/chat_match_egg_dialog_bg.webp';
  static const String chat$chat_match_egg_dialog_bg_webp = 'packages/chat/assets/images/chat_match_egg_dialog_bg.webp';

  static const String chat_match_egg_dialog_love_icon_left_webp = 'assets/images/chat_match_egg_dialog_love_icon_left.webp';
  static const String chat$chat_match_egg_dialog_love_icon_left_webp = 'packages/chat/assets/images/chat_match_egg_dialog_love_icon_left.webp';

  static const String chat_match_egg_dialog_love_icon_right_webp = 'assets/images/chat_match_egg_dialog_love_icon_right.webp';
  static const String chat$chat_match_egg_dialog_love_icon_right_webp = 'packages/chat/assets/images/chat_match_egg_dialog_love_icon_right.webp';

  static const String chat_match_egg_dialog_text_webp = 'assets/images/chat_match_egg_dialog_text.webp';
  static const String chat$chat_match_egg_dialog_text_webp = 'packages/chat/assets/images/chat_match_egg_dialog_text.webp';

  static const String chat_match_empty_bg_webp = 'assets/images/chat_match_empty_bg.webp';
  static const String chat$chat_match_empty_bg_webp = 'packages/chat/assets/images/chat_match_empty_bg.webp';

  static const String chat_match_filter_svg = 'assets/images/chat_match_filter.svg';
  static const String chat$chat_match_filter_svg = 'packages/chat/assets/images/chat_match_filter.svg';

  static const String chat_match_friend_card_add_icon_svg = 'assets/images/chat_match_friend_card_add_icon.svg';
  static const String chat$chat_match_friend_card_add_icon_svg = 'packages/chat/assets/images/chat_match_friend_card_add_icon.svg';

  static const String chat_match_instant_match_btn_webp = 'assets/images/chat_match_instant_match_btn.webp';
  static const String chat$chat_match_instant_match_btn_webp = 'packages/chat/assets/images/chat_match_instant_match_btn.webp';

  static const String chat_match_left_swipe_dislike_webp = 'assets/images/chat_match_left_swipe_dislike.webp';
  static const String chat$chat_match_left_swipe_dislike_webp = 'packages/chat/assets/images/chat_match_left_swipe_dislike.webp';

  static const String chat_match_like_and_sayhi_webp = 'assets/images/chat_match_like_and_sayhi.webp';
  static const String chat$chat_match_like_and_sayhi_webp = 'packages/chat/assets/images/chat_match_like_and_sayhi.webp';

  static const String chat_match_music_anim_webp = 'assets/images/chat_match_music_anim.webp';
  static const String chat$chat_match_music_anim_webp = 'packages/chat/assets/images/chat_match_music_anim.webp';

  static const String chat_match_notification_left_top_icon_webp = 'assets/images/chat_match_notification_left_top_icon.webp';
  static const String chat$chat_match_notification_left_top_icon_webp = 'packages/chat/assets/images/chat_match_notification_left_top_icon.webp';

  static const String chat_match_notification_love_webp = 'assets/images/chat_match_notification_love.webp';
  static const String chat$chat_match_notification_love_webp = 'packages/chat/assets/images/chat_match_notification_love.webp';

  static const String chat_match_right_swipe_sayhi_webp = 'assets/images/chat_match_right_swipe_sayhi.webp';
  static const String chat$chat_match_right_swipe_sayhi_webp = 'packages/chat/assets/images/chat_match_right_swipe_sayhi.webp';

  static const String chat_package_svg = 'assets/images/chat_package.svg';
  static const String chat$chat_package_svg = 'packages/chat/assets/images/chat_package.svg';

  static const String chat_package_best_svg = 'assets/images/chat_package_best.svg';
  static const String chat$chat_package_best_svg = 'packages/chat/assets/images/chat_package_best.svg';

  static const String chat_package_dialog_bg_svg = 'assets/images/chat_package_dialog_bg.svg';
  static const String chat$chat_package_dialog_bg_svg = 'packages/chat/assets/images/chat_package_dialog_bg.svg';

  static const String chat_package_open_png = 'assets/images/chat_package_open.png';
  static const String chat$chat_package_open_png = 'packages/chat/assets/images/chat_package_open.png';

  static const String chat_power_png = 'assets/images/chat_power.png';
  static const String chat$chat_power_png = 'packages/chat/assets/images/chat_power.png';

  static const String chat_profile_comp_header_webp = 'assets/images/chat_profile_comp_header.webp';
  static const String chat$chat_profile_comp_header_webp = 'packages/chat/assets/images/chat_profile_comp_header.webp';

  static const String chat_top_contact_svg = 'assets/images/chat_top_contact.svg';
  static const String chat$chat_top_contact_svg = 'packages/chat/assets/images/chat_top_contact.svg';

  static const String chat_user_tag_bg_png = 'assets/images/chat_user_tag_bg.png';
  static const String chat$chat_user_tag_bg_png = 'packages/chat/assets/images/chat_user_tag_bg.png';

  static const String chat_voice_msg_left_svg = 'assets/images/chat_voice_msg_left.svg';
  static const String chat$chat_voice_msg_left_svg = 'packages/chat/assets/images/chat_voice_msg_left.svg';

  static const String chat_voice_msg_right_svg = 'assets/images/chat_voice_msg_right.svg';
  static const String chat$chat_voice_msg_right_svg = 'packages/chat/assets/images/chat_voice_msg_right.svg';

  static const String chat_voice_record_svg = 'assets/images/chat_voice_record.svg';
  static const String chat$chat_voice_record_svg = 'packages/chat/assets/images/chat_voice_record.svg';

  static const String chat_wedding_invite_heart_webp = 'assets/images/chat_wedding_invite_heart.webp';
  static const String chat$chat_wedding_invite_heart_webp = 'packages/chat/assets/images/chat_wedding_invite_heart.webp';

  static const String dialog_bottom_close_png = 'assets/images/dialog_bottom_close.png';
  static const String chat$dialog_bottom_close_png = 'packages/chat/assets/images/dialog_bottom_close.png';

  static const String emote_add_png = 'assets/images/emote/add.png';
  static const String chat$emote_add_png = 'packages/chat/assets/images/emote/add.png';

  static const String emote_edit_png = 'assets/images/emote/edit.png';
  static const String chat$emote_edit_png = 'packages/chat/assets/images/emote/edit.png';

  static const String emote_emoji_a1_png = 'assets/images/emote/emoji/a1.png';
  static const String chat$emote_emoji_a1_png = 'packages/chat/assets/images/emote/emoji/a1.png';

  static const String emote_emoji_a10_png = 'assets/images/emote/emoji/a10.png';
  static const String chat$emote_emoji_a10_png = 'packages/chat/assets/images/emote/emoji/a10.png';

  static const String emote_emoji_a2_png = 'assets/images/emote/emoji/a2.png';
  static const String chat$emote_emoji_a2_png = 'packages/chat/assets/images/emote/emoji/a2.png';

  static const String emote_emoji_a3_png = 'assets/images/emote/emoji/a3.png';
  static const String chat$emote_emoji_a3_png = 'packages/chat/assets/images/emote/emoji/a3.png';

  static const String emote_emoji_a4_png = 'assets/images/emote/emoji/a4.png';
  static const String chat$emote_emoji_a4_png = 'packages/chat/assets/images/emote/emoji/a4.png';

  static const String emote_emoji_a5_png = 'assets/images/emote/emoji/a5.png';
  static const String chat$emote_emoji_a5_png = 'packages/chat/assets/images/emote/emoji/a5.png';

  static const String emote_emoji_a6_png = 'assets/images/emote/emoji/a6.png';
  static const String chat$emote_emoji_a6_png = 'packages/chat/assets/images/emote/emoji/a6.png';

  static const String emote_emoji_a7_png = 'assets/images/emote/emoji/a7.png';
  static const String chat$emote_emoji_a7_png = 'packages/chat/assets/images/emote/emoji/a7.png';

  static const String emote_emoji_a8_png = 'assets/images/emote/emoji/a8.png';
  static const String chat$emote_emoji_a8_png = 'packages/chat/assets/images/emote/emoji/a8.png';

  static const String emote_emoji_a9_png = 'assets/images/emote/emoji/a9.png';
  static const String chat$emote_emoji_a9_png = 'packages/chat/assets/images/emote/emoji/a9.png';

  static const String emote_emoji_b1_png = 'assets/images/emote/emoji/b1.png';
  static const String chat$emote_emoji_b1_png = 'packages/chat/assets/images/emote/emoji/b1.png';

  static const String emote_emoji_b2_png = 'assets/images/emote/emoji/b2.png';
  static const String chat$emote_emoji_b2_png = 'packages/chat/assets/images/emote/emoji/b2.png';

  static const String emote_emoji_b3_png = 'assets/images/emote/emoji/b3.png';
  static const String chat$emote_emoji_b3_png = 'packages/chat/assets/images/emote/emoji/b3.png';

  static const String emote_emoji_b4_png = 'assets/images/emote/emoji/b4.png';
  static const String chat$emote_emoji_b4_png = 'packages/chat/assets/images/emote/emoji/b4.png';

  static const String emote_emoji_b5_png = 'assets/images/emote/emoji/b5.png';
  static const String chat$emote_emoji_b5_png = 'packages/chat/assets/images/emote/emoji/b5.png';

  static const String emote_emoji_b6_png = 'assets/images/emote/emoji/b6.png';
  static const String chat$emote_emoji_b6_png = 'packages/chat/assets/images/emote/emoji/b6.png';

  static const String emote_emoji_b7_png = 'assets/images/emote/emoji/b7.png';
  static const String chat$emote_emoji_b7_png = 'packages/chat/assets/images/emote/emoji/b7.png';

  static const String emote_emoji_b8_png = 'assets/images/emote/emoji/b8.png';
  static const String chat$emote_emoji_b8_png = 'packages/chat/assets/images/emote/emoji/b8.png';

  static const String emote_emoji_b9_png = 'assets/images/emote/emoji/b9.png';
  static const String chat$emote_emoji_b9_png = 'packages/chat/assets/images/emote/emoji/b9.png';

  static const String emote_emoji_c1_png = 'assets/images/emote/emoji/c1.png';
  static const String chat$emote_emoji_c1_png = 'packages/chat/assets/images/emote/emoji/c1.png';

  static const String emote_emoji_c10_png = 'assets/images/emote/emoji/c10.png';
  static const String chat$emote_emoji_c10_png = 'packages/chat/assets/images/emote/emoji/c10.png';

  static const String emote_emoji_c11_png = 'assets/images/emote/emoji/c11.png';
  static const String chat$emote_emoji_c11_png = 'packages/chat/assets/images/emote/emoji/c11.png';

  static const String emote_emoji_c2_png = 'assets/images/emote/emoji/c2.png';
  static const String chat$emote_emoji_c2_png = 'packages/chat/assets/images/emote/emoji/c2.png';

  static const String emote_emoji_c3_png = 'assets/images/emote/emoji/c3.png';
  static const String chat$emote_emoji_c3_png = 'packages/chat/assets/images/emote/emoji/c3.png';

  static const String emote_emoji_c4_png = 'assets/images/emote/emoji/c4.png';
  static const String chat$emote_emoji_c4_png = 'packages/chat/assets/images/emote/emoji/c4.png';

  static const String emote_emoji_c5_png = 'assets/images/emote/emoji/c5.png';
  static const String chat$emote_emoji_c5_png = 'packages/chat/assets/images/emote/emoji/c5.png';

  static const String emote_emoji_c6_png = 'assets/images/emote/emoji/c6.png';
  static const String chat$emote_emoji_c6_png = 'packages/chat/assets/images/emote/emoji/c6.png';

  static const String emote_emoji_c7_png = 'assets/images/emote/emoji/c7.png';
  static const String chat$emote_emoji_c7_png = 'packages/chat/assets/images/emote/emoji/c7.png';

  static const String emote_emoji_c8_png = 'assets/images/emote/emoji/c8.png';
  static const String chat$emote_emoji_c8_png = 'packages/chat/assets/images/emote/emoji/c8.png';

  static const String emote_emoji_c9_png = 'assets/images/emote/emoji/c9.png';
  static const String chat$emote_emoji_c9_png = 'packages/chat/assets/images/emote/emoji/c9.png';

  static const String emote_emoji_d1_png = 'assets/images/emote/emoji/d1.png';
  static const String chat$emote_emoji_d1_png = 'packages/chat/assets/images/emote/emoji/d1.png';

  static const String emote_emoji_d2_png = 'assets/images/emote/emoji/d2.png';
  static const String chat$emote_emoji_d2_png = 'packages/chat/assets/images/emote/emoji/d2.png';

  static const String emote_emoji_d3_png = 'assets/images/emote/emoji/d3.png';
  static const String chat$emote_emoji_d3_png = 'packages/chat/assets/images/emote/emoji/d3.png';

  static const String emote_emoji_d4_png = 'assets/images/emote/emoji/d4.png';
  static const String chat$emote_emoji_d4_png = 'packages/chat/assets/images/emote/emoji/d4.png';

  static const String emote_emoji_d5_png = 'assets/images/emote/emoji/d5.png';
  static const String chat$emote_emoji_d5_png = 'packages/chat/assets/images/emote/emoji/d5.png';

  static const String emote_emoji_d6_png = 'assets/images/emote/emoji/d6.png';
  static const String chat$emote_emoji_d6_png = 'packages/chat/assets/images/emote/emoji/d6.png';

  static const String emote_emoji_e1_png = 'assets/images/emote/emoji/e1.png';
  static const String chat$emote_emoji_e1_png = 'packages/chat/assets/images/emote/emoji/e1.png';

  static const String emote_emoji_e2_png = 'assets/images/emote/emoji/e2.png';
  static const String chat$emote_emoji_e2_png = 'packages/chat/assets/images/emote/emoji/e2.png';

  static const String emote_emoji_e3_png = 'assets/images/emote/emoji/e3.png';
  static const String chat$emote_emoji_e3_png = 'packages/chat/assets/images/emote/emoji/e3.png';

  static const String emote_emoji_f1_png = 'assets/images/emote/emoji/f1.png';
  static const String chat$emote_emoji_f1_png = 'packages/chat/assets/images/emote/emoji/f1.png';

  static const String emote_emoji_f2_png = 'assets/images/emote/emoji/f2.png';
  static const String chat$emote_emoji_f2_png = 'packages/chat/assets/images/emote/emoji/f2.png';

  static const String emote_emoji_f3_png = 'assets/images/emote/emoji/f3.png';
  static const String chat$emote_emoji_f3_png = 'packages/chat/assets/images/emote/emoji/f3.png';

  static const String emote_emoji_f4_png = 'assets/images/emote/emoji/f4.png';
  static const String chat$emote_emoji_f4_png = 'packages/chat/assets/images/emote/emoji/f4.png';

  static const String emote_emoji_f5_png = 'assets/images/emote/emoji/f5.png';
  static const String chat$emote_emoji_f5_png = 'packages/chat/assets/images/emote/emoji/f5.png';

  static const String emote_emoji_f6_png = 'assets/images/emote/emoji/f6.png';
  static const String chat$emote_emoji_f6_png = 'packages/chat/assets/images/emote/emoji/f6.png';

  static const String emote_emoji_g1_png = 'assets/images/emote/emoji/g1.png';
  static const String chat$emote_emoji_g1_png = 'packages/chat/assets/images/emote/emoji/g1.png';

  static const String emote_emoji_g10_png = 'assets/images/emote/emoji/g10.png';
  static const String chat$emote_emoji_g10_png = 'packages/chat/assets/images/emote/emoji/g10.png';

  static const String emote_emoji_g11_png = 'assets/images/emote/emoji/g11.png';
  static const String chat$emote_emoji_g11_png = 'packages/chat/assets/images/emote/emoji/g11.png';

  static const String emote_emoji_g12_png = 'assets/images/emote/emoji/g12.png';
  static const String chat$emote_emoji_g12_png = 'packages/chat/assets/images/emote/emoji/g12.png';

  static const String emote_emoji_g13_png = 'assets/images/emote/emoji/g13.png';
  static const String chat$emote_emoji_g13_png = 'packages/chat/assets/images/emote/emoji/g13.png';

  static const String emote_emoji_g14_png = 'assets/images/emote/emoji/g14.png';
  static const String chat$emote_emoji_g14_png = 'packages/chat/assets/images/emote/emoji/g14.png';

  static const String emote_emoji_g15_png = 'assets/images/emote/emoji/g15.png';
  static const String chat$emote_emoji_g15_png = 'packages/chat/assets/images/emote/emoji/g15.png';

  static const String emote_emoji_g16_png = 'assets/images/emote/emoji/g16.png';
  static const String chat$emote_emoji_g16_png = 'packages/chat/assets/images/emote/emoji/g16.png';

  static const String emote_emoji_g17_png = 'assets/images/emote/emoji/g17.png';
  static const String chat$emote_emoji_g17_png = 'packages/chat/assets/images/emote/emoji/g17.png';

  static const String emote_emoji_g18_png = 'assets/images/emote/emoji/g18.png';
  static const String chat$emote_emoji_g18_png = 'packages/chat/assets/images/emote/emoji/g18.png';

  static const String emote_emoji_g19_png = 'assets/images/emote/emoji/g19.png';
  static const String chat$emote_emoji_g19_png = 'packages/chat/assets/images/emote/emoji/g19.png';

  static const String emote_emoji_g2_png = 'assets/images/emote/emoji/g2.png';
  static const String chat$emote_emoji_g2_png = 'packages/chat/assets/images/emote/emoji/g2.png';

  static const String emote_emoji_g20_png = 'assets/images/emote/emoji/g20.png';
  static const String chat$emote_emoji_g20_png = 'packages/chat/assets/images/emote/emoji/g20.png';

  static const String emote_emoji_g3_png = 'assets/images/emote/emoji/g3.png';
  static const String chat$emote_emoji_g3_png = 'packages/chat/assets/images/emote/emoji/g3.png';

  static const String emote_emoji_g4_png = 'assets/images/emote/emoji/g4.png';
  static const String chat$emote_emoji_g4_png = 'packages/chat/assets/images/emote/emoji/g4.png';

  static const String emote_emoji_g5_png = 'assets/images/emote/emoji/g5.png';
  static const String chat$emote_emoji_g5_png = 'packages/chat/assets/images/emote/emoji/g5.png';

  static const String emote_emoji_g6_png = 'assets/images/emote/emoji/g6.png';
  static const String chat$emote_emoji_g6_png = 'packages/chat/assets/images/emote/emoji/g6.png';

  static const String emote_emoji_g7_png = 'assets/images/emote/emoji/g7.png';
  static const String chat$emote_emoji_g7_png = 'packages/chat/assets/images/emote/emoji/g7.png';

  static const String emote_emoji_g8_png = 'assets/images/emote/emoji/g8.png';
  static const String chat$emote_emoji_g8_png = 'packages/chat/assets/images/emote/emoji/g8.png';

  static const String emote_emoji_g9_png = 'assets/images/emote/emoji/g9.png';
  static const String chat$emote_emoji_g9_png = 'packages/chat/assets/images/emote/emoji/g9.png';

  static const String emote_emoji_h1_png = 'assets/images/emote/emoji/h1.png';
  static const String chat$emote_emoji_h1_png = 'packages/chat/assets/images/emote/emoji/h1.png';

  static const String emote_emoji_h10_png = 'assets/images/emote/emoji/h10.png';
  static const String chat$emote_emoji_h10_png = 'packages/chat/assets/images/emote/emoji/h10.png';

  static const String emote_emoji_h11_png = 'assets/images/emote/emoji/h11.png';
  static const String chat$emote_emoji_h11_png = 'packages/chat/assets/images/emote/emoji/h11.png';

  static const String emote_emoji_h12_png = 'assets/images/emote/emoji/h12.png';
  static const String chat$emote_emoji_h12_png = 'packages/chat/assets/images/emote/emoji/h12.png';

  static const String emote_emoji_h13_png = 'assets/images/emote/emoji/h13.png';
  static const String chat$emote_emoji_h13_png = 'packages/chat/assets/images/emote/emoji/h13.png';

  static const String emote_emoji_h14_png = 'assets/images/emote/emoji/h14.png';
  static const String chat$emote_emoji_h14_png = 'packages/chat/assets/images/emote/emoji/h14.png';

  static const String emote_emoji_h15_png = 'assets/images/emote/emoji/h15.png';
  static const String chat$emote_emoji_h15_png = 'packages/chat/assets/images/emote/emoji/h15.png';

  static const String emote_emoji_h16_png = 'assets/images/emote/emoji/h16.png';
  static const String chat$emote_emoji_h16_png = 'packages/chat/assets/images/emote/emoji/h16.png';

  static const String emote_emoji_h17_png = 'assets/images/emote/emoji/h17.png';
  static const String chat$emote_emoji_h17_png = 'packages/chat/assets/images/emote/emoji/h17.png';

  static const String emote_emoji_h2_png = 'assets/images/emote/emoji/h2.png';
  static const String chat$emote_emoji_h2_png = 'packages/chat/assets/images/emote/emoji/h2.png';

  static const String emote_emoji_h3_png = 'assets/images/emote/emoji/h3.png';
  static const String chat$emote_emoji_h3_png = 'packages/chat/assets/images/emote/emoji/h3.png';

  static const String emote_emoji_h4_png = 'assets/images/emote/emoji/h4.png';
  static const String chat$emote_emoji_h4_png = 'packages/chat/assets/images/emote/emoji/h4.png';

  static const String emote_emoji_h5_png = 'assets/images/emote/emoji/h5.png';
  static const String chat$emote_emoji_h5_png = 'packages/chat/assets/images/emote/emoji/h5.png';

  static const String emote_emoji_h6_png = 'assets/images/emote/emoji/h6.png';
  static const String chat$emote_emoji_h6_png = 'packages/chat/assets/images/emote/emoji/h6.png';

  static const String emote_emoji_h7_png = 'assets/images/emote/emoji/h7.png';
  static const String chat$emote_emoji_h7_png = 'packages/chat/assets/images/emote/emoji/h7.png';

  static const String emote_emoji_h8_png = 'assets/images/emote/emoji/h8.png';
  static const String chat$emote_emoji_h8_png = 'packages/chat/assets/images/emote/emoji/h8.png';

  static const String emote_emoji_h9_png = 'assets/images/emote/emoji/h9.png';
  static const String chat$emote_emoji_h9_png = 'packages/chat/assets/images/emote/emoji/h9.png';

  static const String emote_emoji_i1_png = 'assets/images/emote/emoji/i1.png';
  static const String chat$emote_emoji_i1_png = 'packages/chat/assets/images/emote/emoji/i1.png';

  static const String emote_emoji_i10_png = 'assets/images/emote/emoji/i10.png';
  static const String chat$emote_emoji_i10_png = 'packages/chat/assets/images/emote/emoji/i10.png';

  static const String emote_emoji_i11_png = 'assets/images/emote/emoji/i11.png';
  static const String chat$emote_emoji_i11_png = 'packages/chat/assets/images/emote/emoji/i11.png';

  static const String emote_emoji_i12_png = 'assets/images/emote/emoji/i12.png';
  static const String chat$emote_emoji_i12_png = 'packages/chat/assets/images/emote/emoji/i12.png';

  static const String emote_emoji_i13_png = 'assets/images/emote/emoji/i13.png';
  static const String chat$emote_emoji_i13_png = 'packages/chat/assets/images/emote/emoji/i13.png';

  static const String emote_emoji_i14_png = 'assets/images/emote/emoji/i14.png';
  static const String chat$emote_emoji_i14_png = 'packages/chat/assets/images/emote/emoji/i14.png';

  static const String emote_emoji_i15_png = 'assets/images/emote/emoji/i15.png';
  static const String chat$emote_emoji_i15_png = 'packages/chat/assets/images/emote/emoji/i15.png';

  static const String emote_emoji_i16_png = 'assets/images/emote/emoji/i16.png';
  static const String chat$emote_emoji_i16_png = 'packages/chat/assets/images/emote/emoji/i16.png';

  static const String emote_emoji_i17_png = 'assets/images/emote/emoji/i17.png';
  static const String chat$emote_emoji_i17_png = 'packages/chat/assets/images/emote/emoji/i17.png';

  static const String emote_emoji_i18_png = 'assets/images/emote/emoji/i18.png';
  static const String chat$emote_emoji_i18_png = 'packages/chat/assets/images/emote/emoji/i18.png';

  static const String emote_emoji_i19_png = 'assets/images/emote/emoji/i19.png';
  static const String chat$emote_emoji_i19_png = 'packages/chat/assets/images/emote/emoji/i19.png';

  static const String emote_emoji_i2_png = 'assets/images/emote/emoji/i2.png';
  static const String chat$emote_emoji_i2_png = 'packages/chat/assets/images/emote/emoji/i2.png';

  static const String emote_emoji_i20_png = 'assets/images/emote/emoji/i20.png';
  static const String chat$emote_emoji_i20_png = 'packages/chat/assets/images/emote/emoji/i20.png';

  static const String emote_emoji_i21_png = 'assets/images/emote/emoji/i21.png';
  static const String chat$emote_emoji_i21_png = 'packages/chat/assets/images/emote/emoji/i21.png';

  static const String emote_emoji_i22_png = 'assets/images/emote/emoji/i22.png';
  static const String chat$emote_emoji_i22_png = 'packages/chat/assets/images/emote/emoji/i22.png';

  static const String emote_emoji_i23_png = 'assets/images/emote/emoji/i23.png';
  static const String chat$emote_emoji_i23_png = 'packages/chat/assets/images/emote/emoji/i23.png';

  static const String emote_emoji_i24_png = 'assets/images/emote/emoji/i24.png';
  static const String chat$emote_emoji_i24_png = 'packages/chat/assets/images/emote/emoji/i24.png';

  static const String emote_emoji_i25_png = 'assets/images/emote/emoji/i25.png';
  static const String chat$emote_emoji_i25_png = 'packages/chat/assets/images/emote/emoji/i25.png';

  static const String emote_emoji_i26_png = 'assets/images/emote/emoji/i26.png';
  static const String chat$emote_emoji_i26_png = 'packages/chat/assets/images/emote/emoji/i26.png';

  static const String emote_emoji_i27_png = 'assets/images/emote/emoji/i27.png';
  static const String chat$emote_emoji_i27_png = 'packages/chat/assets/images/emote/emoji/i27.png';

  static const String emote_emoji_i28_png = 'assets/images/emote/emoji/i28.png';
  static const String chat$emote_emoji_i28_png = 'packages/chat/assets/images/emote/emoji/i28.png';

  static const String emote_emoji_i3_png = 'assets/images/emote/emoji/i3.png';
  static const String chat$emote_emoji_i3_png = 'packages/chat/assets/images/emote/emoji/i3.png';

  static const String emote_emoji_i4_png = 'assets/images/emote/emoji/i4.png';
  static const String chat$emote_emoji_i4_png = 'packages/chat/assets/images/emote/emoji/i4.png';

  static const String emote_emoji_i5_png = 'assets/images/emote/emoji/i5.png';
  static const String chat$emote_emoji_i5_png = 'packages/chat/assets/images/emote/emoji/i5.png';

  static const String emote_emoji_i6_png = 'assets/images/emote/emoji/i6.png';
  static const String chat$emote_emoji_i6_png = 'packages/chat/assets/images/emote/emoji/i6.png';

  static const String emote_emoji_i7_png = 'assets/images/emote/emoji/i7.png';
  static const String chat$emote_emoji_i7_png = 'packages/chat/assets/images/emote/emoji/i7.png';

  static const String emote_emoji_i8_png = 'assets/images/emote/emoji/i8.png';
  static const String chat$emote_emoji_i8_png = 'packages/chat/assets/images/emote/emoji/i8.png';

  static const String emote_emoji_i9_png = 'assets/images/emote/emoji/i9.png';
  static const String chat$emote_emoji_i9_png = 'packages/chat/assets/images/emote/emoji/i9.png';

  static const String emote_emoji_j1_png = 'assets/images/emote/emoji/j1.png';
  static const String chat$emote_emoji_j1_png = 'packages/chat/assets/images/emote/emoji/j1.png';

  static const String emote_emoji_j10_png = 'assets/images/emote/emoji/j10.png';
  static const String chat$emote_emoji_j10_png = 'packages/chat/assets/images/emote/emoji/j10.png';

  static const String emote_emoji_j11_png = 'assets/images/emote/emoji/j11.png';
  static const String chat$emote_emoji_j11_png = 'packages/chat/assets/images/emote/emoji/j11.png';

  static const String emote_emoji_j12_png = 'assets/images/emote/emoji/j12.png';
  static const String chat$emote_emoji_j12_png = 'packages/chat/assets/images/emote/emoji/j12.png';

  static const String emote_emoji_j13_png = 'assets/images/emote/emoji/j13.png';
  static const String chat$emote_emoji_j13_png = 'packages/chat/assets/images/emote/emoji/j13.png';

  static const String emote_emoji_j14_png = 'assets/images/emote/emoji/j14.png';
  static const String chat$emote_emoji_j14_png = 'packages/chat/assets/images/emote/emoji/j14.png';

  static const String emote_emoji_j15_png = 'assets/images/emote/emoji/j15.png';
  static const String chat$emote_emoji_j15_png = 'packages/chat/assets/images/emote/emoji/j15.png';

  static const String emote_emoji_j16_png = 'assets/images/emote/emoji/j16.png';
  static const String chat$emote_emoji_j16_png = 'packages/chat/assets/images/emote/emoji/j16.png';

  static const String emote_emoji_j17_png = 'assets/images/emote/emoji/j17.png';
  static const String chat$emote_emoji_j17_png = 'packages/chat/assets/images/emote/emoji/j17.png';

  static const String emote_emoji_j18_png = 'assets/images/emote/emoji/j18.png';
  static const String chat$emote_emoji_j18_png = 'packages/chat/assets/images/emote/emoji/j18.png';

  static const String emote_emoji_j19_png = 'assets/images/emote/emoji/j19.png';
  static const String chat$emote_emoji_j19_png = 'packages/chat/assets/images/emote/emoji/j19.png';

  static const String emote_emoji_j2_png = 'assets/images/emote/emoji/j2.png';
  static const String chat$emote_emoji_j2_png = 'packages/chat/assets/images/emote/emoji/j2.png';

  static const String emote_emoji_j20_png = 'assets/images/emote/emoji/j20.png';
  static const String chat$emote_emoji_j20_png = 'packages/chat/assets/images/emote/emoji/j20.png';

  static const String emote_emoji_j21_png = 'assets/images/emote/emoji/j21.png';
  static const String chat$emote_emoji_j21_png = 'packages/chat/assets/images/emote/emoji/j21.png';

  static const String emote_emoji_j22_png = 'assets/images/emote/emoji/j22.png';
  static const String chat$emote_emoji_j22_png = 'packages/chat/assets/images/emote/emoji/j22.png';

  static const String emote_emoji_j23_png = 'assets/images/emote/emoji/j23.png';
  static const String chat$emote_emoji_j23_png = 'packages/chat/assets/images/emote/emoji/j23.png';

  static const String emote_emoji_j24_png = 'assets/images/emote/emoji/j24.png';
  static const String chat$emote_emoji_j24_png = 'packages/chat/assets/images/emote/emoji/j24.png';

  static const String emote_emoji_j25_png = 'assets/images/emote/emoji/j25.png';
  static const String chat$emote_emoji_j25_png = 'packages/chat/assets/images/emote/emoji/j25.png';

  static const String emote_emoji_j26_png = 'assets/images/emote/emoji/j26.png';
  static const String chat$emote_emoji_j26_png = 'packages/chat/assets/images/emote/emoji/j26.png';

  static const String emote_emoji_j27_png = 'assets/images/emote/emoji/j27.png';
  static const String chat$emote_emoji_j27_png = 'packages/chat/assets/images/emote/emoji/j27.png';

  static const String emote_emoji_j28_png = 'assets/images/emote/emoji/j28.png';
  static const String chat$emote_emoji_j28_png = 'packages/chat/assets/images/emote/emoji/j28.png';

  static const String emote_emoji_j29_png = 'assets/images/emote/emoji/j29.png';
  static const String chat$emote_emoji_j29_png = 'packages/chat/assets/images/emote/emoji/j29.png';

  static const String emote_emoji_j3_png = 'assets/images/emote/emoji/j3.png';
  static const String chat$emote_emoji_j3_png = 'packages/chat/assets/images/emote/emoji/j3.png';

  static const String emote_emoji_j30_png = 'assets/images/emote/emoji/j30.png';
  static const String chat$emote_emoji_j30_png = 'packages/chat/assets/images/emote/emoji/j30.png';

  static const String emote_emoji_j31_png = 'assets/images/emote/emoji/j31.png';
  static const String chat$emote_emoji_j31_png = 'packages/chat/assets/images/emote/emoji/j31.png';

  static const String emote_emoji_j4_png = 'assets/images/emote/emoji/j4.png';
  static const String chat$emote_emoji_j4_png = 'packages/chat/assets/images/emote/emoji/j4.png';

  static const String emote_emoji_j5_png = 'assets/images/emote/emoji/j5.png';
  static const String chat$emote_emoji_j5_png = 'packages/chat/assets/images/emote/emoji/j5.png';

  static const String emote_emoji_j6_png = 'assets/images/emote/emoji/j6.png';
  static const String chat$emote_emoji_j6_png = 'packages/chat/assets/images/emote/emoji/j6.png';

  static const String emote_emoji_j7_png = 'assets/images/emote/emoji/j7.png';
  static const String chat$emote_emoji_j7_png = 'packages/chat/assets/images/emote/emoji/j7.png';

  static const String emote_emoji_j8_png = 'assets/images/emote/emoji/j8.png';
  static const String chat$emote_emoji_j8_png = 'packages/chat/assets/images/emote/emoji/j8.png';

  static const String emote_emoji_j9_png = 'assets/images/emote/emoji/j9.png';
  static const String chat$emote_emoji_j9_png = 'packages/chat/assets/images/emote/emoji/j9.png';

  static const String emote_emoji_l1_png = 'assets/images/emote/emoji/l1.png';
  static const String chat$emote_emoji_l1_png = 'packages/chat/assets/images/emote/emoji/l1.png';

  static const String emote_emoji_l10_png = 'assets/images/emote/emoji/l10.png';
  static const String chat$emote_emoji_l10_png = 'packages/chat/assets/images/emote/emoji/l10.png';

  static const String emote_emoji_l11_png = 'assets/images/emote/emoji/l11.png';
  static const String chat$emote_emoji_l11_png = 'packages/chat/assets/images/emote/emoji/l11.png';

  static const String emote_emoji_l12_png = 'assets/images/emote/emoji/l12.png';
  static const String chat$emote_emoji_l12_png = 'packages/chat/assets/images/emote/emoji/l12.png';

  static const String emote_emoji_l13_png = 'assets/images/emote/emoji/l13.png';
  static const String chat$emote_emoji_l13_png = 'packages/chat/assets/images/emote/emoji/l13.png';

  static const String emote_emoji_l14_png = 'assets/images/emote/emoji/l14.png';
  static const String chat$emote_emoji_l14_png = 'packages/chat/assets/images/emote/emoji/l14.png';

  static const String emote_emoji_l15_png = 'assets/images/emote/emoji/l15.png';
  static const String chat$emote_emoji_l15_png = 'packages/chat/assets/images/emote/emoji/l15.png';

  static const String emote_emoji_l16_png = 'assets/images/emote/emoji/l16.png';
  static const String chat$emote_emoji_l16_png = 'packages/chat/assets/images/emote/emoji/l16.png';

  static const String emote_emoji_l17_png = 'assets/images/emote/emoji/l17.png';
  static const String chat$emote_emoji_l17_png = 'packages/chat/assets/images/emote/emoji/l17.png';

  static const String emote_emoji_l18_png = 'assets/images/emote/emoji/l18.png';
  static const String chat$emote_emoji_l18_png = 'packages/chat/assets/images/emote/emoji/l18.png';

  static const String emote_emoji_l19_png = 'assets/images/emote/emoji/l19.png';
  static const String chat$emote_emoji_l19_png = 'packages/chat/assets/images/emote/emoji/l19.png';

  static const String emote_emoji_l2_png = 'assets/images/emote/emoji/l2.png';
  static const String chat$emote_emoji_l2_png = 'packages/chat/assets/images/emote/emoji/l2.png';

  static const String emote_emoji_l20_png = 'assets/images/emote/emoji/l20.png';
  static const String chat$emote_emoji_l20_png = 'packages/chat/assets/images/emote/emoji/l20.png';

  static const String emote_emoji_l21_png = 'assets/images/emote/emoji/l21.png';
  static const String chat$emote_emoji_l21_png = 'packages/chat/assets/images/emote/emoji/l21.png';

  static const String emote_emoji_l22_png = 'assets/images/emote/emoji/l22.png';
  static const String chat$emote_emoji_l22_png = 'packages/chat/assets/images/emote/emoji/l22.png';

  static const String emote_emoji_l23_png = 'assets/images/emote/emoji/l23.png';
  static const String chat$emote_emoji_l23_png = 'packages/chat/assets/images/emote/emoji/l23.png';

  static const String emote_emoji_l3_png = 'assets/images/emote/emoji/l3.png';
  static const String chat$emote_emoji_l3_png = 'packages/chat/assets/images/emote/emoji/l3.png';

  static const String emote_emoji_l4_png = 'assets/images/emote/emoji/l4.png';
  static const String chat$emote_emoji_l4_png = 'packages/chat/assets/images/emote/emoji/l4.png';

  static const String emote_emoji_l5_png = 'assets/images/emote/emoji/l5.png';
  static const String chat$emote_emoji_l5_png = 'packages/chat/assets/images/emote/emoji/l5.png';

  static const String emote_emoji_l6_png = 'assets/images/emote/emoji/l6.png';
  static const String chat$emote_emoji_l6_png = 'packages/chat/assets/images/emote/emoji/l6.png';

  static const String emote_emoji_l7_png = 'assets/images/emote/emoji/l7.png';
  static const String chat$emote_emoji_l7_png = 'packages/chat/assets/images/emote/emoji/l7.png';

  static const String emote_emoji_l8_png = 'assets/images/emote/emoji/l8.png';
  static const String chat$emote_emoji_l8_png = 'packages/chat/assets/images/emote/emoji/l8.png';

  static const String emote_emoji_l9_png = 'assets/images/emote/emoji/l9.png';
  static const String chat$emote_emoji_l9_png = 'packages/chat/assets/images/emote/emoji/l9.png';

  static const String emote_emoji_m1_png = 'assets/images/emote/emoji/m1.png';
  static const String chat$emote_emoji_m1_png = 'packages/chat/assets/images/emote/emoji/m1.png';

  static const String emote_emoji_m2_png = 'assets/images/emote/emoji/m2.png';
  static const String chat$emote_emoji_m2_png = 'packages/chat/assets/images/emote/emoji/m2.png';

  static const String emote_emoji_m3_png = 'assets/images/emote/emoji/m3.png';
  static const String chat$emote_emoji_m3_png = 'packages/chat/assets/images/emote/emoji/m3.png';

  static const String emote_emoji_m4_png = 'assets/images/emote/emoji/m4.png';
  static const String chat$emote_emoji_m4_png = 'packages/chat/assets/images/emote/emoji/m4.png';

  static const String emote_emoji_m5_png = 'assets/images/emote/emoji/m5.png';
  static const String chat$emote_emoji_m5_png = 'packages/chat/assets/images/emote/emoji/m5.png';

  static const String emote_emoji_m6_png = 'assets/images/emote/emoji/m6.png';
  static const String chat$emote_emoji_m6_png = 'packages/chat/assets/images/emote/emoji/m6.png';

  static const String emote_emoji_m7_png = 'assets/images/emote/emoji/m7.png';
  static const String chat$emote_emoji_m7_png = 'packages/chat/assets/images/emote/emoji/m7.png';

  static const String emote_emoji_n1_png = 'assets/images/emote/emoji/n1.png';
  static const String chat$emote_emoji_n1_png = 'packages/chat/assets/images/emote/emoji/n1.png';

  static const String emote_emoji_n10_png = 'assets/images/emote/emoji/n10.png';
  static const String chat$emote_emoji_n10_png = 'packages/chat/assets/images/emote/emoji/n10.png';

  static const String emote_emoji_n11_png = 'assets/images/emote/emoji/n11.png';
  static const String chat$emote_emoji_n11_png = 'packages/chat/assets/images/emote/emoji/n11.png';

  static const String emote_emoji_n12_png = 'assets/images/emote/emoji/n12.png';
  static const String chat$emote_emoji_n12_png = 'packages/chat/assets/images/emote/emoji/n12.png';

  static const String emote_emoji_n13_png = 'assets/images/emote/emoji/n13.png';
  static const String chat$emote_emoji_n13_png = 'packages/chat/assets/images/emote/emoji/n13.png';

  static const String emote_emoji_n14_png = 'assets/images/emote/emoji/n14.png';
  static const String chat$emote_emoji_n14_png = 'packages/chat/assets/images/emote/emoji/n14.png';

  static const String emote_emoji_n15_png = 'assets/images/emote/emoji/n15.png';
  static const String chat$emote_emoji_n15_png = 'packages/chat/assets/images/emote/emoji/n15.png';

  static const String emote_emoji_n16_png = 'assets/images/emote/emoji/n16.png';
  static const String chat$emote_emoji_n16_png = 'packages/chat/assets/images/emote/emoji/n16.png';

  static const String emote_emoji_n17_png = 'assets/images/emote/emoji/n17.png';
  static const String chat$emote_emoji_n17_png = 'packages/chat/assets/images/emote/emoji/n17.png';

  static const String emote_emoji_n18_png = 'assets/images/emote/emoji/n18.png';
  static const String chat$emote_emoji_n18_png = 'packages/chat/assets/images/emote/emoji/n18.png';

  static const String emote_emoji_n2_png = 'assets/images/emote/emoji/n2.png';
  static const String chat$emote_emoji_n2_png = 'packages/chat/assets/images/emote/emoji/n2.png';

  static const String emote_emoji_n3_png = 'assets/images/emote/emoji/n3.png';
  static const String chat$emote_emoji_n3_png = 'packages/chat/assets/images/emote/emoji/n3.png';

  static const String emote_emoji_n4_png = 'assets/images/emote/emoji/n4.png';
  static const String chat$emote_emoji_n4_png = 'packages/chat/assets/images/emote/emoji/n4.png';

  static const String emote_emoji_n5_png = 'assets/images/emote/emoji/n5.png';
  static const String chat$emote_emoji_n5_png = 'packages/chat/assets/images/emote/emoji/n5.png';

  static const String emote_emoji_n6_png = 'assets/images/emote/emoji/n6.png';
  static const String chat$emote_emoji_n6_png = 'packages/chat/assets/images/emote/emoji/n6.png';

  static const String emote_emoji_n7_png = 'assets/images/emote/emoji/n7.png';
  static const String chat$emote_emoji_n7_png = 'packages/chat/assets/images/emote/emoji/n7.png';

  static const String emote_emoji_n8_png = 'assets/images/emote/emoji/n8.png';
  static const String chat$emote_emoji_n8_png = 'packages/chat/assets/images/emote/emoji/n8.png';

  static const String emote_emoji_n9_png = 'assets/images/emote/emoji/n9.png';
  static const String chat$emote_emoji_n9_png = 'packages/chat/assets/images/emote/emoji/n9.png';

  static const String emote_gif_1_png = 'assets/images/emote/gif/1.png';
  static const String chat$emote_gif_1_png = 'packages/chat/assets/images/emote/gif/1.png';

  static const String emote_gif_10_png = 'assets/images/emote/gif/10.png';
  static const String chat$emote_gif_10_png = 'packages/chat/assets/images/emote/gif/10.png';

  static const String emote_gif_11_png = 'assets/images/emote/gif/11.png';
  static const String chat$emote_gif_11_png = 'packages/chat/assets/images/emote/gif/11.png';

  static const String emote_gif_12_png = 'assets/images/emote/gif/12.png';
  static const String chat$emote_gif_12_png = 'packages/chat/assets/images/emote/gif/12.png';

  static const String emote_gif_13_png = 'assets/images/emote/gif/13.png';
  static const String chat$emote_gif_13_png = 'packages/chat/assets/images/emote/gif/13.png';

  static const String emote_gif_14_png = 'assets/images/emote/gif/14.png';
  static const String chat$emote_gif_14_png = 'packages/chat/assets/images/emote/gif/14.png';

  static const String emote_gif_15_png = 'assets/images/emote/gif/15.png';
  static const String chat$emote_gif_15_png = 'packages/chat/assets/images/emote/gif/15.png';

  static const String emote_gif_16_png = 'assets/images/emote/gif/16.png';
  static const String chat$emote_gif_16_png = 'packages/chat/assets/images/emote/gif/16.png';

  static const String emote_gif_17_png = 'assets/images/emote/gif/17.png';
  static const String chat$emote_gif_17_png = 'packages/chat/assets/images/emote/gif/17.png';

  static const String emote_gif_18_png = 'assets/images/emote/gif/18.png';
  static const String chat$emote_gif_18_png = 'packages/chat/assets/images/emote/gif/18.png';

  static const String emote_gif_19_png = 'assets/images/emote/gif/19.png';
  static const String chat$emote_gif_19_png = 'packages/chat/assets/images/emote/gif/19.png';

  static const String emote_gif_2_png = 'assets/images/emote/gif/2.png';
  static const String chat$emote_gif_2_png = 'packages/chat/assets/images/emote/gif/2.png';

  static const String emote_gif_20_png = 'assets/images/emote/gif/20.png';
  static const String chat$emote_gif_20_png = 'packages/chat/assets/images/emote/gif/20.png';

  static const String emote_gif_21_png = 'assets/images/emote/gif/21.png';
  static const String chat$emote_gif_21_png = 'packages/chat/assets/images/emote/gif/21.png';

  static const String emote_gif_3_png = 'assets/images/emote/gif/3.png';
  static const String chat$emote_gif_3_png = 'packages/chat/assets/images/emote/gif/3.png';

  static const String emote_gif_4_png = 'assets/images/emote/gif/4.png';
  static const String chat$emote_gif_4_png = 'packages/chat/assets/images/emote/gif/4.png';

  static const String emote_gif_5_png = 'assets/images/emote/gif/5.png';
  static const String chat$emote_gif_5_png = 'packages/chat/assets/images/emote/gif/5.png';

  static const String emote_gif_6_png = 'assets/images/emote/gif/6.png';
  static const String chat$emote_gif_6_png = 'packages/chat/assets/images/emote/gif/6.png';

  static const String emote_gif_7_png = 'assets/images/emote/gif/7.png';
  static const String chat$emote_gif_7_png = 'packages/chat/assets/images/emote/gif/7.png';

  static const String emote_gif_8_png = 'assets/images/emote/gif/8.png';
  static const String chat$emote_gif_8_png = 'packages/chat/assets/images/emote/gif/8.png';

  static const String emote_gif_9_png = 'assets/images/emote/gif/9.png';
  static const String chat$emote_gif_9_png = 'packages/chat/assets/images/emote/gif/9.png';

  static const String emote_kb_emoji_png = 'assets/images/emote/kb_emoji.png';
  static const String chat$emote_kb_emoji_png = 'packages/chat/assets/images/emote/kb_emoji.png';

  static const String emote_kb_emoji_favorite_png = 'assets/images/emote/kb_emoji_favorite.png';
  static const String chat$emote_kb_emoji_favorite_png = 'packages/chat/assets/images/emote/kb_emoji_favorite.png';

  static const String emote_kb_emoji_yellow_png = 'assets/images/emote/kb_emoji_yellow.png';
  static const String chat$emote_kb_emoji_yellow_png = 'packages/chat/assets/images/emote/kb_emoji_yellow.png';

  static const String emote_kb_emote_gif_png = 'assets/images/emote/kb_emote_gif.png';
  static const String chat$emote_kb_emote_gif_png = 'packages/chat/assets/images/emote/kb_emote_gif.png';

  static const String emote_kb_magic_png = 'assets/images/emote/kb_magic.png';
  static const String chat$emote_kb_magic_png = 'packages/chat/assets/images/emote/kb_magic.png';

  static const String emote_magic_10memoj_shy_png = 'assets/images/emote/magic/10memoj_shy.png';
  static const String chat$emote_magic_10memoj_shy_png = 'packages/chat/assets/images/emote/magic/10memoj_shy.png';

  static const String emote_magic_11memoj_kiss_png = 'assets/images/emote/magic/11memoj_kiss.png';
  static const String chat$emote_magic_11memoj_kiss_png = 'packages/chat/assets/images/emote/magic/11memoj_kiss.png';

  static const String emote_magic_12memoj_wuya_png = 'assets/images/emote/magic/12memoj_wuya.png';
  static const String chat$emote_magic_12memoj_wuya_png = 'packages/chat/assets/images/emote/magic/12memoj_wuya.png';

  static const String emote_magic_12memoj_wuya2_png = 'assets/images/emote/magic/12memoj_wuya2.png';
  static const String chat$emote_magic_12memoj_wuya2_png = 'packages/chat/assets/images/emote/magic/12memoj_wuya2.png';

  static const String emote_magic_13memoj_asleep_png = 'assets/images/emote/magic/13memoj_asleep.png';
  static const String chat$emote_magic_13memoj_asleep_png = 'packages/chat/assets/images/emote/magic/13memoj_asleep.png';

  static const String emote_magic_14memoj_angry_png = 'assets/images/emote/magic/14memoj_angry.png';
  static const String chat$emote_magic_14memoj_angry_png = 'packages/chat/assets/images/emote/magic/14memoj_angry.png';

  static const String emote_magic_15memoj_roar_png = 'assets/images/emote/magic/15memoj_roar.png';
  static const String chat$emote_magic_15memoj_roar_png = 'packages/chat/assets/images/emote/magic/15memoj_roar.png';

  static const String emote_magic_16memoj_bye_png = 'assets/images/emote/magic/16memoj_bye.png';
  static const String chat$emote_magic_16memoj_bye_png = 'packages/chat/assets/images/emote/magic/16memoj_bye.png';

  static const String emote_magic_17memoj_covereyes_png = 'assets/images/emote/magic/17memoj_covereyes.png';
  static const String chat$emote_magic_17memoj_covereyes_png = 'packages/chat/assets/images/emote/magic/17memoj_covereyes.png';

  static const String emote_magic_18memoj_awkward_png = 'assets/images/emote/magic/18memoj_awkward.png';
  static const String chat$emote_magic_18memoj_awkward_png = 'packages/chat/assets/images/emote/magic/18memoj_awkward.png';

  static const String emote_magic_19memoj_excrment_png = 'assets/images/emote/magic/19memoj_excrment.png';
  static const String chat$emote_magic_19memoj_excrment_png = 'packages/chat/assets/images/emote/magic/19memoj_excrment.png';

  static const String emote_magic_1memoj_cute_png = 'assets/images/emote/magic/1memoj_cute.png';
  static const String chat$emote_magic_1memoj_cute_png = 'packages/chat/assets/images/emote/magic/1memoj_cute.png';

  static const String emote_magic_20memoj_fighting_png = 'assets/images/emote/magic/20memoj_fighting.png';
  static const String chat$emote_magic_20memoj_fighting_png = 'packages/chat/assets/images/emote/magic/20memoj_fighting.png';

  static const String emote_magic_21memoj_morning_png = 'assets/images/emote/magic/21memoj_morning.png';
  static const String chat$emote_magic_21memoj_morning_png = 'packages/chat/assets/images/emote/magic/21memoj_morning.png';

  static const String emote_magic_22memoj_curllips_png = 'assets/images/emote/magic/22memoj_curllips.png';
  static const String chat$emote_magic_22memoj_curllips_png = 'packages/chat/assets/images/emote/magic/22memoj_curllips.png';

  static const String emote_magic_23memoj_contempt_png = 'assets/images/emote/magic/23memoj_contempt.png';
  static const String chat$emote_magic_23memoj_contempt_png = 'packages/chat/assets/images/emote/magic/23memoj_contempt.png';

  static const String emote_magic_24memoj_chagrin_png = 'assets/images/emote/magic/24memoj_chagrin.png';
  static const String chat$emote_magic_24memoj_chagrin_png = 'packages/chat/assets/images/emote/magic/24memoj_chagrin.png';

  static const String emote_magic_25memoj_digNose_png = 'assets/images/emote/magic/25memoj_digNose.png';
  static const String chat$emote_magic_25memoj_digNose_png = 'packages/chat/assets/images/emote/magic/25memoj_digNose.png';

  static const String emote_magic_26memoj_rolleye_png = 'assets/images/emote/magic/26memoj_rolleye.png';
  static const String chat$emote_magic_26memoj_rolleye_png = 'packages/chat/assets/images/emote/magic/26memoj_rolleye.png';

  static const String emote_magic_27memoj_crazy_png = 'assets/images/emote/magic/27memoj_crazy.png';
  static const String chat$emote_magic_27memoj_crazy_png = 'packages/chat/assets/images/emote/magic/27memoj_crazy.png';

  static const String emote_magic_28memoj_goodnight_png = 'assets/images/emote/magic/28memoj_goodnight.png';
  static const String chat$emote_magic_28memoj_goodnight_png = 'packages/chat/assets/images/emote/magic/28memoj_goodnight.png';

  static const String emote_magic_29memoj_heartBroken_png = 'assets/images/emote/magic/29memoj_heartBroken.png';
  static const String chat$emote_magic_29memoj_heartBroken_png = 'packages/chat/assets/images/emote/magic/29memoj_heartBroken.png';

  static const String emote_magic_2memoj_smile_png = 'assets/images/emote/magic/2memoj_smile.png';
  static const String chat$emote_magic_2memoj_smile_png = 'packages/chat/assets/images/emote/magic/2memoj_smile.png';

  static const String emote_magic_30memoj_curse_png = 'assets/images/emote/magic/30memoj_curse.png';
  static const String chat$emote_magic_30memoj_curse_png = 'packages/chat/assets/images/emote/magic/30memoj_curse.png';

  static const String emote_magic_31memoj_squint_png = 'assets/images/emote/magic/31memoj_squint.png';
  static const String chat$emote_magic_31memoj_squint_png = 'packages/chat/assets/images/emote/magic/31memoj_squint.png';

  static const String emote_magic_32memoj_frighten_png = 'assets/images/emote/magic/32memoj_frighten.png';
  static const String chat$emote_magic_32memoj_frighten_png = 'packages/chat/assets/images/emote/magic/32memoj_frighten.png';

  static const String emote_magic_33memoj_getup_png = 'assets/images/emote/magic/33memoj_getup.png';
  static const String chat$emote_magic_33memoj_getup_png = 'packages/chat/assets/images/emote/magic/33memoj_getup.png';

  static const String emote_magic_34memoj_hinhin_png = 'assets/images/emote/magic/34memoj_hinhin.png';
  static const String chat$emote_magic_34memoj_hinhin_png = 'packages/chat/assets/images/emote/magic/34memoj_hinhin.png';

  static const String emote_magic_35memoj_titter_png = 'assets/images/emote/magic/35memoj_titter.png';
  static const String chat$emote_magic_35memoj_titter_png = 'packages/chat/assets/images/emote/magic/35memoj_titter.png';

  static const String emote_magic_36memoj_heng_png = 'assets/images/emote/magic/36memoj_heng.png';
  static const String chat$emote_magic_36memoj_heng_png = 'packages/chat/assets/images/emote/magic/36memoj_heng.png';

  static const String emote_magic_37memoj_love_png = 'assets/images/emote/magic/37memoj_love.png';
  static const String chat$emote_magic_37memoj_love_png = 'packages/chat/assets/images/emote/magic/37memoj_love.png';

  static const String emote_magic_38memoj_hug_png = 'assets/images/emote/magic/38memoj_hug.png';
  static const String chat$emote_magic_38memoj_hug_png = 'packages/chat/assets/images/emote/magic/38memoj_hug.png';

  static const String emote_magic_39memoj_mad_png = 'assets/images/emote/magic/39memoj_mad.png';
  static const String chat$emote_magic_39memoj_mad_png = 'packages/chat/assets/images/emote/magic/39memoj_mad.png';

  static const String emote_magic_3memoj_dumbfounding_png = 'assets/images/emote/magic/3memoj_dumbfounding.png';
  static const String chat$emote_magic_3memoj_dumbfounding_png = 'packages/chat/assets/images/emote/magic/3memoj_dumbfounding.png';

  static const String emote_magic_40memoj_ok_png = 'assets/images/emote/magic/40memoj_ok.png';
  static const String chat$emote_magic_40memoj_ok_png = 'packages/chat/assets/images/emote/magic/40memoj_ok.png';

  static const String emote_magic_41memoj_areYouFunny_png = 'assets/images/emote/magic/41memoj_areYouFunny.png';
  static const String chat$emote_magic_41memoj_areYouFunny_png = 'packages/chat/assets/images/emote/magic/41memoj_areYouFunny.png';

  static const String emote_magic_42memoj_penpen_png = 'assets/images/emote/magic/42memoj_penpen.png';
  static const String chat$emote_magic_42memoj_penpen_png = 'packages/chat/assets/images/emote/magic/42memoj_penpen.png';

  static const String emote_magic_43memoj_showTongue_png = 'assets/images/emote/magic/43memoj_showTongue.png';
  static const String chat$emote_magic_43memoj_showTongue_png = 'packages/chat/assets/images/emote/magic/43memoj_showTongue.png';

  static const String emote_magic_44memoj_praise_png = 'assets/images/emote/magic/44memoj_praise.png';
  static const String chat$emote_magic_44memoj_praise_png = 'packages/chat/assets/images/emote/magic/44memoj_praise.png';

  static const String emote_magic_45memoj_smoking_png = 'assets/images/emote/magic/45memoj_smoking.png';
  static const String chat$emote_magic_45memoj_smoking_png = 'packages/chat/assets/images/emote/magic/45memoj_smoking.png';

  static const String emote_magic_46memoj_sleep_png = 'assets/images/emote/magic/46memoj_sleep.png';
  static const String chat$emote_magic_46memoj_sleep_png = 'packages/chat/assets/images/emote/magic/46memoj_sleep.png';

  static const String emote_magic_47memoj_shutup_png = 'assets/images/emote/magic/47memoj_shutup.png';
  static const String chat$emote_magic_47memoj_shutup_png = 'packages/chat/assets/images/emote/magic/47memoj_shutup.png';

  static const String emote_magic_48memoj_unlucky_png = 'assets/images/emote/magic/48memoj_unlucky.png';
  static const String chat$emote_magic_48memoj_unlucky_png = 'packages/chat/assets/images/emote/magic/48memoj_unlucky.png';

  static const String emote_magic_4memoj_perspiration_png = 'assets/images/emote/magic/4memoj_perspiration.png';
  static const String chat$emote_magic_4memoj_perspiration_png = 'packages/chat/assets/images/emote/magic/4memoj_perspiration.png';

  static const String emote_magic_5memoj_cry_png = 'assets/images/emote/magic/5memoj_cry.png';
  static const String chat$emote_magic_5memoj_cry_png = 'packages/chat/assets/images/emote/magic/5memoj_cry.png';

  static const String emote_magic_6memoj_greed_png = 'assets/images/emote/magic/6memoj_greed.png';
  static const String chat$emote_magic_6memoj_greed_png = 'packages/chat/assets/images/emote/magic/6memoj_greed.png';

  static const String emote_magic_7memoj_question_png = 'assets/images/emote/magic/7memoj_question.png';
  static const String chat$emote_magic_7memoj_question_png = 'packages/chat/assets/images/emote/magic/7memoj_question.png';

  static const String emote_magic_8memoj_pity_png = 'assets/images/emote/magic/8memoj_pity.png';
  static const String chat$emote_magic_8memoj_pity_png = 'packages/chat/assets/images/emote/magic/8memoj_pity.png';

  static const String emote_magic_9memoj_laugh_png = 'assets/images/emote/magic/9memoj_laugh.png';
  static const String chat$emote_magic_9memoj_laugh_png = 'packages/chat/assets/images/emote/magic/9memoj_laugh.png';

  static const String emote_magic_audio_memoj_angry_mp3 = 'assets/images/emote/magic/audio/memoj_angry.mp3';
  static const String chat$emote_magic_audio_memoj_angry_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_angry.mp3';

  static const String emote_magic_audio_memoj_areYouFunny_mp3 = 'assets/images/emote/magic/audio/memoj_areYouFunny.mp3';
  static const String chat$emote_magic_audio_memoj_areYouFunny_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_areYouFunny.mp3';

  static const String emote_magic_audio_memoj_asleep_mp3 = 'assets/images/emote/magic/audio/memoj_asleep.mp3';
  static const String chat$emote_magic_audio_memoj_asleep_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_asleep.mp3';

  static const String emote_magic_audio_memoj_awkward_mp3 = 'assets/images/emote/magic/audio/memoj_awkward.mp3';
  static const String chat$emote_magic_audio_memoj_awkward_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_awkward.mp3';

  static const String emote_magic_audio_memoj_bye_mp3 = 'assets/images/emote/magic/audio/memoj_bye.mp3';
  static const String chat$emote_magic_audio_memoj_bye_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_bye.mp3';

  static const String emote_magic_audio_memoj_chagrin_mp3 = 'assets/images/emote/magic/audio/memoj_chagrin.mp3';
  static const String chat$emote_magic_audio_memoj_chagrin_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_chagrin.mp3';

  static const String emote_magic_audio_memoj_contempt_mp3 = 'assets/images/emote/magic/audio/memoj_contempt.mp3';
  static const String chat$emote_magic_audio_memoj_contempt_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_contempt.mp3';

  static const String emote_magic_audio_memoj_covereyes_mp3 = 'assets/images/emote/magic/audio/memoj_covereyes.mp3';
  static const String chat$emote_magic_audio_memoj_covereyes_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_covereyes.mp3';

  static const String emote_magic_audio_memoj_crazy_mp3 = 'assets/images/emote/magic/audio/memoj_crazy.mp3';
  static const String chat$emote_magic_audio_memoj_crazy_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_crazy.mp3';

  static const String emote_magic_audio_memoj_cry_mp3 = 'assets/images/emote/magic/audio/memoj_cry.mp3';
  static const String chat$emote_magic_audio_memoj_cry_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_cry.mp3';

  static const String emote_magic_audio_memoj_curllips_mp3 = 'assets/images/emote/magic/audio/memoj_curllips.mp3';
  static const String chat$emote_magic_audio_memoj_curllips_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_curllips.mp3';

  static const String emote_magic_audio_memoj_curse_mp3 = 'assets/images/emote/magic/audio/memoj_curse.mp3';
  static const String chat$emote_magic_audio_memoj_curse_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_curse.mp3';

  static const String emote_magic_audio_memoj_cute_mp3 = 'assets/images/emote/magic/audio/memoj_cute.mp3';
  static const String chat$emote_magic_audio_memoj_cute_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_cute.mp3';

  static const String emote_magic_audio_memoj_digNose_mp3 = 'assets/images/emote/magic/audio/memoj_digNose.mp3';
  static const String chat$emote_magic_audio_memoj_digNose_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_digNose.mp3';

  static const String emote_magic_audio_memoj_dumbfounding_mp3 = 'assets/images/emote/magic/audio/memoj_dumbfounding.mp3';
  static const String chat$emote_magic_audio_memoj_dumbfounding_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_dumbfounding.mp3';

  static const String emote_magic_audio_memoj_excrment_mp3 = 'assets/images/emote/magic/audio/memoj_excrment.mp3';
  static const String chat$emote_magic_audio_memoj_excrment_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_excrment.mp3';

  static const String emote_magic_audio_memoj_fighting_mp3 = 'assets/images/emote/magic/audio/memoj_fighting.mp3';
  static const String chat$emote_magic_audio_memoj_fighting_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_fighting.mp3';

  static const String emote_magic_audio_memoj_frighten_mp3 = 'assets/images/emote/magic/audio/memoj_frighten.mp3';
  static const String chat$emote_magic_audio_memoj_frighten_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_frighten.mp3';

  static const String emote_magic_audio_memoj_getup_mp3 = 'assets/images/emote/magic/audio/memoj_getup.mp3';
  static const String chat$emote_magic_audio_memoj_getup_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_getup.mp3';

  static const String emote_magic_audio_memoj_goodnight_mp3 = 'assets/images/emote/magic/audio/memoj_goodnight.mp3';
  static const String chat$emote_magic_audio_memoj_goodnight_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_goodnight.mp3';

  static const String emote_magic_audio_memoj_greed_mp3 = 'assets/images/emote/magic/audio/memoj_greed.mp3';
  static const String chat$emote_magic_audio_memoj_greed_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_greed.mp3';

  static const String emote_magic_audio_memoj_heartBroken_mp3 = 'assets/images/emote/magic/audio/memoj_heartBroken.mp3';
  static const String chat$emote_magic_audio_memoj_heartBroken_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_heartBroken.mp3';

  static const String emote_magic_audio_memoj_heng_mp3 = 'assets/images/emote/magic/audio/memoj_heng.mp3';
  static const String chat$emote_magic_audio_memoj_heng_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_heng.mp3';

  static const String emote_magic_audio_memoj_hinhin_mp3 = 'assets/images/emote/magic/audio/memoj_hinhin.mp3';
  static const String chat$emote_magic_audio_memoj_hinhin_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_hinhin.mp3';

  static const String emote_magic_audio_memoj_hug_mp3 = 'assets/images/emote/magic/audio/memoj_hug.mp3';
  static const String chat$emote_magic_audio_memoj_hug_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_hug.mp3';

  static const String emote_magic_audio_memoj_kiss_mp3 = 'assets/images/emote/magic/audio/memoj_kiss.mp3';
  static const String chat$emote_magic_audio_memoj_kiss_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_kiss.mp3';

  static const String emote_magic_audio_memoj_laugh_mp3 = 'assets/images/emote/magic/audio/memoj_laugh.mp3';
  static const String chat$emote_magic_audio_memoj_laugh_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_laugh.mp3';

  static const String emote_magic_audio_memoj_love_mp3 = 'assets/images/emote/magic/audio/memoj_love.mp3';
  static const String chat$emote_magic_audio_memoj_love_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_love.mp3';

  static const String emote_magic_audio_memoj_mad_mp3 = 'assets/images/emote/magic/audio/memoj_mad.mp3';
  static const String chat$emote_magic_audio_memoj_mad_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_mad.mp3';

  static const String emote_magic_audio_memoj_morning_mp3 = 'assets/images/emote/magic/audio/memoj_morning.mp3';
  static const String chat$emote_magic_audio_memoj_morning_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_morning.mp3';

  static const String emote_magic_audio_memoj_ok_mp3 = 'assets/images/emote/magic/audio/memoj_ok.mp3';
  static const String chat$emote_magic_audio_memoj_ok_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_ok.mp3';

  static const String emote_magic_audio_memoj_penpen_mp3 = 'assets/images/emote/magic/audio/memoj_penpen.mp3';
  static const String chat$emote_magic_audio_memoj_penpen_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_penpen.mp3';

  static const String emote_magic_audio_memoj_perspiration_mp3 = 'assets/images/emote/magic/audio/memoj_perspiration.mp3';
  static const String chat$emote_magic_audio_memoj_perspiration_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_perspiration.mp3';

  static const String emote_magic_audio_memoj_pity_mp3 = 'assets/images/emote/magic/audio/memoj_pity.mp3';
  static const String chat$emote_magic_audio_memoj_pity_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_pity.mp3';

  static const String emote_magic_audio_memoj_praise_mp3 = 'assets/images/emote/magic/audio/memoj_praise.mp3';
  static const String chat$emote_magic_audio_memoj_praise_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_praise.mp3';

  static const String emote_magic_audio_memoj_question_mp3 = 'assets/images/emote/magic/audio/memoj_question.mp3';
  static const String chat$emote_magic_audio_memoj_question_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_question.mp3';

  static const String emote_magic_audio_memoj_roar_mp3 = 'assets/images/emote/magic/audio/memoj_roar.mp3';
  static const String chat$emote_magic_audio_memoj_roar_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_roar.mp3';

  static const String emote_magic_audio_memoj_rolleye_mp3 = 'assets/images/emote/magic/audio/memoj_rolleye.mp3';
  static const String chat$emote_magic_audio_memoj_rolleye_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_rolleye.mp3';

  static const String emote_magic_audio_memoj_showTongue_mp3 = 'assets/images/emote/magic/audio/memoj_showTongue.mp3';
  static const String chat$emote_magic_audio_memoj_showTongue_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_showTongue.mp3';

  static const String emote_magic_audio_memoj_shutup_mp3 = 'assets/images/emote/magic/audio/memoj_shutup.mp3';
  static const String chat$emote_magic_audio_memoj_shutup_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_shutup.mp3';

  static const String emote_magic_audio_memoj_shy_mp3 = 'assets/images/emote/magic/audio/memoj_shy.mp3';
  static const String chat$emote_magic_audio_memoj_shy_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_shy.mp3';

  static const String emote_magic_audio_memoj_sleep_mp3 = 'assets/images/emote/magic/audio/memoj_sleep.mp3';
  static const String chat$emote_magic_audio_memoj_sleep_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_sleep.mp3';

  static const String emote_magic_audio_memoj_smile_mp3 = 'assets/images/emote/magic/audio/memoj_smile.mp3';
  static const String chat$emote_magic_audio_memoj_smile_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_smile.mp3';

  static const String emote_magic_audio_memoj_smoking_mp3 = 'assets/images/emote/magic/audio/memoj_smoking.mp3';
  static const String chat$emote_magic_audio_memoj_smoking_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_smoking.mp3';

  static const String emote_magic_audio_memoj_squint_mp3 = 'assets/images/emote/magic/audio/memoj_squint.mp3';
  static const String chat$emote_magic_audio_memoj_squint_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_squint.mp3';

  static const String emote_magic_audio_memoj_titter_mp3 = 'assets/images/emote/magic/audio/memoj_titter.mp3';
  static const String chat$emote_magic_audio_memoj_titter_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_titter.mp3';

  static const String emote_magic_audio_memoj_unlucky_mp3 = 'assets/images/emote/magic/audio/memoj_unlucky.mp3';
  static const String chat$emote_magic_audio_memoj_unlucky_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_unlucky.mp3';

  static const String emote_magic_audio_memoj_wuya_mp3 = 'assets/images/emote/magic/audio/memoj_wuya.mp3';
  static const String chat$emote_magic_audio_memoj_wuya_mp3 = 'packages/chat/assets/images/emote/magic/audio/memoj_wuya.mp3';

  static const String emote_yellow_0_png = 'assets/images/emote/yellow/0.png';
  static const String chat$emote_yellow_0_png = 'packages/chat/assets/images/emote/yellow/0.png';

  static const String emote_yellow_1_png = 'assets/images/emote/yellow/1.png';
  static const String chat$emote_yellow_1_png = 'packages/chat/assets/images/emote/yellow/1.png';

  static const String emote_yellow_10_png = 'assets/images/emote/yellow/10.png';
  static const String chat$emote_yellow_10_png = 'packages/chat/assets/images/emote/yellow/10.png';

  static const String emote_yellow_11_png = 'assets/images/emote/yellow/11.png';
  static const String chat$emote_yellow_11_png = 'packages/chat/assets/images/emote/yellow/11.png';

  static const String emote_yellow_12_png = 'assets/images/emote/yellow/12.png';
  static const String chat$emote_yellow_12_png = 'packages/chat/assets/images/emote/yellow/12.png';

  static const String emote_yellow_13_png = 'assets/images/emote/yellow/13.png';
  static const String chat$emote_yellow_13_png = 'packages/chat/assets/images/emote/yellow/13.png';

  static const String emote_yellow_14_png = 'assets/images/emote/yellow/14.png';
  static const String chat$emote_yellow_14_png = 'packages/chat/assets/images/emote/yellow/14.png';

  static const String emote_yellow_15_png = 'assets/images/emote/yellow/15.png';
  static const String chat$emote_yellow_15_png = 'packages/chat/assets/images/emote/yellow/15.png';

  static const String emote_yellow_16_png = 'assets/images/emote/yellow/16.png';
  static const String chat$emote_yellow_16_png = 'packages/chat/assets/images/emote/yellow/16.png';

  static const String emote_yellow_17_png = 'assets/images/emote/yellow/17.png';
  static const String chat$emote_yellow_17_png = 'packages/chat/assets/images/emote/yellow/17.png';

  static const String emote_yellow_18_png = 'assets/images/emote/yellow/18.png';
  static const String chat$emote_yellow_18_png = 'packages/chat/assets/images/emote/yellow/18.png';

  static const String emote_yellow_2_png = 'assets/images/emote/yellow/2.png';
  static const String chat$emote_yellow_2_png = 'packages/chat/assets/images/emote/yellow/2.png';

  static const String emote_yellow_3_png = 'assets/images/emote/yellow/3.png';
  static const String chat$emote_yellow_3_png = 'packages/chat/assets/images/emote/yellow/3.png';

  static const String emote_yellow_4_png = 'assets/images/emote/yellow/4.png';
  static const String chat$emote_yellow_4_png = 'packages/chat/assets/images/emote/yellow/4.png';

  static const String emote_yellow_5_png = 'assets/images/emote/yellow/5.png';
  static const String chat$emote_yellow_5_png = 'packages/chat/assets/images/emote/yellow/5.png';

  static const String emote_yellow_6_png = 'assets/images/emote/yellow/6.png';
  static const String chat$emote_yellow_6_png = 'packages/chat/assets/images/emote/yellow/6.png';

  static const String emote_yellow_7_png = 'assets/images/emote/yellow/7.png';
  static const String chat$emote_yellow_7_png = 'packages/chat/assets/images/emote/yellow/7.png';

  static const String emote_yellow_8_png = 'assets/images/emote/yellow/8.png';
  static const String chat$emote_yellow_8_png = 'packages/chat/assets/images/emote/yellow/8.png';

  static const String emote_yellow_9_png = 'assets/images/emote/yellow/9.png';
  static const String chat$emote_yellow_9_png = 'packages/chat/assets/images/emote/yellow/9.png';

  static const String friend_card_change_bg_svg = 'assets/images/friend_card_change_bg.svg';
  static const String chat$friend_card_change_bg_svg = 'packages/chat/assets/images/friend_card_change_bg.svg';

  static const String ic_ability_shop_png = 'assets/images/ic_ability_shop.png';
  static const String chat$ic_ability_shop_png = 'packages/chat/assets/images/ic_ability_shop.png';

  static const String ic_add_reply_webp = 'assets/images/ic_add_reply.webp';
  static const String chat$ic_add_reply_webp = 'packages/chat/assets/images/ic_add_reply.webp';

  static const String ic_agree_normal_png = 'assets/images/ic_agree_normal.png';
  static const String chat$ic_agree_normal_png = 'packages/chat/assets/images/ic_agree_normal.png';

  static const String ic_agree_selected_png = 'assets/images/ic_agree_selected.png';
  static const String chat$ic_agree_selected_png = 'packages/chat/assets/images/ic_agree_selected.png';

  static const String ic_agree_small_svg = 'assets/images/ic_agree_small.svg';
  static const String chat$ic_agree_small_svg = 'packages/chat/assets/images/ic_agree_small.svg';

  static const String ic_chat_first_charge_svg = 'assets/images/ic_chat_first_charge.svg';
  static const String chat$ic_chat_first_charge_svg = 'packages/chat/assets/images/ic_chat_first_charge.svg';

  static const String ic_chat_first_charge_webp = 'assets/images/ic_chat_first_charge.webp';
  static const String chat$ic_chat_first_charge_webp = 'packages/chat/assets/images/ic_chat_first_charge.webp';

  static const String ic_chat_moment_bg_webp = 'assets/images/ic_chat_moment_bg.webp';
  static const String chat$ic_chat_moment_bg_webp = 'packages/chat/assets/images/ic_chat_moment_bg.webp';

  static const String ic_chat_moment_bg_dark_webp = 'assets/images/ic_chat_moment_bg_dark.webp';
  static const String chat$ic_chat_moment_bg_dark_webp = 'packages/chat/assets/images/ic_chat_moment_bg_dark.webp';

  static const String ic_chat_notification_female_png = 'assets/images/ic_chat_notification_female.png';
  static const String chat$ic_chat_notification_female_png = 'packages/chat/assets/images/ic_chat_notification_female.png';

  static const String ic_chat_notification_male_png = 'assets/images/ic_chat_notification_male.png';
  static const String chat$ic_chat_notification_male_png = 'packages/chat/assets/images/ic_chat_notification_male.png';

  static const String ic_delete_webp = 'assets/images/ic_delete.webp';
  static const String chat$ic_delete_webp = 'packages/chat/assets/images/ic_delete.webp';

  static const String ic_disagree_normal_png = 'assets/images/ic_disagree_normal.png';
  static const String chat$ic_disagree_normal_png = 'packages/chat/assets/images/ic_disagree_normal.png';

  static const String ic_disagree_selected_png = 'assets/images/ic_disagree_selected.png';
  static const String chat$ic_disagree_selected_png = 'packages/chat/assets/images/ic_disagree_selected.png';

  static const String ic_disagree_small_svg = 'assets/images/ic_disagree_small.svg';
  static const String chat$ic_disagree_small_svg = 'packages/chat/assets/images/ic_disagree_small.svg';

  static const String ic_emoticon_close_webp = 'assets/images/ic_emoticon_close.webp';
  static const String chat$ic_emoticon_close_webp = 'packages/chat/assets/images/ic_emoticon_close.webp';

  static const String ic_game_verify_svg = 'assets/images/ic_game_verify.svg';
  static const String chat$ic_game_verify_svg = 'packages/chat/assets/images/ic_game_verify.svg';

  static const String ic_game_verify_false_svg = 'assets/images/ic_game_verify_false.svg';
  static const String chat$ic_game_verify_false_svg = 'packages/chat/assets/images/ic_game_verify_false.svg';

  static const String ic_heart_flip_guide_bg_webp = 'assets/images/ic_heart_flip_guide_bg.webp';
  static const String chat$ic_heart_flip_guide_bg_webp = 'packages/chat/assets/images/ic_heart_flip_guide_bg.webp';

  static const String ic_heart_flip_icon_webp = 'assets/images/ic_heart_flip_icon.webp';
  static const String chat$ic_heart_flip_icon_webp = 'packages/chat/assets/images/ic_heart_flip_icon.webp';

  static const String ic_invite_game_aad_png = 'assets/images/ic_invite_game_aad.png';
  static const String chat$ic_invite_game_aad_png = 'packages/chat/assets/images/ic_invite_game_aad.png';

  static const String ic_list_more_svg = 'assets/images/ic_list_more.svg';
  static const String chat$ic_list_more_svg = 'packages/chat/assets/images/ic_list_more.svg';

  static const String ic_match_rule_svg = 'assets/images/ic_match_rule.svg';
  static const String chat$ic_match_rule_svg = 'packages/chat/assets/images/ic_match_rule.svg';

  static const String ic_next_svg = 'assets/images/ic_next.svg';
  static const String chat$ic_next_svg = 'packages/chat/assets/images/ic_next.svg';

  static const String ic_next_small_svg = 'assets/images/ic_next_small.svg';
  static const String chat$ic_next_small_svg = 'packages/chat/assets/images/ic_next_small.svg';

  static const String ic_orderdeliver_png = 'assets/images/ic_orderdeliver.png';
  static const String chat$ic_orderdeliver_png = 'packages/chat/assets/images/ic_orderdeliver.png';

  static const String ic_quick_reply_review_webp = 'assets/images/ic_quick_reply_review.webp';
  static const String chat$ic_quick_reply_review_webp = 'packages/chat/assets/images/ic_quick_reply_review.webp';

  static const String ic_quick_reply_review_fail_webp = 'assets/images/ic_quick_reply_review_fail.webp';
  static const String chat$ic_quick_reply_review_fail_webp = 'packages/chat/assets/images/ic_quick_reply_review_fail.webp';

  static const String ic_quick_reply_review_ok_webp = 'assets/images/ic_quick_reply_review_ok.webp';
  static const String chat$ic_quick_reply_review_ok_webp = 'packages/chat/assets/images/ic_quick_reply_review_ok.webp';

  static const String ic_quick_reply_voice_webp = 'assets/images/ic_quick_reply_voice.webp';
  static const String chat$ic_quick_reply_voice_webp = 'packages/chat/assets/images/ic_quick_reply_voice.webp';

  static const String ic_quick_reply_voice_1_webp = 'assets/images/ic_quick_reply_voice_1.webp';
  static const String chat$ic_quick_reply_voice_1_webp = 'packages/chat/assets/images/ic_quick_reply_voice_1.webp';

  static const String ic_quick_reply_voice_2_webp = 'assets/images/ic_quick_reply_voice_2.webp';
  static const String chat$ic_quick_reply_voice_2_webp = 'packages/chat/assets/images/ic_quick_reply_voice_2.webp';

  static const String ic_sound_pause_webp = 'assets/images/ic_sound_pause.webp';
  static const String chat$ic_sound_pause_webp = 'packages/chat/assets/images/ic_sound_pause.webp';

  static const String ic_sound_pause_dark_webp = 'assets/images/ic_sound_pause_dark.webp';
  static const String chat$ic_sound_pause_dark_webp = 'packages/chat/assets/images/ic_sound_pause_dark.webp';

  static const String ic_sound_play_webp = 'assets/images/ic_sound_play.webp';
  static const String chat$ic_sound_play_webp = 'packages/chat/assets/images/ic_sound_play.webp';

  static const String ic_sound_play_dark_webp = 'assets/images/ic_sound_play_dark.webp';
  static const String chat$ic_sound_play_dark_webp = 'packages/chat/assets/images/ic_sound_play_dark.webp';

  static const String ic_sweet_album_webp = 'assets/images/ic_sweet_album.webp';
  static const String chat$ic_sweet_album_webp = 'packages/chat/assets/images/ic_sweet_album.webp';

  static const String icon_checkbox_selected_svg = 'assets/images/icon_checkbox_selected.svg';
  static const String chat$icon_checkbox_selected_svg = 'packages/chat/assets/images/icon_checkbox_selected.svg';

  static const String inviteRoom_svg = 'assets/images/inviteRoom.svg';
  static const String chat$inviteRoom_svg = 'packages/chat/assets/images/inviteRoom.svg';

  static const String package_display_background_png = 'assets/images/package_display_background.png';
  static const String chat$package_display_background_png = 'packages/chat/assets/images/package_display_background.png';

  static const String phone_small_png = 'assets/images/phone_small.png';
  static const String chat$phone_small_png = 'packages/chat/assets/images/phone_small.png';

  static const String phone_small_svg = 'assets/images/phone_small.svg';
  static const String chat$phone_small_svg = 'packages/chat/assets/images/phone_small.svg';

  static const String received_gift_bg_left_png = 'assets/images/received_gift_bg_left.png';
  static const String chat$received_gift_bg_left_png = 'packages/chat/assets/images/received_gift_bg_left.png';

  static const String received_gift_bg_right_png = 'assets/images/received_gift_bg_right.png';
  static const String chat$received_gift_bg_right_png = 'packages/chat/assets/images/received_gift_bg_right.png';

  static const String received_gift_dialog_top_png = 'assets/images/received_gift_dialog_top.png';
  static const String chat$received_gift_dialog_top_png = 'packages/chat/assets/images/received_gift_dialog_top.png';

  static const String received_gift_notice_icon_png = 'assets/images/received_gift_notice_icon.png';
  static const String chat$received_gift_notice_icon_png = 'packages/chat/assets/images/received_gift_notice_icon.png';

  static const String tacit_msg_bg_webp = 'assets/images/tacit_msg_bg.webp';
  static const String chat$tacit_msg_bg_webp = 'packages/chat/assets/images/tacit_msg_bg.webp';

  static const String tacit_msg_bg_dark_webp = 'assets/images/tacit_msg_bg_dark.webp';
  static const String chat$tacit_msg_bg_dark_webp = 'packages/chat/assets/images/tacit_msg_bg_dark.webp';

  static const String video_small_png = 'assets/images/video_small.png';
  static const String chat$video_small_png = 'packages/chat/assets/images/video_small.png';

  static const String video_small_svg = 'assets/images/video_small.svg';
  static const String chat$video_small_svg = 'packages/chat/assets/images/video_small.svg';
}
