// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 294.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'rank';

  static const String avatar_ring_png = 'assets/images/avatar_ring.png';
  static const String rank$avatar_ring_png =
      'packages/rank/assets/images/avatar_ring.png';

  static const String bg_break_up_webp = 'assets/images/bg_break_up.webp';
  static const String rank$bg_break_up_webp =
      'packages/rank/assets/images/bg_break_up.webp';

  static const String bg_date_label_webp = 'assets/images/bg_date_label.webp';
  static const String rank$bg_date_label_webp =
      'packages/rank/assets/images/bg_date_label.webp';

  static const String bg_lucky_bag_icon_webp =
      'assets/images/bg_lucky_bag_icon.webp';
  static const String rank$bg_lucky_bag_icon_webp =
      'packages/rank/assets/images/bg_lucky_bag_icon.webp';

  static const String bg_marry_rank_top_webp =
      'assets/images/bg_marry_rank_top.webp';
  static const String rank$bg_marry_rank_top_webp =
      'packages/rank/assets/images/bg_marry_rank_top.webp';

  static const String bg_propose_webp = 'assets/images/bg_propose.webp';
  static const String rank$bg_propose_webp =
      'packages/rank/assets/images/bg_propose.webp';

  static const String bg_rank_case_bg_top1_png =
      'assets/images/bg_rank_case_bg_top1.png';
  static const String rank$bg_rank_case_bg_top1_png =
      'packages/rank/assets/images/bg_rank_case_bg_top1.png';

  static const String bg_rank_case_bg_top2_png =
      'assets/images/bg_rank_case_bg_top2.png';
  static const String rank$bg_rank_case_bg_top2_png =
      'packages/rank/assets/images/bg_rank_case_bg_top2.png';

  static const String bg_rank_case_bg_top3_png =
      'assets/images/bg_rank_case_bg_top3.png';
  static const String rank$bg_rank_case_bg_top3_png =
      'packages/rank/assets/images/bg_rank_case_bg_top3.png';

  static const String bg_rank_case_bg_top4_png =
      'assets/images/bg_rank_case_bg_top4.png';
  static const String rank$bg_rank_case_bg_top4_png =
      'packages/rank/assets/images/bg_rank_case_bg_top4.png';

  static const String bg_rank_case_icon_top1_png =
      'assets/images/bg_rank_case_icon_top1.png';
  static const String rank$bg_rank_case_icon_top1_png =
      'packages/rank/assets/images/bg_rank_case_icon_top1.png';

  static const String bg_rank_case_icon_top2_png =
      'assets/images/bg_rank_case_icon_top2.png';
  static const String rank$bg_rank_case_icon_top2_png =
      'packages/rank/assets/images/bg_rank_case_icon_top2.png';

  static const String bg_rank_case_icon_top3_png =
      'assets/images/bg_rank_case_icon_top3.png';
  static const String rank$bg_rank_case_icon_top3_png =
      'packages/rank/assets/images/bg_rank_case_icon_top3.png';

  static const String bg_rank_cp1_png = 'assets/images/bg_rank_cp1.png';
  static const String rank$bg_rank_cp1_png =
      'packages/rank/assets/images/bg_rank_cp1.png';

  static const String bg_rank_cp2_png = 'assets/images/bg_rank_cp2.png';
  static const String rank$bg_rank_cp2_png =
      'packages/rank/assets/images/bg_rank_cp2.png';

  static const String bg_rank_heart_beat_webp =
      'assets/images/bg_rank_heart_beat.webp';
  static const String rank$bg_rank_heart_beat_webp =
      'packages/rank/assets/images/bg_rank_heart_beat.webp';

  static const String bg_rank_star_png = 'assets/images/bg_rank_star.png';
  static const String rank$bg_rank_star_png =
      'packages/rank/assets/images/bg_rank_star.png';

  static const String bg_rank_star_new_top0_png =
      'assets/images/bg_rank_star_new_top0.png';
  static const String rank$bg_rank_star_new_top0_png =
      'packages/rank/assets/images/bg_rank_star_new_top0.png';

  static const String bg_rank_star_new_top1_png =
      'assets/images/bg_rank_star_new_top1.png';
  static const String rank$bg_rank_star_new_top1_png =
      'packages/rank/assets/images/bg_rank_star_new_top1.png';

  static const String bg_rank_star_new_top2_png =
      'assets/images/bg_rank_star_new_top2.png';
  static const String rank$bg_rank_star_new_top2_png =
      'packages/rank/assets/images/bg_rank_star_new_top2.png';

  static const String bg_rank_star_top0_png =
      'assets/images/bg_rank_star_top0.png';
  static const String rank$bg_rank_star_top0_png =
      'packages/rank/assets/images/bg_rank_star_top0.png';

  static const String bg_rank_star_top1_png =
      'assets/images/bg_rank_star_top1.png';
  static const String rank$bg_rank_star_top1_png =
      'packages/rank/assets/images/bg_rank_star_top1.png';

  static const String bg_rank_week_top1_png =
      'assets/images/bg_rank_week_top1.png';
  static const String rank$bg_rank_week_top1_png =
      'packages/rank/assets/images/bg_rank_week_top1.png';

  static const String bg_wedding_webp = 'assets/images/bg_wedding.webp';
  static const String rank$bg_wedding_webp =
      'packages/rank/assets/images/bg_wedding.webp';

  static const String count_down_icon_webp =
      'assets/images/count_down_icon.webp';
  static const String rank$count_down_icon_webp =
      'packages/rank/assets/images/count_down_icon.webp';

  static const String create_add_svg = 'assets/images/create_add.svg';
  static const String rank$create_add_svg =
      'packages/rank/assets/images/create_add.svg';

  static const String gift_awake_bg_webp = 'assets/images/gift_awake_bg.webp';
  static const String rank$gift_awake_bg_webp =
      'packages/rank/assets/images/gift_awake_bg.webp';

  static const String gift_awake_first_webp =
      'assets/images/gift_awake_first.webp';
  static const String rank$gift_awake_first_webp =
      'packages/rank/assets/images/gift_awake_first.webp';

  static const String gift_awake_second_webp =
      'assets/images/gift_awake_second.webp';
  static const String rank$gift_awake_second_webp =
      'packages/rank/assets/images/gift_awake_second.webp';

  static const String gift_awake_third_webp =
      'assets/images/gift_awake_third.webp';
  static const String rank$gift_awake_third_webp =
      'packages/rank/assets/images/gift_awake_third.webp';

  static const String gift_weak_icon_png = 'assets/images/gift_weak_icon.png';
  static const String rank$gift_weak_icon_png =
      'packages/rank/assets/images/gift_weak_icon.png';

  static const String gift_week_champion_bg_star_webp =
      'assets/images/gift_week/champion_bg_star.webp';
  static const String rank$gift_week_champion_bg_star_webp =
      'packages/rank/assets/images/gift_week/champion_bg_star.webp';

  static const String gift_week_gift_week_rank_empty_webp =
      'assets/images/gift_week/gift_week_rank_empty.webp';
  static const String rank$gift_week_gift_week_rank_empty_webp =
      'packages/rank/assets/images/gift_week/gift_week_rank_empty.webp';

  static const String gift_week_last_week_big_man_webp =
      'assets/images/gift_week/last_week_big_man.webp';
  static const String rank$gift_week_last_week_big_man_webp =
      'packages/rank/assets/images/gift_week/last_week_big_man.webp';

  static const String gift_week_last_week_champion_webp =
      'assets/images/gift_week/last_week_champion.webp';
  static const String rank$gift_week_last_week_champion_webp =
      'packages/rank/assets/images/gift_week/last_week_champion.webp';

  static const String gift_week_last_week_left_bottom_diamond_webp =
      'assets/images/gift_week/last_week_left_bottom_diamond.webp';
  static const String rank$gift_week_last_week_left_bottom_diamond_webp =
      'packages/rank/assets/images/gift_week/last_week_left_bottom_diamond.webp';

  static const String gift_week_last_week_platform_star_webp =
      'assets/images/gift_week/last_week_platform_star.webp';
  static const String rank$gift_week_last_week_platform_star_webp =
      'packages/rank/assets/images/gift_week/last_week_platform_star.webp';

  static const String gift_week_last_week_right_top_diamond_webp =
      'assets/images/gift_week/last_week_right_top_diamond.webp';
  static const String rank$gift_week_last_week_right_top_diamond_webp =
      'packages/rank/assets/images/gift_week/last_week_right_top_diamond.webp';

  static String gift_week_rankx_webp(Object p0) =>
      'assets/images/gift_week/rank${p0.toString()}.webp';

  static String rank$gift_week_rankx_webp(Object p0) =>
      'packages/rank/assets/images/gift_week/rank${p0.toString()}.webp';

  static const String gift_week_rank_type_tab_item_bg_webp =
      'assets/images/gift_week/rank_type_tab_item_bg.webp';
  static const String rank$gift_week_rank_type_tab_item_bg_webp =
      'packages/rank/assets/images/gift_week/rank_type_tab_item_bg.webp';

  static const String gift_week_selected_gift_bg_webp =
      'assets/images/gift_week/selected_gift_bg.webp';
  static const String rank$gift_week_selected_gift_bg_webp =
      'packages/rank/assets/images/gift_week/selected_gift_bg.webp';

  static const String gift_week_user_week_star_bg_webp =
      'assets/images/gift_week/user_week_star_bg.webp';
  static const String rank$gift_week_user_week_star_bg_webp =
      'packages/rank/assets/images/gift_week/user_week_star_bg.webp';

  static const String glory_headline_bg_webp =
      'assets/images/glory_headline_bg.webp';
  static const String rank$glory_headline_bg_webp =
      'packages/rank/assets/images/glory_headline_bg.webp';

  static const String glory_headline_bg_dark_webp =
      'assets/images/glory_headline_bg_dark.webp';
  static const String rank$glory_headline_bg_dark_webp =
      'packages/rank/assets/images/glory_headline_bg_dark.webp';

  static const String god_bg_audio_pause_blue_webp =
      'assets/images/god/bg_audio_pause_blue.webp';
  static const String rank$god_bg_audio_pause_blue_webp =
      'packages/rank/assets/images/god/bg_audio_pause_blue.webp';

  static const String god_bg_audio_pause_pink_webp =
      'assets/images/god/bg_audio_pause_pink.webp';
  static const String rank$god_bg_audio_pause_pink_webp =
      'packages/rank/assets/images/god/bg_audio_pause_pink.webp';

  static const String god_bg_audio_play_blue_webp =
      'assets/images/god/bg_audio_play_blue.webp';
  static const String rank$god_bg_audio_play_blue_webp =
      'packages/rank/assets/images/god/bg_audio_play_blue.webp';

  static const String god_bg_audio_play_pink_webp =
      'assets/images/god/bg_audio_play_pink.webp';
  static const String rank$god_bg_audio_play_pink_webp =
      'packages/rank/assets/images/god/bg_audio_play_pink.webp';

  static const String god_bg_match_gang_up_webp =
      'assets/images/god/bg_match_gang_up.webp';
  static const String rank$god_bg_match_gang_up_webp =
      'packages/rank/assets/images/god/bg_match_gang_up.webp';

  static const String god_ic_chat_webp = 'assets/images/god/ic_chat.webp';
  static const String rank$god_ic_chat_webp =
      'packages/rank/assets/images/god/ic_chat.webp';

  static const String god_ic_chat_dark_webp =
      'assets/images/god/ic_chat_dark.webp';
  static const String rank$god_ic_chat_dark_webp =
      'packages/rank/assets/images/god/ic_chat_dark.webp';

  static const String god_ic_female_svg = 'assets/images/god/ic_female.webp';
  static const String rank$god_ic_female_svg =
      'packages/rank/assets/images/god/ic_female.webp';

  static const String god_ic_lightning_webp =
      'assets/images/god/ic_lightning.webp';
  static const String rank$god_ic_lightning_webp =
      'packages/rank/assets/images/god/ic_lightning.webp';

  static const String god_ic_male_svg = 'assets/images/god/ic_male.webp';
  static const String rank$god_ic_male_svg =
      'packages/rank/assets/images/god/ic_male.webp';

  static const String home_hour_rank_bg_webp =
      'assets/images/home_hour_rank_bg.webp';
  static const String rank$home_hour_rank_bg_webp =
      'packages/rank/assets/images/home_hour_rank_bg.webp';

  static const String ic_arrow_round_svg = 'assets/images/ic_arrow_round.svg';
  static const String rank$ic_arrow_round_svg =
      'packages/rank/assets/images/ic_arrow_round.svg';

  static const String ic_arrow_small_svg = 'assets/images/ic_arrow_small.svg';
  static const String rank$ic_arrow_small_svg =
      'packages/rank/assets/images/ic_arrow_small.svg';

  static const String ic_arrow_small_dark_svg =
      'assets/images/ic_arrow_small_dark.svg';
  static const String rank$ic_arrow_small_dark_svg =
      'packages/rank/assets/images/ic_arrow_small_dark.svg';

  static const String ic_back_svg = 'assets/images/ic_back.svg';
  static const String rank$ic_back_svg =
      'packages/rank/assets/images/ic_back.svg';

  static const String ic_boss_seat_svg = 'assets/images/ic_boss_seat.svg';
  static const String rank$ic_boss_seat_svg =
      'packages/rank/assets/images/ic_boss_seat.svg';

  static const String ic_clock_svg = 'assets/images/ic_clock.svg';
  static const String rank$ic_clock_svg =
      'packages/rank/assets/images/ic_clock.svg';

  static const String ic_clock_webp = 'assets/images/ic_clock.webp';
  static const String rank$ic_clock_webp =
      'packages/rank/assets/images/ic_clock.webp';

  static const String ic_defend_upgrade_tips_webp =
      'assets/images/ic_defend_upgrade_tips.webp';
  static const String rank$ic_defend_upgrade_tips_webp =
      'packages/rank/assets/images/ic_defend_upgrade_tips.webp';

  static const String ic_god_tag_webp = 'assets/images/ic_god_tag.webp';
  static const String rank$ic_god_tag_webp =
      'packages/rank/assets/images/ic_god_tag.webp';

  static const String ic_heart_liked_png = 'assets/images/ic_heart_liked.png';
  static const String rank$ic_heart_liked_png =
      'packages/rank/assets/images/ic_heart_liked.png';

  static const String ic_heart_normal_png = 'assets/images/ic_heart_normal.png';
  static const String rank$ic_heart_normal_png =
      'packages/rank/assets/images/ic_heart_normal.png';

  static const String ic_home_banner_embellish_left_png =
      'assets/images/ic_home_banner_embellish_left.png';
  static const String rank$ic_home_banner_embellish_left_png =
      'packages/rank/assets/images/ic_home_banner_embellish_left.png';

  static const String ic_home_banner_embellish_right_png =
      'assets/images/ic_home_banner_embellish_right.png';
  static const String rank$ic_home_banner_embellish_right_png =
      'packages/rank/assets/images/ic_home_banner_embellish_right.png';

  static const String ic_home_create_add_webp =
      'assets/images/ic_home_create_add.webp';
  static const String rank$ic_home_create_add_webp =
      'packages/rank/assets/images/ic_home_create_add.webp';

  static const String ic_home_create_add_dark_webp =
      'assets/images/ic_home_create_add_dark.webp';
  static const String rank$ic_home_create_add_dark_webp =
      'packages/rank/assets/images/ic_home_create_add_dark.webp';

  static const String ic_home_fast_match_webp =
      'assets/images/ic_home_fast_match.webp';
  static const String rank$ic_home_fast_match_webp =
      'packages/rank/assets/images/ic_home_fast_match.webp';

  static const String ic_home_fast_match_dark_webp =
      'assets/images/ic_home_fast_match_dark.webp';
  static const String rank$ic_home_fast_match_dark_webp =
      'packages/rank/assets/images/ic_home_fast_match_dark.webp';

  static const String ic_home_group_chat_webp =
      'assets/images/ic_home_group_chat.webp';
  static const String rank$ic_home_group_chat_webp =
      'packages/rank/assets/images/ic_home_group_chat.webp';

  static const String ic_home_group_premade_webp =
      'assets/images/ic_home_group_premade.webp';
  static const String rank$ic_home_group_premade_webp =
      'packages/rank/assets/images/ic_home_group_premade.webp';

  static const String ic_home_group_rank_webp =
      'assets/images/ic_home_group_rank.webp';
  static const String rank$ic_home_group_rank_webp =
      'packages/rank/assets/images/ic_home_group_rank.webp';

  static const String ic_home_group_welfare_webp =
      'assets/images/ic_home_group_welfare.webp';
  static const String rank$ic_home_group_welfare_webp =
      'packages/rank/assets/images/ic_home_group_welfare.webp';

  static const String ic_home_list_style_1_webp =
      'assets/images/ic_home_list_style_1.webp';
  static const String rank$ic_home_list_style_1_webp =
      'packages/rank/assets/images/ic_home_list_style_1.webp';

  static const String ic_home_list_style_2_webp =
      'assets/images/ic_home_list_style_2.webp';
  static const String rank$ic_home_list_style_2_webp =
      'packages/rank/assets/images/ic_home_list_style_2.webp';

  static const String ic_home_phone_webp = 'assets/images/ic_home_phone.webp';
  static const String rank$ic_home_phone_webp =
      'packages/rank/assets/images/ic_home_phone.webp';

  static const String ic_home_phone_dark_webp =
      'assets/images/ic_home_phone_dark.webp';
  static const String rank$ic_home_phone_dark_webp =
      'packages/rank/assets/images/ic_home_phone_dark.webp';

  static const String ic_home_search_svg = 'assets/images/ic_home_search.svg';
  static const String rank$ic_home_search_svg =
      'packages/rank/assets/images/ic_home_search.svg';

  static const String ic_home_search_webp = 'assets/images/ic_home_search.webp';
  static const String rank$ic_home_search_webp =
      'packages/rank/assets/images/ic_home_search.webp';

  static const String ic_home_search_dark_webp =
      'assets/images/ic_home_search_dark.webp';
  static const String rank$ic_home_search_dark_webp =
      'packages/rank/assets/images/ic_home_search_dark.webp';

  static const String ic_match_arrow_svg = 'assets/images/ic_match_arrow.svg';
  static const String rank$ic_match_arrow_svg =
      'packages/rank/assets/images/ic_match_arrow.svg';

  static const String ic_more_svg = 'assets/images/ic_more.svg';
  static const String rank$ic_more_svg =
      'packages/rank/assets/images/ic_more.svg';

  static const String ic_more_webp = 'assets/images/ic_more.webp';
  static const String rank$ic_more_webp =
      'packages/rank/assets/images/ic_more.webp';

  static const String ic_next_svg = 'assets/images/ic_next.svg';
  static const String rank$ic_next_svg =
      'packages/rank/assets/images/ic_next.svg';

  static const String ic_next_small_svg = 'assets/images/ic_next_small.svg';
  static const String rank$ic_next_small_svg =
      'packages/rank/assets/images/ic_next_small.svg';

  static const String ic_nobility_crown_webp =
      'assets/images/ic_nobility_crown.webp';
  static const String rank$ic_nobility_crown_webp =
      'packages/rank/assets/images/ic_nobility_crown.webp';

  static const String ic_people_in_party_svg =
      'assets/images/ic_people_in_party.svg';
  static const String rank$ic_people_in_party_svg =
      'packages/rank/assets/images/ic_people_in_party.svg';

  static const String ic_phone_webp = 'assets/images/ic_phone.webp';
  static const String rank$ic_phone_webp =
      'packages/rank/assets/images/ic_phone.webp';

  static const String ic_private_msg_webp = 'assets/images/ic_private_msg.webp';
  static const String rank$ic_private_msg_webp =
      'packages/rank/assets/images/ic_private_msg.webp';

  static const String ic_quality_user_webp =
      'assets/images/ic_quality_user.webp';
  static const String rank$ic_quality_user_webp =
      'packages/rank/assets/images/ic_quality_user.webp';

  static const String ic_quick_match_shadow_png =
      'assets/images/ic_quick_match_shadow.png';
  static const String rank$ic_quick_match_shadow_png =
      'packages/rank/assets/images/ic_quick_match_shadow.png';

  static const String ic_rank_cross_pk_icon_webp =
      'assets/images/ic_rank_cross_pk_icon.webp';
  static const String rank$ic_rank_cross_pk_icon_webp =
      'packages/rank/assets/images/ic_rank_cross_pk_icon.webp';

  static const String ic_rank_entrance_png =
      'assets/images/ic_rank_entrance.png';
  static const String rank$ic_rank_entrance_png =
      'packages/rank/assets/images/ic_rank_entrance.png';

  static const String ic_room_svg = 'assets/images/ic_room.svg';
  static const String rank$ic_room_svg =
      'packages/rank/assets/images/ic_room.svg';

  static const String ic_room_create_svg = 'assets/images/ic_room_create.svg';
  static const String rank$ic_room_create_svg =
      'packages/rank/assets/images/ic_room_create.svg';

  static const String ic_room_fleet_webp = 'assets/images/ic_room_fleet.webp';
  static const String rank$ic_room_fleet_webp =
      'packages/rank/assets/images/ic_room_fleet.webp';

  static const String ic_room_live_webp = 'assets/images/ic_room_live.webp';
  static const String rank$ic_room_live_webp =
      'packages/rank/assets/images/ic_room_live.webp';

  static const String ic_round_add_svg = 'assets/images/ic_round_add.svg';
  static const String rank$ic_round_add_svg =
      'packages/rank/assets/images/ic_round_add.svg';

  static const String ic_search_svg = 'assets/images/ic_search.svg';
  static const String rank$ic_search_svg =
      'packages/rank/assets/images/ic_search.svg';

  static const String ic_selected_svg = 'assets/images/ic_selected.svg';
  static const String rank$ic_selected_svg =
      'packages/rank/assets/images/ic_selected.svg';

  static const String ic_selected_dark_svg =
      'assets/images/ic_selected_dark.svg';
  static const String rank$ic_selected_dark_svg =
      'packages/rank/assets/images/ic_selected_dark.svg';

  static const String ic_sign_webp = 'assets/images/ic_sign.webp';
  static const String rank$ic_sign_webp =
      'packages/rank/assets/images/ic_sign.webp';

  static const String ic_sign_dark_webp = 'assets/images/ic_sign_dark.webp';
  static const String rank$ic_sign_dark_webp =
      'packages/rank/assets/images/ic_sign_dark.webp';

  static const String ic_sound_pause_png = 'assets/images/ic_sound_pause.png';
  static const String rank$ic_sound_pause_png =
      'packages/rank/assets/images/ic_sound_pause.png';

  static const String ic_sound_pause_dark_png =
      'assets/images/ic_sound_pause_dark.png';
  static const String rank$ic_sound_pause_dark_png =
      'packages/rank/assets/images/ic_sound_pause_dark.png';

  static const String ic_sound_play_png = 'assets/images/ic_sound_play.png';
  static const String rank$ic_sound_play_png =
      'packages/rank/assets/images/ic_sound_play.png';

  static const String ic_sound_play_dark_png =
      'assets/images/ic_sound_play_dark.png';
  static const String rank$ic_sound_play_dark_png =
      'packages/rank/assets/images/ic_sound_play_dark.png';

  static const String ic_week_star_webp = 'assets/images/ic_week_star.webp';
  static const String rank$ic_week_star_webp =
      'packages/rank/assets/images/ic_week_star.webp';

  static const String icon_day_png = 'assets/images/icon_day.png';
  static const String rank$icon_day_png =
      'packages/rank/assets/images/icon_day.png';

  static const String left_order_webp = 'assets/images/left_order.webp';
  static const String rank$left_order_webp =
      'packages/rank/assets/images/left_order.webp';

  static const String live_rank_hour_png = 'assets/images/live_rank_hour.png';
  static const String rank$live_rank_hour_png =
      'packages/rank/assets/images/live_rank_hour.png';

  static const String marry_bless_corner_mark_webp =
      'assets/images/marry_bless_corner_mark.webp';
  static const String rank$marry_bless_corner_mark_webp =
      'packages/rank/assets/images/marry_bless_corner_mark.webp';

  static const String marry_love_corner_mark_webp =
      'assets/images/marry_love_corner_mark.webp';
  static const String rank$marry_love_corner_mark_webp =
      'packages/rank/assets/images/marry_love_corner_mark.webp';

  static const String mate_relation_left_semicircle_webp =
      'assets/images/mate_relation_left_semicircle.webp';
  static const String rank$mate_relation_left_semicircle_webp =
      'packages/rank/assets/images/mate_relation_left_semicircle.webp';

  static const String mate_relation_middle_love_webp =
      'assets/images/mate_relation_middle_love.webp';
  static const String rank$mate_relation_middle_love_webp =
      'packages/rank/assets/images/mate_relation_middle_love.webp';

  static const String mate_relation_right_semicircle_webp =
      'assets/images/mate_relation_right_semicircle.webp';
  static const String rank$mate_relation_right_semicircle_webp =
      'packages/rank/assets/images/mate_relation_right_semicircle.webp';

  static const String pk_pk_rank_faq_webp = 'assets/images/pk/pk_rank_faq.webp';
  static const String rank$pk_pk_rank_faq_webp =
      'packages/rank/assets/images/pk/pk_rank_faq.webp';

  static const String pk_pk_rank_history_lose_webp =
      'assets/images/pk/pk_rank_history_lose.webp';
  static const String rank$pk_pk_rank_history_lose_webp =
      'packages/rank/assets/images/pk/pk_rank_history_lose.webp';

  static const String pk_pk_rank_history_pk_webp =
      'assets/images/pk/pk_rank_history_pk.webp';
  static const String rank$pk_pk_rank_history_pk_webp =
      'packages/rank/assets/images/pk/pk_rank_history_pk.webp';

  static const String pk_pk_rank_history_punish_webp =
      'assets/images/pk/pk_rank_history_punish.webp';
  static const String rank$pk_pk_rank_history_punish_webp =
      'packages/rank/assets/images/pk/pk_rank_history_punish.webp';

  static const String pk_pk_rank_history_tie_webp =
      'assets/images/pk/pk_rank_history_tie.webp';
  static const String rank$pk_pk_rank_history_tie_webp =
      'packages/rank/assets/images/pk/pk_rank_history_tie.webp';

  static const String pk_pk_rank_history_win_webp =
      'assets/images/pk/pk_rank_history_win.webp';
  static const String rank$pk_pk_rank_history_win_webp =
      'packages/rank/assets/images/pk/pk_rank_history_win.webp';

  static const String rank_bg_companion_rank_menu_webp =
      'assets/images/rank/bg_companion_rank_menu.webp';
  static const String rank$rank_bg_companion_rank_menu_webp =
      'packages/rank/assets/images/rank/bg_companion_rank_menu.webp';

  static const String rank_bg_rank_daily_top_webp =
      'assets/images/rank/bg_rank_daily_top.webp';
  static const String rank$rank_bg_rank_daily_top_webp =
      'packages/rank/assets/images/rank/bg_rank_daily_top.webp';

  static String rank_charm_achieve_rank_x_webp(Object p0) =>
      'assets/images/rank/charm_achieve_rank_${p0.toString()}.webp';

  static String rank$rank_charm_achieve_rank_x_webp(Object p0) =>
      'packages/rank/assets/images/rank/charm_achieve_rank_${p0.toString()}.webp';

  static String rank_charm_achieve_rank_header_x_webp(Object p0) =>
      'assets/images/rank/charm_achieve_rank_header_${p0.toString()}.webp';

  static String rank$rank_charm_achieve_rank_header_x_webp(Object p0) =>
      'packages/rank/assets/images/rank/charm_achieve_rank_header_${p0.toString()}.webp';

  static String rank_charm_achieve_rank_header_dark_x_webp(Object p0) =>
      'assets/images/rank/charm_achieve_rank_header_dark_${p0.toString()}.webp';

  static String rank$rank_charm_achieve_rank_header_dark_x_webp(Object p0) =>
      'packages/rank/assets/images/rank/charm_achieve_rank_header_dark_${p0.toString()}.webp';

  static const String rank_charm_fame_bottom_hat_webp =
      'assets/images/rank/charm_fame_bottom_hat.webp';
  static const String rank$rank_charm_fame_bottom_hat_webp =
      'packages/rank/assets/images/rank/charm_fame_bottom_hat.webp';

  static const String rank_charm_fame_head_border_webp =
      'assets/images/rank/charm_fame_head_border.webp';
  static const String rank$rank_charm_fame_head_border_webp =
      'packages/rank/assets/images/rank/charm_fame_head_border.webp';

  static const String rank_charm_fame_top_hat_webp =
      'assets/images/rank/charm_fame_top_hat.webp';
  static const String rank$rank_charm_fame_top_hat_webp =
      'packages/rank/assets/images/rank/charm_fame_top_hat.webp';

  static const String rank_charm_rank_header_bg_webp =
      'assets/images/rank/charm_rank_header_bg.webp';
  static const String rank$rank_charm_rank_header_bg_webp =
      'packages/rank/assets/images/rank/charm_rank_header_bg.webp';

  static const String rank_charm_rank_header_bg_dark_webp =
      'assets/images/rank/charm_rank_header_bg_dark.webp';
  static const String rank$rank_charm_rank_header_bg_dark_webp =
      'packages/rank/assets/images/rank/charm_rank_header_bg_dark.webp';

  static const String rank_ic_arrowup_svg = 'assets/images/rank/ic_arrowup.svg';
  static const String rank$rank_ic_arrowup_svg =
      'packages/rank/assets/images/rank/ic_arrowup.svg';

  static const String rank_ic_companion_rank_menu_png =
      'assets/images/rank/ic_companion_rank_menu.png';
  static const String rank$rank_ic_companion_rank_menu_png =
      'packages/rank/assets/images/rank/ic_companion_rank_menu.png';

  static const String rank_ic_rank_talent_webp =
      'assets/images/rank/ic_rank_talent.webp';
  static const String rank$rank_ic_rank_talent_webp =
      'packages/rank/assets/images/rank/ic_rank_talent.webp';

  static const String rank_impression_tag_rank_bg_webp =
      'assets/images/rank/impression_tag_rank_bg.webp';
  static const String rank$rank_impression_tag_rank_bg_webp =
      'packages/rank/assets/images/rank/impression_tag_rank_bg.webp';

  static const String rank_impression_tag_rank_top_bg_png =
      'assets/images/rank/impression_tag_rank_top_bg.png';
  static const String rank$rank_impression_tag_rank_top_bg_png =
      'packages/rank/assets/images/rank/impression_tag_rank_top_bg.png';

  static const String rank_knight_rank_header_bg_webp =
      'assets/images/rank/knight_rank_header_bg.webp';
  static const String rank$rank_knight_rank_header_bg_webp =
      'packages/rank/assets/images/rank/knight_rank_header_bg.webp';

  static const String rank_package_png = 'assets/images/rank/package.png';
  static const String rank$rank_package_png =
      'packages/rank/assets/images/rank/package.png';

  // static String rank_rank_x_png(Object p0) =>
  //     'assets/images/rank/rank_${p0.toString()}.png';


  static String rank_rank_x_png(Object p0) =>
      'packages/message/assets/images/ic_rank_${p0}.png';

  static String rank$rank_rank_x_png(Object p0) =>
      'packages/rank/assets/images/rank/rank_${p0.toString()}.png';

  static String rank_rank_big_x_png(Object p0) =>
      'assets/images/rank/rank_big_${p0.toString()}.png';

  static String rank$rank_rank_big_x_png(Object p0) =>
      'packages/rank/assets/images/rank/rank_big_${p0.toString()}.png';

  static const String rank_rank_celebrity_item_bg_webp =
      'assets/images/rank/rank_celebrity_item_bg.webp';
  static const String rank$rank_rank_celebrity_item_bg_webp =
      'packages/rank/assets/images/rank/rank_celebrity_item_bg.webp';

  static const String rank_rank_clock_webp =
      'assets/images/rank/rank_clock.webp';
  static const String rank$rank_rank_clock_webp =
      'packages/rank/assets/images/rank/rank_clock.webp';

  static const String rank_rank_last_week_star_banner_bg_webp =
      'assets/images/rank/rank_last_week_star_banner_bg.webp';
  static const String rank$rank_rank_last_week_star_banner_bg_webp =
      'packages/rank/assets/images/rank/rank_last_week_star_banner_bg.webp';

  static const String rank_ranking_knight_group_rule_webp =
      'assets/images/rank/ranking_knight_group_rule.webp';
  static const String rank$rank_ranking_knight_group_rule_webp =
      'packages/rank/assets/images/rank/ranking_knight_group_rule.webp';

  static const String rank_top_icon1_png = 'assets/images/rank/top_icon1.png';
  static const String rank$rank_top_icon1_png =
      'packages/rank/assets/images/rank/top_icon1.png';

  static const String rank_top_icon2_png = 'assets/images/rank/top_icon2.png';
  static const String rank$rank_top_icon2_png =
      'packages/rank/assets/images/rank/top_icon2.png';

  static const String rank_top_icon3_png = 'assets/images/rank/top_icon3.png';
  static const String rank$rank_top_icon3_png =
      'packages/rank/assets/images/rank/top_icon3.png';

  static const String rank_top_icon4_png = 'assets/images/rank/top_icon4.png';
  static const String rank$rank_top_icon4_png =
      'packages/rank/assets/images/rank/top_icon4.png';

  static const String rank_top_icon5_png = 'assets/images/rank/top_icon5.png';
  static const String rank$rank_top_icon5_png =
      'packages/rank/assets/images/rank/top_icon5.png';

  static const String rank_top_rank1_png = 'assets/images/rank/top_rank1.png';
  static const String rank$rank_top_rank1_png =
      'packages/rank/assets/images/rank/top_rank1.png';

  static const String rank_top_rank2_png = 'assets/images/rank/top_rank2.png';
  static const String rank$rank_top_rank2_png =
      'packages/rank/assets/images/rank/top_rank2.png';

  static const String rank_top_rank3_png = 'assets/images/rank/top_rank3.png';
  static const String rank$rank_top_rank3_png =
      'packages/rank/assets/images/rank/top_rank3.png';

  static const String rank_week_star_title_bg_svg =
      'assets/images/rank/week_star_title_bg.svg';
  static const String rank$rank_week_star_title_bg_svg =
      'packages/rank/assets/images/rank/week_star_title_bg.svg';

  static const String rank_cp_png = 'assets/images/rank_cp.png';
  static const String rank$rank_cp_png =
      'packages/rank/assets/images/rank_cp.png';

  static const String rank_dialog_close_svg =
      'assets/images/rank_dialog_close.svg';
  static const String rank$rank_dialog_close_svg =
      'packages/rank/assets/images/rank_dialog_close.svg';

  static String rank_entertain_card_nox_webp(Object p0) =>
      'assets/images/rank_entertain_card_no${p0.toString()}.webp';

  static String rank$rank_entertain_card_nox_webp(Object p0) =>
      'packages/rank/assets/images/rank_entertain_card_no${p0.toString()}.webp';

  static const String rank_help_icon_png = 'assets/images/rank_help_icon.png';
  static const String rank$rank_help_icon_png =
      'packages/rank/assets/images/rank_help_icon.png';

  static const String rank_hours_avatar_placeholder_webp =
      'assets/images/rank_hours_avatar_placeholder.webp';
  static const String rank$rank_hours_avatar_placeholder_webp =
      'packages/rank/assets/images/rank_hours_avatar_placeholder.webp';

  static const String rank_hours_crown_webp =
      'assets/images/rank_hours_crown.webp';
  static const String rank$rank_hours_crown_webp =
      'packages/rank/assets/images/rank_hours_crown.webp';

  static const String rank_hours_dialog_bg_webp =
      'assets/images/rank_hours_dialog_bg.webp';
  static const String rank$rank_hours_dialog_bg_webp =
      'packages/rank/assets/images/rank_hours_dialog_bg.webp';

  static const String rank_hours_entrance_countdown_webp =
      'assets/images/rank_hours_entrance_countdown.webp';
  static const String rank$rank_hours_entrance_countdown_webp =
      'packages/rank/assets/images/rank_hours_entrance_countdown.webp';

  static const String rank_hours_entrance_hour_webp =
      'assets/images/rank_hours_entrance_hour.webp';
  static const String rank$rank_hours_entrance_hour_webp =
      'packages/rank/assets/images/rank_hours_entrance_hour.webp';

  static const String rank_hours_entrance_shine_webp =
      'assets/images/rank_hours_entrance_shine.webp';
  static const String rank$rank_hours_entrance_shine_webp =
      'packages/rank/assets/images/rank_hours_entrance_shine.webp';

  static const String rank_hours_honour_top_bg_webp =
      'assets/images/rank_hours_honour_top_bg.webp';
  static const String rank$rank_hours_honour_top_bg_webp =
      'packages/rank/assets/images/rank_hours_honour_top_bg.webp';

  static const String rank_hours_link_bg_webp =
      'assets/images/rank_hours_link_bg.webp';
  static const String rank$rank_hours_link_bg_webp =
      'packages/rank/assets/images/rank_hours_link_bg.webp';

  static const String rank_hours_shine_top_bg_webp =
      'assets/images/rank_hours_shine_top_bg.webp';
  static const String rank$rank_hours_shine_top_bg_webp =
      'packages/rank/assets/images/rank_hours_shine_top_bg.webp';

  static String rank_hours_tabs_x_webp(Object p0) =>
      'assets/images/rank_hours_tabs_${p0.toString()}.webp';

  static String rank$rank_hours_tabs_x_webp(Object p0) =>
      'packages/rank/assets/images/rank_hours_tabs_${p0.toString()}.webp';

  static const String rank_hours_title_webp =
      'assets/images/rank_hours_title.webp';
  static const String rank$rank_hours_title_webp =
      'packages/rank/assets/images/rank_hours_title.webp';

  static const String rank_relation_add_png =
      'assets/images/rank_relation_add.png';
  static const String rank$rank_relation_add_png =
      'packages/rank/assets/images/rank_relation_add.png';

  static const String rank_room_online_user_webp =
      'assets/images/rank_room_online_user.webp';
  static const String rank$rank_room_online_user_webp =
      'packages/rank/assets/images/rank_room_online_user.webp';

  static const String rank_sweet_png = 'assets/images/rank_sweet.png';
  static const String rank$rank_sweet_png =
      'packages/rank/assets/images/rank_sweet.png';

  static const String ranker_bg_webp = 'assets/images/ranker_bg.webp';
  static const String rank$ranker_bg_webp =
      'packages/rank/assets/images/ranker_bg.webp';

  static const String ranking_overlord_decro_png =
      'assets/images/ranking_overlord_decro.png';
  static const String rank$ranking_overlord_decro_png =
      'packages/rank/assets/images/ranking_overlord_decro.png';

  static const String ranking_top_three_second_webp =
      'assets/images/ranking_top_three_second.webp';
  static const String rank$ranking_top_three_second_webp =
      'packages/rank/assets/images/ranking_top_three_second.webp';

  static const String ranking_top_three_top_webp =
      'assets/images/ranking_top_three_top.webp';
  static const String rank$ranking_top_three_top_webp =
      'packages/rank/assets/images/ranking_top_three_top.webp';

  static const String room_hot_svg = 'assets/images/room_hot.svg';
  static const String rank$room_hot_svg =
      'packages/rank/assets/images/room_hot.svg';

  static const String room_little_svg = 'assets/images/room_little.svg';
  static const String rank$room_little_svg =
      'packages/rank/assets/images/room_little.svg';

  static const String room_password_png = 'assets/images/room_password.png';
  static const String rank$room_password_png =
      'packages/rank/assets/images/room_password.png';

  static const String room_rank_banner_bg_webp =
      'assets/images/room_rank_banner_bg.webp';
  static const String rank$room_rank_banner_bg_webp =
      'packages/rank/assets/images/room_rank_banner_bg.webp';

  static const String room_rank_banner_next_webp =
      'assets/images/room_rank_banner_next.webp';
  static const String rank$room_rank_banner_next_webp =
      'packages/rank/assets/images/room_rank_banner_next.webp';

  static const String room_rank_bg_webp = 'assets/images/room_rank_bg.webp';
  static const String rank$room_rank_bg_webp =
      'packages/rank/assets/images/room_rank_bg.webp';

  static const String room_rank_icon_webp = 'assets/images/room_rank_icon.webp';
  static const String rank$room_rank_icon_webp =
      'packages/rank/assets/images/room_rank_icon.webp';

  static const String room_ranking_down_png =
      'assets/images/room_ranking_down.png';
  static const String rank$room_ranking_down_png =
      'packages/rank/assets/images/room_ranking_down.png';

  static const String room_ranking_up_png = 'assets/images/room_ranking_up.png';
  static const String rank$room_ranking_up_png =
      'packages/rank/assets/images/room_ranking_up.png';

  static const String slp_cp_png = 'assets/images/slp_cp.png';
  static const String rank$slp_cp_png =
      'packages/rank/assets/images/slp_cp.png';

  static const String slp_female_png = 'assets/images/slp_female.png';
  static const String rank$slp_female_png =
      'packages/rank/assets/images/slp_female.png';

  static const String slp_male_png = 'assets/images/slp_male.png';
  static const String rank$slp_male_png =
      'packages/rank/assets/images/slp_male.png';

  static const String slp_sweet_png = 'assets/images/slp_sweet.png';
  static const String rank$slp_sweet_png =
      'packages/rank/assets/images/slp_sweet.png';

  static const String title_bg_png = 'assets/images/title_bg.png';
  static const String rank$title_bg_png =
      'packages/rank/assets/images/title_bg.png';

  static const String vip_1_png = 'assets/images/vip/1.png';
  static const String rank$vip_1_png = 'packages/rank/assets/images/vip/1.png';

  static const String vip_10_png = 'assets/images/vip/10.png';
  static const String rank$vip_10_png =
      'packages/rank/assets/images/vip/10.png';

  static const String vip_100_png = 'assets/images/vip/100.png';
  static const String rank$vip_100_png =
      'packages/rank/assets/images/vip/100.png';

  static const String vip_11_png = 'assets/images/vip/11.png';
  static const String rank$vip_11_png =
      'packages/rank/assets/images/vip/11.png';

  static const String vip_12_png = 'assets/images/vip/12.png';
  static const String rank$vip_12_png =
      'packages/rank/assets/images/vip/12.png';

  static const String vip_13_png = 'assets/images/vip/13.png';
  static const String rank$vip_13_png =
      'packages/rank/assets/images/vip/13.png';

  static const String vip_14_png = 'assets/images/vip/14.png';
  static const String rank$vip_14_png =
      'packages/rank/assets/images/vip/14.png';

  static const String vip_15_png = 'assets/images/vip/15.png';
  static const String rank$vip_15_png =
      'packages/rank/assets/images/vip/15.png';

  static const String vip_16_png = 'assets/images/vip/16.png';
  static const String rank$vip_16_png =
      'packages/rank/assets/images/vip/16.png';

  static const String vip_17_png = 'assets/images/vip/17.png';
  static const String rank$vip_17_png =
      'packages/rank/assets/images/vip/17.png';

  static const String vip_18_png = 'assets/images/vip/18.png';
  static const String rank$vip_18_png =
      'packages/rank/assets/images/vip/18.png';

  static const String vip_19_png = 'assets/images/vip/19.png';
  static const String rank$vip_19_png =
      'packages/rank/assets/images/vip/19.png';

  static const String vip_2_png = 'assets/images/vip/2.png';
  static const String rank$vip_2_png = 'packages/rank/assets/images/vip/2.png';

  static const String vip_20_png = 'assets/images/vip/20.png';
  static const String rank$vip_20_png =
      'packages/rank/assets/images/vip/20.png';

  static const String vip_21_png = 'assets/images/vip/21.png';
  static const String rank$vip_21_png =
      'packages/rank/assets/images/vip/21.png';

  static const String vip_22_png = 'assets/images/vip/22.png';
  static const String rank$vip_22_png =
      'packages/rank/assets/images/vip/22.png';

  static const String vip_23_png = 'assets/images/vip/23.png';
  static const String rank$vip_23_png =
      'packages/rank/assets/images/vip/23.png';

  static const String vip_24_png = 'assets/images/vip/24.png';
  static const String rank$vip_24_png =
      'packages/rank/assets/images/vip/24.png';

  static const String vip_25_png = 'assets/images/vip/25.png';
  static const String rank$vip_25_png =
      'packages/rank/assets/images/vip/25.png';

  static const String vip_26_png = 'assets/images/vip/26.png';
  static const String rank$vip_26_png =
      'packages/rank/assets/images/vip/26.png';

  static const String vip_27_png = 'assets/images/vip/27.png';
  static const String rank$vip_27_png =
      'packages/rank/assets/images/vip/27.png';

  static const String vip_28_png = 'assets/images/vip/28.png';
  static const String rank$vip_28_png =
      'packages/rank/assets/images/vip/28.png';

  static const String vip_29_png = 'assets/images/vip/29.png';
  static const String rank$vip_29_png =
      'packages/rank/assets/images/vip/29.png';

  static const String vip_3_png = 'assets/images/vip/3.png';
  static const String rank$vip_3_png = 'packages/rank/assets/images/vip/3.png';

  static const String vip_30_png = 'assets/images/vip/30.png';
  static const String rank$vip_30_png =
      'packages/rank/assets/images/vip/30.png';

  static const String vip_31_png = 'assets/images/vip/31.png';
  static const String rank$vip_31_png =
      'packages/rank/assets/images/vip/31.png';

  static const String vip_32_png = 'assets/images/vip/32.png';
  static const String rank$vip_32_png =
      'packages/rank/assets/images/vip/32.png';

  static const String vip_33_png = 'assets/images/vip/33.png';
  static const String rank$vip_33_png =
      'packages/rank/assets/images/vip/33.png';

  static const String vip_34_png = 'assets/images/vip/34.png';
  static const String rank$vip_34_png =
      'packages/rank/assets/images/vip/34.png';

  static const String vip_35_png = 'assets/images/vip/35.png';
  static const String rank$vip_35_png =
      'packages/rank/assets/images/vip/35.png';

  static const String vip_36_png = 'assets/images/vip/36.png';
  static const String rank$vip_36_png =
      'packages/rank/assets/images/vip/36.png';

  static const String vip_37_png = 'assets/images/vip/37.png';
  static const String rank$vip_37_png =
      'packages/rank/assets/images/vip/37.png';

  static const String vip_38_png = 'assets/images/vip/38.png';
  static const String rank$vip_38_png =
      'packages/rank/assets/images/vip/38.png';

  static const String vip_39_png = 'assets/images/vip/39.png';
  static const String rank$vip_39_png =
      'packages/rank/assets/images/vip/39.png';

  static const String vip_4_png = 'assets/images/vip/4.png';
  static const String rank$vip_4_png = 'packages/rank/assets/images/vip/4.png';

  static const String vip_40_png = 'assets/images/vip/40.png';
  static const String rank$vip_40_png =
      'packages/rank/assets/images/vip/40.png';

  static const String vip_41_png = 'assets/images/vip/41.png';
  static const String rank$vip_41_png =
      'packages/rank/assets/images/vip/41.png';

  static const String vip_42_png = 'assets/images/vip/42.png';
  static const String rank$vip_42_png =
      'packages/rank/assets/images/vip/42.png';

  static const String vip_43_png = 'assets/images/vip/43.png';
  static const String rank$vip_43_png =
      'packages/rank/assets/images/vip/43.png';

  static const String vip_44_png = 'assets/images/vip/44.png';
  static const String rank$vip_44_png =
      'packages/rank/assets/images/vip/44.png';

  static const String vip_45_png = 'assets/images/vip/45.png';
  static const String rank$vip_45_png =
      'packages/rank/assets/images/vip/45.png';

  static const String vip_46_png = 'assets/images/vip/46.png';
  static const String rank$vip_46_png =
      'packages/rank/assets/images/vip/46.png';

  static const String vip_47_png = 'assets/images/vip/47.png';
  static const String rank$vip_47_png =
      'packages/rank/assets/images/vip/47.png';

  static const String vip_48_png = 'assets/images/vip/48.png';
  static const String rank$vip_48_png =
      'packages/rank/assets/images/vip/48.png';

  static const String vip_49_png = 'assets/images/vip/49.png';
  static const String rank$vip_49_png =
      'packages/rank/assets/images/vip/49.png';

  static const String vip_5_png = 'assets/images/vip/5.png';
  static const String rank$vip_5_png = 'packages/rank/assets/images/vip/5.png';

  static const String vip_50_png = 'assets/images/vip/50.png';
  static const String rank$vip_50_png =
      'packages/rank/assets/images/vip/50.png';

  static const String vip_51_png = 'assets/images/vip/51.png';
  static const String rank$vip_51_png =
      'packages/rank/assets/images/vip/51.png';

  static const String vip_52_png = 'assets/images/vip/52.png';
  static const String rank$vip_52_png =
      'packages/rank/assets/images/vip/52.png';

  static const String vip_53_png = 'assets/images/vip/53.png';
  static const String rank$vip_53_png =
      'packages/rank/assets/images/vip/53.png';

  static const String vip_54_png = 'assets/images/vip/54.png';
  static const String rank$vip_54_png =
      'packages/rank/assets/images/vip/54.png';

  static const String vip_55_png = 'assets/images/vip/55.png';
  static const String rank$vip_55_png =
      'packages/rank/assets/images/vip/55.png';

  static const String vip_56_png = 'assets/images/vip/56.png';
  static const String rank$vip_56_png =
      'packages/rank/assets/images/vip/56.png';

  static const String vip_57_png = 'assets/images/vip/57.png';
  static const String rank$vip_57_png =
      'packages/rank/assets/images/vip/57.png';

  static const String vip_58_png = 'assets/images/vip/58.png';
  static const String rank$vip_58_png =
      'packages/rank/assets/images/vip/58.png';

  static const String vip_59_png = 'assets/images/vip/59.png';
  static const String rank$vip_59_png =
      'packages/rank/assets/images/vip/59.png';

  static const String vip_6_png = 'assets/images/vip/6.png';
  static const String rank$vip_6_png = 'packages/rank/assets/images/vip/6.png';

  static const String vip_60_png = 'assets/images/vip/60.png';
  static const String rank$vip_60_png =
      'packages/rank/assets/images/vip/60.png';

  static const String vip_61_png = 'assets/images/vip/61.png';
  static const String rank$vip_61_png =
      'packages/rank/assets/images/vip/61.png';

  static const String vip_62_png = 'assets/images/vip/62.png';
  static const String rank$vip_62_png =
      'packages/rank/assets/images/vip/62.png';

  static const String vip_63_png = 'assets/images/vip/63.png';
  static const String rank$vip_63_png =
      'packages/rank/assets/images/vip/63.png';

  static const String vip_64_png = 'assets/images/vip/64.png';
  static const String rank$vip_64_png =
      'packages/rank/assets/images/vip/64.png';

  static const String vip_65_png = 'assets/images/vip/65.png';
  static const String rank$vip_65_png =
      'packages/rank/assets/images/vip/65.png';

  static const String vip_66_png = 'assets/images/vip/66.png';
  static const String rank$vip_66_png =
      'packages/rank/assets/images/vip/66.png';

  static const String vip_67_png = 'assets/images/vip/67.png';
  static const String rank$vip_67_png =
      'packages/rank/assets/images/vip/67.png';

  static const String vip_68_png = 'assets/images/vip/68.png';
  static const String rank$vip_68_png =
      'packages/rank/assets/images/vip/68.png';

  static const String vip_69_png = 'assets/images/vip/69.png';
  static const String rank$vip_69_png =
      'packages/rank/assets/images/vip/69.png';

  static const String vip_7_png = 'assets/images/vip/7.png';
  static const String rank$vip_7_png = 'packages/rank/assets/images/vip/7.png';

  static const String vip_70_png = 'assets/images/vip/70.png';
  static const String rank$vip_70_png =
      'packages/rank/assets/images/vip/70.png';

  static const String vip_71_png = 'assets/images/vip/71.png';
  static const String rank$vip_71_png =
      'packages/rank/assets/images/vip/71.png';

  static const String vip_72_png = 'assets/images/vip/72.png';
  static const String rank$vip_72_png =
      'packages/rank/assets/images/vip/72.png';

  static const String vip_73_png = 'assets/images/vip/73.png';
  static const String rank$vip_73_png =
      'packages/rank/assets/images/vip/73.png';

  static const String vip_74_png = 'assets/images/vip/74.png';
  static const String rank$vip_74_png =
      'packages/rank/assets/images/vip/74.png';

  static const String vip_75_png = 'assets/images/vip/75.png';
  static const String rank$vip_75_png =
      'packages/rank/assets/images/vip/75.png';

  static const String vip_76_png = 'assets/images/vip/76.png';
  static const String rank$vip_76_png =
      'packages/rank/assets/images/vip/76.png';

  static const String vip_77_png = 'assets/images/vip/77.png';
  static const String rank$vip_77_png =
      'packages/rank/assets/images/vip/77.png';

  static const String vip_78_png = 'assets/images/vip/78.png';
  static const String rank$vip_78_png =
      'packages/rank/assets/images/vip/78.png';

  static const String vip_79_png = 'assets/images/vip/79.png';
  static const String rank$vip_79_png =
      'packages/rank/assets/images/vip/79.png';

  static const String vip_8_png = 'assets/images/vip/8.png';
  static const String rank$vip_8_png = 'packages/rank/assets/images/vip/8.png';

  static const String vip_80_png = 'assets/images/vip/80.png';
  static const String rank$vip_80_png =
      'packages/rank/assets/images/vip/80.png';

  static const String vip_81_png = 'assets/images/vip/81.png';
  static const String rank$vip_81_png =
      'packages/rank/assets/images/vip/81.png';

  static const String vip_82_png = 'assets/images/vip/82.png';
  static const String rank$vip_82_png =
      'packages/rank/assets/images/vip/82.png';

  static const String vip_83_png = 'assets/images/vip/83.png';
  static const String rank$vip_83_png =
      'packages/rank/assets/images/vip/83.png';

  static const String vip_84_png = 'assets/images/vip/84.png';
  static const String rank$vip_84_png =
      'packages/rank/assets/images/vip/84.png';

  static const String vip_85_png = 'assets/images/vip/85.png';
  static const String rank$vip_85_png =
      'packages/rank/assets/images/vip/85.png';

  static const String vip_86_png = 'assets/images/vip/86.png';
  static const String rank$vip_86_png =
      'packages/rank/assets/images/vip/86.png';

  static const String vip_87_png = 'assets/images/vip/87.png';
  static const String rank$vip_87_png =
      'packages/rank/assets/images/vip/87.png';

  static const String vip_88_png = 'assets/images/vip/88.png';
  static const String rank$vip_88_png =
      'packages/rank/assets/images/vip/88.png';

  static const String vip_89_png = 'assets/images/vip/89.png';
  static const String rank$vip_89_png =
      'packages/rank/assets/images/vip/89.png';

  static const String vip_9_png = 'assets/images/vip/9.png';
  static const String rank$vip_9_png = 'packages/rank/assets/images/vip/9.png';

  static const String vip_90_png = 'assets/images/vip/90.png';
  static const String rank$vip_90_png =
      'packages/rank/assets/images/vip/90.png';

  static const String vip_91_png = 'assets/images/vip/91.png';
  static const String rank$vip_91_png =
      'packages/rank/assets/images/vip/91.png';

  static const String vip_92_png = 'assets/images/vip/92.png';
  static const String rank$vip_92_png =
      'packages/rank/assets/images/vip/92.png';

  static const String vip_93_png = 'assets/images/vip/93.png';
  static const String rank$vip_93_png =
      'packages/rank/assets/images/vip/93.png';

  static const String vip_94_png = 'assets/images/vip/94.png';
  static const String rank$vip_94_png =
      'packages/rank/assets/images/vip/94.png';

  static const String vip_95_png = 'assets/images/vip/95.png';
  static const String rank$vip_95_png =
      'packages/rank/assets/images/vip/95.png';

  static const String vip_96_png = 'assets/images/vip/96.png';
  static const String rank$vip_96_png =
      'packages/rank/assets/images/vip/96.png';

  static const String vip_97_png = 'assets/images/vip/97.png';
  static const String rank$vip_97_png =
      'packages/rank/assets/images/vip/97.png';

  static const String vip_98_png = 'assets/images/vip/98.png';
  static const String rank$vip_98_png =
      'packages/rank/assets/images/vip/98.png';

  static const String vip_99_png = 'assets/images/vip/99.png';
  static const String rank$vip_99_png =
      'packages/rank/assets/images/vip/99.png';

  static const String wedding_item_bg_webp =
      'assets/images/wedding_item_bg.webp';
  static const String rank$wedding_item_bg_webp =
      'packages/rank/assets/images/wedding_item_bg.webp';

  static const String rank_screen_bg = 'assets/images/rank_screen_bg.png';
  static const String rank$rank_screen_bg =
      'packages/rank/assets/images/rank_screen_bg.png';

  static const String nomal_rang_bottom_bg =
      'assets/images/nomal_rang_bottom_bg.png';
  static const String rank$nomal_rang_bottom_bg =
      'packages/rank/assets/images/nomal_rang_bottom_bg.png';

  static const String nomal_rank_middle_bg =
      'assets/images/nomal_rank_middle_bg.png';
  static const String rank$nomal_rank_middle_bg =
      'packages/rank/assets/images/nomal_rank_middle_bg.png';

  static const String rank_vip_guizu_bg = 'assets/images/rank_vip_guizu_bg.png';
  static const String rank$rank_vip_guizu_bg =
      'packages/rank/assets/images/rank_vip_guizu_bg.png';

  static const String rank_bg_vip_gui_bottom_bg =
      'assets/images/rank_bg_vip_gui_bottom_bg.png';
  static const String rank$rank_bg_vip_gui_bottom_bg =
      'packages/rank/assets/images/rank_bg_vip_gui_bottom_bg.png';

  static const String ranking_main_bg = 'assets/images/ranking_main_bg.png';
  static const String rank$ranking_main_bg =
      'packages/rank/assets/images/ranking_main_bg.png';
}
