// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 19.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'certificate';

  static const String audio_png = 'assets/images/audio.png';
  static const String certificate$audio_png =
      'packages/certificate/assets/images/audio.png';

  static const String certificate_addpic_png =
      'assets/images/certificate_addpic.png';
  static const String certificate$certificate_addpic_png =
      'packages/certificate/assets/images/certificate_addpic.png';

  static const String certificate_wait_webp =
      'assets/images/certificate_wait.webp';
  static const String certificate$certificate_wait_webp =
      'packages/certificate/assets/images/certificate_wait.webp';

  static const String certify_quote1_svg = 'assets/images/certify_quote1.svg';
  static const String certificate$certify_quote1_svg =
      'packages/certificate/assets/images/certify_quote1.svg';

  static const String certify_quote2_svg = 'assets/images/certify_quote2.svg';
  static const String certificate$certify_quote2_svg =
      'packages/certificate/assets/images/certify_quote2.svg';

  static String error_demo_error_demox_webp(Object p0) =>
      'assets/images/error_demo/error_demo${p0.toString()}.webp';

  static String certificate$error_demo_error_demox_webp(Object p0) =>
      'packages/certificate/assets/images/error_demo/error_demo${p0.toString()}.webp';

  static const String ic_add_skill_svg = 'assets/images/ic_add_skill.svg';
  static const String certificate$ic_add_skill_svg =
      'packages/certificate/assets/images/ic_add_skill.svg';

  static const String ic_close_svg = 'assets/images/ic_close.svg';
  static const String certificate$ic_close_svg =
      'packages/certificate/assets/images/ic_close.svg';

  static const String ic_delete_svg = 'assets/images/ic_delete.svg';
  static const String certificate$ic_delete_svg =
      'packages/certificate/assets/images/ic_delete.svg';

  static const String ic_next_small_svg = 'assets/images/ic_next_small.svg';
  static const String certificate$ic_next_small_svg =
      'packages/certificate/assets/images/ic_next_small.svg';

  static const String ic_play_svg = 'assets/images/ic_play.svg';
  static const String certificate$ic_play_svg =
      'packages/certificate/assets/images/ic_play.svg';

  static const String ic_quote_webp = 'assets/images/ic_quote.webp';
  static const String certificate$ic_quote_webp =
      'packages/certificate/assets/images/ic_quote.webp';

  static const String ic_select_svg = 'assets/images/ic_select.svg';
  static const String certificate$ic_select_svg =
      'packages/certificate/assets/images/ic_select.svg';

  static const String ic_skill_verify_svg = 'assets/images/ic_skill_verify.svg';
  static const String certificate$ic_skill_verify_svg =
      'packages/certificate/assets/images/ic_skill_verify.svg';

  static const String ic_stop_svg = 'assets/images/ic_stop.svg';
  static const String certificate$ic_stop_svg =
      'packages/certificate/assets/images/ic_stop.svg';

  static const String ic_tips_webp = 'assets/images/ic_tips.webp';
  static const String certificate$ic_tips_webp =
      'packages/certificate/assets/images/ic_tips.webp';

  static const String ic_voice_svg = 'assets/images/ic_voice.svg';
  static const String certificate$ic_voice_svg =
      'packages/certificate/assets/images/ic_voice.svg';

  static const String icon_edit_png = 'assets/images/icon_edit.png';
  static const String certificate$icon_edit_png =
      'packages/certificate/assets/images/icon_edit.png';

  static const String icon_voice_png = 'assets/images/icon_voice.png';
  static const String certificate$icon_voice_png =
      'packages/certificate/assets/images/icon_voice.png';
}
