name: rank
description: A new Flutter package.
version: 0.0.2

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared:
    path: ../shared

  chat_room:
    path: ../chat_room

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  assets_gen: ^1.5.0
  flutter_lints: ^2.0.2

assets_gen:
  omit_path_levels: 2
  plurals:
    - assets/images/rank_entertain_card_no?.webp
    - assets/images/gift_week/rank?.webp
    - assets/images/rank/charm_achieve_rank_header_dark_?.webp
    - assets/images/rank/charm_achieve_rank_header_?.webp
    - assets/images/rank/charm_achieve_rank_?.webp
    - assets/images/rank/rank_big_?.png
    - assets/images/rank/rank_?.png
    - assets/images/rank_hours_tabs_?.webp

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/rank/
    - assets/images/pk/
    - assets/images/god/
    - assets/images/gift_week/
    - assets/images/topbar/
