name: video
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared:
    path: ../shared

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  assets_gen: ^1.5.0

assets_gen:
  omit_path_levels: 2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
