// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 124.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'profile';

  static const String bg_ani_sign_reward_webp =
      'assets/images/bg_ani_sign_reward.webp';
  static const String profile$bg_ani_sign_reward_webp =
      'packages/profile/assets/images/bg_ani_sign_reward.webp';

  static const String bg_gs_task_header_webp =
      'assets/images/bg_gs_task_header.webp';
  static const String profile$bg_gs_task_header_webp =
      'packages/profile/assets/images/bg_gs_task_header.webp';

  static const String bg_header_webp = 'assets/images/bg_header.webp';
  static const String profile$bg_header_webp =
      'packages/profile/assets/images/bg_header.webp';

  static const String bg_reception_img_webp =
      'assets/images/bg_reception_img.webp';
  static const String profile$bg_reception_img_webp =
      'packages/profile/assets/images/bg_reception_img.webp';

  static const String default_avatar_svg = 'assets/images/default_avatar.svg';
  static const String profile$default_avatar_svg =
      'packages/profile/assets/images/default_avatar.svg';

  static const String goldImage_png = 'assets/images/goldImage.png';
  static const String profile$goldImage_png =
      'packages/profile/assets/images/goldImage.png';

  static const String gs_task_level_doing_webp =
      'assets/images/gs_task_level_doing.webp';
  static const String profile$gs_task_level_doing_webp =
      'packages/profile/assets/images/gs_task_level_doing.webp';

  static const String gs_task_level_done_webp =
      'assets/images/gs_task_level_done.webp';
  static const String profile$gs_task_level_done_webp =
      'packages/profile/assets/images/gs_task_level_done.webp';

  static const String gs_task_level_future_webp =
      'assets/images/gs_task_level_future.webp';
  static const String profile$gs_task_level_future_webp =
      'packages/profile/assets/images/gs_task_level_future.webp';

  static const String ic_activity_svg = 'assets/images/ic_activity.svg';
  static const String profile$ic_activity_svg =
      'packages/profile/assets/images/ic_activity.svg';

  static const String ic_anchor_task_detail_webp =
      'assets/images/ic_anchor_task_detail.webp';
  static const String profile$ic_anchor_task_detail_webp =
      'packages/profile/assets/images/ic_anchor_task_detail.webp';

  static const String ic_anchor_task_list_webp =
      'assets/images/ic_anchor_task_list.webp';
  static const String profile$ic_anchor_task_list_webp =
      'packages/profile/assets/images/ic_anchor_task_list.webp';

  static const String ic_anchor_task_main_webp =
      'assets/images/ic_anchor_task_main.webp';
  static const String profile$ic_anchor_task_main_webp =
      'packages/profile/assets/images/ic_anchor_task_main.webp';

  static const String ic_anchor_task_modify_webp =
      'assets/images/ic_anchor_task_modify.webp';
  static const String profile$ic_anchor_task_modify_webp =
      'packages/profile/assets/images/ic_anchor_task_modify.webp';

  static const String ic_app_review_svg = 'assets/images/ic_app_review.svg';
  static const String profile$ic_app_review_svg =
      'packages/profile/assets/images/ic_app_review.svg';

  static const String ic_arrow_right_svg = 'assets/images/ic_arrow_right.svg';
  static const String profile$ic_arrow_right_svg =
      'packages/profile/assets/images/ic_arrow_right.svg';

  static const String ic_checkbox_selected_webp =
      'assets/images/ic_checkbox_selected.webp';
  static const String profile$ic_checkbox_selected_webp =
      'packages/profile/assets/images/ic_checkbox_selected.webp';

  static const String ic_companion_help_svg =
      'assets/images/ic_companion_help.svg';
  static const String profile$ic_companion_help_svg =
      'packages/profile/assets/images/ic_companion_help.svg';

  static const String ic_contact_svg = 'assets/images/ic_contact.svg';
  static const String profile$ic_contact_svg =
      'packages/profile/assets/images/ic_contact.svg';

  static const String ic_contribute_svg = 'assets/images/ic_contribute.svg';
  static const String profile$ic_contribute_svg =
      'packages/profile/assets/images/ic_contribute.svg';

  static const String ic_copy_svg = 'assets/images/ic_copy.svg';
  static const String profile$ic_copy_svg =
      'packages/profile/assets/images/ic_copy.svg';

  static const String ic_count_bg_png = 'assets/images/ic_count_bg.png';
  static const String profile$ic_count_bg_png =
      'packages/profile/assets/images/ic_count_bg.png';

  static const String ic_create_tour_svg = 'assets/images/ic_create_tour.svg';
  static const String profile$ic_create_tour_svg =
      'packages/profile/assets/images/ic_create_tour.svg';

  static const String ic_encounter_third_svg =
      'assets/images/ic_encounter_third.svg';
  static const String profile$ic_encounter_third_svg =
      'packages/profile/assets/images/ic_encounter_third.svg';

  static const String ic_exchange_code_webp =
      'assets/images/ic_exchange_code.webp';
  static const String profile$ic_exchange_code_webp =
      'packages/profile/assets/images/ic_exchange_code.webp';

  static const String ic_gift_code_webp = 'assets/images/ic_gift_code.webp';
  static const String profile$ic_gift_code_webp =
      'packages/profile/assets/images/ic_gift_code.webp';

  static const String ic_god_svg = 'assets/images/ic_god.svg';
  static const String profile$ic_god_svg =
      'packages/profile/assets/images/ic_god.svg';

  static const String ic_gstask_svg = 'assets/images/ic_gstask.svg';
  static const String profile$ic_gstask_svg =
      'packages/profile/assets/images/ic_gstask.svg';

  static const String ic_help_svg = 'assets/images/ic_help.svg';
  static const String profile$ic_help_svg =
      'packages/profile/assets/images/ic_help.svg';

  static const String ic_home_bind_phone_webp =
      'assets/images/ic_home_bind_phone.webp';
  static const String profile$ic_home_bind_phone_webp =
      'packages/profile/assets/images/ic_home_bind_phone.webp';

  static const String ic_home_bind_phone_dark_webp =
      'assets/images/ic_home_bind_phone_dark.webp';
  static const String profile$ic_home_bind_phone_dark_webp =
      'packages/profile/assets/images/ic_home_bind_phone_dark.webp';

  static const String ic_home_settings_webp =
      'assets/images/ic_home_settings.webp';
  static const String profile$ic_home_settings_webp =
      'packages/profile/assets/images/ic_home_settings.webp';
  static const String profile$ic_home_settings_png =
      'packages/profile/assets/images/ic_home_settings.png';

  static const String ic_home_settings_dark_webp =
      'assets/images/ic_home_settings_dark.webp';
  static const String profile$ic_home_settings_dark_webp =
      'packages/profile/assets/images/ic_home_settings_dark.webp';

  static const String ic_id_svg = 'assets/images/ic_id.svg';
  static const String profile$ic_id_svg =
      'packages/profile/assets/images/ic_id.svg';

  static const String ic_invite_svg = 'assets/images/ic_invite.svg';
  static const String profile$ic_invite_svg =
      'packages/profile/assets/images/ic_invite.svg';

  static const String ic_invite_user_id_png =
      'assets/images/ic_invite_user_id.png';
  static const String profile$ic_invite_user_id_png =
      'packages/profile/assets/images/ic_invite_user_id.png';

  static const String ic_language_svg = 'assets/images/ic_language.svg';
  static const String profile$ic_language_svg =
      'packages/profile/assets/images/ic_language.svg';

  static const String ic_launch_audio_png = 'assets/images/ic_launch_audio.png';
  static const String profile$ic_launch_audio_png =
      'packages/profile/assets/images/ic_launch_audio.png';

  static const String ic_mission_center_svg =
      'assets/images/ic_mission_center.svg';
  static const String profile$ic_mission_center_svg =
      'packages/profile/assets/images/ic_mission_center.svg';

  static const String ic_my_bag_svg = 'assets/images/ic_my_bag.svg';
  static const String profile$ic_my_bag_svg =
      'packages/profile/assets/images/ic_my_bag.svg';

  static const String ic_my_level_svg = 'assets/images/ic_my_level.svg';
  static const String profile$ic_my_level_svg =
      'packages/profile/assets/images/ic_my_level.svg';

  static const String ic_new_webp = 'assets/images/ic_new.webp';
  static const String profile$ic_new_webp =
      'packages/profile/assets/images/ic_new.webp';

  static const String ic_new_user_rank_svg =
      'assets/images/ic_new_user_rank.svg';
  static const String profile$ic_new_user_rank_svg =
      'packages/profile/assets/images/ic_new_user_rank.svg';

  static const String ic_next_svg = 'assets/images/ic_next.svg';
  static const String profile$ic_next_svg =
      'packages/profile/assets/images/ic_next.svg';

  static const String ic_next_webp = 'assets/images/ic_next.webp';
  static const String profile$ic_next_webp =
      'packages/profile/assets/images/ic_next.webp';

  static const String ic_next_small_png = 'assets/images/ic_next_small.png';
  static const String profile$ic_next_small_png =
      'packages/profile/assets/images/ic_next_small.png';

  static const String ic_open_invite_svg = 'assets/images/ic_open_invite.svg';
  static const String profile$ic_open_invite_svg =
      'packages/profile/assets/images/ic_open_invite.svg';

  static const String ic_order_svg = 'assets/images/ic_order.svg';
  static const String profile$ic_order_svg =
      'packages/profile/assets/images/ic_order.svg';

  static const String ic_popularity_svg = 'assets/images/ic_popularity.svg';
  static const String profile$ic_popularity_svg =
      'packages/profile/assets/images/ic_popularity.svg';

  static const String ic_pretty_id_add_webp =
      'assets/images/ic_pretty_id_add.webp';
  static const String profile$ic_pretty_id_add_webp =
      'packages/profile/assets/images/ic_pretty_id_add.webp';

  static const String ic_profile_accost_svg =
      'assets/images/ic_profile_accost.svg';
  static const String profile$ic_profile_accost_svg =
      'packages/profile/assets/images/ic_profile_accost.svg';

  static const String ic_profile_accost_photo_svg =
      'assets/images/ic_profile_accost_photo.svg';
  static const String profile$ic_profile_accost_photo_svg =
      'packages/profile/assets/images/ic_profile_accost_photo.svg';

  static const String ic_profile_admin_dashboard_svg =
      'assets/images/ic_profile_admin_dashboard.svg';
  static const String profile$ic_profile_admin_dashboard_svg =
      'packages/profile/assets/images/ic_profile_admin_dashboard.svg';

  static const String ic_profile_anchor_center_svg =
      'assets/images/ic_profile_anchor_center.svg';
  static const String profile$ic_profile_anchor_center_svg =
      'packages/profile/assets/images/ic_profile_anchor_center.svg';

  static const String ic_profile_anchor_task_svg =
      'assets/images/ic_profile_anchor_task.svg';
  static const String profile$ic_profile_anchor_task_svg =
      'packages/profile/assets/images/ic_profile_anchor_task.svg';

  static const String ic_profile_auth_center_svg =
      'assets/images/ic_profile_auth_center.svg';
  static const String profile$ic_profile_auth_center_svg =
      'packages/profile/assets/images/ic_profile_auth_center.svg';

  static const String ic_profile_credit_svg =
      'assets/images/ic_profile_credit.svg';
  static const String profile$ic_profile_credit_svg =
      'packages/profile/assets/images/ic_profile_credit.svg';

  static const String ic_profile_encounter_svg =
      'assets/images/ic_profile_encounter.svg';
  static const String profile$ic_profile_encounter_svg =
      'packages/profile/assets/images/ic_profile_encounter.svg';

  static const String ic_profile_exclusive_benefit_svg =
      'assets/images/ic_profile_exclusive_benefit.svg';
  static const String profile$ic_profile_exclusive_benefit_svg =
      'packages/profile/assets/images/ic_profile_exclusive_benefit.svg';

  static const String ic_profile_key_svg = 'assets/images/ic_profile_key.svg';
  static const String profile$ic_profile_key_svg =
      'packages/profile/assets/images/ic_profile_key.svg';

  static const String ic_profile_new_user_pay_svg =
      'assets/images/ic_profile_new_user_pay.svg';
  static const String profile$ic_profile_new_user_pay_svg =
      'packages/profile/assets/images/ic_profile_new_user_pay.svg';

  static const String ic_profile_trade_union_settled_webp =
      'assets/images/ic_profile_trade_union_settled.webp';
  static const String profile$ic_profile_trade_union_settled_webp =
      'packages/profile/assets/images/ic_profile_trade_union_settled.webp';

  static const String ic_restore_svg = 'assets/images/ic_restore.svg';
  static const String profile$ic_restore_svg =
      'packages/profile/assets/images/ic_restore.svg';

  static const String ic_room_data_svg = 'assets/images/ic_room_data.svg';
  static const String profile$ic_room_data_svg =
      'packages/profile/assets/images/ic_room_data.svg';

  static const String ic_service_svg = 'assets/images/ic_service.svg';
  static const String profile$ic_service_svg =
      'packages/profile/assets/images/ic_service.svg';

  static const String ic_settings_svg = 'assets/images/ic_settings.svg';
  static const String profile$ic_settings_svg =
      'packages/profile/assets/images/ic_settings.svg';

  static const String ic_sign_close_webp = 'assets/images/ic_sign_close.webp';
  static const String profile$ic_sign_close_webp =
      'packages/profile/assets/images/ic_sign_close.webp';

  static const String ic_sign_day_bg_webp = 'assets/images/ic_sign_day_bg.webp';
  static const String profile$ic_sign_day_bg_webp =
      'packages/profile/assets/images/ic_sign_day_bg.webp';

  static const String ic_sign_in_checked_svg =
      'assets/images/ic_sign_in_checked.svg';
  static const String profile$ic_sign_in_checked_svg =
      'packages/profile/assets/images/ic_sign_in_checked.svg';

  static const String ic_sign_title_bg_png =
      'assets/images/ic_sign_title_bg.png';
  static const String profile$ic_sign_title_bg_png =
      'packages/profile/assets/images/ic_sign_title_bg.png';

  static const String ic_super_admin_svg = 'assets/images/ic_super_admin.svg';
  static const String profile$ic_super_admin_svg =
      'packages/profile/assets/images/ic_super_admin.svg';

  static const String ic_svip_ka_png = 'assets/images/ic_svip_ka.png';
  static const String profile$ic_svip_ka_png =
      'packages/profile/assets/images/ic_svip_ka.png';

  static const String ic_svip_noti_webp = 'assets/images/ic_svip_noti.webp';
  static const String profile$ic_svip_noti_webp =
      'packages/profile/assets/images/ic_svip_noti.webp';

  static const String ic_task_svg = 'assets/images/ic_task.svg';
  static const String profile$ic_task_svg =
      'packages/profile/assets/images/ic_task.svg';

  static const String ic_task_coin_png = 'assets/images/ic_task_coin.png';
  static const String profile$ic_task_coin_png =
      'packages/profile/assets/images/ic_task_coin.png';

  static const String ic_user_transfer_profile_webp =
      'assets/images/ic_user_transfer_profile.webp';
  static const String profile$ic_user_transfer_profile_webp =
      'packages/profile/assets/images/ic_user_transfer_profile.webp';

  static const String ic_vip_mall_svg = 'assets/images/ic_vip_mall.svg';
  static const String profile$ic_vip_mall_svg =
      'packages/profile/assets/images/ic_vip_mall.svg';

  static const String ic_wallet_svg = 'assets/images/ic_wallet.svg';
  static const String profile$ic_wallet_svg =
      'packages/profile/assets/images/ic_wallet.svg';

  static const String icon_check_webp = 'assets/images/icon_check.webp';
  static const String profile$icon_check_webp =
      'packages/profile/assets/images/icon_check.webp';

  static const String icon_wait_webp = 'assets/images/icon_wait.webp';
  static const String profile$icon_wait_webp =
      'packages/profile/assets/images/icon_wait.webp';

  static const String invite_gift_head_bg_webp =
      'assets/images/invite_gift_head_bg.webp';
  static const String profile$invite_gift_head_bg_webp =
      'packages/profile/assets/images/invite_gift_head_bg.webp';

  static const String launch_audio_bg_audio_webp =
      'assets/images/launch_audio/bg_audio.webp';
  static const String profile$launch_audio_bg_audio_webp =
      'packages/profile/assets/images/launch_audio/bg_audio.webp';

  static const String launch_audio_ic_logo_webp =
      'assets/images/launch_audio/ic_logo.webp';
  static const String profile$launch_audio_ic_logo_webp =
      'packages/profile/assets/images/launch_audio/ic_logo.webp';

  static const String launch_audio_ic_selected_webp =
      'assets/images/launch_audio/ic_selected.webp';
  static const String profile$launch_audio_ic_selected_webp =
      'packages/profile/assets/images/launch_audio/ic_selected.webp';

  static const String lovetest_love_test_answer_365_webp =
      'assets/images/lovetest/love_test_answer_365.webp';
  static const String profile$lovetest_love_test_answer_365_webp =
      'packages/profile/assets/images/lovetest/love_test_answer_365.webp';

  static const String lovetest_love_test_answer_face_webp =
      'assets/images/lovetest/love_test_answer_face.webp';
  static const String profile$lovetest_love_test_answer_face_webp =
      'packages/profile/assets/images/lovetest/love_test_answer_face.webp';

  static const String lovetest_love_test_answer_index_bg_webp =
      'assets/images/lovetest/love_test_answer_index_bg.webp';
  static const String profile$lovetest_love_test_answer_index_bg_webp =
      'packages/profile/assets/images/lovetest/love_test_answer_index_bg.webp';

  static const String lovetest_love_test_bg_webp =
      'assets/images/lovetest/love_test_bg.webp';
  static const String profile$lovetest_love_test_bg_webp =
      'packages/profile/assets/images/lovetest/love_test_bg.webp';

  static const String lovetest_love_test_guide_icon_webp =
      'assets/images/lovetest/love_test_guide_icon.webp';
  static const String profile$lovetest_love_test_guide_icon_webp =
      'packages/profile/assets/images/lovetest/love_test_guide_icon.webp';

  static const String lovetest_love_test_mask_webp =
      'assets/images/lovetest/love_test_mask.webp';
  static const String profile$lovetest_love_test_mask_webp =
      'packages/profile/assets/images/lovetest/love_test_mask.webp';

  static const String lovetest_love_test_sayhi_webp =
      'assets/images/lovetest/love_test_sayhi.webp';
  static const String profile$lovetest_love_test_sayhi_webp =
      'packages/profile/assets/images/lovetest/love_test_sayhi.webp';

  static const String lovetest_love_test_share_bg_webp =
      'assets/images/lovetest/love_test_share_bg.webp';
  static const String profile$lovetest_love_test_share_bg_webp =
      'packages/profile/assets/images/lovetest/love_test_share_bg.webp';

  static const String lovetest_love_test_star_webp =
      'assets/images/lovetest/love_test_star.webp';
  static const String profile$lovetest_love_test_star_webp =
      'packages/profile/assets/images/lovetest/love_test_star.webp';

  static const String lovetest_love_test_wow_webp =
      'assets/images/lovetest/love_test_wow.webp';
  static const String profile$lovetest_love_test_wow_webp =
      'packages/profile/assets/images/lovetest/love_test_wow.webp';

  static const String nl_friend_recommend_webp =
      'assets/images/nl_friend_recommend.webp';
  static const String profile$nl_friend_recommend_webp =
      'packages/profile/assets/images/nl_friend_recommend.webp';

  static const String popular_profile_popular_0_png =
      'assets/images/popular/profile_popular_0.png';
  static const String profile$popular_profile_popular_0_png =
      'packages/profile/assets/images/popular/profile_popular_0.png';

  static const String popular_profile_popular_1_png =
      'assets/images/popular/profile_popular_1.png';
  static const String profile$popular_profile_popular_1_png =
      'packages/profile/assets/images/popular/profile_popular_1.png';

  static const String popular_profile_popular_2_png =
      'assets/images/popular/profile_popular_2.png';
  static const String profile$popular_profile_popular_2_png =
      'packages/profile/assets/images/popular/profile_popular_2.png';

  static const String popular_profile_popular_3_png =
      'assets/images/popular/profile_popular_3.png';
  static const String profile$popular_profile_popular_3_png =
      'packages/profile/assets/images/popular/profile_popular_3.png';

  static const String popular_profile_popular_4_png =
      'assets/images/popular/profile_popular_4.png';
  static const String profile$popular_profile_popular_4_png =
      'packages/profile/assets/images/popular/profile_popular_4.png';

  static const String popular_profile_popular_5_png =
      'assets/images/popular/profile_popular_5.png';
  static const String profile$popular_profile_popular_5_png =
      'packages/profile/assets/images/popular/profile_popular_5.png';

  static const String profile_bg_task_webp =
      'assets/images/profile_bg_task.webp';
  static const String profile$profile_bg_task_webp =
      'packages/profile/assets/images/profile_bg_task.webp';

  static const String profile_bubble_triangle_png =
      'assets/images/profile_bubble_triangle.png';
  static const String profile$profile_bubble_triangle_png =
      'packages/profile/assets/images/profile_bubble_triangle.png';

  static const String profile_ic_bubble_png =
      'assets/images/profile_ic_bubble.png';
  static const String profile$profile_ic_bubble_png =
      'packages/profile/assets/images/profile_ic_bubble.png';

  static const String profile_ic_will_task_png =
      'assets/images/profile_ic_will_task.png';
  static const String profile$profile_ic_will_task_png =
      'packages/profile/assets/images/profile_ic_will_task.png';

  static const String profile_recommend_gs_tag_bg_0_webp =
      'assets/images/profile_recommend_gs_tag_bg_0.webp';
  static const String profile$profile_recommend_gs_tag_bg_0_webp =
      'packages/profile/assets/images/profile_recommend_gs_tag_bg_0.webp';

  static const String profile_recommend_gs_tag_bg_1_webp =
      'assets/images/profile_recommend_gs_tag_bg_1.webp';
  static const String profile$profile_recommend_gs_tag_bg_1_webp =
      'packages/profile/assets/images/profile_recommend_gs_tag_bg_1.webp';

  static const String profile_recommend_gs_tag_bg_2_webp =
      'assets/images/profile_recommend_gs_tag_bg_2.webp';
  static const String profile$profile_recommend_gs_tag_bg_2_webp =
      'packages/profile/assets/images/profile_recommend_gs_tag_bg_2.webp';

  static const String profile_task_center_bg_png =
      'assets/images/profile_task_center_bg.png';
  static const String profile$profile_task_center_bg_png =
      'packages/profile/assets/images/profile_task_center_bg.png';

  static const String profile_task_title_png =
      'assets/images/profile_task_title.png';
  static const String profile$profile_task_title_png =
      'packages/profile/assets/images/profile_task_title.png';

  static const String vip_profile_vip_0_png =
      'assets/images/vip/profile_vip_0.png';
  static const String profile$vip_profile_vip_0_png =
      'packages/profile/assets/images/vip/profile_vip_0.png';

  static const String vip_profile_vip_1_png =
      'assets/images/vip/profile_vip_1.png';
  static const String profile$vip_profile_vip_1_png =
      'packages/profile/assets/images/vip/profile_vip_1.png';

  static const String vip_profile_vip_2_png =
      'assets/images/vip/profile_vip_2.png';
  static const String profile$vip_profile_vip_2_png =
      'packages/profile/assets/images/vip/profile_vip_2.png';

  static const String vip_profile_vip_3_png =
      'assets/images/vip/profile_vip_3.png';
  static const String profile$vip_profile_vip_3_png =
      'packages/profile/assets/images/vip/profile_vip_3.png';

  static const String vip_profile_vip_4_png =
      'assets/images/vip/profile_vip_4.png';
  static const String profile$vip_profile_vip_4_png =
      'packages/profile/assets/images/vip/profile_vip_4.png';

  static const String vip_profile_vip_5_png =
      'assets/images/vip/profile_vip_5.png';
  static const String profile$vip_profile_vip_5_png =
      'packages/profile/assets/images/vip/profile_vip_5.png';

  static const String vip_profile_vip_6_png =
      'assets/images/vip/profile_vip_6.png';
  static const String profile$vip_profile_vip_6_png =
      'packages/profile/assets/images/vip/profile_vip_6.png';

  static const String vip_profile_vip_7_png =
      'assets/images/vip/profile_vip_7.png';
  static const String profile$vip_profile_vip_7_png =
      'packages/profile/assets/images/vip/profile_vip_7.png';

  static const String vip_profile_vip_8_png =
      'assets/images/vip/profile_vip_8.png';
  static const String profile$vip_profile_vip_8_png =
      'packages/profile/assets/images/vip/profile_vip_8.png';

  static const String voice_auth_bg_record_female_webp =
      'assets/images/voice_auth/bg_record_female.webp';
  static const String profile$voice_auth_bg_record_female_webp =
      'packages/profile/assets/images/voice_auth/bg_record_female.webp';

  static const String voice_auth_bg_record_male_webp =
      'assets/images/voice_auth/bg_record_male.webp';
  static const String profile$voice_auth_bg_record_male_webp =
      'packages/profile/assets/images/voice_auth/bg_record_male.webp';

  static const String voice_auth_ic_sex_female_webp =
      'assets/images/voice_auth/ic_sex_female.webp';
  static const String profile$voice_auth_ic_sex_female_webp =
      'packages/profile/assets/images/voice_auth/ic_sex_female.webp';

  static const String voice_auth_ic_sex_male_webp =
      'assets/images/voice_auth/ic_sex_male.webp';
  static const String profile$voice_auth_ic_sex_male_webp =
      'packages/profile/assets/images/voice_auth/ic_sex_male.webp';

  static const String mine_icon_top_left =
      'assets/images/mine_icon_top_left.png';
  static const String profile$mine_icon_top_left =
      'packages/profile/assets/images/mine_icon_top_left.png';

  static const String guizu_icon_vip = 'assets/images/guizu_icon_vip.png';
  static const String profile$guizu_icon_vip =
      'packages/profile/assets/images/guizu_icon_vip.png';

  static const String img_vip_guizu_icon =
      'assets/images/img_vip_guizu_icon.png';
  static const String profile$img_vip_guizu_icon =
      'packages/profile/assets/images/img_vip_guizu_icon.png';

  static const String profile$wallet_item_bg_webp =
      'packages/profile/assets/images/wallet_item_bg.webp';

  static const String profile$vip_item_bg_webp =
      'packages/profile/assets/images/vip_item_bg.webp';

  static const String profile$right_arrow_png =
      'packages/profile/assets/images/right_arrow.png';
}
