name: ota_resource_bundle
description: A new Flutter package project.
version: 0.4.2
homepage: "https://github.com/olachat/ota_resource_bundle"

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  archive: ^3.3.2
  collection: ^1.17.0
  crypto: ^3.0.3
  dio: ^5.0.0
  flutter:
    sdk: flutter
  path: ^1.8.2
  path_provider: ^2.1.1
  protobuf: ^3.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  build_runner: ^2.3.0
  faker: ^2.1.0
