// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 157.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'message';

  static const String assets_images_add_friend_change_another_webp =
      'assets/images/add_friend_change_another.webp';
  static const String message$assets_images_add_friend_change_another_webp =
      'packages/message/assets/images/add_friend_change_another.webp';

  static const String assets_images_chat_accost_webp =
      'assets/images/chat_accost.webp';
  static const String message$assets_images_chat_accost_webp =
      'packages/message/assets/images/chat_accost.webp';

  static const String assets_images_chat_birthday_webp =
      'assets/images/chat_birthday.webp';
  static const String message$assets_images_chat_birthday_webp =
      'packages/message/assets/images/chat_birthday.webp';

  static const String assets_images_chat_etc_webp =
      'assets/images/chat_etc.webp';
  static const String message$assets_images_chat_etc_webp =
      'packages/message/assets/images/chat_etc.webp';

  static const String assets_images_chat_etc_dark_webp =
      'assets/images/chat_etc_dark.webp';
  static const String message$assets_images_chat_etc_dark_webp =
      'packages/message/assets/images/chat_etc_dark.webp';

  static const String assets_images_chat_fate_webp =
      'assets/images/chat_fate.webp';
  static const String message$assets_images_chat_fate_webp =
      'packages/message/assets/images/chat_fate.webp';

  static const String assets_images_chat_fate_dark_webp =
      'assets/images/chat_fate_dark.webp';
  static const String message$assets_images_chat_fate_dark_webp =
      'packages/message/assets/images/chat_fate_dark.webp';

  static const String assets_images_chat_hi_webp = 'assets/images/chat_hi.webp';
  static const String message$assets_images_chat_hi_webp =
      'packages/message/assets/images/chat_hi.webp';

  static const String assets_images_chat_hi_dark_webp =
      'assets/images/chat_hi_dark.webp';
  static const String message$assets_images_chat_hi_dark_webp =
      'packages/message/assets/images/chat_hi_dark.webp';

  static const String assets_images_chat_match_webp =
      'assets/images/chat_match.webp';
  static const String message$assets_images_chat_match_webp =
      'packages/message/assets/images/chat_match.webp';

  static const String assets_images_chat_moment_webp =
      'assets/images/chat_moment.webp';
  static const String message$assets_images_chat_moment_webp =
      'packages/message/assets/images/chat_moment.webp';

  static const String assets_images_chat_moment_dark_webp =
      'assets/images/chat_moment_dark.webp';
  static const String message$assets_images_chat_moment_dark_webp =
      'packages/message/assets/images/chat_moment_dark.webp';

  static const String assets_images_chat_notice_webp =
      'assets/images/chat_notice.webp';
  static const String message$assets_images_chat_notice_webp =
      'packages/message/assets/images/chat_notice.webp';

  static const String assets_images_chat_notice_dark_webp =
      'assets/images/chat_notice_dark.webp';
  static const String message$assets_images_chat_notice_dark_webp =
      'packages/message/assets/images/chat_notice_dark.webp';

  static const String assets_images_chat_order_webp =
      'assets/images/chat_order.webp';
  static const String message$assets_images_chat_order_webp =
      'packages/message/assets/images/chat_order.webp';

  static const String assets_images_chat_order_dark_webp =
      'assets/images/chat_order_dark.webp';
  static const String message$assets_images_chat_order_dark_webp =
      'packages/message/assets/images/chat_order_dark.webp';

  static const String assets_images_chat_service_webp =
      'assets/images/chat_service.webp';
  static const String message$assets_images_chat_service_webp =
      'packages/message/assets/images/chat_service.webp';

  static const String assets_images_chat_service_dark_webp =
      'assets/images/chat_service_dark.webp';
  static const String message$assets_images_chat_service_dark_webp =
      'packages/message/assets/images/chat_service_dark.webp';

  static const String assets_images_chat_system_webp =
      'assets/images/chat_system.webp';
  static const String message$assets_images_chat_system_webp =
      'packages/message/assets/images/chat_system.webp';

  static const String assets_images_chat_system_dark_webp =
      'assets/images/chat_system_dark.webp';
  static const String message$assets_images_chat_system_dark_webp =
      'packages/message/assets/images/chat_system_dark.webp';

  static const String assets_images_chat_task_webp =
      'assets/images/chat_task.webp';
  static const String message$assets_images_chat_task_webp =
      'packages/message/assets/images/chat_task.webp';

  static const String assets_images_chat_task_dark_webp =
      'assets/images/chat_task_dark.webp';
  static const String message$assets_images_chat_task_dark_webp =
      'packages/message/assets/images/chat_task_dark.webp';

  static const String assets_images_chat_tempgroup_webp =
      'assets/images/chat_tempgroup.webp';
  static const String message$assets_images_chat_tempgroup_webp =
      'packages/message/assets/images/chat_tempgroup.webp';

  static const String assets_images_chat_tempgroup_dark_webp =
      'assets/images/chat_tempgroup_dark.webp';
  static const String message$assets_images_chat_tempgroup_dark_webp =
      'packages/message/assets/images/chat_tempgroup_dark.webp';

  static const String assets_images_ic_accost_action_webp =
      'assets/images/ic_accost_action.webp';
  static const String message$assets_images_ic_accost_action_webp =
      'packages/message/assets/images/ic_accost_action.webp';

  static const String assets_images_ic_accost_add_image_svg =
      'assets/images/ic_accost_add_image.svg';
  static const String message$assets_images_ic_accost_add_image_svg =
      'packages/message/assets/images/ic_accost_add_image.svg';

  static const String assets_images_ic_accost_add_text_svg =
      'assets/images/ic_accost_add_text.svg';
  static const String message$assets_images_ic_accost_add_text_svg =
      'packages/message/assets/images/ic_accost_add_text.svg';

  static const String assets_images_ic_accost_add_voice_svg =
      'assets/images/ic_accost_add_voice.svg';
  static const String message$assets_images_ic_accost_add_voice_svg =
      'packages/message/assets/images/ic_accost_add_voice.svg';

  static const String assets_images_ic_accost_arrow_svg =
      'assets/images/ic_accost_arrow.svg';
  static const String message$assets_images_ic_accost_arrow_svg =
      'packages/message/assets/images/ic_accost_arrow.svg';

  static const String assets_images_ic_accost_audit_fail_svg =
      'assets/images/ic_accost_audit_fail.svg';
  static const String message$assets_images_ic_accost_audit_fail_svg =
      'packages/message/assets/images/ic_accost_audit_fail.svg';

  static const String assets_images_ic_accost_data_center_webp =
      'assets/images/ic_accost_data_center.webp';
  static const String message$assets_images_ic_accost_data_center_webp =
      'packages/message/assets/images/ic_accost_data_center.webp';

  static const String assets_images_ic_accost_delete_svg =
      'assets/images/ic_accost_delete.svg';
  static const String message$assets_images_ic_accost_delete_svg =
      'packages/message/assets/images/ic_accost_delete.svg';

  static const String assets_images_ic_accost_edit_svg =
      'assets/images/ic_accost_edit.svg';
  static const String message$assets_images_ic_accost_edit_svg =
      'packages/message/assets/images/ic_accost_edit.svg';

  static const String assets_images_ic_accost_empty_png =
      'assets/images/ic_accost_empty.png';
  static const String message$assets_images_ic_accost_empty_png =
      'packages/message/assets/images/ic_accost_empty.png';

  static const String assets_images_ic_accost_help_webp =
      'assets/images/ic_accost_help.webp';
  static const String message$assets_images_ic_accost_help_webp =
      'packages/message/assets/images/ic_accost_help.webp';

  static const String assets_images_ic_accost_image_png =
      'assets/images/ic_accost_image.png';
  static const String message$assets_images_ic_accost_image_png =
      'packages/message/assets/images/ic_accost_image.png';

  static const String assets_images_ic_accost_notify_png =
      'assets/images/ic_accost_notify.png';
  static const String message$assets_images_ic_accost_notify_png =
      'packages/message/assets/images/ic_accost_notify.png';

  static const String assets_images_ic_accost_object_webp =
      'assets/images/ic_accost_object.webp';
  static const String message$assets_images_ic_accost_object_webp =
      'packages/message/assets/images/ic_accost_object.webp';

  static const String assets_images_ic_accost_pause_voice_svg =
      'assets/images/ic_accost_pause_voice.svg';
  static const String message$assets_images_ic_accost_pause_voice_svg =
      'packages/message/assets/images/ic_accost_pause_voice.svg';

  static const String assets_images_ic_accost_play_voice_svg =
      'assets/images/ic_accost_play_voice.svg';
  static const String message$assets_images_ic_accost_play_voice_svg =
      'packages/message/assets/images/ic_accost_play_voice.svg';

  static const String assets_images_ic_accost_rank_webp =
      'assets/images/ic_accost_rank.webp';
  static const String message$assets_images_ic_accost_rank_webp =
      'packages/message/assets/images/ic_accost_rank.webp';

  static const String assets_images_ic_accost_rank_bar_icon_png =
      'assets/images/ic_accost_rank_bar_icon.png';
  static const String message$assets_images_ic_accost_rank_bar_icon_png =
      'packages/message/assets/images/ic_accost_rank_bar_icon.png';

  static const String assets_images_ic_accost_rank_help_svg =
      'assets/images/ic_accost_rank_help.svg';
  static const String message$assets_images_ic_accost_rank_help_svg =
      'packages/message/assets/images/ic_accost_rank_help.svg';

  static const String assets_images_ic_accost_rank_index_1_webp =
      'assets/images/ic_accost_rank_index_1.webp';
  static const String message$assets_images_ic_accost_rank_index_1_webp =
      'packages/message/assets/images/ic_accost_rank_index_1.webp';

  static const String assets_images_ic_accost_rank_index_2_webp =
      'assets/images/ic_accost_rank_index_2.webp';
  static const String message$assets_images_ic_accost_rank_index_2_webp =
      'packages/message/assets/images/ic_accost_rank_index_2.webp';

  static const String assets_images_ic_accost_rank_index_3_webp =
      'assets/images/ic_accost_rank_index_3.webp';
  static const String message$assets_images_ic_accost_rank_index_3_webp =
      'packages/message/assets/images/ic_accost_rank_index_3.webp';

  static const String assets_images_ic_accost_ratio_nor_svg =
      'assets/images/ic_accost_ratio_nor.svg';
  static const String message$assets_images_ic_accost_ratio_nor_svg =
      'packages/message/assets/images/ic_accost_ratio_nor.svg';

  static const String assets_images_ic_accost_ratio_sel_svg =
      'assets/images/ic_accost_ratio_sel.svg';
  static const String message$assets_images_ic_accost_ratio_sel_svg =
      'packages/message/assets/images/ic_accost_ratio_sel.svg';

  static const String assets_images_ic_accost_sort_drag_svg =
      'assets/images/ic_accost_sort_drag.svg';
  static const String message$assets_images_ic_accost_sort_drag_svg =
      'packages/message/assets/images/ic_accost_sort_drag.svg';

  static const String assets_images_ic_accost_sort_top_svg =
      'assets/images/ic_accost_sort_top.svg';
  static const String message$assets_images_ic_accost_sort_top_svg =
      'packages/message/assets/images/ic_accost_sort_top.svg';

  static const String assets_images_ic_accost_text_png =
      'assets/images/ic_accost_text.png';
  static const String message$assets_images_ic_accost_text_png =
      'packages/message/assets/images/ic_accost_text.png';

  static const String assets_images_ic_accost_voice_png =
      'assets/images/ic_accost_voice.png';
  static const String message$assets_images_ic_accost_voice_png =
      'packages/message/assets/images/ic_accost_voice.png';

  static const String assets_images_ic_action_sort_icon_webp =
      'assets/images/ic_action_sort_icon.webp';
  static const String message$assets_images_ic_action_sort_icon_webp =
      'packages/message/assets/images/ic_action_sort_icon.webp';

  static const String assets_images_ic_add_webp = 'assets/images/ic_add.webp';
  static const String message$assets_images_ic_add_webp =
      'packages/message/assets/images/ic_add.webp';

  static const String assets_images_ic_add_dark_webp =
      'assets/images/ic_add_dark.webp';
  static const String message$assets_images_ic_add_dark_webp =
      'packages/message/assets/images/ic_add_dark.webp';

  static const String assets_images_ic_add_friend_svg =
      'assets/images/ic_add_friend.svg';
  static const String message$assets_images_ic_add_friend_svg =
      'packages/message/assets/images/ic_add_friend.svg';

  static const String assets_images_ic_address_book_webp =
      'assets/images/ic_address_book.webp';
  static const String message$assets_images_ic_address_book_webp =
      'packages/message/assets/images/ic_address_book.webp';

  static const String assets_images_ic_agree_normal_png =
      'assets/images/ic_agree_normal.png';
  static const String message$assets_images_ic_agree_normal_png =
      'packages/message/assets/images/ic_agree_normal.png';

  static const String assets_images_ic_agree_selected_png =
      'assets/images/ic_agree_selected.png';
  static const String message$assets_images_ic_agree_selected_png =
      'packages/message/assets/images/ic_agree_selected.png';

  static const String assets_images_ic_auto_call_remind_webp =
      'assets/images/ic_auto_call_remind.webp';
  static const String message$assets_images_ic_auto_call_remind_webp =
      'packages/message/assets/images/ic_auto_call_remind.webp';

  static const String assets_images_ic_chat_match_webp =
      'assets/images/ic_chat_match.webp';
  static const String message$assets_images_ic_chat_match_webp =
      'packages/message/assets/images/ic_chat_match.webp';

  static const String assets_images_ic_clear_all_svg =
      'assets/images/ic_clear_all.svg';
  static const String message$assets_images_ic_clear_all_svg =
      'packages/message/assets/images/ic_clear_all.svg';

  static const String assets_images_ic_clear_user_svg =
      'assets/images/ic_clear_user.svg';
  static const String message$assets_images_ic_clear_user_svg =
      'packages/message/assets/images/ic_clear_user.svg';

  static const String assets_images_ic_close_svg = 'assets/images/ic_close.svg';
  static const String message$assets_images_ic_close_svg =
      'packages/message/assets/images/ic_close.svg';

  static const String assets_images_ic_contact_webp =
      'assets/images/ic_contact.webp';
  static const String message$assets_images_ic_contact_webp =
      'packages/message/assets/images/ic_contact.webp';

  static const String assets_images_ic_contact_dark_webp =
      'assets/images/ic_contact_dark.webp';
  static const String message$assets_images_ic_contact_dark_webp =
      'packages/message/assets/images/ic_contact_dark.webp';

  static const String assets_images_ic_create_group_png =
      'assets/images/ic_create_group.png';
  static const String message$assets_images_ic_create_group_png =
      'packages/message/assets/images/ic_create_group.png';

  static const String assets_images_ic_create_group_dark_png =
      'assets/images/ic_create_group_dark.png';
  static const String message$assets_images_ic_create_group_dark_png =
      'packages/message/assets/images/ic_create_group_dark.png';

  static const String assets_images_ic_data_svg = 'assets/images/ic_data.svg';
  static const String message$assets_images_ic_data_svg =
      'packages/message/assets/images/ic_data.svg';

  static const String assets_images_ic_disagree_normal_png =
      'assets/images/ic_disagree_normal.png';
  static const String message$assets_images_ic_disagree_normal_png =
      'packages/message/assets/images/ic_disagree_normal.png';

  static const String assets_images_ic_disagree_selected_png =
      'assets/images/ic_disagree_selected.png';
  static const String message$assets_images_ic_disagree_selected_png =
      'packages/message/assets/images/ic_disagree_selected.png';

  static const String assets_images_ic_example_change_webp =
      'assets/images/ic_example_change.webp';
  static const String message$assets_images_ic_example_change_webp =
      'packages/message/assets/images/ic_example_change.webp';

  static const String assets_images_ic_fate_add_png =
      'assets/images/ic_fate_add.png';
  static const String message$assets_images_ic_fate_add_png =
      'packages/message/assets/images/ic_fate_add.png';

  static const String assets_images_ic_fate_dialog_title_webp =
      'assets/images/ic_fate_dialog_title.webp';
  static const String message$assets_images_ic_fate_dialog_title_webp =
      'packages/message/assets/images/ic_fate_dialog_title.webp';

  static const String assets_images_ic_fate_guide_left_webp =
      'assets/images/ic_fate_guide_left.webp';
  static const String message$assets_images_ic_fate_guide_left_webp =
      'packages/message/assets/images/ic_fate_guide_left.webp';

  static const String assets_images_ic_fate_guide_right_webp =
      'assets/images/ic_fate_guide_right.webp';
  static const String message$assets_images_ic_fate_guide_right_webp =
      'packages/message/assets/images/ic_fate_guide_right.webp';

  static const String assets_images_ic_fate_spec_bg_webp =
      'assets/images/ic_fate_spec_bg.webp';
  static const String message$assets_images_ic_fate_spec_bg_webp =
      'packages/message/assets/images/ic_fate_spec_bg.webp';

  static const String assets_images_ic_group_chat_svg =
      'assets/images/ic_group_chat.svg';
  static const String message$assets_images_ic_group_chat_svg =
      'packages/message/assets/images/ic_group_chat.svg';

  static const String assets_images_ic_home_search_webp =
      'assets/images/ic_home_search.webp';
  static const String message$assets_images_ic_home_search_webp =
      'packages/message/assets/images/ic_home_search.webp';

  static const String assets_images_ic_intro_svg = 'assets/images/ic_intro.svg';
  static const String message$assets_images_ic_intro_svg =
      'packages/message/assets/images/ic_intro.svg';

  static const String assets_images_ic_join_union_icon_webp =
      'assets/images/ic_join_union_icon.webp';
  static const String message$assets_images_ic_join_union_icon_webp =
      'packages/message/assets/images/ic_join_union_icon.webp';

  static const String assets_images_ic_join_union_next_webp =
      'assets/images/ic_join_union_next.webp';
  static const String message$assets_images_ic_join_union_next_webp =
      'packages/message/assets/images/ic_join_union_next.webp';

  static const String assets_images_ic_message_svg =
      'assets/images/ic_message.svg';
  static const String message$assets_images_ic_message_svg =
      'packages/message/assets/images/ic_message.svg';

  static const String assets_images_ic_message_candy_webp =
      'assets/images/ic_message_candy.webp';
  static const String message$assets_images_ic_message_candy_webp =
      'packages/message/assets/images/ic_message_candy.webp';

  static const String assets_images_ic_message_get_gift_tips_webp =
      'assets/images/ic_message_get_gift_tips.webp';
  static const String message$assets_images_ic_message_get_gift_tips_webp =
      'packages/message/assets/images/ic_message_get_gift_tips.webp';

  static const String assets_images_ic_message_heart_webp =
      'assets/images/ic_message_heart.webp';
  static const String message$assets_images_ic_message_heart_webp =
      'packages/message/assets/images/ic_message_heart.webp';

  static const String assets_images_ic_moment_png =
      'assets/images/ic_moment.png';
  static const String message$assets_images_ic_moment_png =
      'packages/message/assets/images/ic_moment.png';

  static const String assets_images_ic_moment_notice_webp =
      'assets/images/ic_moment_notice.webp';
  static const String message$assets_images_ic_moment_notice_webp =
      'packages/message/assets/images/ic_moment_notice.webp';

  static const String assets_images_ic_my_family_svg =
      'assets/images/ic_my_family.svg';
  static const String message$assets_images_ic_my_family_svg =
      'packages/message/assets/images/ic_my_family.svg';

  static const String assets_images_ic_my_room_svg =
      'assets/images/ic_my_room.svg';
  static const String message$assets_images_ic_my_room_svg =
      'packages/message/assets/images/ic_my_room.svg';

  static const String assets_images_ic_next_small_webp =
      'assets/images/ic_next_small.webp';
  static const String message$assets_images_ic_next_small_webp =
      'packages/message/assets/images/ic_next_small.webp';

  static const String assets_images_ic_open_notification_webp =
      'assets/images/ic_open_notification.webp';
  static const String message$assets_images_ic_open_notification_webp =
      'packages/message/assets/images/ic_open_notification.webp';

  static const String assets_images_ic_open_notification_dark_webp =
      'assets/images/ic_open_notification_dark.webp';
  static const String message$assets_images_ic_open_notification_dark_webp =
      'packages/message/assets/images/ic_open_notification_dark.webp';

  static const String assets_images_ic_playing_webp =
      'assets/images/ic_playing.webp';
  static const String message$assets_images_ic_playing_webp =
      'packages/message/assets/images/ic_playing.webp';

  static const String assets_images_ic_quick_msg_edit_svg =
      'assets/images/ic_quick_msg_edit.svg';
  static const String message$assets_images_ic_quick_msg_edit_svg =
      'packages/message/assets/images/ic_quick_msg_edit.svg';

  static const String assets_images_ic_record_dialog_done_svg =
      'assets/images/ic_record_dialog_done.svg';
  static const String message$assets_images_ic_record_dialog_done_svg =
      'packages/message/assets/images/ic_record_dialog_done.svg';

  static const String assets_images_ic_record_dialog_play_svg =
      'assets/images/ic_record_dialog_play.svg';
  static const String message$assets_images_ic_record_dialog_play_svg =
      'packages/message/assets/images/ic_record_dialog_play.svg';

  static const String assets_images_ic_record_dialog_stop_svg =
      'assets/images/ic_record_dialog_stop.svg';
  static const String message$assets_images_ic_record_dialog_stop_svg =
      'packages/message/assets/images/ic_record_dialog_stop.svg';

  static const String assets_images_ic_record_dialog_voice_svg =
      'assets/images/ic_record_dialog_voice.svg';
  static const String message$assets_images_ic_record_dialog_voice_svg =
      'packages/message/assets/images/ic_record_dialog_voice.svg';

  static const String assets_images_ic_rush_add_svg =
      'assets/images/ic_rush_add.svg';
  static const String message$assets_images_ic_rush_add_svg =
      'packages/message/assets/images/ic_rush_add.svg';

  static const String assets_images_ic_rush_contact_svg =
      'assets/images/ic_rush_contact.svg';
  static const String message$assets_images_ic_rush_contact_svg =
      'packages/message/assets/images/ic_rush_contact.svg';

  static const String assets_images_ic_rush_default_friendcard_audio_png =
      'assets/images/ic_rush_default_friendcard_audio.png';
  static const String
      message$assets_images_ic_rush_default_friendcard_audio_png =
      'packages/message/assets/images/ic_rush_default_friendcard_audio.png';

  static const String assets_images_ic_search_svg =
      'assets/images/ic_search.svg';
  static const String message$assets_images_ic_search_svg =
      'packages/message/assets/images/ic_search.svg';

  static const String assets_images_ic_search_webp =
      'assets/images/ic_search.webp';
  static const String message$assets_images_ic_search_webp =
      'packages/message/assets/images/ic_search.webp';

  static const String assets_images_ic_slide_delete_webp =
      'assets/images/ic_slide_delete.webp';
  static const String message$assets_images_ic_slide_delete_webp =
      'packages/message/assets/images/ic_slide_delete.webp';

  static const String assets_images_ic_slide_top_webp =
      'assets/images/ic_slide_top.webp';
  static const String message$assets_images_ic_slide_top_webp =
      'packages/message/assets/images/ic_slide_top.webp';

  static const String assets_images_ic_slide_top_not_webp =
      'assets/images/ic_slide_top_not.webp';
  static const String message$assets_images_ic_slide_top_not_webp =
      'packages/message/assets/images/ic_slide_top_not.webp';

  static const String assets_images_ic_small_account_webp =
      'assets/images/ic_small_account.webp';
  static const String message$assets_images_ic_small_account_webp =
      'packages/message/assets/images/ic_small_account.webp';

  static const String assets_images_ic_small_account_close_webp =
      'assets/images/ic_small_account_close.webp';
  static const String message$assets_images_ic_small_account_close_webp =
      'packages/message/assets/images/ic_small_account_close.webp';

  static const String assets_images_ic_small_account_dark_webp =
      'assets/images/ic_small_account_dark.webp';
  static const String message$assets_images_ic_small_account_dark_webp =
      'packages/message/assets/images/ic_small_account_dark.webp';

  static const String assets_images_ic_small_account_mate_svg =
      'assets/images/ic_small_account_mate.svg';
  static const String message$assets_images_ic_small_account_mate_svg =
      'packages/message/assets/images/ic_small_account_mate.svg';

  static const String assets_images_ic_small_account_msg_arrow_png =
      'assets/images/ic_small_account_msg_arrow.png';
  static const String message$assets_images_ic_small_account_msg_arrow_png =
      'packages/message/assets/images/ic_small_account_msg_arrow.png';

  static const String assets_images_ic_visitor_webp =
      'assets/images/ic_visitor.webp';
  static const String message$assets_images_ic_visitor_webp =
      'packages/message/assets/images/ic_visitor.webp';

  static const String assets_images_icon_contact_svg =
      'assets/images/icon_contact.svg';
  static const String message$assets_images_icon_contact_svg =
      'packages/message/assets/images/icon_contact.svg';

  static const String assets_images_icon_more_svg =
      'assets/images/icon_more.svg';
  static const String message$assets_images_icon_more_svg =
      'packages/message/assets/images/icon_more.svg';

  static const String assets_images_invite_into_room_png =
      'assets/images/invite_into_room.png';
  static const String message$assets_images_invite_into_room_png =
      'packages/message/assets/images/invite_into_room.png';

  static const String assets_images_invite_into_room_dark_png =
      'assets/images/invite_into_room_dark.png';
  static const String message$assets_images_invite_into_room_dark_png =
      'packages/message/assets/images/invite_into_room_dark.png';

  static const String assets_images_match_guide_close_webp =
      'assets/images/match_guide_close.webp';
  static const String message$assets_images_match_guide_close_webp =
      'packages/message/assets/images/match_guide_close.webp';

  static const String assets_images_match_guide_connect_webp =
      'assets/images/match_guide_connect.webp';
  static const String message$assets_images_match_guide_connect_webp =
      'packages/message/assets/images/match_guide_connect.webp';

  static const String assets_images_match_request_list_banner_bg_webp =
      'assets/images/match_request_list_banner_bg.webp';
  static const String message$assets_images_match_request_list_banner_bg_webp =
      'packages/message/assets/images/match_request_list_banner_bg.webp';

  static const String assets_images_messaage_filter_png =
      'assets/images/messaage_filter.png';
  static const String message$assets_images_messaage_filter_png =
      'packages/message/assets/images/messaage_filter.png';

  static const String assets_images_message_addfriend_close_webp =
      'assets/images/message_addfriend_close.webp';
  static const String message$assets_images_message_addfriend_close_webp =
      'packages/message/assets/images/message_addfriend_close.webp';

  static const String assets_images_message_addfriend_phone_png =
      'assets/images/message_addfriend_phone.png';
  static const String message$assets_images_message_addfriend_phone_png =
      'packages/message/assets/images/message_addfriend_phone.png';

  static const String assets_images_message_addfriend_phone_dark_png =
      'assets/images/message_addfriend_phone_dark.png';
  static const String message$assets_images_message_addfriend_phone_dark_png =
      'packages/message/assets/images/message_addfriend_phone_dark.png';

  static const String assets_images_message_addfriend_qq_png =
      'assets/images/message_addfriend_qq.png';
  static const String message$assets_images_message_addfriend_qq_png =
      'packages/message/assets/images/message_addfriend_qq.png';

  static const String assets_images_message_addfriend_qq_dark_png =
      'assets/images/message_addfriend_qq_dark.png';
  static const String message$assets_images_message_addfriend_qq_dark_png =
      'packages/message/assets/images/message_addfriend_qq_dark.png';

  static const String assets_images_message_addfriend_stranger_png =
      'assets/images/message_addfriend_stranger.png';
  static const String message$assets_images_message_addfriend_stranger_png =
      'packages/message/assets/images/message_addfriend_stranger.png';

  static const String assets_images_message_addfriend_stranger_dark_png =
      'assets/images/message_addfriend_stranger_dark.png';
  static const String
      message$assets_images_message_addfriend_stranger_dark_png =
      'packages/message/assets/images/message_addfriend_stranger_dark.png';

  static const String assets_images_message_addfriend_new_stranger_dark_png =
      'assets/images/message_addfriend_stranger_new_dark.png';
  static const String
      message$assets_images_message_addfriend_new_stranger_dark_png =
      'packages/message/assets/images/message_addfriend_stranger_new_dark.png';

  static const String assets_images_message_addfriend_wx_png =
      'assets/images/message_addfriend_wx.png';
  static const String message$assets_images_message_addfriend_wx_png =
      'packages/message/assets/images/message_addfriend_wx.png';

  static const String assets_images_message_addfriend_wx_dark_png =
      'assets/images/message_addfriend_wx_dark.png';
  static const String message$assets_images_message_addfriend_wx_dark_png =
      'packages/message/assets/images/message_addfriend_wx_dark.png';

  static const String assets_images_message_contact_png =
      'assets/images/message_contact.png';
  static const String message$assets_images_message_contact_png =
      'packages/message/assets/images/message_contact.png';

  static const String assets_images_message_contact_dark_png =
      'assets/images/message_contact_dark.png';
  static const String message$assets_images_message_contact_dark_png =
      'packages/message/assets/images/message_contact_dark.png';

  static const String assets_images_message_fix_profile_png =
      'assets/images/message_fix_profile.png';
  static const String message$assets_images_message_fix_profile_png =
      'packages/message/assets/images/message_fix_profile.png';

  static const String assets_images_message_friend_more_webp =
      'assets/images/message_friend_more.webp';
  static const String message$assets_images_message_friend_more_webp =
      'packages/message/assets/images/message_friend_more.webp';

  static const String assets_images_message_guide_card_button_webp =
      'assets/images/message_guide_card_button.webp';
  static const String message$assets_images_message_guide_card_button_webp =
      'packages/message/assets/images/message_guide_card_button.webp';

  static const String assets_images_message_ic_location_webp =
      'assets/images/message_ic_location.webp';
  static const String message$assets_images_message_ic_location_webp =
      'packages/message/assets/images/message_ic_location.webp';

  static const String assets_images_message_ic_location_dark_webp =
      'assets/images/message_ic_location_dark.webp';
  static const String message$assets_images_message_ic_location_dark_webp =
      'packages/message/assets/images/message_ic_location_dark.webp';

  static const String assets_images_message_ic_photo_png =
      'assets/images/message_ic_photo.png';
  static const String message$assets_images_message_ic_photo_png =
      'packages/message/assets/images/message_ic_photo.png';

  static const String assets_images_message_little_tip_button_webp =
      'assets/images/message_little_tip_button.webp';
  static const String message$assets_images_message_little_tip_button_webp =
      'packages/message/assets/images/message_little_tip_button.webp';

  static const String assets_images_message_match_button_webp =
      'assets/images/message_match_button.webp';
  static const String message$assets_images_message_match_button_webp =
      'packages/message/assets/images/message_match_button.webp';

  static const String assets_images_msg_ic_accompany_webp =
      'assets/images/msg_ic_accompany.webp';
  static const String message$assets_images_msg_ic_accompany_webp =
      'packages/message/assets/images/msg_ic_accompany.webp';

  static const String assets_images_msg_ic_match_webp =
      'assets/images/msg_ic_match.webp';
  static const String message$assets_images_msg_ic_match_webp =
      'packages/message/assets/images/msg_ic_match.webp';

  static const String assets_images_msg_profile_write_webp =
      'assets/images/msg_profile_write.webp';
  static const String message$assets_images_msg_profile_write_webp =
      'packages/message/assets/images/msg_profile_write.webp';

  static const String assets_images_msg_unread_count_bg_png =
      'assets/images/msg_unread_count_bg.png';
  static const String message$assets_images_msg_unread_count_bg_png =
      'packages/message/assets/images/msg_unread_count_bg.png';

  static const String assets_images_sayhi_big_icon_webp =
      'assets/images/sayhi_big_icon.webp';
  static const String message$assets_images_sayhi_big_icon_webp =
      'packages/message/assets/images/sayhi_big_icon.webp';

  static const String assets_images_sayhi_match_bg_webp =
      'assets/images/sayhi_match_bg.webp';
  static const String message$assets_images_sayhi_match_bg_webp =
      'packages/message/assets/images/sayhi_match_bg.webp';

  static const String assets_images_sayhi_match_close_webp =
      'assets/images/sayhi_match_close.webp';
  static const String message$assets_images_sayhi_match_close_webp =
      'packages/message/assets/images/sayhi_match_close.webp';

  static const String assets_images_sayhi_match_location_webp =
      'assets/images/sayhi_match_location.webp';
  static const String message$assets_images_sayhi_match_location_webp =
      'packages/message/assets/images/sayhi_match_location.webp';

  static const String assets_images_sayhi_match_select_webp =
      'assets/images/sayhi_match_select.webp';
  static const String message$assets_images_sayhi_match_select_webp =
      'packages/message/assets/images/sayhi_match_select.webp';

  static const String assets_images_sayhi_match_unselect_webp =
      'assets/images/sayhi_match_unselect.webp';
  static const String message$assets_images_sayhi_match_unselect_webp =
      'packages/message/assets/images/sayhi_match_unselect.webp';

  static const String assets_images_sayhi_small_icon_webp =
      'assets/images/sayhi_small_icon.webp';
  static const String message$assets_images_sayhi_small_icon_webp =
      'packages/message/assets/images/sayhi_small_icon.webp';

  static const String assets_images_void_match_default_header_webp =
      'assets/images/void_match_default_header.webp';
  static const String message$assets_images_void_match_default_header_webp =
      'packages/message/assets/images/void_match_default_header.webp';

  static const String assets_images_void_match_default_header1_webp =
      'assets/images/void_match_default_header1.webp';
  static const String message$assets_images_void_match_default_header1_webp =
      'packages/message/assets/images/void_match_default_header1.webp';

  static const String assets_images_void_match_default_header2_webp =
      'assets/images/void_match_default_header2.webp';
  static const String message$assets_images_void_match_default_header2_webp =
      'packages/message/assets/images/void_match_default_header2.webp';

  static const String assets_images_void_match_default_header3_webp =
      'assets/images/void_match_default_header3.webp';
  static const String message$assets_images_void_match_default_header3_webp =
      'packages/message/assets/images/void_match_default_header3.webp';

  static const String title_mesage_icon = 'assets/images/title_mesage_icon.png';
  static const String message$title_mesage_icon =
      'packages/message/assets/images/title_mesage_icon.png';
}
