// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 16.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'group';

  static const String group_add_member_svg =
      'assets/images/group_add_member.svg';
  static const String group$group_add_member_svg =
      'packages/group/assets/images/group_add_member.svg';

  static const String group_ic_add_svg = 'assets/images/group_ic_add.svg';
  static const String group$group_ic_add_svg =
      'packages/group/assets/images/group_ic_add.svg';

  static const String group_ic_all_person_svg =
      'assets/images/group_ic_all_person.svg';
  static const String group$group_ic_all_person_svg =
      'packages/group/assets/images/group_ic_all_person.svg';

  static const String group_ic_copy_svg = 'assets/images/group_ic_copy.svg';
  static const String group$group_ic_copy_svg =
      'packages/group/assets/images/group_ic_copy.svg';

  static const String ic_next_small_svg = 'assets/images/ic_next_small.svg';
  static const String group$ic_next_small_svg =
      'packages/group/assets/images/ic_next_small.svg';

  static const String icn_chat_svg = 'assets/images/icn_chat.svg';
  static const String group$icn_chat_svg =
      'packages/group/assets/images/icn_chat.svg';

  static const String icn_next_svg = 'assets/images/icn_next.svg';
  static const String group$icn_next_svg =
      'packages/group/assets/images/icn_next.svg';

  static const String tour_group_admin_png =
      'assets/images/tour_group_admin.png';
  static const String group$tour_group_admin_png =
      'packages/group/assets/images/tour_group_admin.png';

  static const String tour_group_asce_png = 'assets/images/tour_group_asce.png';
  static const String group$tour_group_asce_png =
      'packages/group/assets/images/tour_group_asce.png';

  static const String tour_group_captain_png =
      'assets/images/tour_group_captain.png';
  static const String group$tour_group_captain_png =
      'packages/group/assets/images/tour_group_captain.png';

  static const String tour_group_checkbox_selected_webp =
      'assets/images/tour_group_checkbox_selected.webp';
  static const String group$tour_group_checkbox_selected_webp =
      'packages/group/assets/images/tour_group_checkbox_selected.webp';

  static const String tour_group_checkbox_unselected_webp =
      'assets/images/tour_group_checkbox_unselected.webp';
  static const String group$tour_group_checkbox_unselected_webp =
      'packages/group/assets/images/tour_group_checkbox_unselected.webp';

  static const String tour_group_close_mic_png =
      'assets/images/tour_group_close_mic.png';
  static const String group$tour_group_close_mic_png =
      'packages/group/assets/images/tour_group_close_mic.png';

  static const String tour_group_desc_png = 'assets/images/tour_group_desc.png';
  static const String group$tour_group_desc_png =
      'packages/group/assets/images/tour_group_desc.png';

  static const String tour_group_normal_png =
      'assets/images/tour_group_normal.png';
  static const String group$tour_group_normal_png =
      'packages/group/assets/images/tour_group_normal.png';
}
