// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 2.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'flutter_markdown';

  static const String assets_ic_video_play_svg = 'assets/ic_video_play.svg';
  static const String flutter_markdown$assets_ic_video_play_svg =
      'packages/flutter_markdown/assets/ic_video_play.svg';

  static const String assets_logo_png = 'assets/logo.png';
  static const String flutter_markdown$assets_logo_png =
      'packages/flutter_markdown/assets/logo.png';
}
