// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 1.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'loading_more_list';

  static const String assets_empty_jpeg = 'assets/empty.jpeg';
  static const String loading_more_list$assets_empty_jpeg =
      'packages/loading_more_list/assets/empty.jpeg';
}
