// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 10.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'web_game_core';

  static const String ic_close_webp = 'assets/images/ic_close.webp';
  static const String web_game_core$ic_close_webp =
      'packages/web_game_core/assets/images/ic_close.webp';

  static const String loading_bar_bg_style_ar_webp =
      'assets/images/loading_bar_bg_style_ar.webp';
  static const String web_game_core$loading_bar_bg_style_ar_webp =
      'packages/web_game_core/assets/images/loading_bar_bg_style_ar.webp';

  static const String loading_bar_bg_style_normal_webp =
      'assets/images/loading_bar_bg_style_normal.webp';
  static const String web_game_core$loading_bar_bg_style_normal_webp =
      'packages/web_game_core/assets/images/loading_bar_bg_style_normal.webp';

  static const String loading_bg_portrait_style_ar_webp =
      'assets/images/loading_bg_portrait_style_ar.webp';
  static const String web_game_core$loading_bg_portrait_style_ar_webp =
      'packages/web_game_core/assets/images/loading_bg_portrait_style_ar.webp';

  static const String loading_bg_portrait_style_normal_webp =
      'assets/images/loading_bg_portrait_style_normal.webp';
  static const String web_game_core$loading_bg_portrait_style_normal_webp =
      'packages/web_game_core/assets/images/loading_bg_portrait_style_normal.webp';

  static const String loading_flower_bottom_right_webp =
      'assets/images/loading_flower_bottom_right.webp';
  static const String web_game_core$loading_flower_bottom_right_webp =
      'packages/web_game_core/assets/images/loading_flower_bottom_right.webp';

  static const String loading_flower_top_left_webp =
      'assets/images/loading_flower_top_left.webp';
  static const String web_game_core$loading_flower_top_left_webp =
      'packages/web_game_core/assets/images/loading_flower_top_left.webp';

  static const String loading_progress_style_ar_webp =
      'assets/images/loading_progress_style_ar.webp';
  static const String web_game_core$loading_progress_style_ar_webp =
      'packages/web_game_core/assets/images/loading_progress_style_ar.webp';

  static const String loading_progress_style_normal_webp =
      'assets/images/loading_progress_style_normal.webp';
  static const String web_game_core$loading_progress_style_normal_webp =
      'packages/web_game_core/assets/images/loading_progress_style_normal.webp';

  static const String rabbit_lady_webp = 'assets/images/rabbit_lady.webp';
  static const String web_game_core$rabbit_lady_webp =
      'packages/web_game_core/assets/images/rabbit_lady.webp';
}
