// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 3.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'pay';

  static const String ic_check_svg = 'assets/images/ic_check.svg';
  static const String pay$ic_check_svg =
      'packages/pay/assets/images/ic_check.svg';

  static const String ic_pay_checkbox_svg = 'assets/images/ic_pay_checkbox.svg';
  static const String pay$ic_pay_checkbox_svg =
      'packages/pay/assets/images/ic_pay_checkbox.svg';

  static const String ic_pay_checkbox_selected_svg =
      'assets/images/ic_pay_checkbox_selected.svg';
  static const String pay$ic_pay_checkbox_selected_svg =
      'packages/pay/assets/images/ic_pay_checkbox_selected.svg';
}
