name: pulse_log
description: 日志系统插件
version: 1.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  synchronized: ^3.0.0
  path_provider: ^2.0.2
  wifi_info_plugin_plus:
    path: ../android_wifi_info

  carrier_info:
    path: ../carrier_info

  archive: ^3.3.8
  dio: ^5.0.0
  convert: ^3.0.2
  connectivity_plus: ">=2.3.0 <4.0.0"
  network_info_plus: 2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: ly.plugins.pulse_log
        pluginClass: PulseLogPlugin
      ios:
        pluginClass: PulseLogPlugin
