// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 153.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'gift';

  static const String bg_money_png = 'assets/images/bg_money.png';
  static const String gift$bg_money_png =
      'packages/gift/assets/images/bg_money.png';

  static const String click_to_awake_bg_webp =
      'assets/images/click_to_awake_bg.webp';
  static const String gift$click_to_awake_bg_webp =
      'packages/gift/assets/images/click_to_awake_bg.webp';

  static const String constellation_clap_bg_clap_price_webp =
      'assets/images/constellation_clap/bg_clap_price.webp';
  static const String gift$constellation_clap_bg_clap_price_webp =
      'packages/gift/assets/images/constellation_clap/bg_clap_price.webp';

  static const String constellation_clap_bg_head_constellation_webp =
      'assets/images/constellation_clap/bg_head_constellation.webp';
  static const String gift$constellation_clap_bg_head_constellation_webp =
      'packages/gift/assets/images/constellation_clap/bg_head_constellation.webp';

  static const String constellation_clap_bg_head_shadow_webp =
      'assets/images/constellation_clap/bg_head_shadow.webp';
  static const String gift$constellation_clap_bg_head_shadow_webp =
      'packages/gift/assets/images/constellation_clap/bg_head_shadow.webp';

  static const String constellation_clap_bg_name_webp =
      'assets/images/constellation_clap/bg_name.webp';
  static const String gift$constellation_clap_bg_name_webp =
      'packages/gift/assets/images/constellation_clap/bg_name.webp';

  static const String constellation_clap_bg_op_btn_webp =
      'assets/images/constellation_clap/bg_op_btn.webp';
  static const String gift$constellation_clap_bg_op_btn_webp =
      'packages/gift/assets/images/constellation_clap/bg_op_btn.webp';

  static const String constellation_clap_bg_op_btn_disable_webp =
      'assets/images/constellation_clap/bg_op_btn_disable.webp';
  static const String gift$constellation_clap_bg_op_btn_disable_webp =
      'packages/gift/assets/images/constellation_clap/bg_op_btn_disable.webp';

  static const String constellation_clap_bg_result_first_item_webp =
      'assets/images/constellation_clap/bg_result_first_item.webp';
  static const String gift$constellation_clap_bg_result_first_item_webp =
      'packages/gift/assets/images/constellation_clap/bg_result_first_item.webp';

  static const String constellation_clap_bg_result_head_webp =
      'assets/images/constellation_clap/bg_result_head.webp';
  static const String gift$constellation_clap_bg_result_head_webp =
      'packages/gift/assets/images/constellation_clap/bg_result_head.webp';

  static const String constellation_clap_bg_result_item_webp =
      'assets/images/constellation_clap/bg_result_item.webp';
  static const String gift$constellation_clap_bg_result_item_webp =
      'packages/gift/assets/images/constellation_clap/bg_result_item.webp';

  static const String constellation_clap_bg_result_top_item_webp =
      'assets/images/constellation_clap/bg_result_top_item.webp';
  static const String gift$constellation_clap_bg_result_top_item_webp =
      'packages/gift/assets/images/constellation_clap/bg_result_top_item.webp';

  static const String constellation_clap_bg_time_counter_webp =
      'assets/images/constellation_clap/bg_time_counter.webp';
  static const String gift$constellation_clap_bg_time_counter_webp =
      'packages/gift/assets/images/constellation_clap/bg_time_counter.webp';

  static const String constellation_clap_bg_user_label_webp =
      'assets/images/constellation_clap/bg_user_label.webp';
  static const String gift$constellation_clap_bg_user_label_webp =
      'packages/gift/assets/images/constellation_clap/bg_user_label.webp';

  static const String constellation_clap_btn_clap_webp =
      'assets/images/constellation_clap/btn_clap.webp';
  static const String gift$constellation_clap_btn_clap_webp =
      'packages/gift/assets/images/constellation_clap/btn_clap.webp';

  static const String constellation_clap_constellation_text_circle_webp =
      'assets/images/constellation_clap/constellation_text_circle.webp';
  static const String gift$constellation_clap_constellation_text_circle_webp =
      'packages/gift/assets/images/constellation_clap/constellation_text_circle.webp';

  static const String constellation_clap_ic_big_wheel_webp =
      'assets/images/constellation_clap/ic_big_wheel.webp';
  static const String gift$constellation_clap_ic_big_wheel_webp =
      'packages/gift/assets/images/constellation_clap/ic_big_wheel.webp';

  static const String constellation_clap_ic_center_wheel_webp =
      'assets/images/constellation_clap/ic_center_wheel.webp';
  static const String gift$constellation_clap_ic_center_wheel_webp =
      'packages/gift/assets/images/constellation_clap/ic_center_wheel.webp';

  static const String constellation_clap_ic_close_webp =
      'assets/images/constellation_clap/ic_close.webp';
  static const String gift$constellation_clap_ic_close_webp =
      'packages/gift/assets/images/constellation_clap/ic_close.webp';

  static const String constellation_clap_ic_drag_heart_webp =
      'assets/images/constellation_clap/ic_drag_heart.webp';
  static const String gift$constellation_clap_ic_drag_heart_webp =
      'packages/gift/assets/images/constellation_clap/ic_drag_heart.webp';

  static const String constellation_clap_ic_light_circle_webp =
      'assets/images/constellation_clap/ic_light_circle.webp';
  static const String gift$constellation_clap_ic_light_circle_webp =
      'packages/gift/assets/images/constellation_clap/ic_light_circle.webp';

  static const String constellation_clap_ic_move_close_webp =
      'assets/images/constellation_clap/ic_move_close.webp';
  static const String gift$constellation_clap_ic_move_close_webp =
      'packages/gift/assets/images/constellation_clap/ic_move_close.webp';

  static const String constellation_clap_ic_pointer_light_webp =
      'assets/images/constellation_clap/ic_pointer_light.webp';
  static const String gift$constellation_clap_ic_pointer_light_webp =
      'packages/gift/assets/images/constellation_clap/ic_pointer_light.webp';

  static const String constellation_clap_ic_result_heart_webp =
      'assets/images/constellation_clap/ic_result_heart.webp';
  static const String gift$constellation_clap_ic_result_heart_webp =
      'packages/gift/assets/images/constellation_clap/ic_result_heart.webp';

  static const String constellation_clap_ic_wheel_pointer_webp =
      'assets/images/constellation_clap/ic_wheel_pointer.webp';
  static const String gift$constellation_clap_ic_wheel_pointer_webp =
      'packages/gift/assets/images/constellation_clap/ic_wheel_pointer.webp';

  static const String constellation_clap_result_counter_top_shadow_webp =
      'assets/images/constellation_clap/result_counter_top_shadow.webp';
  static const String gift$constellation_clap_result_counter_top_shadow_webp =
      'packages/gift/assets/images/constellation_clap/result_counter_top_shadow.webp';

  static const String constellation_clap_text_clap_done_webp =
      'assets/images/constellation_clap/text_clap_done.webp';
  static const String gift$constellation_clap_text_clap_done_webp =
      'packages/gift/assets/images/constellation_clap/text_clap_done.webp';

  static const String custom_ring_appbar_title_png =
      'assets/images/custom_ring/appbar_title.png';
  static const String gift$custom_ring_appbar_title_png =
      'packages/gift/assets/images/custom_ring/appbar_title.png';

  static const String custom_ring_bg_top_tips_webp =
      'assets/images/custom_ring/bg_top_tips.webp';
  static const String gift$custom_ring_bg_top_tips_webp =
      'packages/gift/assets/images/custom_ring/bg_top_tips.webp';

  static const String custom_ring_heart_webp =
      'assets/images/custom_ring/heart.webp';
  static const String gift$custom_ring_heart_webp =
      'packages/gift/assets/images/custom_ring/heart.webp';

  static const String custom_ring_ring_webp =
      'assets/images/custom_ring/ring.webp';
  static const String gift$custom_ring_ring_webp =
      'packages/gift/assets/images/custom_ring/ring.webp';

  static const String custom_ring_ring_effect_bottom_webp =
      'assets/images/custom_ring/ring_effect_bottom.webp';
  static const String gift$custom_ring_ring_effect_bottom_webp =
      'packages/gift/assets/images/custom_ring/ring_effect_bottom.webp';

  static const String custom_ring_ring_effect_light_webp =
      'assets/images/custom_ring/ring_effect_light.webp';
  static const String gift$custom_ring_ring_effect_light_webp =
      'packages/gift/assets/images/custom_ring/ring_effect_light.webp';

  static const String custom_ring_ring_effect_top_webp =
      'assets/images/custom_ring/ring_effect_top.webp';
  static const String gift$custom_ring_ring_effect_top_webp =
      'packages/gift/assets/images/custom_ring/ring_effect_top.webp';

  static const String custom_ring_sub_title_line_webp =
      'assets/images/custom_ring/sub_title_line.webp';
  static const String gift$custom_ring_sub_title_line_webp =
      'packages/gift/assets/images/custom_ring/sub_title_line.webp';

  static const String custom_ring_tip_user_line_webp =
      'assets/images/custom_ring/tip_user_line.webp';
  static const String gift$custom_ring_tip_user_line_webp =
      'packages/gift/assets/images/custom_ring/tip_user_line.webp';

  static const String custom_ring_user_line_webp =
      'assets/images/custom_ring/user_line.webp';
  static const String gift$custom_ring_user_line_webp =
      'packages/gift/assets/images/custom_ring/user_line.webp';

  static const String diy_gift_avatar_select_icon_png =
      'assets/images/diy_gift_avatar_select_icon.png';
  static const String gift$diy_gift_avatar_select_icon_png =
      'packages/gift/assets/images/diy_gift_avatar_select_icon.png';

  static const String diy_gift_item_bg_webp =
      'assets/images/diy_gift_item_bg.webp';
  static const String gift$diy_gift_item_bg_webp =
      'packages/gift/assets/images/diy_gift_item_bg.webp';

  static const String diy_gift_tab_indicator_webp =
      'assets/images/diy_gift_tab_indicator.webp';
  static const String gift$diy_gift_tab_indicator_webp =
      'packages/gift/assets/images/diy_gift_tab_indicator.webp';

  static const String diy_gift_tab_item_bg_webp =
      'assets/images/diy_gift_tab_item_bg.webp';
  static const String gift$diy_gift_tab_item_bg_webp =
      'packages/gift/assets/images/diy_gift_tab_item_bg.webp';

  static const String diy_gift_tab_selected_png =
      'assets/images/diy_gift_tab_selected.png';
  static const String gift$diy_gift_tab_selected_png =
      'packages/gift/assets/images/diy_gift_tab_selected.png';

  static const String diy_gift_top_bg_webp =
      'assets/images/diy_gift_top_bg.webp';
  static const String gift$diy_gift_top_bg_webp =
      'packages/gift/assets/images/diy_gift_top_bg.webp';

  static const String diy_item_bg_big_png = 'assets/images/diy_item_bg_big.png';
  static const String gift$diy_item_bg_big_png =
      'packages/gift/assets/images/diy_item_bg_big.png';

  static const String diy_item_bg_small_png =
      'assets/images/diy_item_bg_small.png';
  static const String gift$diy_item_bg_small_png =
      'packages/gift/assets/images/diy_item_bg_small.png';

  static const String gift_banner_pig_gift_bg_png =
      'assets/images/gift_banner/pig_gift_bg.png';
  static const String gift$gift_banner_pig_gift_bg_png =
      'packages/gift/assets/images/gift_banner/pig_gift_bg.png';

  static const String gift_banner_pig_gift_ic_left_png =
      'assets/images/gift_banner/pig_gift_ic_left.png';
  static const String gift$gift_banner_pig_gift_ic_left_png =
      'packages/gift/assets/images/gift_banner/pig_gift_ic_left.png';

  static const String gift_banner_pig_gift_ic_right_png =
      'assets/images/gift_banner/pig_gift_ic_right.png';
  static const String gift$gift_banner_pig_gift_ic_right_png =
      'packages/gift/assets/images/gift_banner/pig_gift_ic_right.png';

  static const String gift_banner_relationship_bg_webp =
      'assets/images/gift_banner/relationship_bg.webp';
  static const String gift$gift_banner_relationship_bg_webp =
      'packages/gift/assets/images/gift_banner/relationship_bg.webp';

  static const String gift_complete_png = 'assets/images/gift_complete.png';
  static const String gift$gift_complete_png =
      'packages/gift/assets/images/gift_complete.png';

  static const String gift_ic_cancel_webp = 'assets/images/gift_ic_cancel.webp';
  static const String gift$gift_ic_cancel_webp =
      'packages/gift/assets/images/gift_ic_cancel.webp';

  static const String gift_ic_clear_webp = 'assets/images/gift_ic_clear.webp';
  static const String gift$gift_ic_clear_webp =
      'packages/gift/assets/images/gift_ic_clear.webp';

  static const String gift_pack_gift_pack_bottom_red_pkg_webp =
      'assets/images/gift_pack/gift_pack_bottom_red_pkg.webp';
  static const String gift$gift_pack_gift_pack_bottom_red_pkg_webp =
      'packages/gift/assets/images/gift_pack/gift_pack_bottom_red_pkg.webp';

  static const String gift_pack_gift_pack_daily_coupon_webp =
      'assets/images/gift_pack/gift_pack_daily_coupon.webp';
  static const String gift$gift_pack_gift_pack_daily_coupon_webp =
      'packages/gift/assets/images/gift_pack/gift_pack_daily_coupon.webp';

  static const String gift_pack_gift_pack_daily_coupon_close_webp =
      'assets/images/gift_pack/gift_pack_daily_coupon_close.webp';
  static const String gift$gift_pack_gift_pack_daily_coupon_close_webp =
      'packages/gift/assets/images/gift_pack/gift_pack_daily_coupon_close.webp';

  static const String gift_pack_gift_pack_daily_coupon_next_webp =
      'assets/images/gift_pack/gift_pack_daily_coupon_next.webp';
  static const String gift$gift_pack_gift_pack_daily_coupon_next_webp =
      'packages/gift/assets/images/gift_pack/gift_pack_daily_coupon_next.webp';

  static const String gift_pack_gift_pack_daily_light_bg_webp =
      'assets/images/gift_pack/gift_pack_daily_light_bg.webp';
  static const String gift$gift_pack_gift_pack_daily_light_bg_webp =
      'packages/gift/assets/images/gift_pack/gift_pack_daily_light_bg.webp';

  static const String gift_pack_gift_pack_daily_podium_webp =
      'assets/images/gift_pack/gift_pack_daily_podium.webp';
  static const String gift$gift_pack_gift_pack_daily_podium_webp =
      'packages/gift/assets/images/gift_pack/gift_pack_daily_podium.webp';

  static const String gift_pack_gift_pack_dialog_footer_webp =
      'assets/images/gift_pack/gift_pack_dialog_footer.webp';
  static const String gift$gift_pack_gift_pack_dialog_footer_webp =
      'packages/gift/assets/images/gift_pack/gift_pack_dialog_footer.webp';

  static const String gift_pack_gift_pack_dialog_header_webp =
      'assets/images/gift_pack/gift_pack_dialog_header.webp';
  static const String gift$gift_pack_gift_pack_dialog_header_webp =
      'packages/gift/assets/images/gift_pack/gift_pack_dialog_header.webp';

  static const String gift_pack_gift_pack_dialog_killer_title_webp =
      'assets/images/gift_pack/gift_pack_dialog_killer_title.webp';
  static const String gift$gift_pack_gift_pack_dialog_killer_title_webp =
      'packages/gift/assets/images/gift_pack/gift_pack_dialog_killer_title.webp';

  static const String gift_pack_gift_pack_dialog_title_webp =
      'assets/images/gift_pack/gift_pack_dialog_title.webp';
  static const String gift$gift_pack_gift_pack_dialog_title_webp =
      'packages/gift/assets/images/gift_pack/gift_pack_dialog_title.webp';

  static const String gift_pack_gift_pack_header_bg_webp =
      'assets/images/gift_pack/gift_pack_header_bg.webp';
  static const String gift$gift_pack_gift_pack_header_bg_webp =
      'packages/gift/assets/images/gift_pack/gift_pack_header_bg.webp';

  static const String gift_pack_gift_pack_header_bg_killer_webp =
      'assets/images/gift_pack/gift_pack_header_bg_killer.webp';
  static const String gift$gift_pack_gift_pack_header_bg_killer_webp =
      'packages/gift/assets/images/gift_pack/gift_pack_header_bg_killer.webp';

  static const String gift_pack_gift_pack_main_bg_webp =
      'assets/images/gift_pack/gift_pack_main_bg.webp';
  static const String gift$gift_pack_gift_pack_main_bg_webp =
      'packages/gift/assets/images/gift_pack/gift_pack_main_bg.webp';

  static const String gift_pack_gift_pack_title_bg_webp =
      'assets/images/gift_pack/gift_pack_title_bg.webp';
  static const String gift$gift_pack_gift_pack_title_bg_webp =
      'packages/gift/assets/images/gift_pack/gift_pack_title_bg.webp';

  static const String gift_pack_gift_pack_top_red_pkg_webp =
      'assets/images/gift_pack/gift_pack_top_red_pkg.webp';
  static const String gift$gift_pack_gift_pack_top_red_pkg_webp =
      'packages/gift/assets/images/gift_pack/gift_pack_top_red_pkg.webp';

  static const String gift_pack_gift_pack_triangle_webp =
      'assets/images/gift_pack/gift_pack_triangle.webp';
  static const String gift$gift_pack_gift_pack_triangle_webp =
      'packages/gift/assets/images/gift_pack/gift_pack_triangle.webp';

  static const String gift_pack_recharge_daily_gift_info_webp =
      'assets/images/gift_pack/recharge_daily_gift_info.webp';
  static const String gift$gift_pack_recharge_daily_gift_info_webp =
      'packages/gift/assets/images/gift_pack/recharge_daily_gift_info.webp';

  static const String gift_stopwatch_webp = 'assets/images/gift_stopwatch.webp';
  static const String gift$gift_stopwatch_webp =
      'packages/gift/assets/images/gift_stopwatch.webp';

  static const String gift_top_confess_tips_bg_webp =
      'assets/images/gift_top_confess_tips_bg.webp';
  static const String gift$gift_top_confess_tips_bg_webp =
      'packages/gift/assets/images/gift_top_confess_tips_bg.webp';

  static const String gift_wish_box_bg_webp =
      'assets/images/gift_wish_box_bg.webp';
  static const String gift$gift_wish_box_bg_webp =
      'packages/gift/assets/images/gift_wish_box_bg.webp';

  static const String gift_wish_box_bg_big_png =
      'assets/images/gift_wish_box_bg_big.png';
  static const String gift$gift_wish_box_bg_big_png =
      'packages/gift/assets/images/gift_wish_box_bg_big.png';

  static const String gift_wish_checked_png =
      'assets/images/gift_wish_checked.png';
  static const String gift$gift_wish_checked_png =
      'packages/gift/assets/images/gift_wish_checked.png';

  static const String gift_wish_uncheck_png =
      'assets/images/gift_wish_uncheck.png';
  static const String gift$gift_wish_uncheck_png =
      'packages/gift/assets/images/gift_wish_uncheck.png';

  static const String graffiti_gift_tip_icon_webp =
      'assets/images/graffiti_gift_tip_icon.webp';
  static const String gift$graffiti_gift_tip_icon_webp =
      'packages/gift/assets/images/graffiti_gift_tip_icon.webp';

  static const String ic_achievement_guide_webp =
      'assets/images/ic_achievement_guide.webp';
  static const String gift$ic_achievement_guide_webp =
      'packages/gift/assets/images/ic_achievement_guide.webp';

  static const String ic_arrow_svg = 'assets/images/ic_arrow.svg';
  static const String gift$ic_arrow_svg =
      'packages/gift/assets/images/ic_arrow.svg';

  static const String ic_arrow_left_png = 'assets/images/ic_arrow_left.png';
  static const String gift$ic_arrow_left_png =
      'packages/gift/assets/images/ic_arrow_left.png';

  static const String ic_arrow_right_png = 'assets/images/ic_arrow_right.png';
  static const String gift$ic_arrow_right_png =
      'packages/gift/assets/images/ic_arrow_right.png';

  static const String ic_arrow_right_webp = 'assets/images/ic_arrow_right.webp';
  static const String gift$ic_arrow_right_webp =
      'packages/gift/assets/images/ic_arrow_right.webp';

  static const String ic_auditing_webp = 'assets/images/ic_auditing.webp';
  static const String gift$ic_auditing_webp =
      'packages/gift/assets/images/ic_auditing.webp';

  static const String ic_back_white_webp = 'assets/images/ic_back_white.webp';
  static const String gift$ic_back_white_webp =
      'packages/gift/assets/images/ic_back_white.webp';

  static const String ic_charge_gift_webp = 'assets/images/ic_charge_gift.webp';
  static const String gift$ic_charge_gift_webp =
      'packages/gift/assets/images/ic_charge_gift.webp';

  static const String ic_down_arrow_png = 'assets/images/ic_down_arrow.png';
  static const String gift$ic_down_arrow_png =
      'packages/gift/assets/images/ic_down_arrow.png';

  static const String ic_edit_webp = 'assets/images/ic_edit.webp';
  static const String gift$ic_edit_webp =
      'packages/gift/assets/images/ic_edit.webp';

  static const String ic_gift_checkbox_png =
      'assets/images/ic_gift_checkbox.png';
  static const String gift$ic_gift_checkbox_png =
      'packages/gift/assets/images/ic_gift_checkbox.png';

  static const String ic_gift_pack_webp = 'assets/images/ic_gift_pack.webp';
  static const String gift$ic_gift_pack_webp =
      'packages/gift/assets/images/ic_gift_pack.webp';

  static const String ic_gift_select_png = 'assets/images/ic_gift_select.png';
  static const String gift$ic_gift_select_png =
      'packages/gift/assets/images/ic_gift_select.png';

  static const String ic_gift_select_svg = 'assets/images/ic_gift_select.svg';
  static const String gift$ic_gift_select_svg =
      'packages/gift/assets/images/ic_gift_select.svg';

  static const String ic_gift_select_new_svg =
      'assets/images/ic_gift_select_new.svg';
  static const String gift$ic_gift_select_new_svg =
      'packages/gift/assets/images/ic_gift_select_new.svg';

  static const String ic_gift_unselect_png =
      'assets/images/ic_gift_unselect.png';
  static const String gift$ic_gift_unselect_png =
      'packages/gift/assets/images/ic_gift_unselect.png';

  static const String ic_intimacy_pay_switch_png =
      'assets/images/ic_intimacy_pay_switch.png';
  static const String gift$ic_intimacy_pay_switch_png =
      'packages/gift/assets/images/ic_intimacy_pay_switch.png';

  static const String ic_lock_special_play_svg =
      'assets/images/ic_lock_special_play.svg';
  static const String gift$ic_lock_special_play_svg =
      'packages/gift/assets/images/ic_lock_special_play.svg';

  static const String ic_mic_select_svg = 'assets/images/ic_mic_select.svg';
  static const String gift$ic_mic_select_svg =
      'packages/gift/assets/images/ic_mic_select.svg';

  static const String ic_next_svg = 'assets/images/ic_next.svg';
  static const String gift$ic_next_svg =
      'packages/gift/assets/images/ic_next.svg';

  static const String ic_next_small_svg = 'assets/images/ic_next_small.svg';
  static const String gift$ic_next_small_svg =
      'packages/gift/assets/images/ic_next_small.svg';

  static const String ic_notice_svg = 'assets/images/ic_notice.svg';
  static const String gift$ic_notice_svg =
      'packages/gift/assets/images/ic_notice.svg';

  static const String ic_refresh_png = 'assets/images/ic_refresh.png';
  static const String gift$ic_refresh_png =
      'packages/gift/assets/images/ic_refresh.png';

  static const String ic_special_play_record_voice_webp =
      'assets/images/ic_special_play_record_voice.webp';
  static const String gift$ic_special_play_record_voice_webp =
      'packages/gift/assets/images/ic_special_play_record_voice.webp';

  static const String ic_special_play_voice_png =
      'assets/images/ic_special_play_voice.png';
  static const String gift$ic_special_play_voice_png =
      'packages/gift/assets/images/ic_special_play_voice.png';

  static const String ic_tab_big_png = 'assets/images/ic_tab_big.png';
  static const String gift$ic_tab_big_png =
      'packages/gift/assets/images/ic_tab_big.png';

  static const String ic_tab_select_bg_png =
      'assets/images/ic_tab_select_bg.png';
  static const String gift$ic_tab_select_bg_png =
      'packages/gift/assets/images/ic_tab_select_bg.png';

  static const String ic_tab_small_png = 'assets/images/ic_tab_small.png';
  static const String gift$ic_tab_small_png =
      'packages/gift/assets/images/ic_tab_small.png';

  static const String ic_up_arrow_svg = 'assets/images/ic_up_arrow.svg';
  static const String gift$ic_up_arrow_svg =
      'packages/gift/assets/images/ic_up_arrow.svg';

  static const String intimate_interact_dialog_close_svg =
      'assets/images/intimate_interact/dialog_close.svg';
  static const String gift$intimate_interact_dialog_close_svg =
      'packages/gift/assets/images/intimate_interact/dialog_close.svg';

  static const String intimate_interact_dialog_ic_hi_svg =
      'assets/images/intimate_interact/dialog_ic_hi.svg';
  static const String gift$intimate_interact_dialog_ic_hi_svg =
      'packages/gift/assets/images/intimate_interact/dialog_ic_hi.svg';

  static const String intimate_interact_dialog_title_peach_left_png =
      'assets/images/intimate_interact/dialog_title_peach_left.png';
  static const String gift$intimate_interact_dialog_title_peach_left_png =
      'packages/gift/assets/images/intimate_interact/dialog_title_peach_left.png';

  static const String intimate_interact_dialog_title_peach_right_png =
      'assets/images/intimate_interact/dialog_title_peach_right.png';
  static const String gift$intimate_interact_dialog_title_peach_right_png =
      'packages/gift/assets/images/intimate_interact/dialog_title_peach_right.png';

  static const String intimate_interact_dialog_title_text_png =
      'assets/images/intimate_interact/dialog_title_text.png';
  static const String gift$intimate_interact_dialog_title_text_png =
      'packages/gift/assets/images/intimate_interact/dialog_title_text.png';

  static const String intimate_interact_dialog_top_bg_png =
      'assets/images/intimate_interact/dialog_top_bg.png';
  static const String gift$intimate_interact_dialog_top_bg_png =
      'packages/gift/assets/images/intimate_interact/dialog_top_bg.png';

  static const String intimate_interact_ic_arrow_down_svg =
      'assets/images/intimate_interact/ic_arrow_down.svg';
  static const String gift$intimate_interact_ic_arrow_down_svg =
      'packages/gift/assets/images/intimate_interact/ic_arrow_down.svg';

  static const String intimate_interact_ic_arrow_right_svg =
      'assets/images/intimate_interact/ic_arrow_right.svg';
  static const String gift$intimate_interact_ic_arrow_right_svg =
      'packages/gift/assets/images/intimate_interact/ic_arrow_right.svg';

  static const String intimate_interact_msg_gift_bag_png =
      'assets/images/intimate_interact/msg_gift_bag.png';
  static const String gift$intimate_interact_msg_gift_bag_png =
      'packages/gift/assets/images/intimate_interact/msg_gift_bag.png';

  static const String intimate_interact_msg_gift_wave_png =
      'assets/images/intimate_interact/msg_gift_wave.png';
  static const String gift$intimate_interact_msg_gift_wave_png =
      'packages/gift/assets/images/intimate_interact/msg_gift_wave.png';

  static const String intimate_interact_msg_intro_peach_png =
      'assets/images/intimate_interact/msg_intro_peach.png';
  static const String gift$intimate_interact_msg_intro_peach_png =
      'packages/gift/assets/images/intimate_interact/msg_intro_peach.png';

  static const String intimate_interact_msg_photo_bottom_png =
      'assets/images/intimate_interact/msg_photo_bottom.png';
  static const String gift$intimate_interact_msg_photo_bottom_png =
      'packages/gift/assets/images/intimate_interact/msg_photo_bottom.png';

  static const String intimate_interact_msg_photo_middle_png =
      'assets/images/intimate_interact/msg_photo_middle.png';
  static const String gift$intimate_interact_msg_photo_middle_png =
      'packages/gift/assets/images/intimate_interact/msg_photo_middle.png';

  static const String intimate_interact_msg_photo_top_png =
      'assets/images/intimate_interact/msg_photo_top.png';
  static const String gift$intimate_interact_msg_photo_top_png =
      'packages/gift/assets/images/intimate_interact/msg_photo_top.png';

  static const String intimate_interact_public_screen_peach_1_png =
      'assets/images/intimate_interact/public_screen_peach_1.png';
  static const String gift$intimate_interact_public_screen_peach_1_png =
      'packages/gift/assets/images/intimate_interact/public_screen_peach_1.png';

  static const String intimate_interact_public_screen_peach_2_png =
      'assets/images/intimate_interact/public_screen_peach_2.png';
  static const String gift$intimate_interact_public_screen_peach_2_png =
      'packages/gift/assets/images/intimate_interact/public_screen_peach_2.png';

  static const String intimate_interact_public_screen_peach_3_png =
      'assets/images/intimate_interact/public_screen_peach_3.png';
  static const String gift$intimate_interact_public_screen_peach_3_png =
      'packages/gift/assets/images/intimate_interact/public_screen_peach_3.png';

  static const String limit_package_all_mic_send_left_png =
      'assets/images/limit_package/all_mic_send_left.png';
  static const String gift$limit_package_all_mic_send_left_png =
      'packages/gift/assets/images/limit_package/all_mic_send_left.png';

  static const String limit_package_all_mic_send_right_png =
      'assets/images/limit_package/all_mic_send_right.png';
  static const String gift$limit_package_all_mic_send_right_png =
      'packages/gift/assets/images/limit_package/all_mic_send_right.png';

  static const String limit_package_bg_gift_webp =
      'assets/images/limit_package/bg_gift.webp';
  static const String gift$limit_package_bg_gift_webp =
      'packages/gift/assets/images/limit_package/bg_gift.webp';

  static const String limit_package_gift_top_png =
      'assets/images/limit_package/gift_top.png';
  static const String gift$limit_package_gift_top_png =
      'packages/gift/assets/images/limit_package/gift_top.png';

  static const String limit_package_git_panel_banner_clock_png =
      'assets/images/limit_package/git_panel_banner_clock.png';
  static const String gift$limit_package_git_panel_banner_clock_png =
      'packages/gift/assets/images/limit_package/git_panel_banner_clock.png';

  static const String limit_package_git_panel_banner_crown_png =
      'assets/images/limit_package/git_panel_banner_crown.png';
  static const String gift$limit_package_git_panel_banner_crown_png =
      'packages/gift/assets/images/limit_package/git_panel_banner_crown.png';

  static const String limit_package_git_panel_banner_left_png =
      'assets/images/limit_package/git_panel_banner_left.png';
  static const String gift$limit_package_git_panel_banner_left_png =
      'packages/gift/assets/images/limit_package/git_panel_banner_left.png';

  static const String limit_package_git_panel_banner_more_png =
      'assets/images/limit_package/git_panel_banner_more.png';
  static const String gift$limit_package_git_panel_banner_more_png =
      'packages/gift/assets/images/limit_package/git_panel_banner_more.png';

  static const String limit_package_git_panel_banner_right_png =
      'assets/images/limit_package/git_panel_banner_right.png';
  static const String gift$limit_package_git_panel_banner_right_png =
      'packages/gift/assets/images/limit_package/git_panel_banner_right.png';

  static const String limit_package_ic_gift_title_png =
      'assets/images/limit_package/ic_gift_title.png';
  static const String gift$limit_package_ic_gift_title_png =
      'packages/gift/assets/images/limit_package/ic_gift_title.png';

  static const String limit_package_ic_star_bottom_png =
      'assets/images/limit_package/ic_star_bottom.png';
  static const String gift$limit_package_ic_star_bottom_png =
      'packages/gift/assets/images/limit_package/ic_star_bottom.png';

  static const String limit_package_ic_star_top_png =
      'assets/images/limit_package/ic_star_top.png';
  static const String gift$limit_package_ic_star_top_png =
      'packages/gift/assets/images/limit_package/ic_star_top.png';

  static const String record_voice_gift_invite_dialog_logo_webp =
      'assets/images/record_voice_gift_invite_dialog_logo.webp';
  static const String gift$record_voice_gift_invite_dialog_logo_webp =
      'packages/gift/assets/images/record_voice_gift_invite_dialog_logo.webp';

  static const String record_voice_gift_logo_webp =
      'assets/images/record_voice_gift_logo.webp';
  static const String gift$record_voice_gift_logo_webp =
      'packages/gift/assets/images/record_voice_gift_logo.webp';

  static const String tag_gift_tag_gift_card_end_webp =
      'assets/images/tag_gift/tag_gift_card_end.webp';
  static const String gift$tag_gift_tag_gift_card_end_webp =
      'packages/gift/assets/images/tag_gift/tag_gift_card_end.webp';

  static const String tag_gift_tag_gift_card_start_webp =
      'assets/images/tag_gift/tag_gift_card_start.webp';
  static const String gift$tag_gift_tag_gift_card_start_webp =
      'packages/gift/assets/images/tag_gift/tag_gift_card_start.webp';

  static const String tag_gift_tag_gift_header_bg_webp =
      'assets/images/tag_gift/tag_gift_header_bg.webp';
  static const String gift$tag_gift_tag_gift_header_bg_webp =
      'packages/gift/assets/images/tag_gift/tag_gift_header_bg.webp';

  static const String tag_gift_tag_gift_title_bg_webp =
      'assets/images/tag_gift/tag_gift_title_bg.webp';
  static const String gift$tag_gift_tag_gift_title_bg_webp =
      'packages/gift/assets/images/tag_gift/tag_gift_title_bg.webp';

  static const String tag_gift_bg_webp = 'assets/images/tag_gift_bg.webp';
  static const String gift$tag_gift_bg_webp =
      'packages/gift/assets/images/tag_gift_bg.webp';

  static const String tag_gift_icon_webp = 'assets/images/tag_gift_icon.webp';
  static const String gift$tag_gift_icon_webp =
      'packages/gift/assets/images/tag_gift_icon.webp';

  static const String tag_gift_name_title_webp =
      'assets/images/tag_gift_name_title.webp';
  static const String gift$tag_gift_name_title_webp =
      'packages/gift/assets/images/tag_gift_name_title.webp';

  static const String tag_gift_name_title_no_webp =
      'assets/images/tag_gift_name_title_no.webp';
  static const String gift$tag_gift_name_title_no_webp =
      'packages/gift/assets/images/tag_gift_name_title_no.webp';

  static const String tag_gift_select_png = 'assets/images/tag_gift_select.png';
  static const String gift$tag_gift_select_png =
      'packages/gift/assets/images/tag_gift_select.png';

  static const String tag_gift_send_webp = 'assets/images/tag_gift_send.webp';
  static const String gift$tag_gift_send_webp =
      'packages/gift/assets/images/tag_gift_send.webp';

  static const String tag_gift_send_bg_webp =
      'assets/images/tag_gift_send_bg.webp';
  static const String gift$tag_gift_send_bg_webp =
      'packages/gift/assets/images/tag_gift_send_bg.webp';

  static const String tag_gift_send_down_arrow_webp =
      'assets/images/tag_gift_send_down_arrow.webp';
  static const String gift$tag_gift_send_down_arrow_webp =
      'packages/gift/assets/images/tag_gift_send_down_arrow.webp';

  static const String tag_gift_title_webp = 'assets/images/tag_gift_title.webp';
  static const String gift$tag_gift_title_webp =
      'packages/gift/assets/images/tag_gift_title.webp';

  static const String tag_gift_unselect_webp =
      'assets/images/tag_gift_unselect.webp';
  static const String gift$tag_gift_unselect_webp =
      'packages/gift/assets/images/tag_gift_unselect.webp';

  static const String tag_gift_user_select_webp =
      'assets/images/tag_gift_user_select.webp';
  static const String gift$tag_gift_user_select_webp =
      'packages/gift/assets/images/tag_gift_user_select.webp';

  static const String throne_throne_gift_bg_webp =
      'assets/images/throne/throne_gift_bg.webp';
  static const String gift$throne_throne_gift_bg_webp =
      'packages/gift/assets/images/throne/throne_gift_bg.webp';

  static const String throne_throne_top_tips_bg_webp =
      'assets/images/throne/throne_top_tips_bg.webp';
  static const String gift$throne_throne_top_tips_bg_webp =
      'packages/gift/assets/images/throne/throne_top_tips_bg.webp';
  static const String btn_gift_name_bg_webp =
      'assets/images/btn_gift_name_bg.webp';
  static const String gift$btn_gift_name_bg_webp =
      'packages/gift/$btn_gift_name_bg_webp';

  static const String daliy_gift_icon_bg_webp =
      'assets/images/daliy_gift_icon_bg.webp';
  static const String gift$daliy_gift_icon_bg_webp =
      'packages/gift/assets/$daliy_gift_icon_bg_webp';

  static const String top_left_icon_webp = 'assets/images/top_left_icon.webp';
  static const String gift$top_left_icon_webp =
      'packages/gift/assets/$top_left_icon_webp';

  static const String bottom_right_icon_webp =
      'assets/images/bottom_right_icon.webp';
  static const String gift$bottom_right_icon_webp =
      'packages/gift/assets/$bottom_right_icon_webp';

  static const String gift_title_bgn_webp = 'assets/images/gift_title_bg.webp';
  static const String gift$gift_title_bg_webp =
      'packages/gift/assets/$gift_title_bgn_webp';

  static const String gift_start_icon_webp =
      'assets/images/gift_start_icon.webp';
  static const String gift$gift_start_icon_webp =
      'packages/gift/assets/$gift_title_bgn_webp';
}
