// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 9.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'search';

  static const String hot_person_png = 'assets/images/hot_person.png';
  static const String search$hot_person_png =
      'packages/search/assets/images/hot_person.png';

  static const String ic_egg_video_back_webp =
      'assets/images/ic_egg_video_back.webp';
  static const String search$ic_egg_video_back_webp =
      'packages/search/assets/images/ic_egg_video_back.webp';

  static const String ic_expand_svg = 'assets/images/ic_expand.svg';
  static const String search$ic_expand_svg =
      'packages/search/assets/images/ic_expand.svg';

  static const String ic_search_egg_bar_search_svg =
      'assets/images/ic_search_egg_bar_search.svg';
  static const String search$ic_search_egg_bar_search_svg =
      'packages/search/assets/images/ic_search_egg_bar_search.svg';

  static const String ic_search_egg_chat_webp =
      'assets/images/ic_search_egg_chat.webp';
  static const String search$ic_search_egg_chat_webp =
      'packages/search/assets/images/ic_search_egg_chat.webp';

  static const String icon_search_svg = 'assets/images/icon_search.svg';
  static const String search$icon_search_svg =
      'packages/search/assets/images/icon_search.svg';

  static const String search_egg_card_bg_webp =
      'assets/images/search_egg_card_bg.webp';
  static const String search$search_egg_card_bg_webp =
      'packages/search/assets/images/search_egg_card_bg.webp';

  static const String search_type_more_webp =
      'assets/images/search_type_more.webp';
  static const String search$search_type_more_webp =
      'packages/search/assets/images/search_type_more.webp';

  static const String work_like_webp = 'assets/images/work_like.webp';
  static const String search$work_like_webp =
      'packages/search/assets/images/work_like.webp';
}
