name: group
description: 聊天群组管理
version: 0.0.1
author:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  flutter_lints: ^2.0.2
  assets_gen: ^1.5.0

assets_gen:
  omit_path_levels: 2

flutter:
  assets:
    - assets/images/
