// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 3.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'video';

  static const String player_btn_play_png = 'assets/images/player_btn_play.png';
  static const String video$player_btn_play_png =
      'packages/video/assets/images/player_btn_play.png';

  static const String player_vnum_png = 'assets/images/player_vnum.png';
  static const String video$player_vnum_png =
      'packages/video/assets/images/player_vnum.png';

  static const String video_vnum_png = 'assets/images/video_vnum.png';
  static const String video$video_vnum_png =
      'packages/video/assets/images/video_vnum.png';
}
