name: commonrtc_api
description: A new Flutter project.
version: 1.0.7
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  path_provider: ^2.0.0

  audio_volume_prob:
    path: ../../audio_volume_prob

  synchronized: 3.0.0
  json_annotation: 4.5.0
  crypto: ^3.0.3
  convert: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
